### ISSUE TITLE
Interface autoloading fails in worker thread.

### ISSUE THREAD

**Issue by Danack** [krakjoe/pthreads#153]
Hey Joe,

I found a weird issue with Interfaces not being autoloaded in a Worker thread when they've already been loaded in the main thread. 

Very possibly not actually a bug in Pthreads but just a generic PHP issue, but as it affects pthreads, here it is:
## How to reproduce
1. Instantiate a class that implements an interface in the main thread.
2. Instantiate a second class that implements the same interface in the Worker thread.

As the code required to reproduce is over 4 files, I put an example project on https://github.com/Danack/TestRigPthreads/tree/master/InterfaceAutoloading The script to run is pthreadTest.php
## Expected result

When the second class is autoloaded, the interface that it implements should also be autoloaded.

> Run TestTask
> Creating class2 - which loads interface
> Loading class: TestClass2
> Loading class: TestInterface
## Actual result

It looks like PHP isn't attempting to autoload the interface in the Worker thread:

> Run TestTask
> Creating class2 - which loads interface
> Loading class: TestClass2
> PHP Fatal error:  TestClass2 cannot implement TestInterface - it is not an interface in /home/intahwebz/intahwebz/basereality/test/pthreads/TestClass2.php on line 3
> PHP Stack trace:
> PHP   1. TestTask->run() > /home/intahwebz/intahwebz/basereality/test/pthreads/pthreadTest.php:0
> PHP   2. spl_autoload_call() /home/intahwebz/intahwebz/basereality/test/pthreads/pthreadTest.php:49
> PHP   3. simplestAutoloader() /home/intahwebz/intahwebz/basereality/test/pthreads/pthreadTest.php:0
> PHP   4. require() /home/intahwebz/intahwebz/basereality/test/pthreads/pthreadTest.php:10
> Segmentation fault

Skipping instantiating (and so autoloading) the interface in the main thread makes the object creation in the worker thread work. This happens in both CLI and PHP-FPM.

cheers
Dan

**Comment by IVIR3zaM** [comment]
Hi Joe

this problem is exists in v2.0.10 yet. in branch PHP5 you fixed it and changed the package.xml to v2.0.11 but you didn't release that. if you don't have a plan for another changes for release v2.0.11 please draft it. because this bug is annoying. and in many projects php 5 is still in charge.

PS: thanks a lot for this wonderful library. concurrency in php was my concern for many times.
