### ISSUE TITLE
make test: 70% of tests are failing

### ISSUE THREAD

**Issue by sr78ger** [krakjoe/pthreads#202]
Hi.

I'm trying to build pthreads (0.45) using php 5.5.6, 5.4.22, 5.3.27 on CentOS6.5. I've tried several methods: building php with --enable-pthreads=static and --enable-maintainer-zts or as an module. 

Number of tests :   40                40
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :   28 ( 70.0%) ( 70.0%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   12 ( 30.0%) ( 30.0%)

php -dextension=pthreads.so --ri=pthreads
pthreads
Version => 0.45-rc

./configure \
--with-libdir=lib64 \
--with-layout=PHP \
--with-pear \
--with-apxs2 \
--enable-calendar \
--enable-bcmath \
--with-gmp \
--enable-exif \
--with-mcrypt \
--with-mhash \
--with-zlib \
--with-bz2 \
--enable-zip \
--enable-ftp \
--enable-mbstring \
--with-iconv \
--enable-intl \
--with-icu-dir=/usr \
--with-gettext \
--with-pspell \
--enable-sockets \
--with-openssl \
--with-curl \
--with-curlwrappers \
--with-gd \
--enable-gd-native-ttf \
--with-jpeg-dir=/usr \
--with-png-dir=/usr \
--with-zlib-dir=/usr \
--with-xpm-dir=/usr \
--with-vpx-dir=/usr \
--with-freetype-dir=/usr \
--with-t1lib=/usr \
--with-libxml-dir=/usr \
--with-mysql=mysqlnd \
--with-mysqli=mysqlnd \
--with-pdo-mysql=mysqlnd \
--enable-soap \
--with-xmlrpc \
--with-xsl \
--with-tidy=/usr \
--with-readline \
--enable-libxml \
--enable-xml \
--enable-dom \
--enable-simplexml \
--enable-xmlreader \
--enable-xmlwriter \
--enable-pcntl \
--enable-sysvshm \
--enable-sysvmsg \
--enable-shmop \
--enable-maintainer-zts \
--enable-cli

make 
make test

Thanks in advance
Stefab

**Comment by emiglobetrotting** [comment]
Trying to reinstall php7 (zts) + pthreads on ubuntu 14.04 with this [installation](http://stackoverflow.com/questions/34969325/how-to-install-php7-zts-pthreads-on-ubuntu-14-04/35003411#35003411) which was working and yields pass result of about 90% but now test pass result is 21.7%. Please help me.
