### ISSUE TITLE
Installation of pthreads on Windows 7 x86 with XAMPP

### ISSUE THREAD

**Issue by ghost** [krakjoe/pthreads#212]
This is how the installation should go:
1. Use the valid pthreads package for your PHP version.
2. Throw "pthreadVC2.dll" into "windows/system32".
3. add line:"extension=php_pthreads.dll" to the "php.ini" file.
4. Throw "pthreadVC2.dll" into the folder with "php.exe".
5. Throw "php_pthreads.dll" into the "php/ext" folder.

The errors I got while installing the pthreads package:

Error 1:
php_error.log: PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_pthreads.dll'....

Solution: throw "pthreadVC2.dll" into "windows/system32".

Error 2:
php_error.log: PHP Warning:  PHP Startup: pthreads: Unable to initialize module
Module compiled with module API=20090626
PHP    compiled with module API=20100525
These options need to match
 in Unknown on line 0

Solution: use a valid pthreads package for your PHP version.

PS. I would also to thank the pthreads team for building a such cool thing for the PHP community.

**Comment by developernaren** [comment]
is there a way to know which pthread to use with which php version. I get the same error 
Unable to initialize module
Module compiled with module API=20131226
PHP compiled with module API=20121212

which version of pthreads should I use. The one I tried to use now is 2.9.0
