### ISSUE TITLE
Thread::kill() won't kill a Thread locked on fgets()

### ISSUE THREAD

**Issue by shoghicp** [krakjoe/pthreads#230]
A Thread locked on a fgets() operation (specifically when reading from STDIN) will not be forcefully killed.

``` php
<?php

class AsyncInput extends Thread{
    public $line;
    public $stop;
    public function __construct(){
        $this->line = false;
        $this->stop = false;
        $this->start();
    }

    public function stop(){
        $this->stop = true;
    }

    public function run(){
        $fp = fopen("php://stdin", "r");
        do{
            $this->line = trim(fgets($fp));     
            $this->wait();
            $this->line = false;
        }while($this->stop !== true);
        fclose($fp);
    }
}

$input = new AsyncInput;
/*
    do things, and poll the input when needed. if a line is available, ::line will be true.
    STDIN / fgets is blocking, and stream_select will return true even when switching windows.
*/

for($i = 0; $i < 3; ++$i){ //read three lines
    while($input->line === false){
        usleep(1); //Fix 100% cpu
    }
    $line = $input->line;
    $input->notify();
    echo $input->line . PHP_EOL;
    usleep(50000);
}

/*
    Now, since the thread is already waiting on fgets(), I can't stop it directly.
    I use Thread::kill() for that
*/

$input->stop(); //Wont work
var_dump($input->kill());

exit(0);

```

Input (via keyboard):

```
a
b
c
```

Output:

```
a
b
c
bool(false)
```

Then it hangs until "Enter" is pressed one more time (leaving the fgets() lock).

stream_select() on STDIN is too buggy to be used, for example, switching windows will cause it to return true, even when fgets() (or fread()) will lock.

**Comment by raavishh** [comment]
Hi Krakjoe,

Can you please help me understanding Synchronization in PHP.

**Comment by raavishh** [comment]
Hi Krakjoe,

i need to use pthread in my project. i have created threads successfully and worked perfectly. but, not able to kill threads. i was just googling the same found this post.

**Comment by bnikola** [comment]
@raavishh - may I suggest that you open a question on [stackoverflow.com](http://www.stackoverflow.com) and tag it appropriately? That way we can avoid the discussion about synchronization from issues on github.
