### ISSUE TITLE
Fatal Error: Class 'Thread not found in

### ISSUE THREAD

**Issue by nic335** [krakjoe/pthreads#247]
Im getting this title as an error.

my php version is 5.5.9  -  php-5.5.9-Win32-VC11-x86 thread sage
php_pthreads-0.1.0-5.5-ts-vc11-x64

I did corectly copy pThreadsVC2.dll in the same folder as php.exe,php-cgi.exe.
I also did put the file php_pthreads.dll in the ext directory

In my php.ini the extension_dir is corectly set to the ext folder that has the php_pthreads.dll.

I also saw on internet that some poeple say to put this following line extension=php_pthreads.dll
In php.ini

After all that I still can't use pthreads.  If Someone has an idea, What should I do

Thanks for any help

**Comment by chinmay235** [comment]
Hi
My PHP version 7.1
I have tried to run Thread in my web page I am getting same error message.

Here I have followed these step

I copied php_pthreads.dll to the php\ext\ directory.
Also pthreadVC2.dll to the php\ directory.

I add this line to php.ini file
extension=php_pthreads.dll

**Comment by ymotse** [comment]
@saleemkce , Thanks!!! 
My compiler was VC11, and then, I downloaded "php_pthreads-2.0.9-5.6-ts-**vc11**-x64", and worked!!
--------------------
How upgrade the compiler version to VC14?
Thank you all!

**Comment by saleemkce** [comment]
@ymotse I'm glad you got it working :)

**Comment by saleemkce** [comment]
Hi Isac,

  Go to this downloads page
http://windows.php.net/downloads/pecl/releases/pthreads/3.1.6/  It contains
.dll file for *VC14*. Remove your old *vc file and replace with the file
you find inside the zip directory. Make sure you choose right OS.
(32-bit/64-bit).

**Comment by giyorasharaby** [comment]
Hi
I have the same fatal error (“Class Thread not found”) and although I read the above steps carefully I cannot resolve this.  I did the following:
1)	Installed XAMPP. 
When I run phpinfo() I get the following info (I also attached the full file):
![php](https://user-images.githubusercontent.com/35330950/35637826-0da47b2e-06be-11e8-8211-3639931f989b.jpg)

PHP version 7.1.13
Compiler MSVC14 (Visual C++ 2015)
Architecture x86
Thread Safety: Enabled
Loaded Configuration File: c:\xampp\php\php.ini

I downloaded [](http://windows.php.net/downloads/pecl/releases/pthreads/3.1.6/php_pthreads-3.1.6-7.0-ts-vc14-x64.zip) – I made sure that this file has the same version number (14) as my XAMPP compilation.
I am using windows 7 x64 so I believe this is a proper file to use according to the description above.

From the zip I extracted :+1: 

1)	pthreadVC2.dll to c:\xampp\php and 
2)	php_pthreads.dld to c:\xampp\php\ext

I added the line “extension=php_pthreads.dll” to c:\xampp\php\php.ini

After all this – I still get the error.
Any help will be much appreciated
Thanks
Giyora

**Comment by giyorasharaby** [comment]
BTW: As a source for the files pthreadVC2.dll and php_pthreads.dld I used the file "http://windows.php.net/downloads/pecl/releases/pthreads/3.1.6/php_pthreads-3.1.6-7.0-ts-vc14-x64.zip". 
My windows OS is x64 bit hence I used this file version.
Once it try has failed, I also tried using the file "php_pthreads-3.1.6-7.0-ts-vc14-x86.zip" as the source for these files- same results.
Any guess what am I doing wrong here?

**Comment by sarkerzaman** [comment]
I used the file "http://windows.php.net/downloads/pecl/releases/pthreads/3.1.6/php_pthreads-3.1.6-7.0-ts-vc14-x64.zip".

From the zip I extracted 
    pthreadVC2.dll to c:\xampp\php and
    php_pthreads.dld to c:\xampp\php\ext
    I added the line “extension=php_pthreads.dll” to c:\xampp\php\php.ini

My Windows OS is x64 bit.
PHP Version 7.1.7
Thread Safety: Enabled

After all this – I still get the error.
Any help will be much appreciated
Thanks
Zaman

**Comment by tpunt** [comment]
@sarkerzaman PHP 7.1 was not supported by that release (only PHP 7.0). Any PHP version below 7.2 is not supported anymore due to race conditions in ZTS mode.

**Comment by sarkerzaman** [comment]
@tpunt I have tried with PHP 7.0 but still not working.

**Comment by blessonabraham** [comment]
Facing the same issue with PHP Version 7.2.12 and php_pthreads-3.2.0-7.2-ts-vc15-x64. and why its closed?

**Comment by ravindra-gadekar** [comment]
It is work for VC15?
