### ISSUE TITLE
undefined reference to `_zval_ptr_dtor_wrapper'

### ISSUE THREAD

**Issue by mouradsm** [krakjoe/pthreads#279]
when i'm building the app throw an error:
 /pthreads/iterators/default.h:49: undefined reference to `_zval_ptr_dtor_wrapper'

how can i solve this?

**Comment by TonyStark** [comment]
the same issue occured in phpdbg package, but i solved by ```make distclean``` and re -configure package.

**Comment by flip111** [comment]
Just want to say thank you.
```
make distclean
./buildconf --force
./configure --enable-debug
make -j4
sudo make install
```
and everything was restored for me as well. (this was not related to pthreads i just found it by google)
