### ISSUE TITLE
pthreads leaks memory when using Threaded on Windows

### ISSUE THREAD

**Issue by shoghicp** [krakjoe/pthreads#289]
This is related to #272. A fix was issued for Linux, that worked, but on Windows it only made PHP report the correct amount of memory used.

Running this code on Windows 7 64-bit, PHP 5.5.10 64-bit with pthreads 2.0.4 will leak memory, but won't crash due to being out of memory:

``` php
<?php

class ThreadTest extends Thread{

    public function __construct(Threaded $threaded){
        $this->list = $threaded;
        $this->start();
    }

    public function run(){
        while(true){
            isset($this->list[0]); //Leak
        }
    }
}

$threaded = new Threaded;
$test = new ThreadTest($threaded);
$test->join();
```

This time I replaced the method call to a simple `isset()`. The leak happens whether that index is set or not.

Thanks for your time!

**Comment by Patchstar** [comment]
Hi,

issue still exists. Simply test it on Windows Server with IIS 7.5
PHP Version 5.6.8 64Bit TS
Installed: php_pthreads-2.0.9-5.6-ts-vc11-x86.zip

run Demo Skript: StackableArray.php
1. Call: php-cgi.exe blocks 500MB Ram (see in Task Manager)
2. Call:  php-cgi.exe blocks 1000MB Ram (see in Task Manager)
2. Call:  php-cgi.exe blocks 1500MB Ram (see in Task Manager)

after 8 calls windows will kill php-cgi.exe from task and you got Error  500
