### ISSUE TITLE
Use a pdo connection already declared

### ISSUE THREAD

**Issue by Grandnainconnu** [krakjoe/pthreads#326]
Hi,
I'm french so sorry for bad language...
I have discovered Pthreads one weeks ago and i have one problem.

For not eating my ram resources i want to passing a pdo connection already declared into my worker class, i show exemple.

<?php

$my_connection = new PDO(...);

class MyClient extends Worker
{
     public static $db_realm;

```
 public function __construct()
 {
        global $my_connection;

        static::$db_realm = $my_connection;
 }
```

}

?>

But it return serialization error.

One solution is possible? Because it's for an emulator and for 60 players it eat 55mb...

You can also see the rmy work on https://github.com/Hetarnam/AtomePHP

Have good day and thank you in advance ! :)

**Comment by lidrissi** [comment]
this can help https://github.com/krakjoe/pthreads/blob/master/examples/Singleton.php
