### ISSUE TITLE
Massive performance loss

### ISSUE THREAD

**Issue by wagnert** [krakjoe/pthreads#362]
Hi Joe,

as in Issue #361 described, we're actually try to update to latest pthreads 2.0.10. While we still have some problems with pthreads > 2.0.8 version 2.0.7 is working now :)

After some performance benchmarks we see a massive performance loss with 2.0.7 documented by the following screenshots:

![pthreads-2 0 7](https://cloud.githubusercontent.com/assets/287509/4701517/e3ca2bd4-5859-11e4-8f80-08023235c8c0.png)
![pthreads-2 0 10](https://cloud.githubusercontent.com/assets/287509/4701518/e517e6f2-5859-11e4-864e-d39e9a42be89.png)

I think that a performance impact around 5 % because of improved stability, security and memory handling will be quite o. k., but a slow down from 234 req/s to  2,33 req/s when calling an example servlet is quite too massive. and makes the appserver absolutely obsolete.

As i'm not sure, if the problem is based in our code, it would be helpful, if you can specify a list of things we should ignore to optimise performance. On the other hand, i think it can't be in our code, because 1.0.1 works almost perfect.

If you want to test it by yourself, you can simple download the latest appserver.io version from builds.appserver.io and install pthreads 2.0.7.

Thanks
Tim

**Comment by 2072** [comment]
I want to share something I recently discovered in my own software concerning performances: I used to make exceptions to 'bubble' between threads. What I didn't realize is that an exception object as a 'trace' member which contains references to all the arguments of every function call leading to the creation of the Exception object. So each time I was treating such an exception I was actually serializing an enormous set of objects... A query involving an exception was up to a hundred times slower than a normal query.
I discovered the problem accidentally when I introduced closures in some places which was triggering a 'can't serialize closure' error.

Maybe this is unrelated to your particular performance issue but just in case...

**Comment by zelgerj** [comment]
Hi Joe,

we've localized the reason why the performance got worse with pthreads >= v2.0.8 and wanted to discuss a possible solution for that, because for now we can not use it without doing the following modifications to `object.c` in `pthreads_routine`:

Your Version (@line 846):
```c
/**
* Startup Block Begin
**/
TSRMLS_FETCH();

/* set thread local storage */
thread->tls = TSRMLS_C;
```

Modified Version:
```c
/**
* Startup Block Begin
**/
/* create new context */
void ***tsrm_ls = NULL;
thread->tls = tsrm_ls = tsrm_new_interpreter_context();

/* set interpreter context */
tsrm_set_interpreter_context(tsrm_ls);
```

Your Version (@line 1060):
```c
/* shutdown request */
php_request_shutdown(TSRMLS_C);
```

Modified Version:
```c
/* shutdown request */
php_request_shutdown(TSRMLS_C);

/* free interpreter */
tsrm_free_interpreter_context(tsrm_ls);
```

It's seems that using `TSRMLS_FETCH();` ends up in a massive performance loss when having many worker queues and other things using threads with threaded objects...

Do you see any solution for that? Maybe to keep it configurable which initialization type of tsrmls you want to use?

Cheers,
Johann.

**Comment by krakjoe** [comment]
Put in a PR with changes, I'll test and merge it.

**Comment by zelgerj** [comment]
PR is ready https://github.com/krakjoe/pthreads/pull/422

**Comment by zelgerj** [comment]
new PR is ready and travis approved https://github.com/krakjoe/pthreads/pull/424.
Dunno what happened but travis fucked up last time...
