### ISSUE TITLE
pthread classes not found

### ISSUE THREAD

**Issue by ghost** [krakjoe/pthreads#363]
Running example files :

`Fatal error: Class 'Thread' not found in /root/www/html/examples/SocketServer.php on line 15`
`Fatal error: Class 'Stackable' not found in /root/www/html/examples/StackableArray.php on line 25`
`Fatal error: Class 'Worker' not found in /root/www/html/examples/MySQLi.php on line 8`

Running `apachectl -V` says :

```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jul 22 2014 14:36:38
Server's Module Magic Number: 20120211:27
Server loaded:  APR 1.5.1-dev, APR-UTIL 1.5.3
Compiled using: APR 1.5.1-dev, APR-UTIL 1.5.3
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"
```

I am using Debian/Mint distro and installed apache2 via synaptics (so default config I guess...) then downloaded php5 sources via `apt-get` and compiled with options (in debian/rules under `COMMON_CONFIG`)

```
    --enable-maintainer-zts \
    --enable-pthreads \
```

Phpinfo says `Thread Safety     enabled` and pthreads correctly shows as loaded module.

From https://github.com/krakjoe/pthreads/issues/30 I understand I need to reinstall Apache from source ?

As a backstory, I tried lots of different build configs (`--with-tsrm-pthreads`, `--enable-roxen-zts`, `--enable-maintainer-zts` etc.. that I found thru `./configure --help`) and 100% of the time, my phpinfo under apache would show `Thread Safety  disabled`. I even tried phpinfo under the built-in php webserver and I would get the same results - no thread safety enabled, no pthreads loaded.

Now then I ran `./buildconf --force` before compiling my packages and it seems it did the trick. I am fairly new to Linux so could anyone confirm `./buildconf --force` is mandatory and what does it do exactly ??

That's 2 questions in once im aware but I hope you can help me get pthreads running soon =)

Cheers, and thx for the module.

-Lapinott

**Comment by sureshshinde1689** [comment]
I am trying on WAMP, i got error : Class 'Worker' not found . What should i do?

**Comment by lapinott** [comment]
You need to include and enable the pthreads module. Lastest release is found here http://windows.php.net/downloads/pecl/releases/pthreads/2.0.9/

Instructions are found here http://php.net/manual/fr/pthreads.installation.php please read 1st comment.

**Comment by sureshshinde1689** [comment]
Thank you very much.............
