### ISSUE TITLE
Losing the value when assigning it to parent class member with self::

### ISSUE THREAD

**Issue by AlBundyLoves69** [krakjoe/pthreads#368]
You find a very detailed description of the issue here:
http://stackoverflow.com/questions/26787725/php-bug-in-threaded-environment-assigning-value-to-parent-static-member-in-same

Using parent:: instead of self:: fixes it but self:: should work as well.

**Comment by BurakDev** [comment]
I have this problem since pthreads 5.x, when I use eval(); to assign value it works perfectly (assigning socket ressource)

**Comment by krakjoe** [comment]
This was fixed in the last few commits:

	<?php
	class MyFileAbstract extends Threaded
	{
		protected static $m_Connection;

		public static function init() {
		    static::openFile();
		    echo "Member accessed from parent: ";
		    var_dump(self::$m_Connection);   # the resource is empty
		}
	}

	class MyFile extends MyFileAbstract
	{
		public static function openFile() {
		    self::$m_Connection = fopen("/etc/php.ini", "r");

		    echo "Member accessed from child: ";
		    var_dump(self::$m_Connection);   # the resource has value
		}
	}

	class MyThread extends Thread
	{
		public function run() {
		    MyFile::init();
		}

	}

	echo "Correct output:\n";
	MyFile::init();
	echo "\n";

	echo "Threaded output:\n";
	$myThread = new MyThread();
	$myThread->start();
	$myThread->join();
	?>

Output:

	Correct output:
	Member accessed from child: resource(5) of type (stream)
	Member accessed from parent: resource(5) of type (stream)

	Threaded output:
	Member accessed from child: resource(2) of type (stream)
	Member accessed from parent: resource(5) of type (stream)

Sorry about the wait ...

**Comment by BurakDev** [comment]
Yay ! Thanks @krakjoe :+1:
