### ISSUE TITLE
Doctrine Entity Manager with PThreads and Symfony2

### ISSUE THREAD

**Issue by svenpelster** [krakjoe/pthreads#369]
Hi krakjoe, 

I'm currentliy working with a thread safe version of PHP 5.6.2 with pthreads, Symfony2 and Doctrine2.
All works fine so far, but I have some problems with the EntityManager of Doctrine2.
I can't pass it from the standard Symfony2 context into my thread, because it can't be serialized.
In this case **$this->em** is my Doctrine Entity Manager. 

```
$pool = new \Pool(4, ThreadedWorker::class, [serialize($asyncFileStorage),  serialize($this->em)]);
foreach ($files as $file) {
  $this->em->refresh($file);
  $pool->submit(new AsyncArticleXmlConverter(serialize($file), serialize($this->product), $this>pubDate));
}
$pool->shutdown();

$pool->collect(function($work){
  return $work->isGarbage();
 });
```
Doesn't work. I always get the following error.
```
[PDOException]                                     
  You cannot serialize or unserialize PDO instances
```
So i recreated my Symfony2 Container inside of the **Worker** class and start the threads like this
```
    public function run()
    {
        require_once '/data/hydra/app/bootstrap.php.cache';
        require_once '/data/hydra/app/AppKernel.php';

        $kernel = new \AppKernel('dev', true);
        $kernel->loadClassCache();
        $kernel->boot();

        $this->container = $kernel->getContainer();
    }

    public function start($options = null)
    {
        return parent::start(PTHREADS_INHERIT_NONE);
    }
```
The container and object access works like a charm, but when I access the database with the Entity Manager, the complete command stops working after the first four threads.
Again **$this->em** is my Doctrine Entity Manager.
```
$this->em->persist($obj);
// After the flush the command stops working
$this->em->flush();

// Command stops working
$this->em->refresh($obj);

$this->em->remove($obj);
// After the flush the command stops working
$this->em->flush();
```

Is there a way to handle non-thread-safe objects like the entity manager? I'm trying a lot of different ways to access the database with it, but either it can't be serialized or the command stops working.
Any help or hint is appreciated. :-)

**Comment by adamus-tork** [comment]
Does this static member workaroud requires 5.6? I'm having nulls or segfaults with 5.5.9 php  (zts) and with the most recent version of pthreads when passing $em (Doctrine), even to only one thread.

Can you please show an example, how should it be done? I've googled my day :S

**Comment by krakjoe** [comment]
This is no longer applicable to seven, so closing.

**Comment by mmeloni** [comment]
@svenpelster Can you explain how you have recreated the container? I'm trying to getting help here http://stackoverflow.com/questions/32952438/symfony-doctrine-entity-manager-injected-in-thread .
For your opinion is possible to use a service as a thread?

**Comment by svenpelster** [comment]
@mmeloni 
As mentioned in the stackoverflow thread: You can't really share the Entity Manager with all Threads. You can create a new manager for each thread, but we never got it 100% perfect. 
We created a new AppKernel within the Worker. Inside of our threads we accessed the entity manager and container, which we declared as static.

Here is a code snippet:
Worker
```
class Worker extends \Worker
{
  public function run()
  {
    // Loading the Cache and Classes
    require_once __DIR__.'/../../../../../app/bootstrap.php.cache';
    require_once __DIR__.'/../../../../../app/AppKernel.php';
    // Creating a new AppKernel with the given environment
    $kernel = new \AppKernel($this->env, $debug);
    $kernel->loadClassCache();
    $kernel->boot();
    // Passing the container
    $this->container = serialize($kernel->getContainer());
  }
}
```

Thread
```
class Thread extends \Collectable
{
  public static $em;
  public static $container;

  public function run()
  {
    // Get the serialized contrainer 
    static::$container = unserialize($this->worker->container);
    // Create entity manager
    static::$em = static::$container->get('doctrine.orm.entity_manager');
    ...
  }
}
```

**Comment by smolinari** [comment]
I'd like to suggest having a look at appserver.io. They might have solved some of the problems you are encountering with their persistence container. 

http://appserver.io/get-started/documentation/1.0/persistence-container.html

https://github.com/appserver-io/appserver/tree/master/src/AppserverIo/Appserver/PersistenceContainer

At a minimum, the code might shed some light to the right direction to take, if there is one.

Scott

**Comment by mmeloni** [comment]
@svenpelster Tnx for your help . I have share my works on stackoverflow.

**Comment by mmeloni** [comment]
@smolinari  Tnx Scott . appserver.io is very interesting. It 's a revolution for php standard patterns . They have solved my problem with a php daemon always running . This approach is new for us and too much complex for our needs for now . But anyway I will keep for future project monitored app.io.

**Comment by StasToken** [comment]
Hello, and you can tell me how the same will be in symfony 4-I was pushed with the same problem but in version 4 no loadClass
