### ISSUE TITLE
Exception doesn't mark thread as isTerminated

### ISSUE THREAD

**Issue by mixadior** [krakjoe/pthreads#387]
```php

<?php

class T6 extends \Thread
{
    public function run()
    {
        $e = new \Exception('Yo!');
        throw $e;
    }
}

$tt = new T6();

$tt->start();
$tt->join();

var_dump($tt->isTerminated());

```

```
[vagrant@vagrant-centos64 QueueBerry]$ /opt/php-pthreads/bin/php ./bug_thread.php 
bool(false)
```

PHP 5.6.3 , pthreads 2.0.11 (current), build by your spex, if needed centos 6.x package here - http://feodosian.com/static/php-threads-build/php5.6-19112014/php-pthreads-rolling-rhel.x86_64.rpm

**Comment by mitaichik** [comment]
Me too have this problem. (OS X 10.10.2, php 5.6.5 (cli and fpm), pthreads 2.0.10). It not work if throw my exception. But strange - if it core php exception (like class not found) - it work.

**Comment by pfofi** [comment]
Shutdown functions won't be called either if an uncaught exception occurs. But if you do something like
```php
set_exception_handler(function ($exception) {
    throw $exception;
});
```
they will. `Threaded::isTerminated()` however still returns `false` then.

I find this most problematic in conjunction with `Worker`. If you keep stacking objects onto a started (not terminated/shutdown) worker, you should be able to assume these objects will eventually get executed. But they won't if any run method threw an exception - the worker's context is "dead" then. The snipped above fixes that for now.

**Comment by krakjoe** [comment]
Fixed in PHP7, on list of things to back port.
