### ISSUE TITLE
Unable to store Stream resources in Thread object

### ISSUE THREAD

**Issue by chibisuke** [krakjoe/pthreads#39]
As soon as I assign a stream resource to a thread object member the stream resource gets somehow damaged. 

``` php
class fw_reader extends Thread {
    public function run() {
        $stream = fopen('c:\windows\system32\drivers\etc\hosts','r');
        $this->socket = $stream;
        stream_set_blocking($this->socket, true);
        stream_set_timeout($this->socket, 2);
    }
}

$fw_r = new fw_reader();
$fw_r->start();
$fw_r->join();
```

error message is:
Warning: stream_set_timeout(): 2 is not a valid stream resource in P:\php\test.php on line 6

Using PHP 5.4, pthreads [245dbb1619d76227ae731befcbf64dd8529f72f4] on windows

If I change $this->socket to $stream it works fine.Also if I reverse the order of the "steam_set_blocking" and the "stream_set_timeout the error happens on the stream_set_blocking command and if I add a print_r($this->socket) before the steam_set_ it happens on both.

Any idea?

EDIT: I can confirm the same problem also happening with Stackable objects (instread Thread), while it works if using global scope

**Comment by torstahl** [comment]
Helllo

i have the same Problem on php5-5.4.20 with pthreads 2.0.10

class Joy {
    public $device = '/tmp/test.txt';
    public $stream;

    public function __construct()
    {
    }

    public function open()
    {
        $this->stream = fopen($this->device,'rb');
        stream_set_blocking ($this->stream,0);
        var_dump($this->stream);
    } // end function open

    public function read()
    {
        var_dump($this->stream);
        echo $line = stream_get_contents($this->stream,8)."\n";
    }

    /**
     *
     */
    public function close()
    {
        fclose($this->stream);
    } // end function close
}

class Test extends Thread {

    private $xr;

    public function run()
    {
        // works
        $joystick = new Joy();
        $joystick->open();
        $joystick->read();
        $joystick->close();

        // don't work
        $this->xr = new Joy();
        $this->xr->open();
        $this->xr->read();
        $this->xr->close();
   }
}

$test =new Test();
$test->start();

stream is NULL when using this.

Best Regards
Torsten

**Comment by rdlowrey** [comment]
In passing I noticed the examples here are messing with blocking flags on filesystem resources. As a public service announcement:

> Setting non-blocking mode on a filesystem resource will have *no* effect. It's a waste of time whether or not you're using pthreads.

Here's a good read on the subject: 

http://www.remlab.net/op/nonblock.shtml

**Comment by torstahl** [comment]
Hello
i use this to read from a joystick device /dev/input/js0
so for the report the stream_set_blocking is not necessary.

BR/Torsten
