### ISSUE TITLE
memory errors with objects that have many attributes and linking to each other

### ISSUE THREAD

**Issue by simllll** [krakjoe/pthreads#390]
The following script fails on Linux with following error message:
```
Program received signal SIGSEGV, Segmentation fault.
0x000000000092eeb5 in zend_hash_destroy (ht=0x7ffff7f1c848) at /home/adminuser/Downloads/php-5.6.3/Zend/zend_hash.c:546
546                     p = p->pListNext;
```

The real strange thign is, if you remove some attributes from class "A" or remove the echo with the json_encode in there, then the script does not segfault anymore. 

```php
<?php

class AbstractClass extends Stackable  { 
}

class A extends AbstractClass {
	protected $numberX;
	   public function setNumberX($x) { $this->numberX = $x; }
    public function getNumberX() { return $this->numberX; }
	
	protected $stringInstanceId;
    protected $numberAuditTime;
    protected $objectB;
    protected $someValue1aaaabbbbbbbba; 
    protected $someValue2; 
    protected $someValue3;
    protected $someValue4;
    protected $someValue5;
    protected $customId; 
    protected $asdfghjklasdfgasdfsdfdsf;
    protected $aaaaaaaaaaaaaaaaaa; 

    public function getStringInstanceId() { return $this->stringInstanceId; }
 
    public function getNumberAuditTime() { return $this->numberAuditTime; }
    public function getObjectB() { return $this->objectB; }
    public function getSomeValue1aaaabbbbbbbba() { return $this->someValue1aaaabbbbbbbba; }
    public function getSomeValue2()    {        return $this->someValue2;    }
    public function getSomeValue3()    {        return $this->someValue3;    }
    public function getSomeValue4()    {        return $this->someValue4;    }
    public function getSomeValue5()     {         return $this->someValue5;     }
    public function getCustomId()     {         return $this->customId;    }
    public function getAsdfghjklasdfgasdfsdfdsf()     {        return $this->asdfghjklasdfgasdfsdfdsf;    }
    public function getAaaaaaaaaaaaaaaaaa() {  return $this->aaaaaaaaaaaaaaaaaa;     }
}

class B extends AbstractClass {
	protected $numberX;
	protected $numberAuditTime;
    protected $objectA;
	
	public function setObjectA($a) { $this->objectA = $a; }
	public function getObjectA()	{		return $this->objectA;	}
	public function setNumberX($x)	{		$this->numberX = $x;	}
	public function getNumberX()	{		return $this->numberX;	}
	public function getNumberAuditTime()	{		return $this->numberAuditTime;	}
}

$prep = null;
function dosomething() 
{
	global $prep;
	if($prep==null) $prep = new Preparator();
	for($i=0;$i<2;$i++) // you need at least two calls of "doIt"..
	{
		$prep->doIt();
		//$prep->doIt(2,1);
	}
	$retVal = $prep->getIt();
	echo "got ".count($retVal)." entries\n";
	return $retVal;
}


class Preparator {
	private $allObjs;
	private $cache;
	public function __construct()
	{
		$this->allObjs= array();
		$this->cache = array();
	}
	
	public function getIt() 
	{
		$allobjs = $this->allObjs;
		$this->allObjs = array();
		return $allobjs;
	}
	
	public function doIt($level=0) {
		$a = new A();
//		$a->setNumberX(rand(0,50));
		
		$this->allObjs[] = $a;
		//echo "adding A:".json_encode($a)."\n";

		$b = new B();
	//	$b->setNumberX(rand(0,500));
		$b->setObjectA($a);
		
		//commenting next line, results into a working script..?! WHAT?!?
		echo "adding B:".json_encode($b)."\n";
		
		$this->allObjs[] = $b;
		
		if($level==0) 
		{
			$this->doIt($level+1);
		}

		return null;
	}
}

$all = dosomething(); // fails

die("done\n");
```

**Comment by krakjoe** [comment]
Executing in PHP7 without error.

	<?php

	class AbstractClass extends Threaded  { 
	}

	class A extends AbstractClass {
	    protected $numberX;
	       public function setNumberX($x) { $this->numberX = $x; }
	    public function getNumberX() { return $this->numberX; }

	    protected $stringInstanceId;
	    protected $numberAuditTime;
	    protected $objectB;
	    protected $someValue1aaaabbbbbbbba; 
	    protected $someValue2; 
	    protected $someValue3;
	    protected $someValue4;
	    protected $someValue5;
	    protected $customId; 
	    protected $asdfghjklasdfgasdfsdfdsf;
	    protected $aaaaaaaaaaaaaaaaaa; 

	    public function getStringInstanceId() { return $this->stringInstanceId; }

	    public function getNumberAuditTime() { return $this->numberAuditTime; }
	    public function getObjectB() { return $this->objectB; }
	    public function getSomeValue1aaaabbbbbbbba() { return $this->someValue1aaaabbbbbbbba; }
	    public function getSomeValue2()    {        return $this->someValue2;    }
	    public function getSomeValue3()    {        return $this->someValue3;    }
	    public function getSomeValue4()    {        return $this->someValue4;    }
	    public function getSomeValue5()     {         return $this->someValue5;     }
	    public function getCustomId()     {         return $this->customId;    }
	    public function getAsdfghjklasdfgasdfsdfdsf()     {        return $this->asdfghjklasdfgasdfsdfdsf;    }
	    public function getAaaaaaaaaaaaaaaaaa() {  return $this->aaaaaaaaaaaaaaaaaa;     }
	}

	class B extends AbstractClass {
	    protected $numberX;
	    protected $numberAuditTime;
	    protected $objectA;

	    public function setObjectA($a) { $this->objectA = $a; }
	    public function getObjectA()    {       return $this->objectA;  }
	    public function setNumberX($x)  {       $this->numberX = $x;    }
	    public function getNumberX()    {       return $this->numberX;  }
	    public function getNumberAuditTime()    {       return $this->numberAuditTime;  }
	}

	$prep = null;
	function dosomething() 
	{
	    global $prep;
	    if($prep==null) $prep = new Preparator();
	    for($i=0;$i<2;$i++) // you need at least two calls of "doIt"..
	    {
		$prep->doIt();
		//$prep->doIt(2,1);
	    }
	    $retVal = $prep->getIt();
	    echo "got ".count($retVal)." entries\n";
	    return $retVal;
	}


	class Preparator {
	    private $allObjs;
	    private $cache;
	    public function __construct()
	    {
		$this->allObjs= array();
		$this->cache = array();
	    }

	    public function getIt() 
	    {
		$allobjs = $this->allObjs;
		$this->allObjs = array();
		return $allobjs;
	    }

	    public function doIt($level=0) {
		$a = new A();
	//      $a->setNumberX(rand(0,50));

		$this->allObjs[] = $a;
		//echo "adding A:".json_encode($a)."\n";

		$b = new B();
	    //  $b->setNumberX(rand(0,500));
		$b->setObjectA($a);

		//commenting next line, results into a working script..?! WHAT?!?
		echo "adding B:".json_encode($b)."\n";

		$this->allObjs[] = $b;

		if($level==0) 
		{
		    $this->doIt($level+1);
		}

		return null;
	    }
	}

	$all = dosomething(); // fails

	die("done\n");

Sorry it took so long and sorry it's not the version you are probably working with right now, but gotta look forward to 7 ;)
