### ISSUE TITLE
pthreads and yii2

### ISSUE THREAD

**Issue by deka6pb** [krakjoe/pthreads#397]
Good afternoon.
My English is bad:)
I like your product, but I had a problem. I'm using pthreads together with yii2. I would like to use in class Stackable Model Yii. How do I do this? In the Yii are tied to namespase.

**Comment by krakjoe** [comment]
As mentioned the autoloader does need to be re-registered in the threaded context. "use" won't work by itself.

Here is an example repo for using auto loading and composer, you can extrapolate from this what is required: https://github.com/krakjoe/pthreads-autoloading-composer

**Comment by mitaichik** [comment]
Anybody find solution for Yii2? @krakjoy example work with composer autoloader, but i can't understand how it use with Yii autoloader (based on application config, like aliases)

**Comment by RamzyVirani** [comment]
hey karkjeo, I really appreciate your efforts. I am also trying to use pthreads with Yii2 Framework, i followed your shared link `https://github.com/krakjoe/pthreads-autoloading-composer` but I cannot understand where and how to use it. can you please give me a how to use in real life application?
