### ISSUE TITLE
Windows CLI crash on passing Threaded to Thread

### ISSUE THREAD

**Issue by Doggie52** [krakjoe/pthreads#398]
Hello,

OS: Windows 8.1 x64
PHP: 5.6.3 (cli) (TS VC11)

This may be similar to amphp/thread#13. Below follows the simplest version of my code I was able to produce:

```php
<?php

class A {
	
	public function test() {
		$queue = new Threaded;
		$thread = new T( $queue );

		$thread->start();
		$thread->join();
	}
}

class T extends Thread {

	private $queue;

	public function T( $queue ) {
		$this->queue = $queue;
	}

	public function run() {
		var_dump( $this->queue );
	}
}

$app = new A;

$app->test();
```

I tried to emulate the response in https://github.com/krakjoe/pthreads/issues/358#issuecomment-57090365. Running this simply crashes my CLI (*CLI has stopped working*). Is there something fundamentally wrong in my code or is this a bug?

**Comment by krakjoe** [comment]
Closing, no feedback since forever :)
