### ISSUE TITLE
Provide a way to get memory usage over some/all threads

### ISSUE THREAD

**Issue by shoghicp** [krakjoe/pthreads#405]
Because of `memory_get_usage()` only getting the current thread memory usage, getting the usage of some or all threads is hard.

Is it possible to implement a method in Thread to get the memory usage of that specific thread (this would allow getting global measurements), or if simpler, a global measurement function?

Some users were complaining that my application reports 30MB of usage when it's using 1.5GB with just other 4 idle threads. I'm already fixing that issue with few workarounds, but reporting the correct memory would be great :)

**Comment by krakjoe** [comment]
memory_get_usage can only report memory allocated by Zend's memory manager, memory allocated by pthreads for threaded objects is allocated by the system, not Zend. This is why the numbers are skewed, they are always skewed whether pthreads is loaded or not.

The solution is just to realize that memory_get_usage isn't reliable. There isn't a sensible way to get the real memory allocated by system and zend.

**Comment by shoghicp** [comment]
Alright, thanks!
I know that it is not reliable, that's why I asked for a better way. I guess I'll use the memory the system itself reports and other some code to get each value from different threads. I might as well remove the memory limit as it is only reliable per thread
