### ISSUE TITLE
Callback passed to Thread instance

### ISSUE THREAD

**Issue by kbokarius** [krakjoe/pthreads#410]
We're running into an issue using pthreads with PHP 5.6.4. Any time we pass a class instance method as a callback to a thread and the callback is executed in the thread's run() method, it appears that the class instance containing the callback method is serialized and a copy of that class instance is made. The callback method then executes in this new class instance and doesn't have access to the data in the origin class instance. Is this a limitation of pthreads or is there a way around this? In other words, is there a way to pass a callback method to a thread and have it execute normally and pass data back to the original class instance that contains the callback?

The example below prints :
Storage count: 1
Storage count: 1
Storage count: 1
Storage count: 1
Storage count: 1

While it should print:
Storage count: 1
Storage count: 2
Storage count: 3
Storage count: 4
Storage count: 5

I realize there's a Stackable class that we can use for a thread-safe array. Our goal though is to provide a library that can easily be consumed, where users can pass callbacks to the library and have our library execute those callbacks within running threads. It seems that depending on how the callbacks are implemented, the users may or may not be able to do this, and would at times be forced to write special pthread-safe (i.e., Stackables) code to accomplish what they need.

```PHP
<?php
class Test
{
    public $storage = array();
    public function callback()
    {
        array_push($this->storage, 1);
        Print "Storage count: " . count($this->storage) . "\r\n";
    }
}

class Runner extends Thread
{
    public $callback = null;
    public function run()
    {
        $cb = $this->callback;
        $cb();
    }
}

$test = new Test();
for ($i = 0; $i < 5; $i++)
{
    $runner = new Runner();
    $runner->callback = array($test, 'callback');
    $runner->start();
}
sleep(3)
?>
```

**Comment by krakjoe** [comment]
You seem to already know the solution, an array is not thread safe, use a Threaded object.

There is much code in the examples folder that can help you to understand.
