### ISSUE TITLE
PHP pthread not echoing from run()

### ISSUE THREAD

**Issue by tekbird** [krakjoe/pthreads#412]
I have come across this strange issue of PHP not writing to standard out when echoed from the run() method of a PHP pthread. I also observed that it cannot resolve any namespace, neither any error on these disabilities.

Can somebody suggest a solution for this?

In the collowing sample code, echo 'test'; won't simply happen!

    class ChildThread extends Thread {

        public $data;

        public function run() {
          /* Do some work */

          $this->data = 'result';
          echo 'test'; 
        }
    }

    $threads=array();

    for($i=0;$i<50;$i++){
        $threads[] = new ChildThread();
        $threads[$i]->start();
    }

    for($i=0;$i<50;$i++){
        $threads[$i]->join();
        echo $threads[$i]->data.'<br/>';
    }

**Comment by krakjoe** [comment]
While you are executing in a web sapi, such as mod_php or fpm, it is not a good idea to try to write standard output from anything other than the main thread. This is because Zend doesn't provide facility to set the output stream, because it would be extremely dangerous to do so.
