### ISSUE TITLE
Unable to pass a Threaded created by Threaded::from() to a Thread 

### ISSUE THREAD

**Issue by SirSnyder** [krakjoe/pthreads#413]
Hello,

I create a Threaded Object with the help of Threaded::from(). This Threaded Object passed to a Thread results in a null pointer and I've no glue what is getting wrong.

A little example:

```
global $objDynamicThreaded, $objStaticThreaded, $executor;

    class StaticThreaded extends Threaded
    {
        public function run()
        {
            echo 'static threaded function, threadid: '. Thread::getCurrentThreadId() . PHP_EOL;
        }
    }

    class Executor extends Thread
    {
        /** @var Threaded */
        protected $objRunnable;

        public function setRunnable(Threaded $runnable)
        {
            $this->objRunnable = $runnable;
        }

        public function run()
        {
            if($this->objRunnable !== null)
            {
                $this->objRunnable->run();
            }
            else
            {
                echo 'no runnable ;-( - threadid: '. Thread::getCurrentThreadId() . PHP_EOL;
            }
        }
    }
    echo 'Static vs Dynamic Test - threadid: '. Thread::getCurrentThreadId() . PHP_EOL;

    /**
     * static
     */
    $objStaticThreaded = new StaticThreaded();

    /**
     * dynamic
     */
    $objDynamicThreaded = Threaded::from(function()
    {
        echo 'dynamic threaded function - threadid: '. Thread::getCurrentThreadId() . PHP_EOL;
    });

    $executor = new Executor();
    $executor->setRunnable($objDynamicThreaded);    // works not: no runnable ;-( - threadid: 21796
//    $executor->setRunnable($objStaticThreaded);     // works: static threaded function, threadid: 20336
    $executor->start();
    $executor->join();
```
Maybe I'm doing something wrong? Thx

**Comment by krakjoe** [comment]
Deprecated in 7, it's no longer required because of anonymous class support.

	<?php
	class Executor extends Worker
	{
		/** @var Threaded */
		protected $objRunnable;

		public function setRunnable(Threaded $runnable) {
			$this->objRunnable = $runnable;
		}

		public function run() {
			if($this->objRunnable != null) {
				$this->objRunnable->run();
			}
		}
	}

	$executor = new Executor();
	$runnable = new class extends Threaded {
		public function run() {
			printf("Executing %s\n", __CLASS__);
		}
	};
	$executor->setRunnable($runnable);

	$executor->start();
	$executor->join();

Yeilds

        Executing class@anonymous/usr/src/pthreads/from.php0x7f3ae398d1af

Sorry it's probably not the version you are using right now, but I gotta focus on 7 ;)

**Comment by SirSnyder** [comment]
Many thanks for your support and engagement! It's fairly ok to focus on 7. I will adopt pthread 3 as fast as possible.
