### ISSUE TITLE
Test is failed on SUHOSIN patched PHP.

### ISSUE THREAD

**Issue by toshiyuki-ogawa** [krakjoe/pthreads#414]
Hello, krakjoe.
I maked pthreads module in debian PHP which is applied [SUHOSIN](http://suhosin.org/) [patch](http://suhosin.org/stories/download.html). When I run 'TESTS=ext/pthreads make test', [ext/pthreads/tests/thread.phpt](https://github.com/toshiyuki-ogawa/pthreads/blob/master/tests/thread.phpt) is FAILED. It didn't do [var_dump($thread->join())](https://github.com/toshiyuki-ogawa/pthreads/blob/master/tests/thread.phpt#L14), It was likely to abondon main thread. I inspected php source code and finally found that PHP terminated at [this line](https://github.com/toshiyuki-ogawa/php-src/blob/t-PHP-5.3.29-ubuntu/Zend/zend_hash.c#L311). This line points that the [HashTable.pDestructor](https://github.com/toshiyuki-ogawa/php-src/blob/t-PHP-5.3.29-ubuntu/Zend/zend_hash.h#L75) is not registered. So I wrote workaround this problem. Now I am ready to [pull request](https://github.com/toshiyuki-ogawa/pthreads/commit/fdcda7acc0f25289538e017478e8f631f9bdfb63) for this issue. The workaround bring in  [SUHOSIH](https://github.com/toshiyuki-ogawa/pthreads/blob/fdcda7acc0f25289538e017478e8f631f9bdfb63/src/prepare.c#L79) macro to pthreads code. Dose this have any problems ? If not, I will pull request.

**Comment by chibisuke** [comment]
imho if your programming is that insecure that you need to use suhosin 
you most likely do not have the ability to properly work with pthreads. 
On the other hand, if you're using pthreads you propably know enougth 
about propper programming techniques to not need suhosin.

**Comment by toshiyuki-ogawa** [comment]
Thanks for your opinion, chibisuke. I am agree your opinion. I'm thinking that SUHOSIN may be unnecessary for the developer who has ability to work with pthreads.
I wrote issue at a package-maintainer's standpoint. The package-maintainer have no idia that each developer has ability to work with pthreads. He may want to make PHP more safely for developpers who don't have it. Actually In my linux os which is ubuntu, PHP has been applied SUHOSIN patch. I think many linux users use a package-management system such as apt-get, yum, pacman or pear. I hope that many users use pthreads quickly and easily by using package-management system.
By the way, I am not package-maintainer, but want to manage PHP with apt-get even if install custumized PHP which is enabled pthreads. I will do it by running dpkg with customized PHP which is maked in my linux. I am going to request for creating pthreads package to debian PHP package-maintainer.

**Comment by krakjoe** [comment]
Please use the PR system to make PR's, this simplifies CI.

It doesn't sound very nice, btw, but feel free to PR and I can review it properly.
