### ISSUE TITLE
Symfony2 Class 'Thread' not found

### ISSUE THREAD

**Issue by jbetanzos** [krakjoe/pthreads#416]
Hi, I'm trying to integrate pthreads in a symfony2 project but I run a test example in a single file outside symfony and all goes well. After I try to call the same code inside symfony bundle it keeps telling me that Class 'Thread' not found.

Hope you can help, thanks

**Comment by krakjoe** [comment]
Please link to a minimal reproduce script/setup, use gist for multiple files please.

**Comment by zelgerj** [comment]
You think you just forgot the `\` in front of the classname `Thread`...Maybe there won't be any namespace  in your test-script, but in symfony2 they are...

This should work:
```php
$thread = new \Thread();
```
Cheers,
Johann
