### ISSUE TITLE
question: using pool from multiple contexts

### ISSUE THREAD

**Issue by coolemza** [krakjoe/pthreads#417]
pool is a very suitable class\architecture, and it is impossible to use pool->submit() from multiple contexts, but maybe there are some solutions to avoid this limitation? for example if i have pool of sql workers that implements all my db recording needs, it would be very convenient to be able to submit record tasks to pool from multiple contexts. ty

**Comment by krakjoe** [comment]
I've thought about this, a lot. I see the use case, but, there are many barriers to making that work, and breaching those barriers would result in unstable execution. I think there is no way to do this without having negative side effects.

Let's keep it simple.
