### ISSUE TITLE
Xampp cannot load extension

### ISSUE THREAD

**Issue by juradee** [krakjoe/pthreads#418]
After install dll's in to xampp\php folder and restart apache server I get error
"PHP Warning:  PHP Startup:  in Unknown on line 0"
Extension doesn't work

PHP Version: 5.5.11
PHP Extension Build : API20121212,TS,VC11 
Extention version : php_pthreads-2.0.10-5.6-ts-vc11-x64.zip
OS : Windows 8.1
Apache: 2.4.

**Comment by krakjoe** [comment]
You are using a PHP-5.6 dll and running PHP-5.5, that should solve it.

**Comment by juradee** [comment]
Same problem with Extention version : php_pthreads-2.0.10-5.5-ts-vc11-x64.zip

**Comment by chibisuke** [comment]
xampp by default ships with non-threded PHP. You need a PHP thats threadsafe, and of course your extensions php version needs to match aswell.

**Comment by zelgerj** [comment]
@juradee You could also use our web stack called appserver.io.
It replaces the "old" Xampp thing and works on windows with pthreads included etc...
Just check it out Check it out http://appserver.io. If you have any questions visit our gitter chat.
Cheers, Johann.
