### ISSUE TITLE
pthreads and PHP 7 ? 

### ISSUE THREAD

**Issue by zelgerj** [krakjoe/pthreads#421]
Hi Joe,

how about pthreads and PHP7? Will it eventually be part of PHP7 core?
Would be cool to hear what the plans are...

Cheers,
Johann

**Comment by shoghicp** [comment]
I asked him over twitter a while ago, and he said he will be working on it on the future when he has enough time. It's the only extension stopping me from using PHP 7 on my project :)

**Comment by krakjoe** [comment]
There will be a version of pthreads for PHP7.

pthreads is not likely to be part of the core, ever.

I don't know when I'll next have a week or more to do the work on pthreads.

**Comment by zelgerj** [comment]
Ok! Thanks for that information Joe!
Cheers,
Johann

**Comment by smolinari** [comment]
Hey Joe. This is humble me, a fan or the pthreads technology, cheering you on to get it PHP7 compatible! :smile: 

Scott

**Comment by SnakeO** [comment]
:dancers: pthreads + php7 :love_hotel:

**Comment by Striker209** [comment]
@shoghicp I was just searching for pthreads for PHP7 :D

**Comment by smolinari** [comment]
Go Joe! Go Joe! Go Joe! :dancers: :+1: 

Scott
