### ISSUE TITLE
The best method....

### ISSUE THREAD

**Issue by Hetarnam** [krakjoe/pthreads#427]
Hi everyone!

I'm french sorry for bad lanaguage.

I'm here because i have to do an emulator for a private server for one MMORPG.

I want to have one thread by client because the game work with socket, so one socket connection by thread.

I had to create an "king" class to manage all clients, and access to everything.

For finish, i use CLI to listen the socket port, so after exit of client, he thread have to be deleted completly and it does not remain in the memory.

Is that possible? If yes how? 

Thanks for reading and i hope an answer!

**Comment by Hetarnam** [comment]
up please :(

**Comment by bnikola** [comment]
Thread per socket is not the best option. You don't need pthreads for what you want. Since you're using CLI version of PHP, you can use an event loop (libev, libuv, whichever you might prefer) and every time someone connects - add the socket resource to an array. Upon activity on a socket, execute event loop event watcher. Asynchronous approach is much more resource friendly, as well as easier than working with threads.

**Comment by Hetarnam** [comment]
Mmhh, good idea, thanks, but

Can we do event when we want and CLI destroy unused ram after delete one while?

**Comment by bnikola** [comment]
@Hetarnam  I really can't make out what you're asking.. If you do things properly, you shouldn't be in a position where you have memory allocated for nothing. Technically, you can destroy your CLI process and restart it using some sort of a supervisor and "free" the memory that way ([supervisord.org](www.supervisord.org) and have a persistence layer. However, without further information - I don't think you need pthreads for what your task and this ticket could be closed, we're going a little bit offtopic here.

**Comment by Bizarrus** [comment]
how do you store the client-threads?
Im working on the same concept: A server manages lot of clients, each client with thread.

We can't help with your wrong turn if you don't tell us code. Please provide it.

**Comment by krakjoe** [comment]
This is not the place to get help with code, closing.
