### ISSUE TITLE
Fatal errors in Threaded::run() leave Worker functionning in a damaged state

### ISSUE THREAD

**Issue by 2072** [krakjoe/pthreads#430]
If a task makes a Fatal Error from a call made in `Threaded::run()` the Worker thread is left running but the context set by `Worker::run()` is lost (cleared). If the fatal error occurs directly in `Threaded::Run()` then the context is preserved.

I'm not even sure a worker should actually continue running in this case. IMHO it would be best for it to shutdown cleanly and let the user handle the situation in PHP land.

Also while trying to understand the intended behaviour I stumbled upon something I don't understand in https://github.com/krakjoe/pthreads/blob/master/src/object.c#L1029

```c
/* deal with references to stacked objects */
if (!terminated && inwork) {
	zval_ptr_dtor(&ZEG->This);
} else inwork = 1;
```

`terminated` is set to `1` when a fatal errors occurs and `inwork` is set to `1` after running `Worker::run()` but this means that `zval_ptr_dtor(&ZEG->This)` is never called when a fatal error occurs, is this normal?

Code to reproduce the problem:

```php
<?php
error_reporting(E_ALL | E_STRICT);
ini_set("display_startup_errors", true);


class aWorker extends Worker {

    public function run() {
        $greatContext = "blah";

        echo "Worker started, context set to '$greatContext'" . PHP_EOL;
    }
}

class aTask extends Threaded {
    protected $id = 0;

    public function __construct($id) {
        $this->id = $id;
    }

    private function makeFatalError() {
        $theNullPointer = null;
        echo "crashing worker..." . PHP_EOL;
        $theNullPointer->fatal();
    }

    public function run() {
        echo "executing task " . var_export($this->id, true) . PHP_EOL;
        if (!isset($greatContext)) {
            echo "Worker damaged" . PHP_EOL;
            return;
        }

        $this->makeFatalError(); //NOTE: if this function is inlined, the context remains undamaged

    }
}


$i = 0;
$aWorker = new aWorker;
$aFirstTask = new aTask($i++);
$aWorker->start();

$aWorker->stack($aFirstTask);
$anotherTask = new aTask($i++);
$aWorker->stack($anotherTask);
$aWorker->shutdown();

echo PHP_EOL;
```

Outputs:
```
Worker started, context set to 'blah'
executing task 0
crashing worker...

Fatal error: Call to a member function fatal() on null in /home/john/pthreadsissue430.php on line 25
executing task 1
Worker damaged
```

**Comment by krakjoe** [comment]
As far as I can tell, this is no longer applicable to PHP7.

If you test with 7 and don't get the expected result, please open an issue.
