### ISSUE TITLE
Embedded Examples not working faultlessly. :(

### ISSUE THREAD

**Issue by browniebraun** [krakjoe/pthreads#431]
I tried to execute a few embedded examples which unfortunately will always fail
on my test environment. (SUSE, 3.0.42-0.7, PHP 5.4.11, pthreads 2.0.10)

pthreads/examples/Stacking.php
pthreads/examples/StackableArray.php

>>>php Stacking.php
Stacking: 1/1
Stacking: 2/2
Stacking: 3/3
Stacking: 4/4
Stacking: 5/5
Stacking: 6/6
Stacking: 7/7
Stacking: 8/8
Stacking: 9/9
Stacking: 10/10
Setup ExampleWorker (140587355301632) Complete
failed to get worker something is wrong ...
Work Object
(
    [local] => Array
        (
            [0] => 46354913900
        )

    [worker] =>
)
failed to get worker something is wrong ...
.....
.....

>>>php StackableArray.php
StackableArray Object
(
    [0] => h
)
GOT 100 T's
StackableArray Object
(
    [0] => h
)

Any ideas what's going wrong? Seems to me that stackables are not working.

**Comment by browniebraun** [comment]
I've just checked both scripts on my Windows machine and they are working fine. (Windows7, PHP 5.4.28, pthreads 2.0.10) - weird. :/
Do you have any idea/hint what could be wrong with my first setup?

Regards
-Andi

**Comment by krakjoe** [comment]
The stacking example was removed (in 7) because it was buggy, I'm not able to reproduce any error with StackableArray.

If there is still a problem, please open a new issue.
