### ISSUE TITLE
Yii2 unable to access the framework context

### ISSUE THREAD

**Issue by vitorhorta** [krakjoe/pthreads#433]
I am trying to use pthreads on Yii2 to send emails asynchronously but I can't have access to the Yii base class when working in a Thread. Here is what I am trying:

class AsyncMailer extends \Thread {

    public $message;
    protected $id;

    public function __construct($id,$message) {
        $this->id = $id;
        $this->message = $message;
    }

    public function run() {
        \Yii::$app->mailer->compose('myTemplate', ['myVar' => 'test'])
            ->setFrom(\Yii::$app->params['supportEmail'])
            ->setTo('email@email.com')
            ->setSubject('My Subject')
            ->send();
    }
}

What I get is:   Class 'Yii' not found.

Could you please help me with this issue? 

Thanks in advance

**Comment by bnikola** [comment]
Your problem has been explained in #397

**Comment by vitorhorta** [comment]
Thanks for you answer bnikola but, like mitaichik and RamzyVirani, I still can't solve my problem.

Here is a list of what I tried so far:
1. Require Yii autoload inside and outside the "run" method
2. Require "yii2/Yii.php" which gives me "Cannot redeclare Yii class"
3. Override default inheritance behaviour with PTHREADS_INHERIT_NONE and PTHREADS_INHERIT_ALL

Also I tried running the exactly example at https://github.com/krakjoe/pthreads-autoloading-composer and it doesn't work for me as well.

Does anyone have a solution for this ?

**Comment by bnikola** [comment]
Did you try only with `PTHREADS_INHERIT_FUNCTIONS` and then requiring autoloader in the `run` method?

**Comment by vitorhorta** [comment]
Here is what I get trying this:

Fatal error: Cannot redeclare composerRequired2414c4777e3cf74e79d7ab8d7498589() (previously declared in autoload_real.php:52) in autoload_real.php on line 55

Fatal error: Cannot redeclare Composer\Autoload\includeFile() (previously declared in \ClassLoader.php:410) in ClassLoader.php on line 413

First error is coming from "require_once($this->loader);" on Autoloader Class run method.

Second error from "require(__DIR__ . '/../../vendor/autoload.php');" from Task Class run method. 

Using other constants gives me Yii not found.

**Comment by bnikola** [comment]
Right, that means you included autoloader in the code that tries to boot up your threads. Is it possible to include Yii autoloader *only* in thread's `run` method or you need the entire framework available inside / outside threads? The way I solved this problem was to create a "special" autoloader for threads that featured only changed name of the `composerRequire....` method. It sucks, but that's what has to be done.

**Comment by vitorhorta** [comment]
I think I need the entire framework available in thread's **run** method to do some relevant work inside it. It would be nice to have this working well so I could skip using cronjobs, queue etc...

**Comment by vitorhorta** [comment]
Fixed the issue including **index.php** which runs the application inside the **run** method.

Now it works nice but still have some problems. 
I can't use my async task and redirect to another page using  **$controller->redirect**. Sometimes it turns the task synchronous and sometimes it just doesn't execute.

Do you know why Redirect method cause this problem with my task ? Calling **render** and any **actionMethod** works good too, but sometimes we need to redirect!

**Comment by bnikola** [comment]
@vitorhorta - may I ask - why would you need threads? To me, it makes little sense that you would do redirect action from a controller. I must admit I don't know how Yii works, but I don't see a reason why a thread would have to initiate a redirect action. I'd reconsider using threads, they are extremely powerful and fun to work with but threading your application doesn't mean it will work quicker or better in any way.

**Comment by vitorhorta** [comment]
@bnikola The thread is not initiating a redirect action. My action does what it must do and leave the expensive work to a Thread and then the action redirects to another url. Please see the code below:

 public function actionFirst($id, $status)
    {
        /*Action working
          ...
        */
        
       AsyncMailer::sendMail($message); //Leaving the expensive work to Thread

       return $this->redirect(Yii::$app->urlManager->createUrl('url')); //Redirect to page
    }

    The problem is that the redirect causes the Thread to work synchronous or it just interrupt the Thread.

**Comment by bnikola** [comment]
You are not joining with the thread. Also, using threads really makes no sense in your context. You can't leave thread to do work while you redirect. The redirect in your context means leaving the PHP process, sending a `Location` header back to browser and initiating the whole new connection + acquiring a new PHP process, different to the one that you threaded, to do the work. Because you don't join with the thread, it sometimes hangs, sometimes doesn't execute. Technically, your choice to use threads for async mailing is the culprit. When used to serve web pages, PHP doesn't expose many features that people need, which long-running processes usually expose. This is why we create daemons and use message queues and have asynchronous systems that deal with tasks such as message sending. If I'm not mistaken, you should be able to do what you want using `register_shutdown_function` that deals with sending E-Mails, which executes after PHP is finished doing its work (in your case performing the redirect) - it's not ideal, and alternative is creating a daemon (either in PHP or any other language) which usually do much, much better job (from maintenance and resource usage POV).

However, the original issue was being unable to use Yii in threaded context. I think we solved the issue by using this:

- Use `PTHREADS_INHERIT_FUNCTIONS` when starting thread
- Create an autoloader for thread context where `composerRequire[hash_here]` contains a different name so no duplicate method declarations occur
- Include mentioned autoloader in thread's `run` method

I think that further talk is a bit offtopic because it relates to different approach to solve the problem, so if you agree, I think we could close the issue because the main question has been answered?

**Comment by vitorhorta** [comment]
@bnikola You are totally right, thank you very much for the support and all this explanation. 

One more thing, in my case I used PTHREADS_INHERIT_NONE when starting thread.

The issue can be closed now.

**Comment by shamyyl** [comment]
@vitorhorta I do not fully understand exactly how you solved the problem?

**Comment by JakeFalcor** [comment]
try `require_once` :)

**Comment by shamyyl** [comment]
of course this is also not working

**Comment by bnikola** [comment]
@shamyyl  - we went through step-by-step how to bootstrap a framework within a thread. It appears you didn't follow the bulletpoints exactly.

**Comment by shamyyl** [comment]
When i add ```require 'vendor/autoload.php``` there is throws exception

```
Fatal error: Cannot redeclare composerRequired6115553bdfa768fa745e19facbc91d1e()
``` 

There isn`t any solutions for this above

**Comment by bnikola** [comment]
@shamyyl  - I managed to bootstrap several frameworks in threads, and I posted a solution like a few guys before me. I can't force you to read carefully, but I can tell you didn't follow the steps exactly. I'd love to help you out, but if you refuse to read then how can we cooperate? When you invoke `$thread->start()` you must pass another argument, like this: `$thread->start(PTHREADS_INHERIT_NONE);` (that's how vitohorta did it). If you do that, then the method will not be defined in the thread (the method `composerRequired6115553bdfa768fa745e19facbc91d1e`) and you will not get a fatal error. If the described method doesn't work, you can the following simple check in `autoload_real.php`:

```php
if(!function_exists('composerRequired6115553bdfa768fa745e19facbc91d1e'))
{
    function composerRequired6115553bdfa768fa745e19facbc91d1e($file) {
        require $file;
    }
}
```

There was a PR for composer that addressed this issue but it was refused so you will have to modify the file manually.

Those are your only options, and they will definitely work

**Comment by shamyyl** [comment]
Using ```PTHREADS_INHERIT_NONE``` option didn`t give any effect. 

Framework classes can not be seen in thread`s run method.

**Comment by bnikola** [comment]
Alright, I'm sorry I was unable to help you. Maybe someone else with more knowledge will. Good luck nevertheless.

**Comment by shamyyl** [comment]
@vitorhorta, how do you solve the problem?

**Comment by vitorhorta** [comment]
@shamyyl Require the yii2 autoload and the index.php inside the Task run method using PTHREADS_INHERIT_NONE worked good for me.

Please check my Task Class:

class Task extends \Collectable
{
    public function __construct($message)
    {
        $this->message = $message;
    }

    public function run()
    {
        require_once(__DIR__ . '/../../vendor/autoload.php');
        require_once(__DIR__ . '/../../backend/web/index.php');

        //expensive work here
    }

    protected $message;
}

Another solution for async work is to use curl. To do this I've followed this post and made few changes:

http://petewarden.com/2008/06/10/how-to-post-an-2/comment-page-1/

Let me know if I can be more helpful to you.

**Comment by shamyyl** [comment]
I can`t use ```require_once(__DIR__ . '/../../backend/web/index.php');``` code, because i use console application.

there is my not working code:
```php
class MailerDaemonThread extends Thread
{
    protected $message;

    public function __construct($message)
    {
        $this->message = json_decode($message);
    }

    public function run()
    {
        require_once($_SERVER['PWD'].'/vendor/autoload.php');

        require($_SERVER['PWD'].'/vendor/yiisoft/yii2/Yii.php');

        $config = require($_SERVER['PWD']. '/config/console.php');

        $application = new \yii\console\Application($config);
        $application->run();

        $action = $this->message->_action;
        $data = $this->message->_data;

//        ConsoleTool::log('THREAD');
        (new MailerCommand('mailer-command', 'mailer'))->$action(...$data);
    }
}
```

Could this be due to the fact that I use a Thread class?

**Comment by vitorhorta** [comment]
Did you try running the example at https://github.com/krakjoe/pthreads-autoloading-composer ?
Try running it and then require autoload in the auto.php to check if you can access the framework.

Also note that my index.php is responsible for starting the yii2 application, so I think you should look for a similar file in your console application.
This file should contain something similar to:

$application = new yii\web\Application($config);
$application->run();

But with console instead of web.

Anyway if you want to send mail then I think you should really consider the curl option.

**Comment by shamyyl** [comment]
When i am using the example from [https://github.com/krakjoe/pthreads-autoloading-composer](https://github.com/krakjoe/pthreads-autoloading-composer), i have the same effect:
```
Class Autoloadable not found
```

**Comment by shamyyl** [comment]
Problem solved. This is my solution for yii console application:

I included next lines in thread`s run method from ./yii file:

```php
       defined('YII_DEBUG') or define('YII_DEBUG', true);

        // fcgi doesn't have STDIN and STDOUT defined by default
        defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
        defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

        require_once($_SERVER['PWD'].'/vendor/autoload.php');
        require_once($_SERVER['PWD'].'/vendor/yiisoft/yii2/Yii.php');

        $config = require_once($_SERVER['PWD'].'/config/console.php');

        $application = new \yii\console\Application($config);
```
as you can see without ```$application->run()``` code. And it works!

@vitorhorta, @bnikola Thank you very much for your help!

**Comment by krakjoe** [comment]
Closing, since you got your help, and this isn't really the place to ask ... SO FTW ;)
