### ISSUE TITLE
Segmentation fault circular reference - Accessing Pool from within Thread. 

### ISSUE THREAD

**Issue by relentless1** [krakjoe/pthreads#434]
Hi,

Basically I'm trying to write a web crawler, I'm using Pooling based on the code from the bottom of this page:

http://php.net/manual/en/class.pool.php

As it's a web crawler the worker threads need to be able to add new jobs to the pool, every time I try make reference to the pool from within the thread it throws a Segmentation fault. I've tried a few different ways but all end up with the same fault:

1. From the example above I add the Pool to the Config object:

    $config->pool = $pool;

2. Tried setting a $pool property to Task class and setting it with the constructor:

    Class Task extends Stackable{   
    protected $pool;
    public function __construct($pool){
        $this->pool= $pool;
    }

     $pool->submit(new Task($pool));

3. Lastly I tried forgetting about referencing the pool from within the Thread and tried to wait for new tasks externally however this just after processing a few tasks: 

    while ($config->arr->count() > 0) {
    
    $link = $config->arr->shift();
    
    echo "adding task $i total:".$config->arr->count()."\n";

    $pool->submit(new Task($link));
   
   if ($i==0) {
   
        sleep(10); //wait for new tasks
   
   }
   
    $i++;
 
    }       
        

$pool->shutdown();

Number 1 and 2 will throw a segmentation fault due to a circular reference I believe. For the life of me I can't see how to add new tasks to the pool from within the Thread.

Help!

Thank you

**Comment by SirSnyder** [comment]
Pool is not threadable. Please read https://gist.github.com/krakjoe/9384409

"The Pool class is not thread safe; it therefore cannot be used from multiple contexts, since the underlying Worker class has restrictions that make this necessary."

**Comment by relentless1** [comment]
Ok that makes sense. How could I know if all threads within the Pool have finished? I see the collect() method but don't see how that can tell me if there are no more tasks in the Pool to run?

**Comment by relentless1** [comment]
The provided pthreads example throws a segmentation fault also:

https://github.com/krakjoe/pthreads/blob/master/examples/StackableArray.php

Is this up to date?

**Comment by krakjoe** [comment]
If there is still a problem here (not able to reproduce myself), please open a new report.
