### ISSUE TITLE
Sharing object between threads

### ISSUE THREAD

**Issue by russianlagman** [krakjoe/pthreads#435]
Hi, how to share SplObjectStorage object between two threads?

**Comment by pfofi** [comment]
Not possible, `SplObjectStorage` isn't thread-safe.
http://stackoverflow.com/a/31269338/2032498

Maybe you can create your own `SplObjectStorage` implementation by utilizing [`spl_object_hash()`](http://php.net/spl_object_hash) somehow.

**Comment by krakjoe** [comment]
Sorry this is not the place to get help with code.
