### ISSUE TITLE
[BUG] PHP 5.6 has ZTS enabled, but pthreads states it isn't.

### ISSUE THREAD

**Issue by CozyLife** [krakjoe/pthreads#436]
I've enabled ZTS and the output of phpinfo() shows "Thread Safety: Enabled," yet when I run pecl install pthreads, I get the error, "checking checking for ZTS... configure: error: pthreads requires ZTS, please re-compile PHP with ZTS enabled."

I'm running PHP 5.6.7 on my development rig, and pthreads supports a minimum of 5.3. Has pthreads been tested with PHP 5.6?

UPDATE: I figured out what's going on. My client interface isn't ZTS enabled, but my web environment is.

**Comment by wagnert** [comment]
Can you attach your configure string, please. Pthreads itself works with PHP 5.6!

**Comment by CozyLife** [comment]
There are two configure strings, but only one is accessible in PHP 5.6.7 AFAIK. The configure script uses php-config to get the configure params among other things, and the output of that is not that of a ZTS enabled setup. However, my rig uses the [Webtatic release](https://webtatic.com/packages/php56/) for CentOS 7 which uses php-zts for everything ZTS enabled, while anything not specifying the -zts suffix is not a ZTS environment.

It'd be nice to have the option of manually specifying configure parameters to differentiate between the environments, so I'll reopen this issue. The cli isn't ZTS enabled, and that really sucks that there isn't a ZTS version for it, so the configure script was unreliable.

**Work Around**

I haven't started programming with pthreads yet, but I did manage to get it installed on my web environment. For anyone who might find this information useful, here's how I did it.

- Install the Webtatic release for both the ZTS environment (mod_php - Requires Apache 2.2+) and the non-ZTS environment. (php56w and php56w-cli) Also, install php56w-devel for the development SDK. In CentOS 7 based systems, you use Yum as follows.
```
sudo rpm -Uvh https://mirror.webtatic.com/yum/el7/epel-release.rpm
sudo rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
sudo yum install php56w php56w-cli php56w-devel mod_php
```
Make sure that your Apache config has MPM set to "Worker" mode, not "prefork."
- Go to /usr/include and rename your "php" directory to "php_OLD" and create a symlink from /usr/include/php-zts/php to /usr/include/php.
- Install pthreads as you normally would.
- Remove your symlink.
- Move the pthreads.so file from /usr/lib64/php/modules to /usr/lib64/php-zts/modules. Don't copy the file as the environment you just installed it to does not support ZTS. You should move the file so you don't wind up with bugs later.
- In your /etc/php-zts.d directory, add an ini file with the line ``` extension=pthreads.so ```. Don't add it to your /etc/php.d directory!
- Restart Apache and check to see that pthreads shows up in your phpinfo() output.

**A word of caution**
I have yet to start programming in pthreads yet, so I don't know if everything is stable in installing it that way.

**Comment by chibisuke** [comment]
if you have multiple php versions installed, they reside in different 
paths.
You can |use the configure option --with-php-config to specify which one 
to use.

example: |
|./configure --with-php-config=/usr/local/php5/bin/php-config5|||

**Comment by CozyLife** [comment]
I'm using the same version of PHP, but with two different environments, so that configure option doesn't work. They both rely on the same php-config. The only difference in the environment is the static object libphp5-zts.so which is an Apache module.

**Comment by chibisuke** [comment]
Then you should check/fix your PHP installations. All modules reply on the correct php-config to be used, especially since the module path is different for TS/non-TS versions. Using the same php-config for two PHP installations will only work if the configure args and version are the same, which can't be true for ts/non-ts version.

**Comment by CozyLife** [comment]
I don't have much of a choice unless I want to recompile my entire PHP distro and redo all of my config. I've moved on to a different tactic using concurrent streams instead of hardware based separation. Check out the link I showed you if you want to learn more about the release I'm using if you plan on changing the code. Thanks!

**Comment by chibisuke** [comment]
compiling PHP yourself is actually the easiest variation of all 
possibilitys I found so far.

you put all the modules you want in the ext directory, run buildconf and 
then build just normally as if they'd be part of the distribution. I 
don't know why most ppl are afraid of building stuff themselfs.

**Comment by CozyLife** [comment]
I'm not afraid of it, and I've built many programs. My reasoning is that it's a headache to constantly build everything I need, and redo it when something changes. Plus, the fact that most programs have dependencies, but no one tells you where to get them. Sometimes the dependencies need to get compiled for the distro I'm using. Sometimes I can't figure out what dependency is needed, and I get odd cryptic error messages I need to spend hours trying to decode.

Compiling, IMO, should only be done by the software devs who either create or wish to modify the software. People shouldn't have to compile your program just because they can. That's the whole reason for Yum, and apt-get. The only problem is, not everything is available through a repo.
