### ISSUE TITLE
Can't initialize codeginiter CI object while working with threading

### ISSUE THREAD

**Issue by pareshbalar** [krakjoe/pthreads#439]
Hi,

I want to get CI object with threading but i'm getting this error.

"Fatal error: Cannot assign by reference to overloaded object"

here is the sample code.

class Test extends Thread {

	public $ci = NULL;
	
	public function __construct()
	{
		$this->ci = &get_instance();
	}
	
	public function run()
	{
		var_dump($this->ci);	
	}
	
}

$test = new Test();
$test->run();

Also i tried to pass CI object through constructor then my PHP crashed :(

Sample code for that

class Test extends Thread {

	public function __construct($ci)
	{
		$this->ci =$ci;
	}
	
	public function run()
	{
		var_dump($this->ci);	
	}
	
}

$CI = &get_instance();
$test = new Test($CI);
$test->run();

**Comment by bnikola** [comment]
You have to perform CodeIgniter initialization in the Thread's `run` method, not in constructor. I think that this issue pops up every once in a while and it's due to lack of reading the examples and other issues. Basically, include autoloader in the `run` method and create your CodeIgniter instance there. You cannot save an instance of a resource in a member of a thread, it's related to sharing and a lot of other things explained nicely by great guys who maintain this project. Please, take some time and go through examples and other similar issues. For example, Yii related problems have exactly the same "fix" - issues #397 and #433

**Comment by pareshbalar** [comment]
Tried that also. its not working.

class Test extends Thread {

public function __construct()
{
}

public function run()
{

}

}

$CI = &get_instance();
$test = new Test($CI);
$test->run();

**Comment by bnikola** [comment]
The code you posted doesn't include the autoloader in run method nor does it instantiate CI object. It just creates a thread that does nothing.

**Comment by pareshbalar** [comment]
comment was posted by mistake.

here is the code.

class Test extends Thread {

public function __construct()
{
}

public function run()
{

}

}

$CI = &get_instance();
$test = new Test($CI);
$test->run();

**Comment by pareshbalar** [comment]
Also Why PHP is getting crashed when i'm using this code. i'm just passing CI object in constructor.

class Test extends Thread {

public function __construct($ci)
{
    $this->ci =$ci;
}

public function run()
{
    var_dump($this->ci);    
}

}

$CI = &get_instance();
$test = new Test($CI);
$test->start();

**Comment by bnikola** [comment]
You can't pass non-thread safe objects to the constructor. Did you read any of the related issues or the guide about how to use threads and what you can "pass" to the constructor?

**Comment by pareshbalar** [comment]
Sorry, do not have time for that currently. will explore thread later on in detail.
currently just want to implement it.
Please can you share example how will i get CI instance in thread run method ?

**Comment by bnikola** [comment]
Sorry, do not have time for that currently. This matter has been covered, if you can't be bothered  to read then why use threads?

**Comment by pareshbalar** [comment]
Cool. Thanks for the reply Nikola. appreciate your help today.
and implementing the "special" autoloader for threads should not be the
solution.

On Wed, Apr 22, 2015 at 8:04 PM, Nikola <notifications@github.com> wrote:

> Sorry, do not have time for that currently. This matter has been covered,
> if you can't be bothered to read then why use threads?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/krakjoe/pthreads/issues/439#issuecomment-95208955>.
>



-- 


Regards,
Paresh Balar

**Comment by bnikola** [comment]
You said you have no time to read pthreads documentation. You didn't read similar tickets. You don't even understand *why* I even told you to include autoloader in Thread's `run` method. If you won't read and if you refuse to **understand**, why are you even asking questions here? I tried to help you, your decision was to be rude to the point where you ask for copy paste code to stick in your spaghetti app. Congratulations and good luck getting further help. This issue should be closed, it's ID: 10T type of issue.

**Comment by pareshbalar** [comment]
Hey Nikola, Sorry if you feel i'm rude.
i just said i do not have time currently because issue was urgent.
also i'm using bonfire. and tried to include autoloader in thread's run method. but it is showing error because there is dependency of $RTR global variable for loading helper and libraries.
i also tried to run thread in virgin context and load bonfire using it's index.php file but there is issue of system folder path.
