### ISSUE TITLE
Pool stalls when new work begin submitted is limited

### ISSUE THREAD

**Issue by cpriest** [krakjoe/pthreads#443]
I suspect that ->submit() is what/where the code/collection cleanup is happening.

In my current code I simply have it creating a Collectable for each directory to iterate over.  Each collectable simply iterates over the directory, adding directories to a shared data array.  In the main thread of execution there is an infinite loop that adds new collectables for new directories found from the collectable.

If I limit the number of 'outstanding' work that is ->submit()'d to the pool, it stalls.  If I eliminate the outstanding work limit, it runs to completion just fine.

I'm calling ->collect() on each iteration through the main loop and then adding new work if there is work remaining.

Perhaps this is related to #441 in that the work is actually completed but the Collectable is not always being released from ($this->work) from within the pool.  Ergo once the work queued reaches the limit I impose then it stalls because the Pool thinks it has no more work remaining while its work count indicates otherwise.

**Comment by cpriest** [comment]
More evidence to support this, as I tighten how much outstanding work can exist before new work is submitted, the problem gets worse.

At 10 threads with max work being 5x threads it stalls rather rapidly (2351 / 8231), at 20x it gets to about (5k / 8k) 

Adding a gc_collect_cycles() in the loop seems to help w/ the problem at 20x but it still does not always completed.  At 5x the gc_collect_cycles() had almost no effect.

**Comment by krakjoe** [comment]
Hi Clint :)

I'm hella busy right now, it might be next weekend before I get to dig deep into this ... do post anything else you find ...

**Comment by cpriest** [comment]
No worries, I could not find any further rhyme or reason to it and 
eventually just took out the stop lights for now.

**Comment by krakjoe** [comment]
This should be fixed in 7 as mentioned in other bugs .... sorry the response took forever and sorry I haven't solved the problem in 5, but there is only one of me ;)

**Comment by cpriest** [comment]
No problem Joe, I know the feeling!
