### ISSUE TITLE
Error in `php': double free or corruption (!prev)

### ISSUE THREAD

**Issue by wake-up-neo** [krakjoe/pthreads#444]
Trying to use pthreads for content collector through the REST API.

As it millions of requests with gigs of data I need to split the process into multiple threads.

How it works:
N requests were splitted among 8 (cpu cores) threads, each thread uses multi-curl with allowed 20 parallel requests at the time. In +/- one minute the application falls down with "Error in `php': double free or corruption (!prev)". 

I believe in 2 possible reasons:
1) pthreads + multicurl
2) pthreads + passing instance ($this) into thread

The way I use pthreads:

    final class AsyncClosure extends \Thread
    {
        protected $closure;
        protected $config = [];

        public function __construct($closure, array $config = [])
        {
            $this->closure = $closure;
            $this->config = $config;
        }

        public function run()
        {
            spl_autoload_register('autoload');
            $closure = $this->closure;
            if (is_callable($closure)) {
                $closure($this->config);
            }
        }
    }

/////////////////

    $threads = [];
    for ($i = 0; $i <= $slices; $i++) {
        $threads[$i] = new AsyncClosure($process, [
             'instructions' => $this->instructions_2,
             'data' => array_slice($data, ($i * $length), $length, true),
             'instance' => $this
         ]);
         $threads[$i]->start();
    }

The same code/approach with multi-curl but without splitting into threads works for several hours without problems.

**Comment by pfofi** [comment]
It's hard to reproduce this without a working code sample.
Could you provide a simple working code sample that reproduces this error?

**Comment by krakjoe** [comment]
In order to help, I need minimal executable code that reproduces the issue.

Feel free to reopen or open a new issue with requested information.
