### ISSUE TITLE
Exceptions not throwing when thread instantiated in class

### ISSUE THREAD

**Issue by petehayes102** [krakjoe/pthreads#445]
Hi Joe,

I've found an issue where I can't throw exceptions if a thread is instantiated within a class. I.e.

    <?php
    
    new MyClass();
    
    class MyClass {
        public function __construct() {
            $thread = new MyThread();
            $thread->start();
    
            echo 'You can see this immediately', PHP_EOL;
            throw new Exception('But this is delayed');
        }
    }
    
    class MyThread extends Thread {
        public function run() {
            sleep(2);
        }
    }

However if I modify the code slightly to instantiate the thread outside of the class, it throws the exception without waiting for the thread to terminate:

    <?php

    new MyClass(new MyThread());

    class MyClass {
        public function __construct($thread) {
            $thread->start();

            echo 'You can see this immediately', PHP_EOL;
            throw new Exception('But this is delayed');
        }
    }

    class MyThread extends Thread {
        public function run() {
            sleep(2);
        }
    }

Any ideas?

Cheers mate!

**Comment by chibisuke** [comment]
you're creating a thread object as a local variable and then running the 
thread.

Using pthreads you're responsible to keep references to all your objects 
until the thread is terminated, so your thread objects gets deleted 
while the thread is still active.

**Comment by petehayes102** [comment]
Ah, yes you're totally right. Thanks mate!!
