### ISSUE TITLE
No output on Windows running PHP 5.6

### ISSUE THREAD

**Issue by fletchto99** [krakjoe/pthreads#447]
I'm running [PHP version 5.6 x86 for Windows](http://windows.php.net/download/) (thread safe version) and I'm trying to get pThreads working. I've followed the instructions posted in the ReadMe.md however pThreads does not appear to work correctly.

PHPInfo reports Thread Safety is enabled and pThreads v2.0.10 is enabled under the extensions section however when I navigate to my test.php page which has the example directly from the ReadMe, the page is just blank. I've modified the code slightly to:

````php
<?php

class AsyncOperation extends Thread {
  public function __construct($arg){
    $this->arg = $arg;
  }

  public function run(){
    if($this->arg){
      printf("Hello %s\n", $this->arg);
    }
  }
}
$thread = new AsyncOperation("World");
if($thread->start())
  $thread->join();

echo 'This is the only thing printed on the page';

?>
````

And the only thing on the screen is the echo statement 'This is the only thing printed on the page'

**Comment by fletchto99** [comment]
So I can't really explain this but calling phpinfo then running the Async task allows it to work. 

````php
<?php

phpinfo();

class AsyncOperation extends Thread {
  public function __construct($arg){
    $this->arg = $arg;
  }

  public function run(){
    if($this->arg){
      printf("Hello %s\n", $this->arg);
    }
  }
}

$thread = new AsyncOperation("World");
if($thread->start())
  $thread->join();

echo 'This works!! But now it's below PHP info output';

?>
````

**Comment by fletchto99** [comment]
So to make this even stranger, calling phpinfo with specific parameters makes hello world display or not display.

For example:

````php
<?php
phpinfo(TEST_PARAMETER);

class AsyncOperation extends Thread {
  public function __construct($arg){
    $this->arg = $arg;
  }

  public function run(){
    if($this->arg){
      printf("Hello %s\n", $this->arg);
    }
  }
}
$thread = new AsyncOperation("World");
if($thread->start())
  $thread->join();

?>
````

Hello world will be printed with the above code if TEST_PARAMETER is replaced with 32. But Hello World will **not** be printed if TEST_PARAMETER is replaced with 64.

**Comment by fletchto99** [comment]
Alright so I've done some more testing. It appears that executing the script **without** the phpinfo via command line works but via a browser it does not. This leads me to believe it's a php.ini/iis configuration issue?

**Comment by JakeFalcor** [comment]
Considering it works via console but not by browser, there seems to be server caching mechanism working which prohibits output to be displayed in the process until it's buffer is full. Try forcing explicit flushing by calling `flush()` (check output buffering family functions - http://php.net/manual/en/ref.outcontrol.php - and try to mess with them around).

I would also suggest trying to save files using file_put_contents or similar functions from inside threads to check they are really working. In my opinion, one should not rely on threads echo'ing anything to output.

As for myself, I happily managed to get pthreads working with `Pool`s and workers, so I can definitely say they are worth looking into (and they displayed output too).

**Comment by fletchto99** [comment]
@JakeFalcor I've tried to forcing the buffer to flush without success as well. The funny thing is that if I call `ob_start()` then `phpinfo()` followed by `ob_end_clean()` then run the multithreaded code, nothing is printed. But without the ob_ code, the echo is there. I'll try writing the contents to a file instead of echoing them and see what happens, but ultimately I will be echoing the contents.

**Comment by JakeFalcor** [comment]
Then maybe storing what you intend to echo in some shared variable would be they way to go? I mean, you could use the logger example (couldn't find a link though). From what you're saying, I'm judging you want some sort of an heavy duty application which would output results of it's operation to browser.

Also, I have tested your example code on windows with apache 2.4/php 5.6.8 x86, and had no issues regarding anything not being displayed. You have also said that by running code from console (i.e. calling php interpreter directly) there was no issue. This further suggests that some buffering mechanism, specific to IIS, is at fault.

As for usage of pthreads, I strongly recommend using higher abstraction level classes, like workers/threaded/pools, unless you specifically need this much degree of control over every thread.

**Comment by fletchto99** [comment]
The final implementation will be for printing multiple PDF files, and will be using a pool, along with workers. I'm using wkhtml to generate multiple PDFs and wkhtml is extremely slow at rendering the JS. ~10-15sec per PDF. Approximately 30 PDFs are generated, zipped and then sent to the client for download.

**Comment by fletchto99** [comment]
The final implementation will be for printing multiple PDF files, and will be using a pool, along with workers. I'm using wkhtml to generate multiple PDFs and wkhtml is extremely slow at rendering the JS. ~10-15sec per PDF. Approximately 30 PDFs are generated, zipped and then sent to the client for download.

**Comment by krakjoe** [comment]
This is a output buffering problem: Zend provides no mechanism to make safe writing to a single stream from multiple threads and by default uses output buffering. If Thread #1 writes the standard output of the main process, it allocates from the request memory pool the buffer, if the main process then tries to free the buffer (when it is flushed) you will get a fault and Zend will complain (share nothing is breached).

The best thing to do is avoid it, it happens to work in CLI mode but only by chance and it's not very robust.

Unfortunately, there isn't anything I can do to change it, so I'm going to close the bug.

**Comment by pfofi** [comment]
@krakjoe, if I understand you correctly, it's generally dangerous to write anything to the output buffer from within a thread.

Would it be possible to let pthreads throw an exception in the main thread once it's joined with a thread that wrote (or attempted to write) something to the output buffer?

Perhaps make the exception optional with an ini option, say pthreads.prevent_thread_output, which defaults to on?

**Comment by JakeFalcor** [comment]
In my opinion, there is no point in forcing anything on anyone. Pthreads in it's current designed is supposed to be for specific group of "power php" users, which take the responsibility of handling their code properly.

In my own code, I capture my output in threads using ob_start and family functions and pass them back as variable - seems to be working just fine in both windows and freebsd environments. Then allow main thread to decide whether to display it or not.

If however your suggestion is considered valid and some mechanism for working with it is implemented, I believe it will be handled just like all the other pThreads options in php implemented by krakjoe: by using [predefined constants](http://php.net/manual/en/pthreads.constants.php). I can't find proper documentation for those, but you might take a look at them. I used them for my own app and I'll post if I re-find any related docs or examples.

**Comment by pfofi** [comment]
Ah yes, `PTHREADS_ALLOW_HEADERS` seems to go in the way I was suggesting.

So headers from threads are already disabled by default. They are, in fact, dropped silently. That seems rather forcefully to me. Maybe the next step is `PTHREADS_ALLOW_OUTPUT`.

**Comment by JakeFalcor** [comment]
I'd like to just reiterate for future reference, that options mentioned earlier can be found here: http://php.net/manual/en/thread.start.php
