### ISSUE TITLE
PHP pthreads difference performance in the browser and console on WINDOWS

### ISSUE THREAD

**Issue by Bargoor** [krakjoe/pthreads#449]
Hello.

I installed Pthreads library on windows from instructions you can found here
http://php.net/manual/en/pthreads.installation.php
It has been installed correctly.

BUT

I ran a few times a script Benchmark.php downloaded from here
https://github.com/krakjoe/pthreads/blob/master/examples/Benchmark.php

    class T extends Thread {
    	public function run() {}
    }
    
    $max = @$argv[1] ? $argv[1] : 100;
    $sample = @$argv[2] ? $argv[2] : 5;
    
    printf("Start(%d) ...", $max);
    $it = 0;
    do {
        $s = microtime(true);
        /* begin test */
        $ts = [];
        while (count($ts)<$max) {
            $t = new T();
            $t->start();
            $ts[]=$t;
        }
        $ts = [];
        /* end test */
        
        $ti [] = $max/(microtime(true)-$s);
        printf(".");
    } while ($it++ < $sample);
    
    printf(" %.3f tps\n", array_sum($ti) / count($ti));

#Windows console:

It is working properly:
#First run 1102 Thread per s
http://screenshu.com/static/uploads/temporary/m5/ah/x0/eh1bs4.jpg

#Second run 974 Thread per s
http://screenshu.com/static/uploads/temporary/s7/jv/cs/jaxu3r.jpg

RAM used ~600MB http://screenshu.com/static/uploads/temporary/mo/yk/hg/fa4m1b.jpg

When the script finishes, php.exe process is finished and released from memory

#Browser (FF and Chrome same error)

#First run 1175 Thread per s  and 161 RAM
http://screenshu.com/static/uploads/temporary/82/v6/56/5aigh6.jpg

#Second run 565 Thread per s  and 534 RAM
http://screenshu.com/static/uploads/temporary/yg/j8/85/tx5ms7.jpg

#Third run 235 Thread per s  and 977 RAM
http://screenshu.com/static/uploads/temporary/gb/sz/6q/kd1jtm.jpg

When the script finishes process <b> httpd.exe IS NO RELEASED FROM MEMORY .</ b>

In the worst case performance dropped to 20 tps and httpd.exe eat 6GB RAM

Configuration:

    > Windows 7 64 bit
    >
    > WampServer64 
    > PHP Version :5.5.12  
    > (php info) 
    > Compiler MSVC11 (Visual C++ 2012)
    > Architecture x64
    > Zend Extension Build API220121212,TS,VC11
    > PHP Extension Build API20121212,TS,VC11  
    > Thread Safety 	enabled 
    >
    > Apache Version :2.4.9
    > 
    > Procesor: i7-4790k

I care for run scripts using pthreads in the browser. Does anyone know why this is happening? 

Please help.

**Comment by bnikola** [comment]
This appears to be Apache related, not PHP related, let alone pthreads related. God knows what happens with Apache, especially on Windows, which is why no sane people use Windows and Apache to serve PHP.

**Comment by krakjoe** [comment]
This is not a bug.
