### ISSUE TITLE
Worker stalls eventually

### ISSUE THREAD

**Issue by pfofi** [krakjoe/pthreads#450]
I might be wrong, but shouldn't this run forever?
```php
class Work extends Threaded
{
    public $inProgress = true;

    public function run()
    {
        static $count = 0;
        echo ++$count, PHP_EOL;

        self::synchronized(function () {
            $this->inProgress = false;
            self::notify();
        });
    }
}

$work = new Work;
$worker = new Worker;
$worker->start();
for (;;) {
    $worker->stack($work);
    $work->synchronized(function () use ($work) {
        if ($work->inProgress) {
            $work->wait();
        }

        $work->inProgress = true;
    });
}
```
It just hangs after a few thousand iterations.

Using PHP 5.6.10 with pthreads 2.0.10 under Linux amd64. Same issue with pthreads-master.

**Comment by pfofi** [comment]
This is perfectly normal behavior. There is no guarantee the worker thread will fire `notify()` while the main thread is waiting.

I did not know what I was doing :)

**Comment by 2072** [comment]
This might be a case of [spurious wakeup](https://en.wikipedia.org/wiki/Spurious_wakeup) which, although rare, are a possibility with most POSIX Thread implementations.

In your first code sample, try to replace:

```php
if ($work->inProgress) {
            $work->wait();
}
```

with:

```
while ($work->inProgress) {
            $work->wait();
}
```

**Comment by pfofi** [comment]
Interesting. When using `while` instead of `if`, it locks up even faster.

**Comment by chibisuke** [comment]
There is a 2nd spot where you have the same issue.

                 if  ($this->queue->count()<  1) {
                     self::wait();

the if should be while aswell.

**Comment by pfofi** [comment]
Thanks for the input, but I don't think this is a case of spurious wakeup (at least not in userland). Even if `wait()` were to awake before the condition is `true`, another call to `stacked()` would be issued a bit early and that's all.

Also, my second example using only `Thread` runs just fine with single `if`.

Here is another example where `Worker` stalls (not using `wait()` this time):
```php
class Work extends Threaded
{
    public static $i = 0;

    public function run()
    {
        ++$this->i;
    }
}
$work = new Work;
$worker = new Worker;
$worker->start();
for (;;) {
    echo "\r", $work->i; // stops increasing after few ten thousands
    if ($worker->getStacked() < 2) {
        $worker->stack($work);
    }
}
```
The main thread doesn't stall, but `getStacked()` won't return a value less than 2 at some point.

**Comment by pfofi** [comment]
I present new evidence to the court. This time `Thread` is affected.

```php
$iMax = 30000;
for ($i = 0; $i < $iMax; $i++) {
    (new Thread)->start(PTHREADS_INHERIT_NONE);
}
echo "finished\n";
```

Sometimes `finished` won't be printed and the process just hangs without load.
The chance that this occurs increases with `$iMax`.

The whole issue might be machine-dependent. I'm investigating.

**Comment by krakjoe** [comment]
I'm going to call this solved in PHP7, I get bored at 4 million ...

```php
<?php
class Work extends Collectable
{
	public $inProgress = true;

	public function run()
	{
	    static $count = 0;
	    echo ++$count, PHP_EOL;

	    $this->synchronized(function () {
	        $this->inProgress = false;
	        $this->notify();
	    });
	}
}

$worker = new Worker;
$worker->start();
for (;;) {
	$work = new Work();
	$worker->stack($work);
	$work->synchronized(function () use ($work) {
	    while ($work->inProgress) { 
	        $work->wait();
	    }
	});

	while ($worker->collect(function (Work $work) : bool {
	            return $work->isGarbage();
	})) continue;
}
```

I am too tired to explain how I done that ... but I done it ... yay php7 :)

**Comment by pfofi** [comment]
Thank you, Joe. Works great!
Have to wrap my mind around the new interface, can't wait to read the docs :)
