### ISSUE TITLE
Getting seg fault

### ISSUE THREAD

**Issue by chippyash** [krakjoe/pthreads#451]
This is a request for help, not a bug report, so if there is a better place to do this, happy to oblige.

I have a bit of code that emulates a Scala like For comprehension using an [Assembly builder](https://github.com/chippyash/Assembly-Builder) pattern and thought that the next step would be to create an async Assembler.  After many blind alleys I came across your code, and I almost have it working - huzzah!

Here is the basic code:

<pre>
class Future extends Thread
{
    protected $closure;
    protected $args;
    protected $result;

    public static function of(Closure $closure, array $args = []) {
        $future =
            new self($closure, $args);
        $future->start();
        return $future;
    }

    public function run() {
        $closure = $this->closure;
        $this->synchronized(function() use($closure) {
            $this->result =
                $closure(...$this->args);
            $this->notify();
        });
    }

    public function getResult() {
        return $this->synchronized(function(){
            while (!$this->result)
                $this->wait();
            return $this->result;
        });
    }

    private function __construct(Closure $closure, array $args = []) {
        $this->closure = $closure;
        $this->args    = $args;
    }
}

class AAssembler extends \Assembler\Assembler
{
    /**
     * Run the Assembly not returning any value.
     * Assembly will not overwrite anything already assembled
     *
     * @return $this
     */
    public function assemble()
    {
        foreach ($this->placeHolders as $name => $placeholder) {
            if (!isset($this->values[$name])) {
                $this->values[$name] = Future::of($this->addVars($placeholder));
            }
        }

        return $this;
    }

    /**
     * Execute the function assigned to the value, binding in values created earlier
     * in the assembly
     *
     * @param \Closure $func
     *
     * @return mixed
     */
    protected function addVars(\Closure $func)
    {
        $args = (new \ReflectionFunction($func))->getParameters();
        if (count($args) === 0) {
            return $func;
        }

        $fArgs = array_values(
            array_intersect_key(
                $this->values,
                array_flip(
                    array_map(function ($value) {
                        return $value->getName();
                    },
                        $args
                    )
                )
            )
        );

        return function() use($func, $fArgs) {return call_user_func_array($func, $fArgs);};
    }
}
</pre>

and the script that I am using to test it:

<pre>
include "../vendor/autoload.php";
include "./AAssembler.php";

function doRunRun($n, Future $f = null)
{
    echo "foo $n started\n";
    sleep(mt_rand(1, 3));
    echo "foo $n finished\n";
    if (!is_null($f)) {
        echo $f->getResult() . "\n";
    }
    return $n;
}

$a = AAssembler::create()
    ->r1(function(){return doRunRun(1);})
    ->r2(function(){return doRunRun(2);})
    ->r3(function(){return doRunRun(3);})
    ->assemble();
</pre>

Now this works absolutely fine, and I can see from multiple runs that indeed it is running async.  The problem is that when I try to inject the results of say r1 into r2, as per the spec for an Assembler. e.g.

<pre>
$a = AAssembler::create()
    ->r1(function(){return doRunRun(1);})
    ->r2(function($r1){return doRunRun(2, $r1);})
    ->r3(function(){return doRunRun(3);})
    ->assemble();
</pre>

Then I get a seg fault `2718 Segmentation fault`.   I appreciate that I have probably missed something in reading your nice articles (I'm a great fan of devs doing documentation btw, so thanks!), but blowed if I can figure it out.

Any help would be appreciated.  Once I can get past the basics, I have all sorts of projects I can use this on ;-)

**Comment by chippyash** [comment]
Forgot to mention, here is the composer.json file:

<pre>
{
    "name": "chippyash/async",
    "require": {
        "chippyash/assembly-builder": "^1.0",
        "chippyash/monad": "^1.2",
        "chippyash/strong-type": "^2.1"
    }
}
</pre>

pthread is not included in the require atm, as this is of course, test code and couldn't work without it!

**Comment by 2072** [comment]
You should provide a backtrace and a PHP-side backtrace, you can do the later by following the steps I followed in https://github.com/krakjoe/pthreads/issues/273#issuecomment-68567695 (using gdb and a debug enabled PHP build):  : 

once in gdb:

load some useful gdb macros:

`source /usr/local/src/php5-build/php-5.6.4/.gdbinit`

set $tsrm_ls: (you can find the value in the bactrace, as it is part of every function call)

`set_ts 0x2f79dd0`

Set $eg (uses the $tsrm_ls set above):

`____executor_globals`

(you can get a list of threads using `info threads` and switch using `thread #`)

And finally get a PHP-side bactrace:

`dump_bt $eg.current_execute_data`

**Comment by chippyash** [comment]
@2072 - most of your comment doesn't make sense, 'cus guess what - in 15 years of using PHP, I've never had to create a debug build, run php in debug mode etc.  This rather points to the fact that pthreads is not perhaps 100% production ready yet.  But hey ho, I have tried to follow your instructions and have built a debug version and then run it - output is at http://pastebin.com/dtB4eL5d. I'm afraid your instructions have lost me at `set $tsrm_ls:`  how do |I do that, and the rest of it?

**Comment by JakeFalcor** [comment]
Being rude to someone is no way of getting assistance, but hey...

What 2072 asked is perfectly fine - after all, you're getting segmentation faults, probably when php thread is trying access memory which it was not allowed to. Getting debug build could allow you to pinpoint what was happening at the time (debugging threads is somewhat difficult) and determine what was misbehaving.

Please give https://gist.github.com/krakjoe/6437782 a read.

**Comment by chippyash** [comment]
@JakeFalcor Sorry if my response appears rude, I just re-read it and don't see it.  I had already read @krakjoe's article but did so again, just in case. I have debug dump - just don't understand how to get to the point that 2072 wants me to get to.

**Comment by 2072** [comment]
@chippyash your comment indeed feels rude but despite that fact I will use some more of my time to help you and, I hope, any one else interested in getting a php-side backtrace using GDB

So,

If `set_ts` doesn't work it means that the GDB macros for PHP where not loaded.

once in GDB type `source /usr/local/src/php-5.6.10/.gdbinit` (make sure that the path and permissions are right)

Once you did that type:

`bt` 

this will print a C-side backtrace where you will find the tsrm_ls value you need to use with the `set_ts` GDB macro. if you get that part right then the `____executor_globals` and the `dump_bt $eg.current_execute_data` commands should work and the later will give you a PHP-side backtrace pointing you at the exact line that triggered the segmentation fault.

for example in the output you provided you should have typed `set_ts 0x1351b90` (you can see this value on line 25)

As there are several threads, you can switch between them use `thread #` where # is the number of the thread you want to switch to. You can get a list of existing threads using `info threads`. Each time you switch thread you need to call `bt`, `set_ts 0x????????`, `____executor_globals` before doing `dump_bt $eg.current_execute_data`

**Comment by JakeFalcor** [comment]
Did you have any luck with it @chippyash ?

I was looking through the code you provided - there seems to be a possible issue with the way you're synchronizing threads? I mean, documentation uses different arguments than you do - you're passing functions just like you should, but notifying and "waiting" the same thread over and over. Compare these two:

( Example from [docs](http://php.net/manual/en/threaded.notify.php) )
```php
<?php
class My extends Thread {
    public function run() {
        /** cause this thread to wait **/
        $this->synchronized(function($thread){
            if (!$thread->done)
                $thread->wait();
        }, $this);
    }
}
$my = new My();
$my->start();
/** send notification to the waiting thread **/
$my->synchronized(function($thread){
    $thread->done = true;
    $thread->notify();
}, $my);
var_dump($my->join());
?>
```

... and yours:

```php
public function run() {
        $closure = $this->closure;
        $this->synchronized(function() use($closure) {
            $this->result =
                $closure(...$this->args);
            $this->notify();
        });
    }

    public function getResult() {
        return $this->synchronized(function(){
            while (!$this->result)
                $this->wait();
            return $this->result;
        });
    }
```

It's probably not part of this particular issue, but I'd like to point it out since I saw this tiny bit of difference.

I myself have used pthreads using `Pool` objects and `Worker`s, which by their design do not require me to keep references to objects like `Thread`s, so you can treat me as novice, but... I guess you should look into how references to threads/objects are kept?

Hope I helped you in any way.

**Comment by chippyash** [comment]
@JakeFalcor  - I did actually try to use the Pool interface before, as it provides a 'simpler' mechanism, but I couldn't quite work out how to return a value back, so took a look at using the raw Threads, following the Future example code provided in the git library.  That's how I got here :-) (and I tried many other libraries in my searching, but as I said in my first post, pthreads has gotten me closer than anything else.)

@2072, here is some output from dbg:

<pre>
(gdb) run
Starting program: /opt/php-zts/bin/php ./testAssembler.php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5bfa700 (LWP 2796)]
foo 1 started
foo 1 finished
[New Thread 0x7ffff53f9700 (LWP 2797)]
[Thread 0x7ffff5bfa700 (LWP 2796) exited]
[New Thread 0x7ffff4993700 (LWP 2798)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff53f9700 (LWP 2797)]
0x0000000000a2d5dc in zend_closure_get_closure (obj=0x7ffff7f3d470, ce_ptr=0x7ffff53f82b0, fptr_ptr=0x7ffff53f82a8, zobj_ptr=0x7ffff53f82c0, tsrm_ls=0x7fffe80008c0)
    at /usr/local/src/php-5.6.10/Zend/zend_closures.c:299
299             if (closure->this_ptr) {
(gdb) source /usr/local/src/php-5.6.10/.gdbinit
(gdb) zbacktrace
foo 3 started
[0x7fffe8004180] call_user_func_array(object[0x7ffff7f3d470], array(1)[0x7ffff7f54e68]) /home/akitson/Projects/async/src/AAssembler.php:100 
[0x7fffe8004020] Future->{closure}() /home/akitson/Projects/async/src/AAssembler.php:26 
[0x7ffff53f8750] Future->{closure}() 
[0x7fffe8003e78] Threaded->synchronized(object[0x7fffe8136b78]) /home/akitson/Projects/async/src/AAssembler.php:28 
(gdb) info threads
  Id   Target Id         Frame 
  4    Thread 0x7ffff4993700 (LWP 2798) "php" 0x00007ffff63c9f3d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
* 3    Thread 0x7ffff53f9700 (LWP 2797) "php" 0x0000000000a2d5dc in zend_closure_get_closure (obj=0x7ffff7f3d470, ce_ptr=0x7ffff53f82b0, fptr_ptr=0x7ffff53f82a8, zobj_ptr=0x7ffff53f82c0, 
    tsrm_ls=0x7fffe80008c0) at /usr/local/src/php-5.6.10/Zend/zend_closures.c:299
  1    Thread 0x7ffff7fe7740 (LWP 2792) "php" 0x00007ffff66d766b in pthread_join (threadid=140737307973376, thread_return=0x0) at pthread_join.c:92
(gdb) thread 0x7ffff4993700
</pre>

I used zbacktrace after following [Dereck Rethan's article](http://derickrethans.nl/phps-segmentation-faults-gdbfu.html).  I also ran the commands that you gave and gained the same [output](http://pastebin.com/nVisTZDK).

**Comment by chippyash** [comment]
@JakeFalcor - Thanks for that. I do think it has something to do with synchronisation etc, and will study your  comment later (after I finish my day job!)  Thanks for your input.

**Comment by JakeFalcor** [comment]
@chippyash I've just read that example, and disregard my comment about differences - on second thought it is perfectly valid code, when thread object being synchronized and calling context is the same object :)

**Comment by chippyash** [comment]
@JakeFalcor - My Future is taken straight from the [pthreads github example](https://github.com/krakjoe/pthreads/blob/master/examples/ClosureFuture.php), (just reformatted to put public before private declarations etc - sorry - old skool.)

I think the debug dump points to what I thought was happening:

somehow, in the addVars method, 

`return function() use($func, $fArgs) {return call_user_func_array($func, $fArgs);};`

is causing the segfault.  I don't know, but I think that the new Thread created using this cannot somehow access the resources to run the new function call, because it cannot access the Future(s) now wrapped in the $fArgs array.  That is really the only difference between my first and second example.

Frustrating!

**Comment by chippyash** [comment]
Yep - maybe my previous comment was correct.  Here is some test code that isolates the problem:

<pre>
$future1 = Future::of(function(){return doRunRun(1);});
$future2 = Future::of(function() {return doRunRun(2);});

$future3 = Future::of(function(){return doRunRun(3);});
$future4 = Future::of(function() use($future3) {return doRunRun(4, $future3);});
</pre>

Future and doRunRun are as detailed in first post.  Running this does not give a segfault, but never returns:

<pre>
foo 1 started
/usr/local/src/php-5.6.10/Zend/zend_hash.c(976) : ht=0x7f14dfd8d510 is inconsistent
foo 2 started
foo 3 started
foo 3 finished
foo 1 finished
foo 2 finished

Process finished with exit code -1
</pre>

exit code == -1 'cus I press ctrl-c.  

Interestingly threads 1 - 3 start and finish (async too!) but 4 never does.

Any ideas anyone?

**Comment by 2072** [comment]
Hmmm... Just in case, does your main thread waits for the others to finish
before exiting? Because if it doesn't, then future3 is released before or
while it's being used by thread 4...

**Comment by chippyash** [comment]
<pre>
$future1 = Future::of(function(){return doRunRun(1);});
$future2 = Future::of(function() {return doRunRun(2);});

$future3 = Future::of(function(){return doRunRun(3);});
$future4 = Future::of(function() use($future3) {return doRunRun(4, $future3);});

echo "main";
</pre>

Never gets to `echo "main";`

**Comment by chippyash** [comment]
<pre>
function doRunRun($n, $f = null)
{
    echo "foo $n started\n";
    sleep(mt_rand(1, 3));
    echo "foo $n finished\n";
    if (!is_null($f)) {
        echo "Consumed $n\n";
    }
    return $n;
}

$future1 = Future::of(function(){return doRunRun(1);});
$future2 = Future::of(function() {return doRunRun(2);});

$future3 = intval(Future::of(function(){return doRunRun(3);})->getResult());
echo "f3 = $future3\n";
$future4 = Future::of(function() use($future3) {return doRunRun(4, $future3);});

echo "main\n";
</pre>

gives 

<pre>
foo 1 started
foo 2 started
foo 3 started
foo 3 finished
f3 = 3
main
/usr/local/src/php-5.6.10/Zend/zend_hash.c(976) : ht=0x7f75f2ef6c10 is inconsistent
foo 1 finished
foo 2 finished

Process finished with exit code -1
</pre>

So it's not the consuming of a Future within a Future (Thread within a thread) that is the problem.

**Comment by chippyash** [comment]
Got it!
<pre>
function doRunRun($n, $f = null)
{
    echo "foo $n started\n";
    sleep(mt_rand(1, 3));
    echo "foo $n finished\n";
    if (!is_null($f)) {
        $value = ($f instanceof Future ? $f->getResult() : $f);
        echo "Consumed $value\n";
    }
    return $n;
}

$future1 = Future::of(function(){return doRunRun(1);});
$future2 = Future::of(function() {return doRunRun(2);});
$future3 = Future::of(function(){return doRunRun(3);});
$future4 = Future::of(function($n) {return doRunRun(4, $n);}, [$future3]);

echo "main\n";
</pre>

gives:
<pre>
foo 1 started
foo 2 started
foo 3 started
main
foo 4 started
foo 1 finished
foo 2 finished
foo 4 finished
foo 3 finished
Consumed 3

Process finished with exit code 0
</pre>

It seems that the problem is the `use` clause when defining a function to go into the `Future`.  Not sure why but by passing in the function parameters as the second parameter to `Future::of()` fixes the problem.  Just got to figure out how to refactor the AAssembler class now around that.

**Comment by krakjoe** [comment]
Also see updates to that example, it's much more reliable when using 3+ (and it's written properly) ...

**Comment by krakjoe** [comment]
Closing issue ... because housework ...
