### ISSUE TITLE
__pthread_mutex_lock "assertion failed" when called from __destruct()

### ISSUE THREAD

**Issue by pfofi** [krakjoe/pthreads#452]
I switched to the current pthreads-master due to a traits problem I was experiencing in 2.0.10.

Now I ran into another problem:
```php
class Work extends Threaded
{
    public function __destruct()
    {
        var_dump(self::isRunning());
    }
}
$work = new Work;
```
Result:
> php: ../nptl/pthread_mutex_lock.c:80: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
> Aborted

When the object is freed with `unset($work)` before script shutdown, it works.

Bug? No Bug? Some configure flag that needs to be set?

*Using PHP-CLI 5.6.10 under Linux*

**Comment by pfofi** [comment]
Also, all properties will be `null` in the destructor:
```php
class Work extends Threaded
{
    private $test = true;

    public function __destruct()
    {
        var_dump($this->test); // expected: TRUE; result: NULL
    }
}

$work = new Work;
unset($work);
```
Is that intended behavior? Because it differs from 2.0.10.

**Comment by 2072** [comment]
Ok I could reproduce this and the culprit is f4ef9c8edd0cf201e09afbb21de47b1093f57184. Reverting it fixes these issues.
If I can find something obvious I'll make a pull request including tests.

**Comment by 2072** [comment]
Ok this was a very simple mistake (PThread object internals are destroyed before userland destructors are called...), pull request coming soon.

**Comment by pfofi** [comment]
Awesome, thanks @2072 !
