### ISSUE TITLE
Memory leak and invalid pointer errors

### ISSUE THREAD

**Issue by Gramzivi** [krakjoe/pthreads#453]
I have pthread 2.0.10 and PHP 5.5.26

When my program without threads, program is running OK, but when I add couple of threads, this errors start to show up:

    /root/.aaa/php/php-5.5.26/Zend/zend_compile.c(5804) :  Freeing 0x7FBFFF1643B0 (32 bytes),     
    script=/home/user/cls/index.php
    Last leak repeated 7 times
    === Total 16 memory leaks detected ===

or

    /root/.aaa/php/php-5.5.26/Zend/zend_variables.c(183) : Block 0x7fbfff16d558 status:
    /root/.aaa/php/php-5.5.26/Zend/zend_execute.h(82) : Actual location (location was relayed)
    Invalid pointer: ((thread_id=0xFF230840) != (expected=0xF15C0700))

**Comment by 2072** [comment]
We need a code sample (the shortest possible) exhibiting the problem in order to help you.

**Comment by Gramzivi** [comment]
My main function:
	$counter = new Counter();
	
	$jobs = array(
		new Process($website_url, $trigger, $counter),
		new Process($website_url, $trigger, $counter),
		new Process($website_url, $trigger, $counter),
		new Process($website_url, $trigger, $counter),
		new Process($website_url, $trigger, $counter),
		new Process($website_url, $trigger, $counter),
		new Process($website_url, $trigger, $counter)
	);
	
	foreach ($jobs as $job)
	    $job->start();
	
	foreach ($jobs as $job)
		$job->join();

}
When i have only one thread, this works. 
And maybe most important thing I didnt mention. On my old server configuration (I think it was pthtead 2.0.8 and php 5.3) this program worked perfectly.

**Comment by 2072** [comment]
I'm sorry but you must give us a minimal but complete example that we can run so that we can debug the problem. This does require some work on your part but I'm afraid there is no other way.

**Comment by Gramzivi** [comment]
This is shortest sample I can show.
https://github.com/Gramzivi/Simple-PHP-Threaded-Crawler

**Comment by krakjoe** [comment]
Without a minimal executable reproducing script, I can't help.

Feel free to open a new report with the information requested.
