### ISSUE TITLE
Overriding thread-variable joins Thread

### ISSUE THREAD

**Issue by digilist** [krakjoe/pthreads#455]
Consider the following example:

```php
<?php
class AsyncOperation extends Thread {
  public function __construct($arg, $sleep){
    $this->arg = $arg;
    $this->sleep = $sleep;
  }

  public function run(){
    if($this->arg){
      sleep($this->sleep);
      echo $this->arg;
    }
  }
}

$thread = new AsyncOperation("Hello", 2);
$thread->start();
echo '.';

$thread = new AsyncOperation("World", 1);
$thread->start();
echo '!';
```

I'd expect the output `.!WorldHello`, but instead I get `.Hello!World`. When I rename the second thread variable, I see the expected output. So I assume, that the thread is joined (or something like that) if I overwrite the variable. 

I've tested it with v2.0.10 and the latest changes from Git.

**Comment by JakeFalcor** [comment]
You cannot depend on output streams joining properly.

See #447

**Comment by krakjoe** [comment]
The thread is joined, because you destroyed the reference to it.
