### ISSUE TITLE
Cannot run "propel query" in thread

### ISSUE THREAD

**Issue by CriztianiX** [krakjoe/pthreads#458]
I'm trying to run a "paginated" query in parallel (using propel ORM and composer) with this code:

```php
require_once './vendor/autoload.php';
require_once './generated-conf/config.php';

class WriterRow extends Stackable 
{
  protected function process($instance, $page)
  {
    $paginated = $instance->paginate($page, $maxPerPage = 10);
    foreach ($paginated as $row) {
      var_dump($row);
    }
  }
}

class SqlWorker extends Worker
{
  public function __construct(WriterRow $logger) {
    $this->logger = $logger;
  }

  protected $logger;
}

class PageWork extends Collectable {
  public $page;

  public function __construct($instance, $page)
  {
    $this->instance = $instance;
    $this->page = $page;
  }

  public function run()
  {
    $this->worker->logger->process($this->instance, $this->page);
    $this->setGarbage();
  }
}

class Main
{
  public static function Init()
  {
    $totalRows = self::getTotalRows();
    $totalPages = self::getTotalPages($totalRows);
    $pool = new Pool(4, 'SqlWorker', array(new WriterRow()));

    for ($i=1; $i <= $totalPages; $i++) { 
        $pageWork = new PageWork(ApplicationUsersQuery::create(), $i);
        $pool->submit($pageWork);
    }

    $pool->shutdown();
    $pool->collect(function($work){
      return $work->isGarbage();
    });
  }

  private static function getTotalRows()
  {
    return ApplicationUsersQuery::create()->count();
  }

  private static function getTotalPages($totalRows)
  {
    return ceil($totalRows/100);
  }
}

Main::Init();
```

But i am getting:
PHP Fatal error:  Class 'Propel\Runtime\Util\PropelModelPager' not found in /home/criztian/workspace/php-pool/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php on line 1418
PHP Fatal error:  Class 'Propel\Runtime\Util\PropelModelPager' not found in /home/criztian/workspace/php-pool/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php on line 1418
PHP Fatal error:  Class 'Propel\Runtime\Util\PropelModelPager' not found in /home/criztian/workspace/php-pool/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php on line 1418
PHP Fatal error:  Class 'Propel\Runtime\Util\PropelModelPager' not found in /home/criztian/workspace/php-pool/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php on line 1418
PHP Fatal error:  Class 'Propel\Runtime\Util\PropelModelPager' not found in /home/criztian/workspace/php-pool/vendor/propel/propel/src/Propel/Runtime/ActiveQuery/ModelCriteria.php on line 1418

where is my error?
Thanks!

**Comment by JakeFalcor** [comment]
Threads do not inherit autoloading from their "parent" thread, and so you should include autoloading scripts in them.

As far as I know, they do not inherit any class definitions, but I'm not sure about that.

**Comment by krakjoe** [comment]
> As far as I know, they do not inherit any class definitions, but I'm not sure about that.

They inherit them all, but that class wasn't loaded in the parent before being referenced in the child ... you should install autoloader ...
