### ISSUE TITLE
With each passing an array slower and slowly

### ISSUE THREAD

**Issue by exileed** [krakjoe/pthreads#460]
Hello,

I have a code

```php
forearch ($days as $day){
$room = getRooms($day);
  foreach ($rooms as $key => $room) {

            $treads[] = $tread = new Async(['getPrice'], [$room, $block ]]);
            $tread->start();
}
 foreach ($treads as $key => $tread) {

            $tread->join();
            foreach ($tread->result as $result) {
         ...
            }
 
        }
}
```
The first day is fast.
If you look at htop used normal threads.

The second and subsequent slow down and
multithreaded run in Kernel level thread

how can I solve this problem?

**Comment by bnikola** [comment]
Don't use threads then? It's unclear what you're doing. You're querying a database?

**Comment by exileed** [comment]
Async(['getPrice'], [$room, $block ]]); - This function has been launched into trade
getPrice -  produces long calculation

Inside thread no not query the database


The problem is that multithreaded go to the Kernel level thread.
And slow down calculations

**Comment by JakeFalcor** [comment]
Sorry, but it's hardly understandable. I didn't get a thing from what you've just written - apart from the fact that it slows down.

Creating a thread for every task and launching it simultanously will not make your application work any faster. As krakjoe stated in documentation - putting more water in a bowl won't make it "wetter". What you probably want to do is use `Pool` to create `Worker`s and pass threads as tasks to do. PHP pthreads Pool implementation sets how many workers should work at any given time.

**Comment by cottton** [comment]
I think i know what your problem is.
try that:
```php
$threads = array(); // change "tread" to "thread" btw =)
foreach ($days as $day){
    $room = getRooms($day);
    foreach ($rooms as $key => $room) {
        $threads[] = $thread = new Async(['getPrice'], [$room, $block ]]);
        $thread->start();
    }
    /* this doesnt belong here (you are still in foreach ($days... =)
    foreach ($treads as $key => $tread) {

        $tread->join();
        foreach ($tread->result as $result) {
            ...
        }
    }*/
}
while(count($threads) > 0){
    foreach ($threads as $key => $thread) {
        if($thread->isRunning() === false){
            // this one is done
            $thread->join();
            // get your results
            foreach ($thread->result as $result) {
                // ...
            }
            // unset (important due to while)
            unset($threads[$key]);
        }
    }
}
```
The problem you have with your current code is
that you wait "in line" on every thread. 
Your script is waiting for the thread if you call `->join()` until it is possible to join() -- until the run() method is done.
So just go through all threads and "ask" if `isRunning() === false`.
If so then the run() method is done and the thread can be joined.

**Comment by krakjoe** [comment]
This doesn't appear to be a bug, so closing.
