### ISSUE TITLE
php7: Singleton

### ISSUE THREAD

**Issue by GreenRover** [krakjoe/pthreads#461]
Hi, here you wrote in 2012 that singleton is now supported.
https://github.com/krakjoe/pthreads/issues/22

I tryed it for php7 seven right now.
https://gist.github.com/GreenRover/e8f2a4b4fb2a2e175175

But "$_registry" will be "unknown" for all childs.

PHP Fatal error:  Uncaught Error: Call to a member function offsetGet() on unknown in /var/www/test/pthread/test.php:35

**Comment by GreenRover** [comment]
For php5.6.9 
It just says: 
PHP Notice:  Undefined index: test in /var/www/test/pthread/Singelton.php on line 35

It seams it creates a new instance of the singleton.

**Comment by krakjoe** [comment]
I think there is some confusion, there is meant to be a new instance for each thread; static scope is treated as thread local. When the new threads call ::getInstance they are creating their own instance and it doesn't have the member test set, so the warning is totally expected.

If there is a bug, and I somehow misunderstand what you are saying, please open a new report ;)
