### ISSUE TITLE
libcurl and segmentation fault

### ISSUE THREAD

**Issue by qiukeren** [krakjoe/pthreads#471]
1.I use the github version of pthreads,
2.libcurl version is libcurl4.1.1(centos libcurl-7.19.7 package)
3.php version 5.6.11

The problem is, the segmentation fault comes sometimes,especially  when i run php X.php the first time in a terminal

and the code is
```
<?php
 class test extends Thread {
    public $url;
    public $result;
    
    public function __construct($url) {
        $this->url = $url;
    }
    
    public function run() {
        if ($this->url) {
            $this->result = model_http_curl_get($this->url);
        }
    }
 }
 function model_http_curl_get($url) {
    $curl = curl_init();  
    curl_setopt($curl, CURLOPT_URL, $url);  
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);  
    curl_setopt($curl, CURLOPT_TIMEOUT, 5);  
    curl_setopt($curl, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.2)');  
    $result = curl_exec($curl);  
    curl_close($curl);  
    return $result;  
 }
 for ($i = 0; $i < 1000; $i++) {
    $urls[] = 'http://www.baidu.com/s?wd='. rand(10000, 20000);
 }

$t = microtime(true);
 foreach ($urls as $key=>$url) {
    $workers[$key] = new test($url);
    $workers[$key]->start();
 }
 foreach ($workers as $key=>$worker) {
    while($workers[$key]->isRunning()) {
        usleep(100);  
    }
    if ($workers[$key]->join()) {
//        dump($workers[$key]->result);
    }
 }
$e = microtime(true);
echo ($e-$t);  

$t = microtime(true);
 foreach ($urls as $key=>$url) {
    model_http_curl_get($url);
//    dump(model_http_curl_get($url));
 }
$e = microtime(true);
echo ($e-$t);  

```

Only thing dumped is dmesg:
```
 in libcurl.so.4.1.1[3f93200000+51000]
php[3234]: segfault at 10 ip 0000003f9322f62b sp 00007f34a9307f60 error 4 in libcurl.so.4.1.1[3f93200000+51000]
php[3506]: segfault at 10 ip 0000003f9322f62b sp 00007f269b59cf60 error 4 in libcurl.so.4.1.1[3f93200000+51000]
php[7678]: segfault at 10 ip 0000003f9322f62b sp 00007f68b5f15f60 error 4 in libcurl.so.4.1.1[3f93200000+51000]
php[15934]: segfault at 10 ip 0000003f9322f62b sp 00007f379ef6af60 error 4
php[15938]: segfault at 10 ip 0000003f9322f62b sp 00007f379e0bbf60 error 4 in libcurl.so.4.1.1[3f93200000+51000] in libcurl.so.4.1.1[3f93200000+51000]

php[17026]: segfault at 10 ip 0000003f9322f62b sp 00007f64d4da4f60 error 4
php[17022]: segfault at 10 ip 0000003f9322f62b sp 00007f64d5c53f60 error 4 in libcurl.so.4.1.1[3f93200000+51000] in libcurl.so.4.1.1[3f93200000+51000]

php[20748]: segfault at 10 ip 00007f37667f640b sp 00007f3757be9fa0 error 4
php[20766]: segfault at 10 ip 00007f37667f640b sp 00007f373b5fcfa0 error 4
php[20751]: segfault at 10 ip 00007f37667f640b sp 00007f3757158fa0 error 4
php[20754]: segfault at 10 ip 00007f37667f640b sp 00007f37566c7fa0 error 4 in libcurl.so.4.1.1[7f37667c6000+52000]
php[20760]: segfault at 10 ip 00007f37667f64ad sp 00007f37551a5fa0 error 6 in libcurl.so.4.1.1[7f37667c6000+52000]
 in libcurl.so.4.1.1[7f37667c6000+52000] in libcurl.so.4.1.1[7f37667c6000+52000]

 in libcurl.so.4.1.1[7f37667c6000+52000]

php[20769]: segfault at 10 ip 00007f37667f640b sp 00007f373abfbfa0 error 4
php[20742]: segfault at 10 ip 00007f37667f640b sp 00007f375d538fa0 error 4 in libcurl.so.4.1.1[7f37667c6000+52000]
 in libcurl.so.4.1.1[7f37667c6000+52000]
```

Is anything wrong with my code ?
or is this a pthreads' bug

**Comment by JakeFalcor** [comment]
Master branch of pThreads php is PHP7 compatible, and it probably broken it's compatibility with PHP 5.*. Krakjoe said there were major changes to the codebase.

Last pthreads version compatible with PHP 5.6 is 2.0.10.

**Comment by qiukeren** [comment]
OK,I will test it

**Comment by qiukeren** [comment]
It does segmentation fault too…（pthreads 2.0.10 from pecl.php.net）

however，the difference is…

it has "(core dumped)"

```
$ php a.php 
kaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishikaishishashakaishishashakaishishashakaishishasha(ignore this and this is debug)
Segmentation fault (core dumped)
```

**Comment by bnikola** [comment]
Is there any reason why you use pthreads extension to perform async multiple requests with curl? Curl already has [curl_multi_init](http://php.net/manual/en/function.curl-multi-init.php) method that lets you do exactly that. The reason I'm writing this reply is because your use of threads is a bit wrong, and you're trying to use them to solve a problem that's been solved. Right tool for the right job, and curl already gives you want you need.

**Comment by qiukeren** [comment]
yes，curl_multi performs badly here in concurrency so I want some thing like thread to solve this.
（50 post to post to 50 different domain cost about 60+ seconds with each post costs 1-2 seconds, all IP are from intranet. It does not seem like a function of well paralleled）
Pthreads does this very well.

**Comment by staabm** [comment]
@qiukeren In case you need only concurrency for http I would recommend to use a "better http" client instead of phtreads, which adds too much complexitiy in case of a http only use-case.

e.g. https://github.com/amphp/artax

**Comment by JakeFalcor** [comment]
Then there is something wrong with you multi_curl implementation. I have used multi_curl in my projects, to make concurrent requests and "faking" threads both.

Making 50 concurrent requests each taking 1-2 secs should result in 2-3 secs of execution time.

**Comment by qiukeren** [comment]
To:JakeFalcor - I added my function on the previous reply.

To:staabm: i would try pthreads+requests.ryanmccue.info, if the segmentation fault again, i would try your artax. After all,this is the beginning of the priject ,and I do not know if my boss has any other idea of concurrency ^_^

**Comment by JakeFalcor** [comment]
multi_curl consists of two parts - one when you send data, and second when you receive it. Here is the code I'm using for myself:

```
$active = null;
do {
    $mrc = curl_multi_exec($mh, $active);
} while ($mrc == CURLM_CALL_MULTI_PERFORM);
while ($active && $mrc == CURLM_OK) {
    if (curl_multi_select($mh) == -1) {
        usleep(100000);
    }
    do {
        $mrc = curl_multi_exec($mh, $active);
    } while ($mrc == CURLM_CALL_MULTI_PERFORM);
}
```

**Comment by qiukeren** [comment]
to JakeFalcor:

 the curl_multi still not work properly here :
```
    while ($active && $mrc == CURLM_OK) {
        if (curl_multi_select($mh) == -1) {
            usleep(100000);
        }
        do {
            $mrc = curl_multi_exec($mh, $active);      <-------bottleneck here ,it loop and loop and loop to 50 seconds
        } while ($mrc == CURLM_CALL_MULTI_PERFORM);
    }
```

like my code
```
    do {
        curl_multi_exec($mh, $running);
    } while ($running > 0);
```

So thread may be a better way.

**Comment by JakeFalcor** [comment]
Do you experience the same when querying a different server, for example google.com?

**Comment by qiukeren** [comment]
Yes. On server , get/post to website using curl_multi does not have the problem, only my intranet machine has this issue.

**Comment by JakeFalcor** [comment]
Then something happens on your intranet server you're querying, which causes subsequent requests to be locked until some resources are free. For example, you might have issue with php file-based sessions acquiring lock on session file and therefore preventing further requests from executing. Or you might be locking a database table/row you expect to work on.  
Either way, it's neither pthreads nor multi_curl issue.

Judging from what you earlier said, I would say sessions are the problem. Try setting every curl handle to use a different cookie jar or not send them at all (`CURLOPT_COOKIE`, http://php.net/manual/pl/function.curl-setopt.php).  
You might also consider querying your server for a simple echoing script to make sure.

**Comment by bnikola** [comment]
I believe we went offtopic when it comes to pthreads project. The likely reason for curl working "slow" for your machine is because it's slow to resolve the remote server or the remote server itself is slow (it is for me when I run your code). Also, another interesting thing is that I'm not getting any segfaults when I run your copy-pasted code (php 5.5.10, I cloned the master 10 mins ago and compiled it against my php) but it eats up a lot of memory. TL;DR: pthreads won't make anything faster, cURL contains a more efficient way of handling multiple requests. You're also using `usleep` which will make the CPU waste cycles for no reason, therefore your approach is slower.

**Comment by qiukeren** [comment]
1.usleep is used of avoiding segmentfault -> whel usleep 1000, the segmentfault actually appear less often.
2.Curl is not slow, my machine is in the server room, and ping server each other get a value that less than 2 ms, both would not be the problem; And 100 threads to baidu.com cost about 0.6 seconds(less than 1),1000 cost 6.X seconds(less than 7)
3.actually,may i say your network to baidu.com is slow. 

My test here is (1000 threads):
```
22:29 $ php a.php 
Segmentation fault (core dumped)    <-it happens *almost everytime* after having  a break

22:29 $ php a.php 
6.3224699497223  <-and here it's ok

22:29 $ php a.php 
Segmentation fault (core dumped)  <-......

22:31 $ php a.php 
6.3776891231537
```

4. You may treat it as an potential bug that would happen under particular case.
I would now test it with php 5.5 ...

**Comment by bnikola** [comment]
Alright, then it seems you're correct, usleep lets you avoid segfaults, you're creating 1000 threads and trying to do something without really understanding what it is. Good luck with your project, I wish you all the best. Consider closing the issue because there are no real problems with pthreads here.

**Comment by cottton** [comment]
I dont get it why you guys are not trying to find the error.
Instead you sugest to use something else.
ofc there are other ways to do that. But perhaps it IS a bug - so why dont check it.

@qiukeren 
try changing the function:
```php
function model_http_curl_get($url) {
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($curl, CURLOPT_TIMEOUT, 5);
    curl_setopt($curl, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.2)');
    $result = curl_exec($curl);
    curl_close($curl);
    return $result;
}
```
to `function model_http_curl_get(){return '';}`
Still crahsing?
I could imagine that there is a problem to use curl @ this function from many different contexts the same time.

tested your code with a little (more efficient join) change on to different systems:
```php
 function model_http_curl_get($url) {
    $curl = curl_init();
    curl_setopt($curl, CURLOPT_URL, $url);
    curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($curl, CURLOPT_TIMEOUT, 5);
    curl_setopt($curl, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.2)');
    $result = curl_exec($curl);
    curl_close($curl);
    return $result;
}
class test extends Thread {
    public $url;
    public $result;

    public function __construct($url) {
        $this->url = $url;
    }

    public function run() {
        echo 'Task: ' . $this->getThreadId() . ' start' . PHP_EOL;
        if ($this->url) {
            $this->result = model_http_curl_get($this->url);
        }
        echo 'Task: ' . $this->getThreadId() . ' done' . PHP_EOL;
    }
}
for ($i = 0; $i < 100; $i++) {
    $urls[] = 'http://www.baidu.com/s?wd='. rand(10000, 20000);
}

$t = microtime(true);
foreach ($urls as $key=>$url) {
    $workers[$key] = new test($url);
    $workers[$key]->start();
}
/*
foreach ($workers as $key=>$worker) {
    while($workers[$key]->isRunning()) {
        usleep(100);
    }
    if ($workers[$key]->join()) {
    //        dump($workers[$key]->result);
    }
}*/
$results = array();
while(!empty($workers)){
    foreach($workers as $key => $worker){
        if($worker->isRunning() === false){
            $results[$worker->url] = $worker->result;
            if($worker->isJoined() === false){
                $worker->join();
            }
            unset($workers[$key]);
        }
    }
    // can do something else in the until all threads are done
    // ...
    echo !isset($x) ? "\r" . ($x=0) : "\r" . ++$x;
}
$e = microtime(true);
echo PHP_EOL . 'time ' . ($e-$t) . PHP_EOL; // time 1.0040581226349 

/* out
linux:
    PHP_VERSION 5.6.10-1~dotdeb+zts+7.3
    round   result
    1       time 2.8878889083862
    2       time 4.1362948417664
    3       time 2.9212110042572
    4       time 3.9105448722839
windows (100 threads due to lack of ressources):
    PHP_VERSION 5.6.11
    php_pthreads-2.0.10-5.6-ts-vc11-x86.zip @ http://windows.php.net/downloads/pecl/releases/pthreads/2.0.10/
     round   result
    1       time 1.0060570240021
    2       time 1.0060570240021
    3       time 1.0060579776764
    4       time 1.0050580501556    
*/
```
no problems at all
