### ISSUE TITLE
core dump while "stack" a conection in a worker

### ISSUE THREAD

**Issue by CriztianiX** [krakjoe/pthreads#472]
Trying to create a conection in the worker and use it in the thread i get:
mundo@mundo-laptop:~/workspace/rds$ php Main.php 
string(26) "instance created in worker"
string(26) "instance created in worker"
string(26) "instance created in worker"
string(26) "instance created in worker"
Violación de segmento (`core' generado)

The worker:
```php
<?php
namespace Rds {
    class Worker extends \Worker {
        protected $loader;
        protected $couchbase;

        public function __construct($loader, $couchbase)
        {
            $this->loader = $loader;
            $this->couchbase = $couchbase->connection();
        }
        public function run()
        {
          require_once($this->loader);
        }

        public function start()
        {
          return parent::start(PTHREADS_INHERIT_NONE);
        }
    }
}
```

The thread part using the conection created in the worker
```php
namespace Rds {
  class Task extends \Collectable {
    public $page;

    public function __construct($page) {
      $this->page = $page;
    }
    public function run()
    {
      $boot = Bootstrap::getInstace();
      $rows = $boot->getPage($this->page);

      $bucket = $this->worker->couchbase;
      ....
}
```

The stackable conection
```php
namespace Rds {
    class CouchbaseConnectionStack extends \Stackable  {
        public function connection()
        {
          var_dump("instance created in worker");
          $connectionString = "http://127.0.0.1";
          $bucket = "default";
          $cluster = new \CouchbaseCluster($connectionString);
          return $cluster->openBucket($bucket);
        }
    }
}
```

The main app:
```php
      $stacks = [ "Vendor/autoload.php", new \Rds\CouchbaseConnectionStack ];
        $pool = new \Pool((int)$numWorkers, \Rds\Worker::class, $stacks);
        for ($page=1; $page <= $totalPages ; $page++) {
          $task = new \Rds\Task($page);
          $pool->submit($task);
        }
        $pool->shutdown();
        $pool->collect(function($work){
          return $work->isGarbage();
        });
```

**Comment by JakeFalcor** [comment]
Sharing resources between threads is not supported by pthreads. You are creating couch database resource in worker constructor and expect it to work in thread which this worker will work upon.

**Comment by CriztianiX** [comment]
Thanks for the reply
what is the correct way to each Worker create its own reusable connections?

**Comment by cottton** [comment]
have a look at https://github.com/krakjoe/pthreads/blob/master/examples/MySQLi.php
`class Query extends Threaded` would be your `class Task extends \Collectable`

**Comment by CriztianiX** [comment]
@cottton Following the example, i still get "core dumped"

I've pushed the full implmenetation in this branch
https://github.com/CriztianiX/couchbase-etl/tree/reuse_couchbase_connection

The files are in https://github.com/CriztianiX/couchbase-etl/tree/reuse_couchbase_connection/Vendor/criztianix/rds/lib
is it an error in the implementation?
Thanks!

**Comment by cottton** [comment]
dunno, but as i follow your code:
you create at `class CouchbaseConnection`
the connection 
if not already set at `class Worker extends \Worker` by `self::$couchbase`
perhaps this is the error (but im not sure).

at `class Task extends \Threaded` 
what you get when you:
```php
// ...
$bucket = $this->worker->getCouchbaseConnection();
var_dump(gettype($bucket)); // <--------------
// ...
```

**Comment by CriztianiX** [comment]
Ok. The error ir very very strange!
getype returns "object"

```bash
php Main.php
string(6) "object"
string(6) "object"
string(6) "object"
string(6) "object"
PHP Fatal error:  Call to undefined method Doctrine\DBAL\Types\IntegerType::upsert() in /home/mundo/workspace/php-rds-to-couchbase/Vendor/criztianix/rds/lib/Task.php on line 22
string(6) "object"
PHP Fatal error:  Call to undefined method Doctrine\DBAL\Types\IntegerType::upsert() in /home/mundo/workspace/php-rds-to-couchbase/Vendor/criztianix/rds/lib/Task.php on line 22
PHP Fatal error:  Call to undefined method Doctrine\DBAL\Types\IntegerType::upsert() in /home/mundo/workspace/php-rds-to-couchbase/Vendor/criztianix/rds/lib/Task.php on line 22
Segmentation fault (`core' generado)
```

The strange is: 
```bash
Call to undefined method Doctrine\DBAL\Types\IntegerType::upsert(
```
It is trying to call upsert in a diferent object in not in couchase connection!

**Comment by cottton** [comment]
I got the same problem in one of my tools.
The object got "another name".
I fixed it like
```php
// ...
if(is_object($obj)and get_class($obj) === 'myExpectedClass'){ ... do stuff ...}
```
and im not proud of that :D (wont work for you code i think)

Now that you also got that problem i searched the reason for that.
see https://github.com/krakjoe/pthreads/issues/474
The problem is the static stored object WHEN the method connection() (was it connection?) gets called from another context.
I think you can fix this if you change
`self::$couchbase` to `$this->couchbase`  
which i do not believe as soon i wrote that ... getting confused more and more with pthreads.

**Comment by CriztianiX** [comment]
Well... i've made the changes in 
https://github.com/CriztianiX/couchbase-etl/blob/reuse_couchbase_connection/Vendor/criztianix/rds/lib/Worker.php#L17

and https://github.com/CriztianiX/couchbase-etl/blob/reuse_couchbase_connection/Vendor/criztianix/rds/lib/Task.php#L17

and the result is the same!
```bash
php Main.php 
Segmentation fault (`core' generado)
```

This is driving me crazy...

**Comment by krakjoe** [comment]
In order to help you, I need a self contained, minimal, executable reproducing code. You need to reduce the problem to it's simplest form.

**Comment by krakjoe** [comment]
This seems to come down to resource usage ... if I'm wrong and there's some bug, reopen, or open a new issue.
