### ISSUE TITLE
Threaded::merge() doesnt work on stdClass

### ISSUE THREAD

**Issue by cottton** [krakjoe/pthreads#473]
Just tried the example on http://php.net/manual/de/threaded.merge.php
and found out that i get a different result:
```php
/*
object(Threaded)#2 (11) {
  ["0"]=>
  int(0)
  ["1"]=>
  int(1)
  ["2"]=>
  int(2)
  ["3"]=>
  int(3)
  ["4"]=>
  int(4)
  ["5"]=>
  int(5)
  ["6"]=>
  int(6)
  ["7"]=>
  int(7)
  ["8"]=>
  int(8)
  ["9"]=>
  int(9)
  ["foo"]=>
  string(3) "bar"
}
*/
```
for 
windows using
PHP_VERSION 5.6.11
php_pthreads-2.0.10-5.6-ts-vc11-x86.zip @ http://windows.php.net/downloads/pecl/releases/pthreads/2.0.10/

and 

linux using
PHP_VERSION 5.6.10-1~dotdeb+zts+7.3

So $stdClass wont be merged.
I couldnt find an example/test here on github using stdClass.
So the question is: is this a bug or?

**Comment by krakjoe** [comment]
Fixed in master and seven, thanks for the report and sorry about the delay ;)
