### ISSUE TITLE
Threads sending messages to a single client.

### ISSUE THREAD

**Issue by ElvenSpellmaker** [krakjoe/pthreads#478]
Hi @krakjoe,

I'm trying to write a small programme as a test that sets up a `Client` which connects to a server (simple 'server' below) and the thread the client is in (the main thread) will spawn `Thread` objects which I want to be able to write back to the `Client` which is connected to the server.
This would allow multiple threads to communicate back to the server through one thread.

Usually with threads I would expect the main thread to block and to service each call one-by-one. Instead the `resource` becomes an `int` (I really hate the `resource` type in PHP) and fails.

Is this the point of the `Share Nothing` motto? Is there no way to be able to thread problems with this extension that use `resource`s?

Below is a minimal example to demonstrate what I mean:

Simple Server:
```PHP
<?php

$socket = stream_socket_server( 'unix:///tmp/testSocket' );
$conn = stream_socket_accept( $socket );

var_dump( fgets( $conn, 512 ) );

fclose( $conn );
fclose( $socket );
unlink( '/tmp/testSocket' );
```

Client Script:
```PHP
<?php

class Client
{
	private $connection;

	public function __construct()
	{
		echo 'I am running!';

		$this->connection = fsockopen( 'unix:///tmp/testSocket', null );
		
		stream_set_blocking( $this->connection, 0 );
	}

	public function say($msg)
	{
		fwrite( $this->connection, "$msg\r\n" );
	}

	public function __clone()
	{
		echo 'I AM A CLONE!';
	}
}

$client = new Client;

class ThreadTest extends Thread
{
	private $client;

	public function __construct(Client $client)
	{
		$this->client = $client;
	}
	
	public function run()
	{
		$this->client->say( 'TEST' );
	}
}

(new ThreadTest($client))->start();
```

When I run the 'server' and then the test thread script I get this output:
```
I am running!PHP Notice:  Constant http\client\curl\HTTP_VERSION_1_0 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\HTTP_VERSION_1_1 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\HTTP_VERSION_2_0 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\HTTP_VERSION_ANY already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\SSL_VERSION_TLSv1 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\SSL_VERSION_TLSv1_0 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\SSL_VERSION_TLSv1_1 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\SSL_VERSION_TLSv1_2 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\SSL_VERSION_SSLv2 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\SSL_VERSION_SSLv3 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\SSL_VERSION_ANY already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\TLSAUTH_SRP already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\IPRESOLVE_V4 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\IPRESOLVE_V6 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\IPRESOLVE_ANY already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\AUTH_BASIC already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\AUTH_DIGEST already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\AUTH_DIGEST_IE already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\AUTH_NTLM already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\AUTH_GSSNEG already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\AUTH_ANY already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\PROXY_SOCKS4 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\PROXY_SOCKS4A already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\PROXY_SOCKS5_HOSTNAME already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\PROXY_SOCKS5 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\PROXY_HTTP already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\PROXY_HTTP_1_0 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\POSTREDIR_301 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\POSTREDIR_302 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\POSTREDIR_303 already defined in Unknown on line 0
PHP Notice:  Constant http\client\curl\POSTREDIR_ALL already defined in Unknown on line 0
PHP Warning:  fwrite() expects parameter 1 to be resource, integer given in ThreadTest.php on line 18
```

 * First thing of note is that the `http` module is re-defining its constants when the thread is run. Is this a problem with the `http` module?
 * Secondly, the write fails and the server returns `bool(false)` because the thread encounters an `int` for the `resource` instead of calling the main thread where the object is and having that object call its own `say` method.
 * Lastly I added the echo in the `__clone` method to see if it has been cloned, and nothing is output which means I assume that the object isn't cloned. (Is it a non-userland clone?)

I hope I've explained this well enough and sorry for posting this here as an issue (if it's not), I couldn't find another way of contacting you to explain this. I assume I am doing something incorrectly and this type of scenario is possible, but I'm not sure what it is I should be doing.

**Comment by JakeFalcor** [comment]
Sharing resources between threads is not recommended and is not guaranteed to work. Instantiate Client object inside Worker/Thread instead or provide the class with a way to initialize resource by itself.

Workers/Threads can be set using parameters to not inherit certain parts of launching context. This should allow you to get rid of notices about already initialized constants. I'll provide you with code as soon as I find it, since this isn't obvious from php.net docs about pthreads and I need to find it again somewhere in github issues here or in examples.

**Comment by ElvenSpellmaker** [comment]
Hi @JakeFalcor,
 
 Thanks for the quick reply and sorry for my slow one.
 
In the case of resources it's not always possible or feasible to have multiple connections to the same resource. As an example of where I intend to use threads, an IRC bot.
 
Each plug-in (as an example) would run in its own thread which would never cause the main thread to halt if a command takes longer than expected.
There can only ever be one connection to the IRC server as your bot is one entity and one Nick. If each thread connected to the IRC server, they'd all be separate users on the network and not as one.
By restricting the connection to only one thread, it'd also make it thread-safe because only one thread could be calling the send method on the main thread, the others would block until it's free. In the other case they could all trample all over each other and send messages together resulting in rubbish on the other end.

What I am trying to achieve is not direct resource sharing, but a way to share a reference to a single object between threads which has a (hopefully synchronised) method which accesses the resource.
 
Surely this is possible, otherwise it really does limit the point of threads...

**Comment by JakeFalcor** [comment]
You're more interested then in thread-to-thread communication, where one thread acts as Parent-Service and subthreads which notify about state changes ("I need to send message now!").

See http://php.net/manual/en/threaded.wait.php and say if it helps.

Also, krakjoe will be mad for discussing code design here instead of StackOverflow, so you might want to ask your question there.

**Comment by krakjoe** [comment]
This was fixed in v3.

v2 is no longer being developed ... use php7 + pthreads v3.

Closing issue ...
