### ISSUE TITLE
'opline': undeclared identifier

### ISSUE THREAD

**Issue by Jan-E** [krakjoe/pthreads#479]
https://github.com/krakjoe/pthreads/blob/seven/src/copy.h#L129
https://github.com/krakjoe/pthreads/blob/seven/src/copy.h#L131

Oops.

C:\php-sdk\php70dev\ext\pthreads\src/copy.h(129): error C2065: 'opline': undeclared identifier
C:\php-sdk\php70dev\ext\pthreads\src/copy.h(129): error C2223: left of '->op1' must point to struct/union
C:\php-sdk\php70dev\ext\pthreads\src/copy.h(131): error C2065: 'opline': undeclared identifier
C:\php-sdk\php70dev\ext\pthreads\src/copy.h(131): error C2223: left of '->op2' must point to struct/union
ext\pthreads\php_pthreads.c(185): warning C4028: formal parameter 2 different from declaration
C:\php-sdk\php70dev\ext\pthreads\classes/threaded.h(297): warning C4013: 'zend_do_inheritance' undefined; assuming extern returning int
C:\php-sdk\php70dev\ext\pthreads\classes/pool.h(110): warning C4018: '<': signed/unsigned mismatch
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe"' : return code '0x2'

Wild guess, replace opline-> by copy[it].:

		if (copy[it].op1_type == IS_CONST)
			copy[it].op1.zv = (zval*)((char*)copy[it].op1.zv + ((char*)op_array->literals - (char*)literals));
		if (copy[it].op2_type == IS_CONST) 
			copy[it].op2.zv = (zval*)((char*)copy[it].op2.zv + ((char*)op_array->literals - (char*)literals));

More or less the same is done in opcache/zend_persist.c

BTW: lock.c should be removed from line 19 of config.w32.

**Comment by Jan-E** [comment]
Actually, line 19 of this config.w32 should be:

    var PTHREADS_EXT_SRC="monitor.c stack.c globals.c prepare.c store.c resources.c handlers.c object.c";

**Comment by krakjoe** [comment]
Indeed oops, I'll get a build going on windows today or tomorrow and fix all of that ...

**Comment by krakjoe** [comment]
Try that maybe, I haven't built on windows yet, I'll still be doing that ... but just in case you get to it before me ;)

**Comment by Jan-E** [comment]
I tried it: it does not work. With x86/32-bits (where ZEND_USE_ABS_CONST_ADDR is defined as 1), I got a blank output from phpinfo(). With x64 php_pthreads.dll loads OK.

**Comment by krakjoe** [comment]
Okay, I'll have to take a look at that ... thanks for the research, that's helpful, I know where to start ;)

**Comment by krakjoe** [comment]
include that last woops too .... should be okay now, right ?

**Comment by Jan-E** [comment]
Fixed after those 2 last commits

**Comment by krakjoe** [comment]
Excellent, thanks for persevering ... I did setup vs wrong, trying to fix it ...

**Comment by Jan-E** [comment]
Did you forget to check 'Programming Languages -> Visual C++ -> Common Tools for Visual C++ 2015'?

And/or did you check the Windows 10 SDK?

**Comment by krakjoe** [comment]
I got C++ tools, got "cl" .... I've seen this error before but can't remember what caused it ...

C:\Users\Joe\php-7.0.0RC1>nmake

Microsoft (R) Program Maintenance Utility Version 14.00.23026.0
Copyright (C) Microsoft Corporation.  All rights reserved.

```
Recreating build dirs
        "" -h win32\ -r C:\Users\Joe\php-7.0.0RC1\Debug_TS\ -x C:\Users\Joe\ph
7.0.0RC1\Debug_TS\ win32\build\wsyslog.mc
'-h' is not recognized as an internal or external command,
operable program or batch file.
NMAKE : fatal error U1077: '"' : return code '0x1'
Stop.
```

Any idea?

**Comment by Jan-E** [comment]
Try recreating the Makefile with

    call buildconf.bat
    cscript /nologo configure.js --enable-snapshot-build --with-mcrypt=static

and then

    nmake snap

**Comment by krakjoe** [comment]
didn't invoke vcvars32.bat ... building now ... thanks ;)
