### ISSUE TITLE
No Rule to make target monitor.c needed by monitor.lo

### ISSUE THREAD

**Issue by turbo124** [krakjoe/pthreads#480]
Hello,

I am having troubles compiling this extension. I have searched extensively and have not seen any similar issues, so I was wondering if i could get some help here.

My System: 

Mac OSX 10.10
PHP 5.6.12 compiled from source with the following ./configure

krakjoe/pthreads using master branch

./configure \                                                      
--prefix=/usr/local \
--with-apxs2=/usr/sbin/apxs \
--with-ldap=/usr \
--with-kerberos=/usr \
--enable-cli \
--with-zlib-dir=/usr \
--enable-exif \
--enable-ftp \
--enable-mbstring \
--enable-mbregex \
--enable-sockets \
--enable-maintainer-zts \
--with-curl=/usr \
--with-config-file-path=/etc \
--sysconfdir=/private/etc \
--with-mysql-sock=/var/mysql/mysql.sock \
--with-mysql=mysqlnd \
--with-mysqli=mysqlnd \
--with-pdo-mysql=mysqlnd \
--with-openssl=/usr \
--with-xmlrpc \
--with-xsl=/usr \
--without-pear \
--with-libxml-dir=/usr \
--with-iconv-dir=/usr/local \
--with-gd \
--with-jpeg-dir=/opt/local \
--with-png-dir=/opt/local \
--with-freetype-dir=/opt/local \
--with-mcrypt=/opt/local \
--enable-debug --enable-maintainer-zts \
--enable-pthreads --enable-mbstring \

the error that trips up the make process is:

make: *** No rule to make target `/php-5.6.12/ext/pthreads/src/monitor.c', needed by `ext/pthreads/src/monitor.lo'.  Stop.

**Comment by krakjoe** [comment]
You are using the wrong branch; You need to use the master branch for PHP5.

**Comment by turbo124** [comment]
Hi There,

I am using the master branch.

I tried this exact same procedure on a CentOS 6.5 box and it worked perfectly, so i am thinking it may have to do with the Mac OS X environment?

**Comment by krakjoe** [comment]
You are not using the master branch, because monitor.c doesn't exist there.

The default branch is now seven, so when you clone the repo you get seven, you want to checkout master branch after clone.

**Comment by turbo124** [comment]
Apologies, i must have tried building against seven first, then switch to master which resulted in failure.

A clean clone fixed this, thanks again.

**Comment by krakjoe** [comment]
No problem, it's my fault for changing the default branch ...
