### ISSUE TITLE
phtread 3.0.0 / php 7.0.0RC2 failed tests

### ISSUE THREAD

**Issue by remicollet** [krakjoe/pthreads#482]
On x86_64, 2 failed tests

     TEST 70/72 [tests/workers-no-start.phpt]
     ========DIFF========
     007+ 
     008+ Termsig=11
     ========DONE========
     FAIL Test pthreads workers rules (start) [tests/workers-no-start.phpt] 

     TEST 72/72 [tests/workers-ok-unstack.phpt]
     ========DIFF========
     005+ 
     006+ Termsig=11
     ========DONE========
     FAIL Test pthreads Worker::unstack [tests/workers-ok-unstack.phpt] 

Will try to produce de backtrace later.

**Comment by krakjoe** [comment]
I'm not using redhat anymore, is there a vagrant image similar to your setup that I can test with maybe ?

Awaiting more feedback I guess ...

**Comment by remicollet** [comment]
on i386, 3 failed test, 2 as above and

     TEST 13/70 [tests/crazy-refcounting-stuff.phpt]
     ========DIFF========
     005+     int(-154355712)
     005-     int(%d)
     010+     int(-157287616)
     010-     int(%d)
     ========DONE========
     FAIL Test managing refcount in userland (super advanced voodoo shit, leave it alone) [tests/crazy-refcounting-stuff.phpt]

**Comment by krakjoe** [comment]
Ok, I'll need traces at least, some info about reproducing environment would be good too, even if just a fedora/rh release ?

**Comment by remicollet** [comment]
Working env: Fedora 21, or 22 or 23, or Centos 6 or 7, with my repository for php 7 RPM
I recommend CentOS 7 (for php-debuginfo package, as I don't provides it for Fedora)

**Comment by krakjoe** [comment]
Ok, I'll grab those too ...

**Comment by remicollet** [comment]
Tips: 

     $ zts-phpize
     $ ./configure     --with-php-config=/usr/bin/zts-php-config

**Comment by remicollet** [comment]
(gdb) bt
     #0  0x00007fd0f8499e91 in pthread_join () from /lib64/libpthread.so.0
     #1  0x00007fd0f71fb02e in pthreads_join (thread=0x7fd0f7481100) at /root/pthreads/src/object.c:378
     #2  0x00007fd0fbbe34fb in dtrace_execute_internal (execute_data=<optimized out>, return_value=<optimized out>) at /usr/src/debug/php-7.0.0RC2/Zend/zend_dtrace.c:107
     #3  0x00007fd0fbbe5de2 in zend_call_function (fci=fci@entry=0x7ffc098fe9b0, fci_cache=fci_cache@entry=0x7ffc098fe980) at /usr/src/debug/php-7.0.0RC2/Zend/zend_execute_API.c:874
     #4  0x00007fd0fbc153a3 in zend_call_method (object=object@entry=0x7ffc098fea70, obj_ce=<optimized out>, fn_proxy=fn_proxy@entry=0x7ffc098fea68, 
         function_name=function_name@entry=0x7fd0fbce0b2a "__destruct", function_name_len=function_name_len@entry=10, retval_ptr=retval_ptr@entry=0x0, param_count=param_count@entry=0, 
         arg1=arg1@entry=0x0, arg2=arg2@entry=0x0) at /usr/src/debug/php-7.0.0RC2/Zend/zend_interfaces.c:104
     #5  0x00007fd0fbc2ead0 in zend_objects_destroy_object (object=<optimized out>) at /usr/src/debug/php-7.0.0RC2/Zend/zend_objects.c:148
     #6  0x00007fd0fbc33f83 in zend_objects_store_del (object=0x7fd0f7481150) at /usr/src/debug/php-7.0.0RC2/Zend/zend_objects_API.c:164
     #7  0x00007fd0fbc0903c in _zend_hash_del_el_ex (prev=<optimized out>, p=<optimized out>, idx=<optimized out>, ht=<optimized out>) at /usr/src/debug/php-7.0.0RC2/Zend/zend_hash.c:958
     #8  _zend_hash_del_el (p=0x7fd0f74581e0, idx=7, ht=0x7fd0fc116930) at /usr/src/debug/php-7.0.0RC2/Zend/zend_hash.c:982
     #9  zend_hash_reverse_apply (ht=0x7fd0fc116930, apply_func=apply_func@entry=0x7fd0fbbe35c0 <zval_call_destructor>) at /usr/src/debug/php-7.0.0RC2/Zend/zend_hash.c:1555
     #10 0x00007fd0fbbe3cc1 in shutdown_destructors () at /usr/src/debug/php-7.0.0RC2/Zend/zend_execute_API.c:240
     #11 0x00007fd0fbbf5055 in zend_call_destructors () at /usr/src/debug/php-7.0.0RC2/Zend/zend.c:950
     #12 0x00007fd0fbb84375 in php_request_shutdown (dummy=dummy@entry=0x0) at /usr/src/debug/php-7.0.0RC2/main/main.c:1761
     #13 0x00007fd0fbc8d5ac in do_cli (argc=64, argv=0x7fd0fc1122b0) at /usr/src/debug/php-7.0.0RC2/sapi/cli/php_cli.c:1139
     #14 0x00007fd0fba5eab0 in main (argc=64, argv=0x7fd0fc1122b0) at /usr/src/debug/php-7.0.0RC2/sapi/cli/php_cli.c:1342

**Comment by krakjoe** [comment]
Am I being stupid, or is there no 32bit CentOS 7 ?

https://wiki.centos.org/Download

**Comment by remicollet** [comment]
Opps, sorry, no CentOS 7 is x86_64 now

**Comment by krakjoe** [comment]
It's going to take me a while to get to reproducing ... can you print *thread in frame 1 for me please ?

**Comment by krakjoe** [comment]
Fixed, thanks @remicollet :)
