### ISSUE TITLE
How to enable pthreads in PHP 5.6.13 at CentOS 6.7?

### ISSUE THREAD

**Issue by paquitodev** [krakjoe/pthreads#488]
I have PHP 5.6.13 installed at CentOS 6.7 through IUS repositories. This is the output of `php -v` command:

    # php -v
    PHP 5.6.13 (cli) (built: Sep  3 2015 11:54:03)
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
        with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
        with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans

For install and enable `pthreads` I have follow this steps:

1. Search the proper packages:

        # yum search pthreads
        ================================= N/S Matched: pthreads ===============================
        mingw32-winpthreads-static.noarch : Static version of the MinGW Windows pthreads library
        mingw64-winpthreads-static.noarch : Static version of the MinGW Windows pthreads library
        php55u-pecl-pthreads-debuginfo.x86_64 : Debug information for package php55u-pecl-pthreads
        php56u-pecl-pthreads-debuginfo.x86_64 : Debug information for package php56u-pecl-pthreads
        mingw32-winpthreads.noarch : MinGW pthread library for the win32 target
        mingw64-winpthreads.noarch : MinGW pthread library for the win64 target
        openblas-threads.i686 : An optimized BLAS library based on GotoBLAS2, pthreads version
        openblas-threads.x86_64 : An optimized BLAS library based on GotoBLAS2, pthreads version
        php55u-pecl-pthreads.x86_64 : Threading API
        php56u-pecl-pthreads.x86_64 : Threading API

2. Install the package:

        #yum install php56u-pecl-pthreads.x86_64

        Resolving Dependencies
        --> Running transaction check
        ---> Package php56u-pecl-pthreads.x86_64 0:2.0.10-2.ius.el6 will be installed
        --> Finished Dependency Resolution

        Dependencies Resolved
        =======================================================================================================================================================================================================================================
         Package                                                         Arch                                              Version                                                        Repository                                      Size
        =======================================================================================================================================================================================================================================
        Installing:
         php56u-pecl-pthreads                                            x86_64                                            2.0.10-2.ius.el6                                               ius                                             71 k

        Transaction Summary
        =======================================================================================================================================================================================================================================
        Install       1 Package(s)

3. Locate where the `.so` did go:

        #locate pthreads.so
        /usr/lib64/php-zts/modules/pthreads.so

4. Enable at `/etc/php.ini` by trying each of the following lines:

        extension=pthreads.so
        extension=/usr/lib64/php-zts/modules/pthreads.so
        zend_extension=pthreads.so
        zend_extension=/usr/lib64/php-zts/modules/pthreads.so

5. Restarted Apache and find for the module

        # php -m | grep pthreads
        Failed loading /usr/lib64/php-zts/modules/pthreads.so:  /usr/lib64/php-zts/modules/pthreads.so: undefined symbol: core_globals_id

And all the time it fails with the message above. What I am doing wrong?

**Note:** I have notice by running `phpinfo()` that `Thread Safety` is disabled, do I need this enabled in order to properly load the library?

**Comment by Brewhaus32** [comment]
Yes, you must build PHP from source and add the parameter --enable-maintainer-zts.

**Comment by guotong1988** [comment]
How to do this in ubuntu ?
apt-cache search pthreads??
also php5.6.

**Comment by morphesus** [comment]
@guotong1988 

1. Compile and install PHP from sources as mentioned by @Brewhaus32 
2. Install pthreads using PECL (See here: https://pecl.php.net/package/pthreads)

For pthreads 3.x.x you'll need to compile and install PHP7 - PHP5 will not work! (And btw PHP7 is MUCH more awesome than PHP5 :D)

You can also install pthreads from source:
`# pthreads Extension build
# ------------------------
git clone https://github.com/krakjoe/pthreads.git /home/pthreads
cd pthreads
phpize
./configure --with-php-config=$PHP_DIRECTORY/bin/php-config
make
make install
mkdir $PHP_DIRECTORY/conf.d
echo "extension=pthreads.so" > /etc/php5ts/conf.d/pthreads.ini`

You may need to adjust the code above (I already did a bit, original see here: https://gist.github.com/Divi/9696838) and you need php7-dev installed - compiled with --enable-maintainer-zts flag.

~ Morph

**Comment by gloffreda** [comment]
Hi
if I have php7 alrady installed ( followed this tuto to upgrade https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-php-7-on-ubuntu-14-04) and running under nginx. 
May I use this script to install and enable pthreads ?

Thank you
