### ISSUE TITLE
Damaged objects within closures

### ISSUE THREAD

**Issue by SirSnyder** [krakjoe/pthreads#494]
Hi @krakjoe, a really strange behaviour in connection with closures. Sadly I've no simple code to reproduce this bug by now. 

Example one(schematic representation)

```
interface TestInterface {}

    class DebugClass implements TestInterface {}

    class SystemLoader
    {
        ....
        public static function setupThreadContext()
        {
            $closure = function()
            {
                return new \DebugClass();
            };
            $objCreated = $closure();

            echo 'first outer instanceof TestInterface check: '. ($objCreated instanceof \TestInterface ? 'true' : 'false') . PHP_EOL;

            self::commonSetup();
        }

        protected static function commonSetup()
        {
            $closure = function()
            {
                $d = new \DebugClass();

                echo 'second inner instanceof TestInterface check: '. ($d instanceof \TestInterface ? 'true' : 'false') . PHP_EOL;

                return $d;
            };
            /** @var Threaded $objCreated */
            $objCreated = $closure();
            
            $objClass = new \ReflectionClass($objCreated);

            var_dump($objClass->getInterfaceNames(), $objClass->implementsInterface(\TestInterface::class));

            echo 'second outer instanceof TestInterface check: '. ($objCreated instanceof \TestInterface ? 'true' : 'false') . PHP_EOL;

        }
        ....
    }

    class Runtime
    {
        ....
        public static function initThreadContext()
        {
            \SystemLoader::setupThreadContext();
        }
        ....
    }

    class Test extends Thread
    {
        public function run()
        {
            \Runtime::initThreadContext();
        }
    }

    $t = new Test();
    $t->start();
    $t->join();
```
Output:
first outer instanceof TestInterface check: true
second inner instanceof TestInterface check: true
array(1) {
  [0]=>
  string(13) "TestInterface"
}
bool(false)  <<-- $objClass->implementsInterface(\TestInterface::class)
second outer instanceof TestInterface check: false

Example two
```
class ThreadLocalStorage
{
    public static function get(ThreadedObject $threaded, $name)
    {
         ...
    }
}

class ThreadedReflectionClass extends \Threaded implements ThreadedObject
    {
        ...

        /**
         * @return \ReflectionClass
         */
        protected function getReflectionClass():\ReflectionClass
        {
            return $this->synchronized(function()
            {
                /** @var \ReflectionClass $objReflectionClass */
                $objReflectionClass = ThreadLocalStorage::get($this, self::TLS_REFLECTION_CLASS);

                if($objReflectionClass === null)
                {
                    $objReflectionClass = new \ReflectionClass($this->strClassname);

                    ThreadLocalStorage::set($this, self::TLS_REFLECTION_CLASS, $objReflectionClass, false);
                }
                return $objReflectionClass;
            });
        }

        ...
    }
```
Fatal error: Uncaught TypeError: Argument 1 passed to com\badnoobcom\liquid\concurrent\ThreadLocalStorage::get() must implement interface com\badnoobcom\liquid\concurrent\ThreadedObject, instance of com\badnoobcom\liquid\concurrent\reflection\ThreadedReflectio
nClass given, called in D:\php\libraries\liquid\src\com\badnoobcom\liquid\concurrent\reflection\ThreadedReflectionClass.php on line 1055 and defined in D:\php\libraries\liquid\src\com\badnoobcom\liquid\concurrent\ThreadLocalStorage.php:193

At some point, it seems, within a closure an object instance loses the implemented interfaces? Any suggests or ideas? I'm baffled right now.

**Comment by krakjoe** [comment]
```
krakjoe@fiji:/usr/src/pthreads$ php test.php
first outer instanceof TestInterface check: true
second inner instanceof TestInterface check: true
array(1) {
  [0]=>
  string(13) "TestInterface"
}
bool(true)
second outer instanceof TestInterface check: true
```

Not able to reproduce here ... can I get some more information about version and operating system ?

When you are posting code in a bug report, please make sure it is executable ;)

**Comment by SirSnyder** [comment]
I would love to provide you with an working example, but it's not that easy. I'm working on it.

php_pthreads-3.0.7-7.0-ts-vc14-x64
php 7 RC 4
win 7 x64

**Comment by krakjoe** [comment]
Can you use the latest release and confirm the bugs presence still before we move forward ?

**Comment by SirSnyder** [comment]
Can you push 3.0.8 to pecl(http://windows.php.net/downloads/pecl/releases/pthreads/)? I've no idea how to compile php 7 on windows.

**Comment by krakjoe** [comment]
Oh, my mistake, I thought I had done that release already ... it'll come in the next day or two, the php.net systems do builds automatically in the hours following release ...

**Comment by krakjoe** [comment]
I have done a release, keep watching for a build on windows.php.net ...

**Comment by SirSnyder** [comment]
windows.php.net won't build.
```
ext\pthreads\php_pthreads.c(163): warning C4013: 'zend_try_exception_handler' undefined; assuming extern returning int
```

**Comment by krakjoe** [comment]
Ah, looks like that function was just added ... finding out what to do ...

**Comment by Jan-E** [comment]
My latest build of RC4 is 4 days old:
https://www.apachelounge.com/viewtopic.php?t=6617

@SirSnyder Need a new one? Which version? TS or NTS? x86 or x64?

**Comment by SirSnyder** [comment]
@Jan-E yes, RC4 TS x64, pthreads 3.0.8

How to build php7 on windows? My last build was 5.4 in 2013

**Comment by krakjoe** [comment]
You really want master, that function was added after RC4 was tagged.

**Comment by SirSnyder** [comment]
ok, than I want master @Jan-E

**Comment by Jan-E** [comment]
OK, stopped the build of RC4 x64. Checking out php master now. The build may take some time.

**Comment by Jan-E** [comment]
Uploading now. 1 minutes left.
https://phpdev.toolsforresearch.com/php-7.1.0-dev-Win32-VC14-x64.zip

BTW for Joe: a pity that php_pthreads does not load anymore in CLI-mode. I cannot show that it is there in a phpinfo.htm that is generated from the command line:
https://phpdev.toolsforresearch.com/php-7.1.0-dev-Win32-VC14-x64.htm

**Comment by Jan-E** [comment]
Uploaded

**Comment by krakjoe** [comment]
It doesn't load in non-cli mode

**Comment by Jan-E** [comment]
It always loaded when I did a 'php-cgi phpinfo.php'. In fact it still does in PHP 5.6.14:
https://phpdev.toolsforresearch.com/php-5.6.14-Win32-VC11-x64.htm

**Comment by SirSnyder** [comment]
@Jan-E Thx very much
@krakjoe unfortunately the new version helped, but I got it :-)
```
const START_COMMON = PTHREADS_INHERIT_NONE | PTHREADS_INHERIT_INI | PTHREADS_ALLOW_HEADERS | PTHREADS_INHERIT_COMMENTS | PTHREADS_INHERIT_INCLUDES | PTHREADS_INHERIT_FUNCTIONS | PTHREADS_INHERIT_CLASSES;

    interface TestInterface {}

    class DebugClass implements TestInterface {}

    class SystemLoader extends Thread
    {
        public static function commonSetup()
        {
            $closure = function()
            {
                $d = new \DebugClass();

                echo 'Closure Check - is instanceof TestInterface: '. ($d instanceof \TestInterface ? 'true' : 'false') . PHP_EOL;

                return $d;
            };
            /** @var DebugClass $objCreated */
            $objCreated = $closure();

            $objClass = new \ReflectionClass($objCreated);

            echo \TestInterface::class .' available: '. (interface_exists(\TestInterface::class) ? 'true' : 'false') . PHP_EOL;

            var_dump('Implemented interfaces: ', $objClass->getInterfaceNames());

            echo 'Does this instance implements '. \TestInterface::class .': '. ($objClass->implementsInterface(\TestInterface::class) ? 'true' : 'false') . PHP_EOL;

            echo 'Important FINAL Check - is instanceof TestInterface: '. ($objCreated instanceof \TestInterface ? 'true' : 'false') . PHP_EOL;
        }
    }

    class TestThread extends Thread
    {
        public function run()
        {
            SystemLoader::commonSetup();
        }
    }
    SystemLoader::commonSetup();

    echo PHP_EOL .'... everything is fine, starting Thread ...'. PHP_EOL. PHP_EOL;

    $t = new TestThread();
    $t->start(START_COMMON);
    $t->join();
```
result

Closure Check - is instanceof TestInterface: true
TestInterface available: true
string(24) "Implemented interfaces: "
array(1) {
  [0]=>
  string(13) "TestInterface"
}
Does this instance implements TestInterface: true
Important FINAL Check - is instanceof TestInterface: true

... everything is fine, starting Thread ...

Closure Check - is instanceof TestInterface: true
TestInterface available: true
string(24) "Implemented interfaces: "
array(1) {
  [0]=>
  string(13) "TestInterface"
}
Does this instance implements TestInterface: false
Important FINAL Check - is instanceof TestInterface: false

**Comment by krakjoe** [comment]
I got it that time, for sure ...

**Comment by SirSnyder** [comment]
@krakjoe cool, that was fast, thx
@Jan-E could you please provide a new build?

**Comment by Jan-E** [comment]
New version at https://phpdev.toolsforresearch.com/php-7.1.0-dev-Win32-VC14-x64.zip

**Comment by SirSnyder** [comment]
@Jan-E the error still exists in the new version. Are you sure the fix is included?

**Comment by Jan-E** [comment]
I git pulled the new version at 01:12 CEST, compiled it the same minute, added it to the zipfile at 01:15 CEST (about 2 hours ago) and uploaded the zip. The php_pthreads.dll in the zip is newer than the other files. So, yes, I am sure. Check if your php_pthreads.dll is newer than the other files.

**Comment by krakjoe** [comment]
@Jan-E did you run tests, I added a test for it to the repo ?

**Comment by Jan-E** [comment]
I recompiled once again and ran the tests:

	=====================================================================
	Number of tests :   80                79
	Tests skipped   :    1 (  1.2%) --------
	Tests warned    :    0 (  0.0%) (  0.0%)
	Tests failed    :    0 (  0.0%) (  0.0%)
	Expected fail   :    0 (  0.0%) (  0.0%)
	Tests passed    :   79 ( 98.8%) (100.0%)
	---------------------------------------------------------------------
	Time taken      :   98 seconds
	=====================================================================
	
	PASS Test run time cache bug #494 [/php-sdk/php70dev/ext/pthreads/tests/run-time-cache-corruption.phpt]
	SKIP Test waiting timeouts [/php-sdk/php70dev/ext/pthreads/tests/waiting-timeouts.phpt] reason: : no support for this on windows

This version is now at https://phpdev.toolsforresearch.com/php-7.1.0-dev-Win32-VC14-x64.zip

**Comment by SirSnyder** [comment]
That's it @Jan-E thank you guys @krakjoe
