### ISSUE TITLE
CLI or non-CLI

### ISSUE THREAD

**Issue by Jan-E** [krakjoe/pthreads#496]
Quote from the readme:

> I have spent many years trying to explain that threads in a web server just don't make sense.

It makes sense when running Apache on Windows. With php running as mod_php (php5apache2_4.dll or php7apache2_4.dll) you are restricted to a single Apache and a single PHP instance. Which essentially means you can only use one CPU-core at the same time in a PHP-script. In that case it makes sense to use php_threads.dll and open multiple threads.

I had some trouble finding a PHP-script that eats all of the available CPU power, but eventually found a crappy impementation of usleep for Windows.

Take the following PHP-script pool.php:

	<?php
	// http://grokbase.com/t/php/php-notes/073d25kabm/note-73857-added-to-function-usleep
	// Uses 100% CPU!
	// Helper function
	function getmicrotime(){
	     list($usec, $sec) = explode(' ',microtime());
	     return ((float)$usec + (float)$sec);
	}
	
	// usleep alias function for windows
	function msleep($micro_seconds=0) {
	     $stop = getmicrotime() + ($micro_seconds / 1000);
	     while (getmicrotime() <= $stop) {
	         // loop
	     }
	     return true;
	}
	
	echo "Single at ".date('H:i:s', time())." <br>\n";
	msleep(20000); // single
	echo "/Single at ".date('H:i:s', time())." <br>\n";
	
	class My extends Threaded {
	    public function run() {
	        printf("Hello World from %s#%lu at ".date('H:i:s', time())." <br>\n",
	            __CLASS__, Thread::getCurrentThreadId());
			msleep(20000);
	    }
	}
	
	/* create a Pool of four threads */
	/* threads in a pool are created when required */
	$pool = new Pool(4);
	
	/* submit a few tasks to the pool */
	$tasks = 11;
	while ($tasks--) {
	    $pool->submit(new My());
	}
	
	/* shutting down the pool is tantamount to joining all workers */
	/* remember what I said about joining ? */
	$pool->shutdown();
	?>

You will recognize parts of the script from http://stackoverflow.com/a/24076161/872051

If I run this script under Apache 2.4.16 VC9 with PHP 5.3.29 TS (both x86) during the first msleep(20000) only 25% of the CPU power is used, but when running the Pool(4) the CPU usage reaches about 90% on my i5 quattro core.

The same happens if I run 'php.exe pool.php' or 'php-cgi.exe pool.php' from the command line.

**Comment by Jan-E** [comment]
@krakjoe 

> It doesn't load in non-cli mode ... I had to do it :)

It does, if you remove the E_ERROR, "The %s SAPI is not supported by pthreads":

	C:\>d:\phpdev\php70.x64\php-cgi pthreads7.php
	Hello World from My#2648 at 01:22:45 <br>
	Hello World from My#2648 at 01:23:05 <br>
	Hello World from My#2648 at 01:23:25 <br>
	Hello World from My#7188 at 01:22:45 <br>
	Hello World from My#7188 at 01:23:05 <br>
	Hello World from My#7188 at 01:23:25 <br>
	Hello World from My#5268 at 01:22:45 <br>
	Hello World from My#5268 at 01:23:05 <br>
	Hello World from My#5268 at 01:23:25 <br>
	Hello World from My#7036 at 01:22:45 <br>
	Hello World from My#7036 at 01:23:05 <br>
	X-Powered-By: PHP/7.1.0-dev
	Content-type: text/html; charset=UTF-8
	
	Single at 01:22:25 <br>
	/Single at 01:22:45 <br>

Output buffering causes the strange order of the output, but the times make it clear that php-cgi.exe is running 4 threads at the same time. Script:

	<?php
	// http://grokbase.com/t/php/php-notes/073d25kabm/note-73857-added-to-function-usleep
	// Uses 100% CPU!
	// Helper function
	function getmicrotime(){
	     list($usec, $sec) = explode(' ',microtime());
	     return ((float)$usec + (float)$sec);
	}
	
	// usleep alias function for windows
	function msleep($micro_seconds=0) {
	     $stop = getmicrotime() + ($micro_seconds / 1000);
	     while (getmicrotime() <= $stop) {
	         // loop
	     }
	     return true;
	}
	
	echo "Single at ".date('H:i:s', time())." <br>\n";
	msleep(20000); // single
	echo "/Single at ".date('H:i:s', time())." <br>\n";
	
	class My extends Collectable {
	    public function run() {
	        printf("Hello World from %s#%lu at ".date('H:i:s', time())." <br>\n",
	            __CLASS__, Thread::getCurrentThreadId());
			msleep(20000);
	    }
	}
	
	/* create a Pool of four threads */
	/* threads in a pool are created when required */
	$pool = new Pool(4);
	
	/* submit a few tasks to the pool */
	$tasks = 11;
	while ($tasks--) {
	    $pool->submit(new My());
	}
	
	/* shutting down the pool is tantamount to joining all workers */
	/* remember what I said about joining ? */
	$pool->shutdown();
	?>

**Comment by krakjoe** [comment]
> It makes sense when running Apache on Windows. With php running as mod_php (php5apache2_4.dll or php7apache2_4.dll) you are restricted to a single Apache and a single PHP instance.

When Apache is built in Worker mode, you can restrict it to one process, but it's still a multi-threaded process itself, if it weren't you could only serve a single client at a time.

It doesn't make sense anywhere, and isn't going to change; I'm not going to support execution anywhere but CLI.

**Comment by Jan-E** [comment]
Of course it is a multi-threaded process itself, but per client it is single-threaded and limited to a single CPU core. Try the script: it is the only way I can get PHP to use all my cores.

**Comment by krakjoe** [comment]
The architecture is still threaded, multi-threaded applications running inside other multi-threaded applications. with no decent way to make either properly aware or prepared for the other, is a recipe for disaster.

I wrote a little bit about this decision here: http://blog.krakjoe.ninja/2015/09/the-worth-of-advice.html

There is no way to make it good, in the CLI we are safe as can be, anywhere else we are not.

**Comment by Jan-E** [comment]
Quote from the stackoverflow (IIS) thread you are referring to:

> What you really want is concurrency, more specifically asynchronous concurrency since your operations are I/O-bound.

I tried your example at https://gist.github.com/krakjoe/6a9419704aaacfbc6f69 but that also uses max 25% of the available CPU power on my machine. If you want people to follow your advice, you should give them an alternative. Up until now, I haven't found a way to use all of the available CPU power from a single PHP script on Windows.
