### ISSUE TITLE
sleep/usleep alternatives

### ISSUE THREAD

**Issue by SirSnyder** [krakjoe/pthreads#497]
Hi @krakjoe, hi all,

sleep() and usleep() pointing to synchronized Thread::wait(). But in the "primary" Thread there is no Thread Object available.

```
<?php

var_dump(Thread::getCurrentThread()); // null
```

So what could be the alternative in primary Thread? time_nanosleep() ?

**Comment by krakjoe** [comment]
Don't use anything not designed for multi-threading.

If your main context needs to sleep for some reason, then create a monitor:

	<?php
	$monitor = new Threaded();
	$monitor->synchronized(function() use($monitor) {
		$monitor->wait(1000000);
	});
	?>

Other threads can then wake the main context on demand by sending notification to that object.

**Comment by SirSnyder** [comment]
Ah yes, good idea
