### ISSUE TITLE
class inheritance: __set method called instead of protected property

### ISSUE THREAD

**Issue by SirSnyder** [krakjoe/pthreads#499]
Hi @krakjoe, if a parent class extends Threaded and also __set() interceptor is defined, a call of a protected property redirects to this _set() method.

```
class ObjectGraph extends Threaded
    {
        /** @var bool */
        protected $blnIsDefault;

        public function __set(string $name, $value)
        {
            switch($name)
            {
                default :
                {
                    throw new \InvalidArgumentException('undefined property '. $name);
                }
            }
        }
    }

    class DefaultObjectGraph extends ObjectGraph
    {
        public function __construct()
        {
            $this->blnIsDefault = true;
        }
    }

    new DefaultObjectGraph();
```
result

Fatal error: Uncaught InvalidArgumentException: undefined property blnIsDefault in D:\sandbox\v3_tests\bug4\bug4.php:20
Stack trace:
#0 D:\sandbox\v3_tests\bug4\bug4.php(32): ObjectGraph->__set('blnIsDefault', true)
#1 D:\sandbox\v3_tests\bug4\bug4.php(36): DefaultObjectGraph->__construct()
#2 {main}
  thrown in D:\sandbox\v3_tests\bug4\bug4.php on line 20

If ObjectGraph doesn't extends Threaded, it works like expected.

**Comment by krakjoe** [comment]
We have to call magic first if it's set, because if a magic method uses synchronization you will get unexpected results.

**Comment by SirSnyder** [comment]
Ah, good to know about the magic method!
