### ISSUE TITLE
Local static var not working

### ISSUE THREAD

**Issue by SirSnyder** [krakjoe/pthreads#501]
Hi @krakjoe, local static var within thread context not working
```
class MethodWithLocalStaticVar extends Threaded
    {
        public function exec()
        {
            static $strNiceTry = 'value';

            var_dump($strNiceTry);
        }
    }
    $objInstance = new MethodWithLocalStaticVar();
    $objInstance->exec();

    $objThread = new class extends Thread
    {
        public function run()
        {
            $objInstance = new MethodWithLocalStaticVar();
            $objInstance->exec();
        }
    };

    $objThread->start();
    $objThread->join();
```
result:
string(5) "value"
NULL

Thx ;-)

php 7 master
pthreads 3.0.8
win 7 x64

**Comment by krakjoe** [comment]
Thanks for the report ;)

**Comment by SirSnyder** [comment]
@Jan-E could you please provider a new release of pthreads 3 for php 7 master(x64 TS)? Many thanks in advance

**Comment by Jan-E** [comment]
Recompiled:
https://phpdev.toolsforresearch.com/php-7.0.0RC4-nts-Win32-VC14-x64.zip

**Comment by SirSnyder** [comment]
@Jan-E, thanks for your effort, but I need a TS release. NTS doesn't provide pthreads.

**Comment by Jan-E** [comment]
Sorry, wrong link. It was this one:
https://phpdev.toolsforresearch.com/php-7.1.0-dev-Win32-VC14-x64.zip

**Comment by SirSnyder** [comment]
Thx @Jan-E
