### ISSUE TITLE
RefCount question

### ISSUE THREAD

**Issue by SirSnyder** [krakjoe/pthreads#502]
Hi @krakjoe, a question about refcounting
```
class Test extends Volatile
    {
        public $var;
    }


    $objThread = new class extends Thread
    {
        public function run()
        {
            $objHolder      = new Test();
            $objInstance    = new Test();

            $objHolder->var = $objInstance;

            echo 'reference set, refcount '. $objInstance->getRefCount() . PHP_EOL;

            $objHolder->var = null;

            echo 'reference nulled, refcount '. $objInstance->getRefCount() . PHP_EOL;

            unset($objHolder->var);

            echo 'reference unset, refcount '. $objInstance->getRefCount() . PHP_EOL;
        }
    };
    $objThread->start();
    $objThread->join();
```
prints:
reference set, refcount 3
reference nulled, refcount 3
reference unset, refcount 2

It seems, a null assignment doesn't lower the refcount. Why do I have to explicitly unset() the reference to decrease the refcount?

**Comment by krakjoe** [comment]
This is a side effect of volatile objects. We can't do anything about it, if we want Volatile objects to be able to retain references to objects which have no other objects in the engine, which we do.

In all cases, zends' garbage collector and pthreads' store will manage the references appropriately, so that they do not leak.

	<?php
	class Test extends Volatile
	{
		public $var;
	}

	$objThread = new class extends Thread
	{
		public function run()
		{
		    $objHolder      = new Test();
		    $objInstance    = new Test();

		    $objHolder->var = $objInstance;

		    echo 'reference set, refcount '. $objInstance->getRefCount() . PHP_EOL;

		    $objHolder->var = new Test();

		    echo 'reference reset, refcount '. $objInstance->getRefCount() . PHP_EOL;
		}
	};

	$objThread->start();
	$objThread->join();

	$objThread = new class extends Thread
	{
		public function run()
		{
		    $objHolder      = new Test();
		    $objInstance    = new Test();

		    $objHolder->var = $objInstance;

		    echo 'reference set, refcount '. $objInstance->getRefCount() . PHP_EOL;

		    unset($objHolder);

		    echo 'reference container unset, refcount '. $objInstance->getRefCount() . PHP_EOL;
		}
	};
	$objThread->start();
	$objThread->join();

	$objThread = new class extends Thread
	{
		public function run()
		{
		    $objHolder      = new Test();
		    $objInstance    = new Test();

		    $objHolder->var = $objInstance;

		    echo 'reference set, refcount '. $objInstance->getRefCount() . PHP_EOL;

		    $objHolder->var = null;
			$objHolder->var = $objInstance;

		    echo 'reference reset, refcount '. $objInstance->getRefCount() . PHP_EOL;
		}
	};
	$objThread->start();
	$objThread->join();

You shouldn't really care about refcounts beyond that ... this is not meant to be information exposed to userland ;)
