### ISSUE TITLE
Undefined constant PTHREADS_ALLOW_GLOBALS

### ISSUE THREAD

**Issue by SirSnyder** [krakjoe/pthreads#503]
Hi @krakjoe, I liked this feature and used it very much. Was it removed?

**Comment by SirSnyder** [comment]
Found another solution. A Threaded instance will be created in the main context and injected  manually at thread creation time via constructor into the thread. So it's possible to share data globally.

**Comment by krakjoe** [comment]
Yes it was, it was a hack that only caused instability ...

**Comment by smolinari** [comment]
Hehehe.....Did removing the constant also break the PHP docs page? 

http://php.net/manual/en/pthreads.constants.php

:smile: 

Scott
