### ISSUE TITLE
Random "zend_mm_heap corrupted" message within Thread::run method

### ISSUE THREAD

**Issue by SirSnyder** [krakjoe/pthreads#504]
Hello @krakjoe, 
maybe you have an idea to track down this bug. Occasionally my application dies with the message "zend_mm_heap corrupted". According to WinDBG, the error occurs in zend_mm_free_heap(). There is no direct method call which causes the error. I guess the gc kicks in and crashes. If I disable the gc(gc_disable();), everything seems fine. But this is no proper solution. Most crashes happen, if a DependencyInjector with heavy use of the PHP Reflection API(ReflectionClass, ReflectionMethod, ReflectionProperty) is working. To cache the reflection instances, I store them in a simple array(static class property). If I doesn't store them and instead create every time a new instance of Reflection*, everything seems to be ok. Just assumptions, I can't reproduce this behaviour in a stable and easy way, but I try to provide example code. It's not easy. :-/

Thx

--------
Win7 x64
pthreads 3.0.8 (http://windows.php.net/downloads/pecl/releases/pthreads/3.0.8/ is not ready!)
php7 rc 5 (master / build by Jan-E)

Edit// gc_disable() doesn't help

**Comment by smolinari** [comment]
Out of curiosity, but is there a particular reason why you are using Windows?

Scott

**Comment by SirSnyder** [comment]
Yes, there are some reasons. For example, I like the gui, better driver support, stable tools. My alternatives are Ubuntu and Debian. But I feel more comfortable with Win 7.

**Comment by smolinari** [comment]
As a web server or as a development environment? I also like Windows better for development, but I use VMs (with Virtualbox) as the web servers to develop for. 

Scott

**Comment by SirSnyder** [comment]
As a development environment, for sure. If the application works like expected, I test them in a VM(I use Virtualbox too) and lastly at the webserver(check of hardware, cpu architecture, performance). Do you already use pthreads v3?

**Comment by smolinari** [comment]
No. Well, not directly and not yet. My interest is in appserver.io, which uses pthreads for its threaded server concept. I am hoping the appserver.io team will upgrade to pthreads v3 just after PHP7 releases.

Scott

**Comment by krakjoe** [comment]
I do require reproducing code.

**Comment by SirSnyder** [comment]
No reproducible code yet but some more infos. The usage or assignment of a const triggers the error.

```
    interface Object
    {
        const STATIC_DELIMITER = '::';
        const OBJECT_DELIMITER = '->';
    }
```
```
trait ThreadedCommons
{
    public function __hash():string
    {
        return Object::STATIC_DELIMITER . $this->getHash(); // crash
        return '::' . $this->getHash(); // ok
        return $this->getHash(); // ok
    }
}
```
```
trait ThreadedCommons
{
    public function __hash():string
    {
        $s = Object::STATIC_DELIMITER; // this assignment triggers the zend_mm_free_heap error

        return $s . $this->getHash();
    }
}
```

```
trait ThreadedCommons
{
    public function __hash():string
    {
        $s = Object::STATIC_DELIMITER; // this assignment triggers the zend_mm_free_heap error

        return $this->getHash();
    }
}
```
Maybe it's php core related and doesn't belongs to pthreads. I don't know, trying to find a reproducable example.

**Comment by krakjoe** [comment]
Found a typo, probably not related ... */me awaits reproducing code  still*

**Comment by SirSnyder** [comment]
I will setup a VM, but that needs a while. 

Maybe @Jan-E would be so kind and provide a new build(php RC5, pthreads seven branch, x64 and TS) again?

**Comment by Jan-E** [comment]
https://phpdev.toolsforresearch.com/php-7.0.0RC5-Win32-VC14-x64.htm 
https://phpdev.toolsforresearch.com/php-7.0.0RC5-Win32-VC14-x64.zip

**Comment by SirSnyder** [comment]
@Jan-E thank you very much! Do you use VS 14 Community Edition? Installed the VS 14 Community Edition and the cl.exe can not be found, strange ... @krakjoe unfortunately it's not fixed.

**Comment by smolinari** [comment]
Did you test on a VM (i.e. non-windows)? 

Scott

**Comment by SirSnyder** [comment]
@smolinari Nope, with the build provided by @Jan-E. The VM setup needs some time.

**Comment by smolinari** [comment]
With Vagrant and Puphpet and Virtualbox it takes all of about 2 minutes to build a VM with a nightly build of PHP7. 

https://puphpet.com/

Scott

**Comment by SirSnyder** [comment]
@smolinari puphpet looks good, will give it a try. Is there an option to enable php threadsafety? Write me an email, so we do not completely messing up this issue.

**Comment by smolinari** [comment]
AFAIK, thread safe binaries are only a Windows concern.

Scott

**Comment by Jan-E** [comment]
@SirSnyder Yes, I am using the Community Edition. The cl.exe is in C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\amd64\\

**Comment by Jan-E** [comment]
See https://github.com/rlerdorf/php7dev for a preconfigured Debian PHP 7 build box

**Comment by SirSnyder** [comment]
It seems to be fixed on Debian / php 7.0 RC6 + pthreads 3.0.9. Will test it additionaly on Windows

**Comment by krakjoe** [comment]
Need to test against 3.1 ... many faults fixed, few things changed ...

3.1 is going to be the first officially supported version for PHP7, API is finalized by now ... just want to do one last sweep for bugs, then it should be ready about the same time as the first release of 7.0 ...

**Comment by Jan-E** [comment]
All my PHP7 builds have been rebuilt with the latest sources.

https://phpdev.toolsforresearch.com/php-7.0.0RC7-Win32-VC14-x64.htm 
https://phpdev.toolsforresearch.com/php-7.0.0RC7-Win32-VC14-x64.zip

**Comment by krakjoe** [comment]
Thanks @Jan-E

**Comment by krakjoe** [comment]
@SirSnyder pecl has new releases now too, can you test again please ?

**Comment by SirSnyder** [comment]
@krakjoe tested on windows 7 x64, it is fine. Want to test unix too, after I'm done with a possible solution for #516.

**Comment by BurakDev** [comment]
@Jan-E Possible php7 RC8 + pthreads 3.1.3 ? Thanks in advance :heart:

**Comment by Jan-E** [comment]
They are already there:
https://www.apachelounge.com/viewtopic.php?t=6617

**Comment by SirSnyder** [comment]
3.1.3 on Win/Unix crashed, 3.1.4dev on win/unix is ok

**Comment by krakjoe** [comment]
I will be doing a release soon, thanks for update :)
