### ISSUE TITLE
Anonymous class crashes Thread

### ISSUE THREAD

**Issue by SirSnyder** [krakjoe/pthreads#505]
Hi @krakjoe,
a new instance of an anonymous class within a thread context crashes the application. A simple example:

```
class Test extends Thread
    {
        public function run()
        {
            new class {};
        }
    }

    $objThread = new Test();
    $objThread->start();
    $objThread->join();
```

Thx

---

Win7 x64
pthreads 3.0.8 (http://windows.php.net/downloads/pecl/releases/pthreads/3.0.8/ is not ready!)
php7 rc 5 (master / build by Jan-E)

**Comment by krakjoe** [comment]
I know about this, it's because the anon class is not bound when the thread is started ... I'll try to find a fix for it ...

**Comment by SirSnyder** [comment]
That would be great, anon classes are really useful and cool :-)
