### ISSUE TITLE
Can't sleep() with pthreads and php7 (RC5)

### ISSUE THREAD

**Issue by Alaanor** [krakjoe/pthreads#506]
We can't use [usleep][1] and [sleep][2] function with pthread.

It's throw a exception like this:

 > alaanor@notebook:~$ php -r "sleep(5);"
PHP Fatal error:  Uncaught RuntimeException: sleep is not suitable for use in multi threaded applications, use synchronized Threaded::wait in Command line code:1
Stack trace:
#0 Command line code(1): sleep(5)
#1 {main}
  thrown in Command line code on line 1
Fatal error: Uncaught RuntimeException: sleep is not suitable for use in multi threaded applications, use synchronized Threaded::wait in Command line code:1
Stack trace:
#0 Command line code(1): sleep(5)
#1 {main}
  thrown in Command line code on line 1

As you can see, **we aren't into a Thread object**.

But, [time_sleep_until()][4] function work. Why ?

    time_sleep_until(microtime(true)+$time);

Check [my topic on sitepoint forum][3].

Some information:
> alaanor@notebook:~$ php -v
PHP 7.0.0RC5 (cli) (built: Oct 21 2015 14:58:58) ( ZTS DEBUG )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies
alaanor@notebook:~$ php --ri pthreads
pthreads
Version => 3.0.9

Note: I've read post like [#497](https://github.com/krakjoe/pthreads/issues/497) but it's talk about a code into a Thread object instead of me.

  [1]: http://php.net/manual/en/function.usleep.php
  [2]: http://php.net/manual/en/function.sleep.php
  [3]: http://community.sitepoint.com/t/pthreads-and-sleep-function/205575
  [4]: http://php.net/manual/en/function.time-sleep-until.php

**Comment by SirSnyder** [comment]
#497 is not about inside or outside of a Thread object. 

Not elegant but possible.
```
<?php
function _sleep($seconds)
    {
        $monitor = new Threaded();
        $monitor->synchronized(function() use($seconds, $monitor) {
            $monitor->wait($seconds * 1000000);
        });
    }
?>
```

**Comment by Alaanor** [comment]
Thank for sharing ! It's work nicely.

**Comment by emiglobetrotting** [comment]
hi Alaanor , please may you provide your installation of php7 + pthreads enabled. i've tried different ways but yet can't get it enabled.
