### ISSUE TITLE
Apache2 doesn't start

### ISSUE THREAD

**Issue by danilkinanton** [krakjoe/pthreads#509]
I use Apache/2.4.7 and PHP 7.0.0RC6 (cli)
Apache doesn't start after pthreads installation.
Apache error:  * The apache2 instance did not start within 20 seconds. Please read the log files to discover problems.
But Apache error.log is empty.

What is the cause of the problem?

**Comment by krakjoe** [comment]
pthreads cannot be used anywhere but cli in PHP7.

**Comment by smolinari** [comment]
Or you can tryout something like [appserver.io](http://appserver.io/).

Scott
