### ISSUE TITLE
pthreads detected an attempt to connect to an object which has already been destroyed

### ISSUE THREAD

**Issue by yinliangc** [krakjoe/pthreads#511]
```php
<?php

class TestThread extends Thread
{

    public $url;

    public $data;

    public function __construct($url)
    {
        $this->url = $url;
    }

    public function run()
    {
        $this->data = curlGet($this->url);
    }
}

function curlGet($url)
{
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_TIMEOUT, 30);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $curl_body['content'] = curl_exec($ch);    // display "pthreads detected an attempt to connect to an object which has already been destroyed error " in php 7 and pthreads 3.0.08, but works well in php 5.6 and pthreads 2.0.10
    
  //  $curl_body = curl_exec($ch);   // if use this in php 7 and pthreads 3.0.08 works well
    curl_close($ch);
    return $curl_body;
}

function createThread($urlArray)
{
    foreach ($urlArray as $i => $url) {
        $threadArray[$i] = new TestThread($url);
        $threadArray[$i]->start();
    }
    
    foreach ($threadArray as $key => $thread) {
        if ($thread->join()) {
            $threadDataArray[$key] = $thread->data;
        }
    }
    return $threadDataArray;
}

for ($i = 0; $i < 50; $i ++) {
    $url = 'http://127.0.0.1';
    $urlArray[] = $url;
}

$data = createThread($urlArray);

print_r($data);

?>
```

if i use     $curl_body['content'] = curl_exec($ch);    it would display "pthreads detected an attempt to connect to an object which has already been destroyed …' error 
but  $curl_body = curl_exec($ch);   works well, 

$curl_body['content'] = curl_exec($ch);   and $curl_body = curl_exec($ch);  all works well in pthreads 2.0.10, 
is it a bug ?    what's wrong?

**Comment by krakjoe** [comment]
Because of new coercion rules; The ```array``` you are creating in the ```Thread``` is coerced to ```Volatile``` when set as a member of the ```Thread```.

A simpler reproduce is this:

```php
<?php
class Test extends Thread {

	public function run() {
		$this->data = ["Hello"];
	}
}

$test = new Test();
$test->start();
$test->join();
var_dump($test->data);
?>
```

Which yields the same exception that you see.

The solution is forcing pthreads to allow you to use an array by explicitly casting when setting the member, like this:

```php
<?php
class Test extends Thread {

	public function run() {
		$this->data = (array)["Hello"];
	}
}

$test = new Test();
$test->start();
$test->join();
var_dump($test->data);
?>
```

**Comment by yinliangc** [comment]
<?php
class Test extends Thread {

    public function run() {
        $this->data = (array)["Hello"];
    }
}

$test = new Test();
$test->start();
$test->join();
var_dump($test->data);
?>

but the script still display same error, what's wrong ?
my  server is  PHP 7.0.0RC5 (cli)  and pthreads 3.0.08 .

**Comment by krakjoe** [comment]
Update pthreads.

**Comment by yinliangc** [comment]
It works well and hope to join the official version earlier, thanks

**Comment by krakjoe** [comment]
A release is coming, there are/were bugs in the latest RC last time I was testing, so release was delayed.

**Comment by nogrp** [comment]
@yinliangc if I may ask, why use pthreads to perform multiple curl requests when curl extension itself has support for that feature? It would seem that a lot of people using pthreads use it for some sort of parallel url scraping, but we already have it provided by curl.

**Comment by krakjoe** [comment]
FWIW I agree that if you are just doing a lot of I/O then asynchronous I/O is better for that than threads are.

cURL doesn't do anything in parallel though, so if the job is more complex than just downloading a few things, for example, you need to parse some data, then store results in a database, then doing the requests, parsing and insertion in parallel is a solid use case.

**Comment by baldasso** [comment]
One other solution to this problem, since version seven was not official release yet, is cast the array in an object. 

```php
<?php
class Test extends Thread {

    public function run() {
        $this->data = (object)["Hello"];
    }
}

$test = new Test();
$test->start();
$test->join();
var_dump($test->data);
?>
```
