### ISSUE TITLE
Why is the destruct called twice ?

### ISSUE THREAD

**Issue by yagerstano** [krakjoe/pthreads#512]
`class jobs extends Collectable {
        protected $sTime;
        public function __construct(){
    		$this->sTime = microtime(true);
    	}
    	public function __destruct(){
    		$tTime = microtime(TRUE)-$this->sTime;
    		echo "In:".__METHOD__." Elapsed Time:".$tTime."<BR>";
    	}
    }

    class job_GEN extends jobs {
      public $val;
      public function __construct($val){
      	 $this->val = $val;
    	 echo "In:".__METHOD__." Val:".$this->val."<BR>";
    	 parent::__construct(); 
      }
      public function run(){  
        $q = array(); // Array to count insert successes.
    	$range = 1000; //1000000; // Set loop range.
    	$min = 55555; // Lower limit of random range.
    	$max = 99999999999999999; // Uper limit of random range.
    	foreach ( range (0,$range) as $key ) {  // Create random number.
    		$r = mt_rand($min,$max); 
    		array_push($q,$r);
    	}
    	echo "In:".__METHOD__." GEN success:".count(array_unique($q))."<BR>";
      }
    }

    $p = new Pool(3);
    $tasks = array();
    foreach ( range(1,1) as $k ) { 	array_push($tasks,new job_GEN($k));	 }
    foreach ($tasks as $task) { $p->submit($task); }
    
    $p->shutdown();`

This is the output:

In:job_GEN::run GEN success:1001
In:jobs::__destruct Elapsed Time:0.0079128742218018
In:job_GEN::__construct Val:1
In:jobs::__destruct Elapsed Time:1446739672.9232

This is debug_backtrace
first destruct
array(1) {
  [0]=>
  array(5) {
    ["function"]=>
    string(10) "__destruct"
    ["class"]=>
    string(4) "jobs"
    ["object"]=>
    object(job_GEN)#2 (4) {
      ["val"]=>
      int(1)
      ["sTime"]=>
      float(1446740437.6722)
      ["garbage"]=>
      bool(false)
      ["worker"]=>
      object(Worker)#3 (0) {
      }
    }
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(0) {
    }
  }
}
second one
array(1) {
  [0]=>
  array(5) {
    ["function"]=>
    string(10) "__destruct"
    ["class"]=>
    string(4) "jobs"
    ["object"]=>
    object(job_GEN)#2 (3) {
      ["val"]=>
      NULL
      ["sTime":protected]=>
      NULL
      ["garbage":protected]=>
      bool(false)
    }
    ["type"]=>
    string(2) "->"
    ["args"]=>
    array(0) {
    }
  }
}

Hi,
I am new to multi threading, trying to understand,
How come run is before construct ?
Why is the destruct called twice ?
Why is $this->sTime unset in the last destruct ?

Thanks.

**Comment by krakjoe** [comment]
The destructor is called once in every context with a reference to the object.
