### ISSUE TITLE
Feedback - branch management

### ISSUE THREAD

**Issue by browner87** [krakjoe/pthreads#513]
Hi Joe, I'm just wondering if you would consider changing your branching/repo layout structure in future to be a bit more like PHP's. An issue I just worked through was all of a sudden my automated builds started failing (by automated I mean hand-run scripts, as opposed to regularly run). Since I was pulling from the "seven" branch I believe, I was getting your 3.0.x code which is PHP7 only (I'm compiling against 5.6). It would be nice if you had something like "2.0" and "3.0" branches, with "2.0" always referring to the latest 2.0.x code, and "3.0" always pointing to the latest 3.0.x code. This way I can always pull from "2.0", always have the latest 2.0 code, but not have to go back and hard-code tagged versions when there are updates to a newer major release.

Unless of course I am doing this entirely wrong. Git and I have a hate relationship and maybe there is some better approach I'm missing?

**Comment by krakjoe** [comment]
Well you should, for the moment, pull from master to build for 5 ...

This has only just become a problem with 7, really the master branch of pthreads and php-src should be compatible ...

It's a thing I'll solve, sometime ...

**Comment by browner87** [comment]
Ah, I think I just saw what was confusing me - I wasn't specifying a branch, assuming that would lead me to Master, but you have the default branch set to "seven". I'll point directly to Master going forward, thanks :).
