### ISSUE TITLE
Dies this works with linux?

### ISSUE THREAD

**Issue by AmitMY** [krakjoe/pthreads#515]
I could not find anywhere you point out linux support, or lack of support. I can only find Mac OSX and Windows support. (which are great).
I have a 28 threads linux server I want to run some code on. How can I install PTHREADS?

**Comment by krakjoe** [comment]
It's based on Posix Threads, so will work anywhere pthread.h exists.

Mac OSX is mentioned because of the slightly different build chain, and Windows because Posix Threads aren't native there.

**Comment by AmitMY** [comment]
Thanks, Ill go for it!
