### ISSUE TITLE
Open question/requirement about public static variables

### ISSUE THREAD

**Issue by metalwolf** [krakjoe/pthreads#518]
Hi @krakjoe 

This is an open question, 

should public static $var of \Threaded should also be thread local variables ? 
after a simple test , only the public static of \Thread are thread local, but threaded static are program wide and serialized like the rest of the attributes of the volatile class while passing the context between threads.

Thanks

**Comment by krakjoe** [comment]
Please provide reproducing code.

**Comment by metalwolf** [comment]
Hi @krakjoe 
Will not be necesary, i recompiled last version of PHP7 and work file as it should, static of both threaded and volatile are local. Dunno what really happened , but works fine now.
(PHP7RC7 cli, with pthreads 3-0-8 on CentOS 6)
I hence close the issue.
Thanks and sorry to bother

**Comment by krakjoe** [comment]
No bother, thanks for keeping issue up to date ;)
