### ISSUE TITLE
Threads are not being fully destroyed or something

### ISSUE THREAD

**Issue by AmitMY** [krakjoe/pthreads#519]
I am training a Random Forest which is a name for alot of desicision trees.
Im seperating each tree to a thread, thus it utilizes 105%(!) of the CPU which is great.
But, each time I run the code from the start (refresh the page), it takes 4 times as long as the previous time. (Exactly 4 times, checked)
My guess is that Im not destroying threads, and they are staying open.
*Note: an apache restart cleans everything, so im back to the first stage, of 40ms per tree.
*Note: without the hyperthreading, it takes constant time, which is more reliable, but slower.
*Note: Im running PHP 5.6.3
*Clean code is attached [code.txt](https://github.com/krakjoe/pthreads/files/33280/code.txt)

My question:
Is this a problem with the library? Or with my code?

**Comment by krakjoe** [comment]
I need reproducing code.

**Comment by AmitMY** [comment]
OK.
this is an image of my CPU usage after a XAMPP restart, and 6 runs of the scripts back to back.
https://i.gyazo.com/46d0a88c89d21fa3c8a4b9da6c139417.png
(where every red dot is a run of the script).
you can see that first, second, third, and fourth time were ok (the script tells you how much time it took, but then on 5th it took a lot more time, and on 6th much much more.
I tried to debug with xdebug, but without luck.

I cannot attach a rar file. in this link run estimate_status.php
https://drive.google.com/file/d/0B5jORv16xomiWVN3T2cyTmJoSGM/view?usp=sharing

**Comment by krakjoe** [comment]
Reproducing code should be as close as possible to [MCVE](http://stackoverflow.com/help/mcve)

**Comment by AmitMY** [comment]
This is the most minimal I can go, for I am using a library that works 100%.
the only code that should be a concern is the Thread, inside the function "random_forest_classify", which with, has an increasing execution time, and without works in exact time.
Ill try this on a different server and will report back.

**Comment by krakjoe** [comment]
v2 is not supported anymore, use php7 + pthreads v3.

In PHP7 you are not allowed to use pthreads anywhere but CLI.

If you find there is still a problem once upgraded, please open another issue.
