### ISSUE TITLE
memory_get_peak_usage and memory_get_usage are not correct using pthreads

### ISSUE THREAD

**Issue by metalwolf** [krakjoe/pthreads#520]
Hi @krakjoe 

Poking around with memory limits, it appears the native PHP functions have no clue about real memory limits on threads. 
Is there something we can do to get real memory use while using pthreads ? 
It seems the sum of all reported threads is not correct either, made a test and every thread report 2Mb while the OS reports 70Mb when i run 120 threads at the same time... some 170Mb difference..

Any clue on how to manage this ?

Thanks

**Comment by SirSnyder** [comment]
Hi @metalwolf 
please see https://github.com/krakjoe/pthreads/issues/405
