### ISSUE TITLE
Autoloader not called from within Thread

### ISSUE THREAD

**Issue by morria** [krakjoe/pthreads#521]
It looks like the autoloader isn't called from within a thread. Any ideas on why this might be?

```php
<?php

function autoload (string $class_name) {
    require_once(array_pop(explode('\\', $class_name)) . '.php');
}
spl_autoload_register('autoload');

class B extends \Threaded {
    public function run() {
        print_r(new A);
    }
}

// This works when uncommented
// (new B)->run();

// This does not work
$pool = new Pool(1);
$pool->submit(new B);
```

With file `A.php`

```php
class A {}
```

**Comment by morria** [comment]
Registering an autoloader from within B::run() seems to make it work.

**Comment by krakjoe** [comment]
This is expected.

The autoloading stuff is currently part of SPL, it doesn't expose an API, or a reasonable way, to duplicate the configuration from the parent thread.

There might be a solution to this way into the future, there is talk of moving the autoloading stuff to /Zend, which I can just export API's for ...

For now, just registering the autoloader has to do the job ...

**Comment by morria** [comment]
Thanks
