### ISSUE TITLE
3.1.3: Segfault on i386

### ISSUE THREAD

**Issue by remicollet** [krakjoe/pthreads#523]
TEST 56/87 [tests/return-types.phpt]
    ========DIFF========
    001+ Termsig=11
    001- string(4) "some"
    ========DONE========
    FAIL Test return types [tests/return-types.phpt]

**Comment by remicollet** [comment]
Same with 3.1.4

**Comment by krakjoe** [comment]
Sorry, forgot about this one ... just fixed it, will be included in next release ...

**Comment by remicollet** [comment]
This 2 last commit applied, no more segfault, but a failed test:

     TEST 75/87 [tests/verify-overload.phpt]
     ========DIFF========
     001+ Fatal error: Uncaught TypeError: Return value of Test::method() must be an instance of Custom, instance of Custom returned in /builddir/build/BUILD/php-pecl-pthreads-3.1.4/pthreads-3.1.4/tests/verify-overload.php:11
     002+ Stack trace:
     001- object(Custom)#1 (0) {
     002- }
     003+ #0 /builddir/build/BUILD/php-pecl-pthreads-3.1.4/pthreads-3.1.4/tests/verify-overload.php(15): Test->method()
     004+ #1 [internal function]: Test->run()
     005+ #2 {main}
     006+   thrown in /builddir/build/BUILD/php-pecl-pthreads-3.1.4/pthreads-3.1.4/tests/verify-overload.php on line 11
     ========DONE========
     FAIL Test VERIFY_RETURN_TYPE overload [tests/verify-overload.phpt]

**Comment by krakjoe** [comment]
Yeah, still working on it ...

**Comment by krakjoe** [comment]
Try that, I'll leave you to close when confirmed ...

**Comment by remicollet** [comment]
Everything ok now, but i386 and x86_64 test suite are ok.
Thanks.

**Comment by krakjoe** [comment]
Cool, ta ;)
