### ISSUE TITLE
Lots of tasks for a pool

### ISSUE THREAD

**Issue by tomerbal** [krakjoe/pthreads#525]
Hey,

I'm trying to implement Worker Pool with 5 Workers in parallel, when i test a simple pool with 50 tasks everything works fine.
But when i increase the amount of tasks to 5000 the something is wrong,
Is there anything im doing wrong?
Thanks

Code:

```php
<?php
ini_set('max_execution_time', 3000000);

class MyThread extends Worker {
	public function __construct($i) {
	    $this->sn = $i;
	}
	public function run() {
	    $time_start = microtime(true);
	    echo "Thread " . $this->sn . " start running at " . $time_start . "<br>";
	    sleep(0.5);
	    $time_end = microtime(true);
	    $time = $time_end - $time_start;
	    echo "Thread " . $this->sn . " finish in " . $time_end . ". took him $time seconds <br>";
	    $this->setGarbage();
	}
}

$pool = new Pool(5);

$tasks = array();
for ($i = 0; $i < 5000; $i++) {
	$tasks[] = new MyThread($i);
}

foreach ($tasks as $task) {
	$pool->submit($task);
}

$pool->shutdown();

echo "Main done <br>";
?>	
```

**Comment by krakjoe** [comment]
Can you pull the latest sources from master branch and try that ??

On a side note, you can just submit threaded objects to Pool/Worker in pthreads v3, and there is no need to ```setGarbage``` anymore (it is done for you already).

**Comment by tomerbal** [comment]
I'm running php  5.6.16 (VC11) on windows apache 2.4, what is the latest source for that?

Thanks

**Comment by RyanNerd** [comment]
Does pthreads work with Apache now?? I thought Apache is doing its own threading and running ptreads could create a racing condition. Is pthreads is only to be run as CLI?

Anyway, the above code works without errors running as CLI on Linux Mint 17.2
PHP 7.1.0-dev (cli) (built: Dec  3 2015 22:00:02) ( ZTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.4.0rc2-dev, Copyright (c) 2002-2015, by Derick Rethans

output:
...
Thread 4988 start running at 1449385229.3045
Thread 4988 finish in 1449385229.3045. took him 5.9604644775391E-6 seconds
Thread 4993 start running at 1449385229.3045
Thread 4993 finish in 1449385229.3045. took him 5.0067901611328E-6 seconds
Thread 4998 start running at 1449385229.3045
Thread 4998 finish in 1449385229.3045. took him 5.0067901611328E-6 seconds
Main done

**Comment by krakjoe** [comment]
@tomerbal v2 is no longer actively developed ... use php7 + pthreads v3 ...

@RyanNerd pthreads will not work in apache, you can only use pthreads in CLI.

Closing issue ...
