### ISSUE TITLE
how can I cross compile the pthreads PHP extends for IOS ?

### ISSUE THREAD

**Issue by CRQM** [krakjoe/pthreads#534]
how can I cross compile the pthreads PHP extends for IOS ?

thank you ,very much!!!

**Comment by krakjoe** [comment]
I have no experience of doing it myself, I know it's doable ... @shoghicp is a good person to ask about that ...

This isn't a bug in pthreads, so I'm closing, that doesn't end the conversion though, I'm sure you'll get an answer from someone who has done it ...

**Comment by CRQM** [comment]
thank you
