### ISSUE TITLE
pthread Module is loaded but pthread classes are not recognized 

### ISSUE THREAD

**Issue by javidG** [krakjoe/pthreads#535]
I have successfully installed the pThreads , the 'pthreads' is in the loaded modules of php, however I cannot run this script=>

<?php
$thread = new class extends Thread {
    public function run() {
        echo "Hello World\n";
    }
};

$thread->start() && $thread->join();
?>

=> The Error message is 
[Fatal error: Class 'Thread' not found in /Users/javidgajievi/Sites/http/index.php on line 2]

=>Adding the "extension=pthreads.so" in php.ini file prevented apache from running.
![1](https://cloud.githubusercontent.com/assets/16369693/11917563/25d4e728-a726-11e5-889a-231ba4fcd9eb.jpg)
![2](https://cloud.githubusercontent.com/assets/16369693/11917564/26139086-a726-11e5-94c4-95ad152823ee.jpg)

Warm Regards, J. G.

**Comment by krakjoe** [comment]
You cannot load pthreads in apache. Load pthreads in CLI only with ```php-cli.ini``` ...
