### ISSUE TITLE
Nullified local static array caused by class constant as key

### ISSUE THREAD

**Issue by SirSnyder** [krakjoe/pthreads#536]
Hi @krakjoe,

sadly there is no runnable simple sample code yet. I've no idea, how to reproduce the error easily. 

```
    class NotRunnableExample extends Threaded
    {
        const BEFORE = 'before';

        public function example()
        {
            static $arrNullifiedList = [self::BEFORE => true];

            var_dump($arrNullifiedList); // null

            static $arrList = ['before' => true];

            var_dump($arrList);

//            array(1) {
//            ["before"]=>
//              bool(true)
//            }
        }
    }
```

$arrNullifiedList prints null within thread context. In some rare cases, php crashes with a "zend_mm_heap corrupted" message. Maybe you have a clue.

Thx and regards
Bastian

**Comment by krakjoe** [comment]
I do need reproducing code to investigate ...

**Comment by SirSnyder** [comment]
Got it!

```
<?php

    class Test extends Thread
    {
        const CONST_STRING = 'key';

        public function run()
        {
            $this->synchronized(function ()
            {
                static $staticArray = [self::CONST_STRING => true];

                var_dump($staticArray);
            });
        }
    }

    $thread = new Test();
    $thread->start();
    $thread->join();
```
Result: null
Expected : array(1) {
  ["key"]=>
  bool(true)
}

Just a guess. It seems to be the combination of static array, synchronized and the const value used as array key.

**Comment by krakjoe** [comment]
I guess you must be using 7.1 ... I've fixed the class constant copy, so no fault, but the scope of the synchronized block is still not right ...

**Comment by SirSnyder** [comment]
Sorry, my fault @krakjoe. The example is to easy and does not reflect the exact (error) case. But I am working on that. I use 7.0.0 on windows and unix.

Here is a snippet of my code. AspectManager is a singleton instance across all threads. Method 'checkClassForAspect' is the interesting one.
```
<?php

class AspectManager extends Threaded implements EventListener
{
    use ClassInfo;
    use ThreadedSingletonImpl;

    const BEFORE = 'before';

	...
	
    public function onDispatch(Event $event)
    {
        if($event instanceof FileLoaderEvent)
        {
            switch($event->type())
            {
				...
			
                case FileLoaderEvent::LOAD_SUCCESS :
                {
                    /** @var SystemLoaderEvent $objPrevious */
                    $objPrevious = $event->previous();

                    $strClassname = $objPrevious->classname();

                    if(!isset($this->objProcessedClasses[$strClassname]))
                    {
                        $this->synchronized(function () use ($strClassname)
                        {
                            if(!isset($this->objProcessedClasses[$strClassname]))
                            {
                                $this->objProcessedClasses[$strClassname] = true;

                                $this->checkClassForAspect($strClassname);
                            }
                        });
                    }
                }; break;
            }
        }
    }


    protected function checkClassForAspect($classname)
    {
        static $arrtest = [self::BEFORE => true];

        var_dump('TEST 1 ------------------------------------- ', $arrtest, ThreadContext::id(), ThreadContext::name());

        // if(ThreadContext::isPrime() || ThreadContext::isThread()) // $arrtest2 is an array
        if(ThreadContext::isThread()) // $arrtest2 is null
        {
            static $arrtest2 = [self::BEFORE => true];

            var_dump('TEST 2 ------------------------------------- ', $arrtest2, ThreadContext::id(), ThreadContext::name());
        }

		...
    }
}
```

If checkClassForAspect() gets executed by main thread before any another thread (```if(ThreadContext::isPrime() || ThreadContext::isThread())```), the static array $arrtest2 is ok. If the main thread will be blocked (```if(ThreadContext::isThread())```), the static array $arrtest2 is null. $arrtest is fine, all the time. Maybe it's an opcache thing?

**Comment by SirSnyder** [comment]
Hi @krakjoe, maybe I've found something in copy.h line 40 ```if (Z_REFCOUNTED_P(next)) {```.   
```
        if(ThreadContext::isPrime() || ThreadContext::isThread()) // $arrtest2 is an array
        {
            static $arrtest2 = [self::BEFORE => true];

            var_dump('TEST 2 ------------------------------------- ', $arrtest2, ThreadContext::id(), ThreadContext::name());
        }
```
This seems to work, because ```static $arrtest2 = [self::BEFORE => true];``` gets executed before pthreads_copy_statics() will be called. In this peticular case ```if (Z_REFCOUNTED_P(next)) {``` is true and the array becomes a separate copy. If pthreads_copy_statics() is getting called before the line ```static $arrtest2 = [self::BEFORE => true];``` was executed, ```if (Z_REFCOUNTED_P(next)) {``` is false with no separate copy of the array. With a separate copy of $arrtest2 the bug seems to be fixed. Can ```if (Z_REFCOUNTED_P(next)) {``` be skipped/removed? What do you think?

I have to admit that this bug only concerns windows. I've updated to php 7.0.2 and pthreads 3.1.6dev, both, windows and unix. With latest versions unix is ok.
