### ISSUE TITLE
errro starting php-fpm

### ISSUE THREAD

**Issue by younessb** [krakjoe/pthreads#537]
Need help, cant start PHP-fpm I am getting an error : unable to start pthreads module, the fpm-fcgi sapi is not supported by pthreads!!!, I 've compiled PHP with --enable-pthreads=shared option to try to solve the problem but is still there.
I am running php7.0.0.1 and pthreads-3.1.5

**Comment by krakjoe** [comment]
Remove ```extension=pthreads.so``` from your configuration.

Create a ```php-cli.ini``` in the same path as ```php.ini```, this will be used by CLI only, and is where the ```extension=pthreads.so``` line should be.

**Comment by younessb** [comment]
Thanks for your support it's working

**Comment by DaveNascimento** [comment]
Though late, I just wanted to add for posterity that this solution also works for the Caddy server (hence, Laravel Valet). Thank you, krakjoe.
