### ISSUE TITLE
zend_mm_heap corrupted

### ISSUE THREAD

**Issue by Hetarnam** [krakjoe/pthreads#538]
Hi!

I try to launch this mornig the SocketServer example (https://github.com/krakjoe/pthreads/blob/master/examples/SocketServer.php)
and i found when i try to socket_close($client) this error :
zend_mm_heap corrupted

What is the problem? Thank you in advance !

**Comment by SirSnyder** [comment]
Hi @Hetarnam,
please have a look at issue #508. 
Kind regards

**Comment by krakjoe** [comment]
Sorry, resources are officially unsupported, if it doesn't work, there's not much I can do about it ...

Well more precisely, there is not much I can do about Zend streams not working, what I can do is implement a thread safe streams layer, which is something I intend to do, when I have the time ... don't know when that will be ...

**Comment by BoltUser** [comment]
hi @krakjoe sorry but i have the some problem, you know when this bug/proble is fixed?
