### ISSUE TITLE
Installing pthreads does not work on xampp/windows

### ISSUE THREAD

**Issue by greeso** [krakjoe/pthreads#539]
I am trying to install pthreads on xampp with php 7.0.0

My phpinfo shows:
Compiler: MSVC14 (Visual C++ 2015) 
Architecture: x86

So I downloaded the latest pthreads build that matches my environment (this build http://windows.php.net/downloads/pecl/releases/pthreads/3.1.5/php_pthreads-3.1.5-7.0-ts-vc14-x86.zip ), then I setup my environment properly (copied the two required .dll's to the proper location, and setup php.ini, and also fixed my path to include the path for php).

Then when I start apache, I get the following messages on the XAMPP control panel

7:09:56 PM  [Apache] 	Error: Apache shutdown unexpectedly.
7:09:56 PM  [Apache] 	This may be due to a blocked port, missing dependencies, 
7:09:56 PM  [Apache] 	improper privileges, a crash, or a shutdown by another method.
7:09:56 PM  [Apache] 	Press the Logs button to view error logs and check
7:09:56 PM  [Apache] 	the Windows Event Viewer for more clues
7:09:56 PM  [Apache] 	If you need more help, copy and post this
7:09:56 PM  [Apache] 	entire log window on the forums

And error.log show this:
PHP Fatal error:  The apache2handler SAPI is not supported by pthreads in Unknown on line 0
PHP Fatal error:  Unable to start pthreads module in Unknown on line 0

Please advise.

**Comment by bwoebi** [comment]
Well, I think the error log says it all. try using it from cli instead of apache.

**Comment by blackdesert** [comment]
"This may be due to a blocked port, missing dependencies, " 
Solution 1)
Turn off Skype.

Solution 2)
Uncheck "Use port 80 and 443" from skype options.

**Comment by SirSnyder** [comment]
what the ... like the error log already says "The apache2handler SAPI is not supported by pthreads", don't use pthreads in combination with apache. Try use php cli, because pthreads is cli only!

**Comment by greeso** [comment]
The reason for my post is pthreads used to work for me php5 with apache. I wasn't aware this is a feature, not to work with apache.

Can I ask why?

**Comment by bwoebi** [comment]
Right, it's by design (because it led to various subtle bugs). And in general, you really should - if you ever have something that heavy it needs threads - dispatch it to a cli worker process.

**Comment by rangersmash** [comment]
How do you use CLI with Xampp? I tried looking around, however I cannot find anywhere to change it from using apache into CLI?

**Comment by krakjoe** [comment]
You cannot use pthreads inside apache. Load pthreads using ```php-cli.ini``` ...

**Comment by cavo789** [comment]
Like greeso, I'm using phpThreads with success with PHP 5.x.   The existing PHP project, huge, is working fine.  I'm running it from my web browser, I need to specify a few informations then start the process, wait that tasks are done (all threads) and output somes results to the browser.

What to do to keep our project running like that and choose PHP 7.   Is it, really?, impossible in the future with PHP7 ?

Thanks a lot for your valuable answer.

**Comment by bwoebi** [comment]
@cavo789 in any case, you always can proc_open() (or similar) a separate cli process to run the job.

**Comment by cavo789** [comment]
@bwoebi Sorry for my ignorance : a cli process is to run a batch no ?  Here, I've a full bootstrap/jquery interface with a lot of functionnalities, javascript, ajax requests, ... and one process; started by ajax, looks for files on the filesystem.   For that process, I need phpthread.   At that time, my project is working fine and i'm just wanted to test it under PHP 7.  Should I review my architecture for that ?  (if so, I'll certainly not do it and stay under PHP 5.x for a while).  Thanks.
