### ISSUE TITLE
Any chance of a isolated bash script of pthreads v3?

### ISSUE THREAD

**Issue by rangersmash** [krakjoe/pthreads#541]
Any chance we could get an updated version for PHP 7.0.1 and Pthreads 3.1.5? https://gist.github.com/krakjoe/5044339

I've tried using this on Raspbian however I'm just getting errors that it is unable to get pthreads source. I'd love for this script to just install pthreads straight away, as I'm finding the installation of PHP 7 as well as pthreads an issue. Thanks!

**Comment by krakjoe** [comment]
Sure, updated ... should work for 5 still too ...
