### ISSUE TITLE
Serialization of Closure?

### ISSUE THREAD

**Issue by rangersmash** [krakjoe/pthreads#542]
So I have this code running a new thread/function:

        $roundDetails = new RoundDetails($this->server, $clients, $fixedClient, $totalRounds, $byes);
        $round = new Round($roundDetails);
        if($round->start()) {
          sleep($this->settings["roundCountdown"]);
          $round->join();  
        }
        
In my mind, this should execute the functions of the main thread, wait a certain amount of time, then just continue with the code. Round details looks like this: 
[RoundDetailsPHP.txt](https://github.com/krakjoe/pthreads/files/74559/RoundDetailsPHP.txt)

And my round files look like this:
[Round.txt](https://github.com/krakjoe/pthreads/files/74560/Round.txt)

So I'm struggling to identify where I am including a closure and some kind of fix. Also, will there be a way in the future to show the location of the closure as I feel this will help locate these kinds of bugs and let the programmer fix them easier. Thank you!

**Comment by krakjoe** [comment]
Guessing, because the code isn't executable, ```$this->server``` has closures as properties, and trying to serialize it will throw exception.

You may be able to use ```Threaded::extend``` to coerce the class of ```$this->server``` to be thread safe, though this may have unexpected consequences.

Whatever the source of the error, it's expected, so there is no bug here.

**Comment by rangersmash** [comment]
I've attempted to use Threaded::extend(ConnectionInterface::class), however it just results in cannot extend interface ?, so how would I get around this issue?
