### ISSUE TITLE
PHP Warning:  Module 'pthreads' already loaded but......

### ISSUE THREAD

**Issue by javidG** [krakjoe/pthreads#543]
PHP first run.
I ran the php -m command out put is:
-------------------------------------------op--------------------------------------------------------------------------
[PHP Modules]
Core
ctype
date
dom
fileinfo
filter
hash
iconv
json
libxml
pcre
PDO
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
---------------------------------------------------------------------------------------------------------------------

So I created php-cli.ini and included extension=pthreads.so to it then re- php -m out put is:

---------------------------------------------------op------------------------------------------------------------------
PHP Warning:  Module 'pthreads' already loaded in Unknown on line 0
[PHP Modules]
Core
ctype
date
dom
fileinfo
filter
hash
iconv
json
libxml
pcre
PDO
pdo_sqlite
Phar
posix
pthreads
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
---------------------------------------------------------------------------------------------------------------------
 
also apache failed to run logging
-------------------------------------------------op-------------------------------------------------------------------
PHP Fatal error:  Unable to start pthreads module in Unknown on line 0
Unknown(0) : Fatal error - The apache2handler SAPI is not supported by pthreads
Unknown(0) : Fatal error - Unable to start pthreads module 
---------------------------------------------------------------------------------------------------------------------

My environment =>  Mac osx 10.11.2
php 7.0.1
pthreads 3.1.5
apache 2.4.18

I used following configs to compile apache
---------------------------------------------------------------------------------------------------------------------
./configure \
--prefix=/Users/username/{folder}/httpd \
--enable-module=so \
--with-pcre=/Users/username/{folder}/httpd/pcre \
--exec-prefix=/Users/username/{folder}/httpd \
--with-mpm=worker
---------------------------------------------------------------------------------------------------------------------

I used following configs to compile php
---------------------------------------------------------------------------------------------------------------------
./configure \
--prefix=/Users/username/{folder}/php \
--exec-prefix=/Users/username/{folder}/php \
--with-apxs2=/Users/username/{folder}/httpd/bin/apxs \
--enable-maintainer-zts \
--with-tsrm-pthreads \
--enable-pthreads=shared \
--with-config-file-scan-dir=/Users/username/{folder}/php/lib \
--with-config-file-path=/Users/username/{folder}/php/lib \
--enable-debug \
--enable-cli
---------------------------------------------------------------------------------------------------------------------

I tried --enable-pthreads with =shared , =static and none .
I made sure of there is any ini files containing "extension=pthreads.so" line but there was none.

Please help me to get this thing working.

**Comment by krakjoe** [comment]
If mod_php is loading pthreads without there being a directive, then it must be statically compiled, because that's what ```=static``` does.

If you keep reconfiguring and building php without cleaning in between you are going to get strange results.

```
./configure \
--prefix=/Users/username/{folder}/php \
--exec-prefix=/Users/username/{folder}/php \
--with-apxs2=/Users/username/{folder}/httpd/bin/apxs \
--enable-maintainer-zts \
--with-tsrm-pthreads \
--enable-pthreads=shared \
--with-config-file-scan-dir=/Users/username/{folder}/php/lib \
--with-config-file-path=/Users/username/{folder}/php/lib \
--enable-debug \
--enable-cli
```

This looks right to me, start again, vcsclean, clone, or unpack the sources again and use that configure, the key part is only ```--enable-pthreads=shared```.

This isn't an issue with pthreads, so closing, not necessarily the end of the conversation though ;)

**Comment by javidG** [comment]
So, I have reinstalled the OS, basically started from 0, Compiled php as you directed but I am still having the same problem.  While compiling I got some warnings about pthreads should I worry about these logs?:


-------------------------------------------------------Log------------------------------------------------------------------------
=> 

[pthread]



In file included from php/ext/pthreads/src/object.c:26:
ext/pthreads/src/object.h:41:1: warning: '/*' within block comment [-Wcomment]
/* {{{ */
^
php/ext/pthreads/src/object.c:185:3: warning: passing 'unsigned char *' to parameter
      of type 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
                (*buffer), ":%lu:", (long unsigned int) address);
                ^~~~~~~~~
php/main/snprintf.h:87:31: note: passing argument to parameter 's' here
PHPAPI int php_sprintf (char* s, const char* format, ...) PHP_ATTRIBUTE_FORMAT(printf, 2, 3);




ext/pthreads/src/object.h:41:1: warning: '/*' within block comment [-Wcomment]
/* {{{ */
^
php/ext/pthreads/src/handlers.c:85:21: warning: unused variable 'threaded'
      [-Wunused-variable]
        pthreads_object_t *threaded = PTHREADS_FETCH_FROM(Z_OBJ_P(object));
                           ^
php/ext/pthreads/src/handlers.c:144:12: warning: unused variable 'nulled'
      [-Wunused-variable]
        zend_bool nulled = 0;
                  ^





In file included from php/ext/pthreads/src/store.c:30:
ext/pthreads/src/object.h:41:1: warning: '/*' within block comment [-Wcomment]
/* {{{ */
^
In file included from php/ext/pthreads/src/store.c:38:
ext/pthreads/src/copy.h:313:13: warning: unused function 'pthreads_copy_function_ctor' [-Wunused-function]
static void pthreads_copy_function_ctor(zval *bucket) {
            ^



ext/pthreads/src/object.h:41:1: warning: '/*' within block comment [-Wcomment]
/* {{{ */
^
php/ext/pthreads/src/prepare.c:601:22: warning: '&' within '|'
      [-Wbitwise-op-parentheses]
        if (thread->options & PTHREADS_INHERIT_CLASSES|PTHREADS_INHERIT_FUNCTIONS) {
            ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
php/ext/pthreads/src/prepare.c:601:22: note: place parentheses around the '&'
      expression to silence this warning
        if (thread->options & PTHREADS_INHERIT_CLASSES|PTHREADS_INHERIT_FUNCTIONS) {
            ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from php/ext/pthreads/src/prepare.c:38:
ext/pthreads/src/copy.h:313:13: warning: unused function 'pthreads_copy_function_ctor' [-Wunused-function]
static void pthreads_copy_function_ctor(zval *bucket) {



php/ext/pthreads/src/globals.c:78:12: warning: unused variable 'locked'
      [-Wunused-variable]
        zend_bool locked = 0;



ext/pthreads/src/object.h:41:1: warning: '/*' within block comment [-Wcomment]
/* {{{ */
^
In file included from php/ext/pthreads/php_pthreads.c:442:
ext/pthreads/classes/pool.h:141:8: warning: unused variable 'working' [-Wunused-variable]
        zval *working = NULL;
              ^
In file included from php/ext/pthreads/php_pthreads.c:47:
ext/pthreads/src/copy.h:313:13: warning: unused function 'pthreads_copy_function_ctor' [-Wunused-function]
static void pthreads_copy_function_ctor(zval *bucket) {
-------------------------------------------------------Log------------------------------------------------------------------------

**Comment by javidG** [comment]
There must be tiny thing that I miss...

Please check the phpinfo();
![phpinfo](https://cloud.githubusercontent.com/assets/16369693/12079368/a197b23a-b24f-11e5-970f-6d3017e0578a.jpg)

Until here everything is ok.
![pthreds_disabled](https://cloud.githubusercontent.com/assets/16369693/12079419/cc8c3fb8-b251-11e5-94e7-2e6ea4b6e874.jpg)


this is when the problem pops out.
![pthreads_enabled](https://cloud.githubusercontent.com/assets/16369693/12079428/179dbac2-b252-11e5-8d12-dd2273191c45.jpg)

**Comment by JesusTheHun** [comment]
As said in the README, pthreads now only allows CLI.
