### ISSUE TITLE
pthreads 2.0 incompatible to PHP7

### ISSUE THREAD

**Issue by deeky666** [krakjoe/pthreads#545]
Just encountered the following compile error when trying to build pthreads 2.0.10 with PHP7:

```
pthreads.h:41:40: fatal error: ext/standard/php_smart_str.h: No such file or directory
 #include <ext/standard/php_smart_str.h>
                                        ^
compilation terminated.
Makefile:194: recipe for target 'php_pthreads.lo' failed
make: *** [php_pthreads.lo] Error 1
```

Looks like in PHP 5 the header file is named `php_smart_str.h` while it is named `php_smart_string.h` in PHP7. If pthreads 2.0 is not intended to be compatible with PHP7, at least the documentation should reflect this. Currently it states as requirements `PHP5.3+`.

**Comment by smolinari** [comment]
Only version 3 works with PHP7.

Scott

**Comment by deeky666** [comment]
@krakjoe @smolinari the README should be updated then to avoid future confusion.

**Comment by smolinari** [comment]
Well, usually most people use the most up-to-date version, don't they? 

And, it is noted on the README page.

![image](https://cloud.githubusercontent.com/assets/3314957/12199009/170bdeb0-b615-11e5-8621-abd8e8cda728.png)


Scott

**Comment by nogrp** [comment]
Maybe the `README.md` should be updated with big bolded text stuck as first line saying **Please read this entire file first before asking questions**, that could help immensely.

**Comment by smolinari** [comment]
LOL! :smile: :+1: 

Scott

**Comment by deeky666** [comment]
@smolinari @nogrp you are right, I haven't read the `master` README, I have read the README from tag `2.0.10`. This is obviously my mistake ;) Sorry for confusion.

**Comment by nogrp** [comment]
@deeky666  well at least you're the man enough to admit your mistake (don't we all make them all the time?), I made the comment in good faith :) anyway, it seems it's all sorted now, thanks for not taking this the wrong way :+1:

**Comment by deeky666** [comment]
@nogrp nvm if I am too dumb to get this right, I deserve the punches ;)

**Comment by smolinari** [comment]
Hah! And I thought nogrp was the OP admitting to his mistake. How we all make mistakes....

Shit happen!

Scott
