### ISSUE TITLE
Inheritance + Composer + Synchronization (Closures)

### ISSUE THREAD

**Issue by deeky666** [krakjoe/pthreads#546]
I am not sure if I am missing something here but I couldn't find a clear answer to that. I am using `2.0.10` and want to have a Worker using Composer autoloader and use Closures for synchronization in Tasks (simplified code):

```php
class SequentialExecutor extends \Worker
{
    public function run()
    {
        require __DIR__ . '/../../../../../vendor/autoload.php';
    }

    public function start($options = 0)
    {
        parent::start(PTHREADS_INHERIT_NONE);
    }
}

class Task extends \Threaded
{
    public function getResult()
    {
        $this->synchronized(
            function () {
                while (!$this->done) {
                    $this->wait();
                }

                return $this->result;
            }
        );
    }

    public function run()
    {
        $this->synchronized(
            function () {
                // do some work
                $this->done = true;
                $this->notify();
            }
        );
    }
}
```

Now because of `PTHREADS_INHERIT_NONE` I cannot use Closures for synchronization:

```
PHP Fatal error:  Base lambda function for closure not found
```

If I change that to `PTHREADS_INHERIT_FUNCTIONS` I get function redeclaration errors:

```
PHP Fatal error:  Cannot redeclare composerRequire89d38271f1b83b023e03b6841d74a718()
```

How can this scenario be achieved? What is the best approach here? Thanks.

**Comment by wagnert** [comment]
We didn't find a real well working solution for that problem, so we started thread's where we need synchronisation with `synchronized()` without and constant. Optionally you can try to use a `Mutex` instead of the `synchronized` method, but that is not Joe would recommend.

**Comment by deeky666** [comment]
@krakjoe awesome, thanks a lot! Any chance this gets backported to `2.0`? I am not yet able to upgrade to PHP7 unfortunately :(

**Comment by krakjoe** [comment]
Since this breaks such core functionality, I have done that ...

Please upgrade, PHP 5 + pthreads v2 sucks ...

**Comment by deeky666** [comment]
@krakjoe hehe okay then I'll try to upgrade ASAP. Thanks for your effort!
