### ISSUE TITLE
windows apache 2.4 use mod_fcgi  the php pthreads not work

### ISSUE THREAD

**Issue by lljuser** [krakjoe/pthreads#547]
windows apache 2.4 use mod_fcgi  the php pthreads not work

<?php
header("Content-type:text/plain; charset=iso-8859-1\n\n");
error_reporting(E_ALL); 
class AsyncOperation extends Thread {
                public function __construct($arg) {
                $this->arg = $arg;
                }
                public function run() {
                    if ($this->arg) {
						
                       printf("Hello %s\n", $this->arg);
                    }
                }
            }
            $thread = new AsyncOperation("World");
            if ($thread->start()){$thread->join();}
			
?>

[Tue Jan 12 14:42:25.210926 2016] [core:error] [pid 8160:tid 4408] [client ::1:54994] malformed header from script '1.php': Bad header: 5356
[Tue Jan 12 14:42:47.617176 2016] [core:error] [pid 8160:tid 4400] [client ::1:54993] malformed header from script '1.php': Bad header: 8996
[Tue Jan 12 14:45:52.914051 2016] [core:error] [pid 8160:tid 4408] [client ::1:55066] malformed header from script '1.php': Bad header: Hello World
[Tue Jan 12 14:45:55.367176 2016] [core:error] [pid 8160:tid 4400] [client ::1:55065] malformed header from script '1.php': Bad header: Hello World

when I close the mod_cgi 
#LoadModule fcgid_module modules/mod_fcgid.so
use  the
LoadModule php5_module "D:/php-5.6.16/php5apache2_4.dll"
that can work

**Comment by metalwolf** [comment]
Hello @lljuser 
pthreads does NOT work on web servers --- only on CLI mode

Cheers.

**Comment by krakjoe** [comment]
I'm afraid support has been removed for executing threads inside of web server environments.

All the same, the error is probably caused because you are printing on the stdout which fcgid is using as a stream ... if you remove the ```echo```, the error will probably go away ...

This is not a bug I can do anything about, and since usage is restricted in supported versions, I'm gonna close the report ...
