### ISSUE TITLE
cannot extend from interface Collectable

### ISSUE THREAD

**Issue by PeratX** [krakjoe/pthreads#548]
PHP7 + pthreads 3.1.5

please fix !!

And worked with pthreads 3.0.7

**Comment by krakjoe** [comment]
Nothing is broken ... the documentation is out of date ...

```Collectable``` is an interface, one that is already implemented by ```Threaded```.

**Comment by PeratX** [comment]
Thanks!

**Comment by eslindsey** [comment]
If `Threaded` implements `Collectable`, then why am I getting `Call to undefined method MyWork::setGarbage()` in `run()` when MyWork extends Threaded?

**Comment by krakjoe** [comment]
Are you using v3 ?

You should not need to ```setGarbage``` in v3, this is managed by pthreads, the methods are exposed for exceptional cases. The object will only be inserted into garbage list when it has already been executed, and so cannot be collected before execution.

**Comment by eslindsey** [comment]
PHP 7.2.0-dev (cli) (built: Dec 24 2016 09:01:56) ( ZTS DEBUG )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2016 Zend Technologies

#define PHP_PTHREADS_VERSION "3.1.7dev"

I'm probably just having a hard time because the documentation is out of date, but I'd really like to get Pool and it's related classes working "the right way."

**Comment by krakjoe** [comment]
Sorry the docs are out of date ... I'm just one human, one that is spread extremely thinly over a vast amount of OSS work, not to mention work, family, dogs, and scratching my arse.

I will find some time next week to update the documentation for v3.

The ```Worker``` class has ```getStacked```, which will return the size of the execution stack (not inclusive of garbage, that's a separate stack).

You don't *need* to pass a function to ```Worker::collect``` or ```Pool::collect```, the default implementation is fine, once again, you are still able to for exceptional cases, but ordinarily not required.

It may be useful to look through tests, also, php --rc can be helpful (cli reflection).

Once again, sorry the docs are behind, I will fix it ...
