### ISSUE TITLE
how to enable pthreads see my full configuration

### ISSUE THREAD

**Issue by emiglobetrotting** [krakjoe/pthreads#552]
sudo -i;

apt-get update;

apt-get install -y \
  git \
  bison \
  autoconf \
  build-essential \
  pkg-config \
  git-core \
  libltdl-dev \
  libbz2-dev \
  libxml2-dev \
  libxslt1-dev \
  libssl-dev \
  libicu-dev \
  libpspell-dev \
  libenchant-dev \
  libmcrypt-dev \
  libpng-dev \
  libjpeg8-dev \
  libfreetype6-dev \
  libmysqlclient-dev \
  libreadline-dev \
  libcurl4-openssl-dev;

mkdir --parents /usr/local/php7;
mkdir --parents /etc/php7/conf.d;
mkdir --parents /etc/php7/cli/conf.d;
mkdir --parents /etc/php7/fpm/conf.d;

git clone https://github.com/php/php-src /usr/local/src/php7 --branch=php-7.0.0RC2 --depth=1;

cd /usr/local/src/php7/ext;

git clone https://github.com/krakjoe/pthreads -b master pthreads

cd ..

./buildconf --force;

php_configure_args=" \
  --prefix=/usr/local/php7 \
  \
  --with-bz2 \
  --with-zlib \
  --enable-zip \
  \
  --with-mcrypt \
  --with-openssl \
  \
  --with-curl \
  --enable-ftp \
  --with-mysqli \
  --enable-embedded-mysqli \
  --enable-sockets \
  --enable-pcntl \
  \
  --with-pspell \
  --with-enchant \
  --with-gettext \
  \
  --with-gd \
  --enable-exif \
  --with-jpeg-dir \
  --with-png-dir \
  --with-freetype-dir \
  \
  --with-xsl \
  --enable-bcmath \
  --enable-mbstring \
  --enable-calendar \
  \
  --enable-sysvmsg \
  --enable-sysvsem \
  --enable-sysvshm \
  \
  --enable-simplexml \
  --enable-json \
  --enable-hash \
  --enable-libxml \
  --enable-soap \
  --enable-session \
  --enable-xml \
  --enable-wddx \
  --enable-opcache \
  --with-pcre-regex \
  --enable-maintainer-zts \
  --enable-debug \
";

./configure $php_configure_args \
  --with-config-file-path=/etc/php7/cli \
  --without-pear \
  --with-config-file-scan-dir=/etc/php7/cli/conf.d;
make && make install && make clean;

./configure $php_configure_args \
  --disable-cgi --enable-fpm \
  --with-fpm-user=www-data \
  --with-fpm-group=www-data \
  --with-config-file-path=/etc/php7/fpm \
  --with-config-file-scan-dir=/etc/php7/fpm/conf.d;
make && make install && make clean;

chmod o+x /usr/local/php7/bin/php-config

chmod o+x /usr/local/php7/bin/phpize

cd /usr/local/src/php7/ext/pthreads*

/usr/local/php7/bin/phpize

./configure  --enable-pthreads=shared --prefix='/usr/local/php7' --with-libdir='/lib/x86_64-linux-gnu' --with-php-config='/usr/local/php7/bin/php-config'

make && make install

make test

cd /usr/local/src/php7/ext/intl*

/usr/local/php7/bin/phpize

./configure --enable-intl --with-icu-dir=/usr  --prefix='/usr/local/php7' --with-libdir='/lib/x86_64-linux-gnu' --with-php-config='/usr/local/php7/bin/php-config'

make && make install

make test

cp /usr/local/src/php7/php.ini-production /etc/php7/cli/php.ini

ln --symbolic /usr/local/php7/bin/php /usr/bin/php;

ln --symbolic /usr/local/php7/sbin/php-fpm /usr/sbin/php7-fpm;

echo 'zend_extension=opcache.so' > /etc/php7/conf.d/opcache.ini;

echo "extension=pthreads.so" >> /etc/php7/conf.d/pthreads.ini

echo "extension=intl.so" >> /etc/php7/conf.d/intl.ini;

echo 'date.timezone ="Africa/Lagos"' >> /etc/php7/cli/php.ini

ln --symbolic /etc/php7/conf.d/opcache.ini /etc/php7/cli/conf.d/opcache.ini;

ln --symbolic /etc/php7/conf.d/opcache.ini /etc/php7/fpm/conf.d/opcache.ini;

ln --symbolic /etc/php7/conf.d/intl.ini /etc/php7/cli/conf.d/intl.ini;

ln --symbolic /etc/php7/conf.d/intl.ini /etc/php7/fpm/conf.d/intl.ini;

ln --symbolic /etc/php7/conf.d/pthreads.ini /etc/php7/cli/conf.d/pthreads.ini;

ln --symbolic /etc/php7/conf.d/pthreads.ini /etc/php7/fpm/conf.d/pthreads.ini;

FPM

wget -O /etc/init.d/php7-fpm "https://gist.github.com/bjornjohansen/bd1f0a39fd41c7dfeb3a/raw/f0312ec54d1be4a8f6f3e708e46ee34d44ef4657/etc%20inid.d%20php7-fpm"

chmod a+x /etc/init.d/php7-fpm

nano /etc/init.d/php7-fpm

change /usr/local/php7/etc/php-fpm.conf to /etc/php7/fpm/php-fpm.conf

change /usr/local/php7/sbin:/sbin:/usr/sbin:/bin:/usr/bin to /usr/sbin

change NAME=php-fpm to NAME=php7-fpm

wget -O /etc/init/php7-fpm.conf "https://gist.github.com/bjornjohansen/9555c056a7e8d1b1947d/raw/15920fa2f447358fdd1c79eecd75a53aaaec76f9/etc%20init%20php7-fpm"

nano /etc/init/php7-fpm.conf

change /usr/local/php7/sbin/php-fpm --nodaemonize --fpm-config /usr/local/php7/etc/php-fpm.conf to /usr/sbin/php7-fpm --nodaemonize --fpm-config /etc/php7/fpm/php-fpm.conf

nano /usr/local/lib/php7-fpm-checkconf

Copy paste and save

#!/bin/sh
set -e
errors=$(/usr/sbin/php7-fpm --fpm-config /etc/php7/fpm/php-fpm.conf -t 2>&1 | grep "\[ERROR\]" || $
if [ -n "$errors" ]; then
    echo "Please fix your configuration file..."
    echo $errors
    exit 1
fi
exit 0

chmod a+x /usr/local/lib/php7-fpm-checkconf

cp /usr/local/php7/etc/php-fpm.conf.default /etc/php7/fpm/php-fpm.conf

nano /etc/php7/fpm/php-fpm.conf

Uncomment/Change
============================
pid = /var/run/php7-fpm.pid
error_log = /var/log/php-fpm.log
include=/etc/php7/fpm/php-fpm.d/*.conf

cd /etc/php7/fpm

mkdir php-fpm.d

cp /usr/local/php7/etc/php-fpm.d/www.conf.default /etc/php7/fpm/php-fpm.d/www.conf

nano /etc/php7/fpm/php-fpm.d/www.conf

Change
============================
user = www-data
group = www-data
listen = /var/run/php7-fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660
request_terminate_timeout = 1400

Uncomment
============================
listen.allowed_clients = 127.0.0.1
security.limit_extensions = .php .php3 .php4 .php5 .php7

update-rc.d -f php7-fpm defaults

service php7-fpm start

**Comment by emiglobetrotting** [comment]
php7-fpm -t
yields this error message  The fpm-fcgi SAPI is not supported by pthreads in Unknown on line 0
Unknown(0) : Fatal error - The fpm-fcgi SAPI is not supported by pthreads
[20-Jan-2016 14:07:59] NOTICE: PHP message: PHP Fatal error:  Unable to start pthreads module in Unknown on line 0
Unknown(0) : Fatal error - Unable to start pthreads module

**Comment by JesusTheHun** [comment]
pthreads v3 only support CLI SAPI.

**Comment by emiglobetrotting** [comment]
which means i don't need to compile php with the following options --enable-fpm \
--with-fpm-user=www-data \
--with-fpm-group=www-data

**Comment by JesusTheHun** [comment]
Depends on your need. If your install has the only purpose to use pthreads in CLI, then no you do not.

**Comment by krakjoe** [comment]
This isn't really a bug, and it seems like the question has been answered ...

Closing the bug, but not ending the conversation, I'm sure if you ask more questions answers will come ;)

**Comment by emiglobetrotting** [comment]
HI Joe, please may you assist me with a php7 installation that provides support for this great software (pthreads). i really need to deploy my open source project that depends so much on pthreads.

**Comment by JesusTheHun** [comment]
Post your questions on stackoverflow with tags php and pthreads, I'll answer it. I can give you complete install instructions on Ubuntu. I wrote my company's setup process for co-install 5.6 and 7.0-zts with pthreads.

**Comment by emiglobetrotting** [comment]
Hi Jesus, thanks for willing to help. I wish to inform you that I've asked the question on stackoverflow titled "how to install php7 (zts) + pthreads on Ubuntu 14.04"

**Comment by JesusTheHun** [comment]
I've answered your message. We'll continue discussion on SO by now.
