### ISSUE TITLE
Increasing memory infinitely when using Threaded

### ISSUE THREAD

**Issue by ZhyMC** [krakjoe/pthreads#553]
My project create a class called AsyncPool,and it can create 'threaded' easily,and when the 'onRun' finished,the AsyncPool will call onCompletion make the 'threaded' pass the vars to main thread.
then it will destroy the 'threaded' by unsetting the 'threaded's array and cleanObject()
but the vars of threaded classes will not be unset.
i found that the problem causes in the newest pthreads of PHP7 version which cannot rewrite var before the threaded created

**Comment by ZhyMC** [comment]
You canread the codes of AsyncPool.php at a github project named 'iTXTech/Genisys'.
The file is at /src/pocketmine/scheduler/AsyncPool.php

**Comment by ZhyMC** [comment]
only array causes this problem and i can't clean the array vars.

**Comment by JesusTheHun** [comment]
Can you provide a minimal & clear sample of code to reproduce the issue ?

**Comment by ZhyMC** [comment]
@JesusTheHun sure
abstract class AsyncTask extends \Threaded implements \Collectable{
public function onCompletion(Server $server){

	}

	public function cleanObject(){
		foreach($this as $p => $v){
			if(!($v instanceof \Threaded)){ //But array var is instanceof \Threaded and it will not be cleared forever
				$this->{$p} = null;
                                unset($this->{$p});
			}
		}
	}
}

class AsyncPool{
	public function collectTasks(){

		foreach($this->tasks as $task){
			if($task->isFinished() and !$task->isRunning() and !$task->isCrashed()){
				if(!$task->hasCancelledRun()){
					$task->onCompletion($this->server);
				}

				$this->removeTask($task);
			}elseif($task->isTerminated() or $task->isCrashed()){
				$this->removeTask($task, true);
			}
		}

	
	}
}
	private function removeTask(AsyncTask $task, $force = false){
		$task->setGarbage();
		if(isset($this->taskWorkers[$task->getTaskId()])){
			if(!$force and ($task->isRunning() or !$task->isGarbage())){
				return;
			}
			$this->workerUsage[$this->taskWorkers[$task->getTaskId()]]--;
		}

		unset($this->tasks[$task->getTaskId()]);
		unset($this->taskWorkers[$task->getTaskId()]);

		$task->cleanObject();
	}

But array var is instanceof \Threaded and it will not be cleared forever

**Comment by JesusTheHun** [comment]
Class Server doesn't exist. Can you try the code sample you post before posting please ?

**Comment by ZhyMC** [comment]
@JesusTheHun oh it's a part codes of my project,just want to be understood

**Comment by JesusTheHun** [comment]
Well, we won't learn your project to help you. So give a standalone sample please.

**Comment by ZhyMC** [comment]
@JesusTheHun ok,tomorrow i upload a standalone version

**Comment by ZhyMC** [comment]
@krakjoe

**Comment by krakjoe** [comment]
@ZhyMC I too am waiting for minimal example code that exhibits the bug ... you need to take the problem out of your application, and reproduce it in the simplest way possible ...

**Comment by PeratX** [comment]
@krakjoe I will help him to create an example,please wait.

**Comment by PeratX** [comment]
@krakjoe 

<?php

class ExampleTask extends Threaded implements Collectable{
	private $f = [];
	private $isGarbage = false;
	private $isFinished = false;
	
	public function isGarbage() : bool{
		return $this->isGarbage;
	}

	public function setGarbage(){
		$this->isGarbage = true;
	}
	
	public function run(){
		for($i = 0; $i < 10000; $i++){
			$this->f[$i] = zlib_encode(str_repeat("amazing pthreads",1000), ZLIB_ENCODING_DEFLATE,9);
		}
		$this->isFinished = true;
	}
	
	public function collectObject(){
		//$this->f = null;
		//cannot set an array to null
		echo("Example Task #" . spl_object_hash($this) . " has been collected.") . PHP_EOL;
	}
}

class ExampleWorker extends Worker{
	public function run(){
		gc_enable();
		ini_set("memory_limit", -1);
	}
}

echo "pthreads example...".PHP_EOL;
ini_set("memory_limit", -1);
$tasks = [];
$worker = new ExampleWorker();
$worker->start();
while(true){
	$worker->stack($tasks[] = new ExampleTask());
	echo("RAM: " . round((memory_get_usage(true) / 1024) / 1024 , 2) . "MB" . PHP_EOL);
	sleep(0.1); //Just like PocketMine
	/*foreach($tasks as $i => $task){
		if($task->isFinished) {
			$task->setGarbage();
			$task->collectObject();
			unset($tasks[$i]);
		}
	}*/
}

Memory will increase every second

**Comment by ZhyMC** [comment]
lovely peratx

**Comment by PeratX** [comment]
=)

**Comment by krakjoe** [comment]
> Memory will increase every second

Of course it will, ```$tasks``` requires an infinite amount of memory ...

**Comment by PeratX** [comment]
@krakjoe But why I cannot set it to null in colleectObject object???

**Comment by ZhyMC** [comment]
array cannot be set to null but string can. seems like above of them will not be released

**Comment by PeratX** [comment]
And if garbage collection works properly, ram will decrease every two or three seconds...

**Comment by krakjoe** [comment]
> And why pthreads did not collect garbage tasks?

You never called the collector ...

**Comment by PeratX** [comment]
@krakjoe Excuse me. How to call the collector?

**Comment by krakjoe** [comment]
```Worker::collect```

**Comment by PeratX** [comment]
What...

**Comment by ZhyMC** [comment]
EMPTY

**Comment by PeratX** [comment]
=_=

**Comment by ZhyMC** [comment]
Wow,@PeratX

**Comment by PeratX** [comment]
@krakjoe 
<?php

class ExampleTask extends Threaded implements Collectable{
	private $f = [];
	private $isGarbage = false;
	private $isFinished = false;
	
	public function isGarbage() : bool{
		return $this->isGarbage;
	}

	public function setGarbage(){
		$this->isGarbage = true;
	}
	
	public function run(){
		for($i = 0; $i < 10000; $i++){
			$this->f[$i] = zlib_encode(str_repeat("amazing pthreads",1000), ZLIB_ENCODING_DEFLATE,9);
		}
		$this->isFinished = true;
		$this->setGarbage();
	}
	
	public function collectObject(){
		$this->f = null;
		//cannot set an array to null
		echo("Example Task #" . spl_object_hash($this) . " has been collected.") . PHP_EOL;
	}
}

class ExampleWorker extends Worker{
	public function run(){
		gc_enable();
		ini_set("memory_limit", -1);
	}
}

echo "pthreads example...".PHP_EOL;
ini_set("memory_limit", -1);
$tasks = [];
$worker = new ExampleWorker();
$worker->start();
while(true){
	$worker->stack($tasks[] = new ExampleTask());
	echo("RAM: " . round((memory_get_usage() / 1024) / 1024 , 2) . "MB" . PHP_EOL);
			$worker->collect(function($work){
				return $work->isGarbage();
			});
	sleep(0.1); //Just like PocketMine
}

I changed my code like this,memory increased slower. but still increasing...

**Comment by PeratX** [comment]
@krakjoe And thanks you help us a lot. : )

**Comment by krakjoe** [comment]
Here's a cleaned up version of your code, that works:

	<?php
	class ExampleTask extends Threaded {
		private $t = [];

		public function run(){
		    for($i = 0; $i < 10000; $i++){
			    $this->t[$i] = zlib_encode(
					str_repeat("amazing pthreads",1000), ZLIB_ENCODING_DEFLATE,9);
			}
		}
	}

	class ExampleWorker extends Worker {
		public function run(){
		    gc_enable();
		    ini_set("memory_limit", -1);
		}
	}

	echo "pthreads example...".PHP_EOL;

	ini_set("memory_limit", -1);

	$worker = new ExampleWorker();
	$worker->start();

	while(true){
		$i = 0;
	
		$worker->stack(new ExampleTask());

		echo("RAM: " . round((memory_get_usage(true) / 1024) / 1024 , 2) . "MB" . PHP_EOL);

		while ($worker->collect()) {
			/* this will give you some idea of how long you are spending in collection (it's a long time) */
			if ($i++ % 10000 == 0)
				echo ".";

			continue;
		}

		echo PHP_EOL;
	}

You can see that it spends a considerable time in the collect loop, which may not always be desirable, but to ensure you are freeing everything consumed, is what you must do ...

The idea is that you enter into such a loop with a frequency modified for you application, hitting the GC upon every insertion into the stack is a bad idea ...

By default, ```Worker::collect``` doesn't need a ```callable``` any more, it will use ```Worker::collector``` which you can either implement, or rely on the default version of which is the same as ```return $task->isGarbage();```.

You don't actually need to implement ```Collectable``` for your ```Threaded``` objects, it's done by pthreads already.

```Worker::collect``` returns the number of items in the garbage queue, waiting to be destroyed, however it will break out of collection if the thread which owns the stack you are trying to collect from is busy, this is for reasons of stability and predictability. Busyness is determined by a few different criteria. This makes the algorithm non-deterministic, because it may behave differently from run to run. It also means that a single call to ```Worker::collect``` will return if it would otherwise induce lock contention, possibly race conditions, and undesirable performance characteristics due to the objects it is manipulating being referenced and manipulated concurrently in other contexts.

```Pool::collect``` returns the total number of items in the garbage queue of all ```Worker``` objects the ```Pool``` is managing.

**Comment by ZhyMC** [comment]
@krakjoe oh thanks u and your team so much!!! :)

**Comment by krakjoe** [comment]
https://twitter.com/krakjoe/status/696594364890529792 :+1:

**Comment by PeratX** [comment]
@krakjoe So I can use Worker::collector(Collectable $task) to collect a specified task?

**Comment by dktapps** [comment]
This was not a pthreads issue. The issue has been resolved.

**Comment by thebigsmileXD** [comment]
while(true){
    $worker->stack($tasks[] = new ExampleTask());
