### ISSUE TITLE
Error when adding extension=pthreadVC2.dll to php 5.3.8 VC9

### ISSUE THREAD

**Issue by pthreadVC2** [krakjoe/pthreads#554]
I'm using apach2.2.21 and php5.3.8 VC9, (x86).
everything is ok, exept when i use this line : extension=pthreadVC2.dll
i try to restart my server, but it's broken it won't start.
and when i take it off, my php.ini be like :
;extension=pthreadVC2.dll
extension=php_pthreads.dll
, it works fine.

if i use php -m, it gives me pthreads as loaded module.

please any suggestions.

**Comment by krakjoe** [comment]
The extension is ```php_pthreads.dll```, it has a dependency on the normal link library ```pthreadsVC2.dll```.

In an apache setup, you need to ```LoadFile``` ```pthreadsVC2.dll```, the ```extension``` line in ```php.ini``` remains the same.

**Comment by pthreadVC2** [comment]
The link for Files : http://windows.php.net/downloads/pecl/releases/pthreads/2.0.9/
so took the php5.3 x86.
In this folder i don't have pthreadsVC2.dll ,i've this DLL pthreadVC2.dll, i
loaded 'pthreadVC2.dll' in the php/ and apache/bin, for php_pthreads.dll in php/ext.
Once i add : extension=pthreadVC2.dll, the server won't start.
