### ISSUE TITLE
Autoload not copied to new context

### ISSUE THREAD

**Issue by JesusTheHun** [krakjoe/pthreads#556]
Hello,

It started with this question on SO : http://stackoverflow.com/questions/34975566/php-pthreads-and-monolog

To reproduce, create an empty project, then composer require monolog/monolog (stable, 1.17).

Then in a simple script require the vendor/autoload.php and this code :

```
<?php

require 'vendor/autoload.php';

use Monolog\Handler\StreamHandler;
use Monolog\Logger;

$log = new Logger('MyApp');
$log->pushHandler(
    new StreamHandler('php://stdout', Logger::INFO)
);
$log->addInfo("before");

class MyThread extends Thread
{
    public function run()
    {

        echo 'hihi', PHP_EOL;
        $log = new Logger('MyApp');
        $log->pushHandler(
            new StreamHandler('php://stdout', Logger::INFO)
        );
        $log->addInfo("inside");
        echo 'haha', PHP_EOL;
    }
}

$thread = new MyThread();

if ($thread->start()) {
    $thread->join();
    echo 'done', PHP_EOL;
}
```

As you will see, you will be able to use Monolog/Logger.php before (outside) the Thread, but not inside. And a weird part is, the fatal you'll get (class not found) will depends on where you put the log block.

**Comment by krakjoe** [comment]
This is a known limitation ... the autoloader in PHP is actually part of SPL (not, strictly speaking, Zend): It doesn't have an internal API that I can use to set it up correctly, so it's down to the programmer to set it up themselves.

[This](https://github.com/krakjoe/pthreads-autoloading-composer) might be useful to some extent.
