### ISSUE TITLE
Pthread installation, unable to initialize module

### ISSUE THREAD

**Issue by jlcbada** [krakjoe/pthreads#561]
![pthread issue](https://cloud.githubusercontent.com/assets/7043021/12843631/8df4e78e-cc35-11e5-83da-d601b77b8b8b.PNG)
Image to text:
Warning: Php Startup: pthreads: Unable to initialize module
Module&ensp;compiled with module API=20131226
PHP&ensp; compiled with module API=20121212

Pthread version/dl title: php_pthreads-2.0.7-5.6-ts-vc11-x86

PHP version is:  php-5.5.9-Win32-VC11-x86

note: i think i followed the installation procedures correctly.
i think the problem is with PHP Extension Build.
i have it as: API20121212,TS,VC11
my pthread is VC11 and TS as well.. but i dont know know how to check that API thing.
and what does it meant.

anyone?

**Comment by krakjoe** [comment]
The extension has 5.6 version and you are running 5.5.

**Comment by jlcbada** [comment]
just visited the http://windows.php.net/downloads/pecl/releases/pthreads/2.0.7/
where i downloaded it., and saw that there are two different x86
well i ignored it the first time.. but by looking on it the one is 5.6 and the other is 5.5

im so stupid ive never thought what those numbers about at first.
and thanks for pointing that out to me.
