### ISSUE TITLE
pthreads cause error when integrated with simple html dom parser

### ISSUE THREAD

**Issue by jlcbada** [krakjoe/pthreads#563]
here is what im doing
im using 
- pthreads from here
- php Simple Html DOM parser from - simplehtmldom.sourceforge.net

now the process of what i (will) do is:
1. I am reading a bulk of links that is from a text file.
2. I initialize a thread to have a separate process
3. I am creating a log file for this thread so that i will know, what happens later on.

now, this is my code for my thread class.

```
class ReadLinks extends Thread {

private $conn;
private $links;
private $fileObj;

public function __construct($conn, $links, $fileObj) {
    //.. well just asign this to the global variables
}

public function run() {
    try {
        $this->logMsg("Start Reading Reviews");
        $this->readLinks();
    } catch (Exception $ex) {
        $this->logMsg($ex);
    }
    $this->closeLog();
}

private function readLinks() {
    $this->logMsg("Links");
    foreach ($this->links as $link) {
        $link = trim(preg_replace('/\s\s+/', ' ', $link));
        $this->logMsg("Link: " . $link);
        $html = html_readLink($link);
       break;
    }
}

private function logMsg($msg) {//something to write on the text file
}

private function closeLog() {//closes the textfile
}}
```

$conn - is my mysqli link to have db actions in the future

$links - is an array of links to be read.

$fileObj- is a resource return from fopen(). ( well to write into a file)

now who is that html_readlink,
its an outer function that is like this:

```
function html_readLink($link) {
    return file_get_html($link);}
```

basically it is the resource returned by a function from simple html dom parser

now, i have as well a function that reads a link alone to do the other (different business requirement) and im using the simple html dom parser with ease.

with the pthreads, i tried writing the file(logs first) so that i can ensure that everything as well works fine.
about contacting db is not yet sure., well ill try to figure it out if it works fine, but logically it should work.

now when i called this class: its like this:

```
try {
    $thread = new readLinks($conn, $Links, createlog());
    if ($thread->start()) {
        $thread->join();
    } else {
        echo "something i need to research if this happens";
    }
} catch (Exception $err) {
    echo $err; //something i need to research as well if this happens
}
```

i got this error

```
Warning: Invalid argument supplied for foreach() in C:\my\path\to\simplehtmldom_1_5\simple_html_dom.php on line 1119
```

that simplehtmldom code is:

```
function clear()
{
    foreach ($this->nodes as $n) {$n->clear(); $n = null;}
    // This add next line is documented in the sourceforge repository. 2977248 as a fix for ongoing memory leaks that occur even with the use of clear.
    if (isset($this->children)) foreach ($this->children as $n) {$n->clear(); $n = null;}
    if (isset($this->parent)) {$this->parent->clear(); unset($this->parent);}
    if (isset($this->root)) {$this->root->clear(); unset($this->root);}
    unset($this->doc);
    unset($this->noise);
}
```

now that is the source code coming from simple html dom. that foreach is the one that is returning the error. now my other code using simple html dom doesn't have a problem with simple html dom. but with pthreads i got this error.

also, when i change my codes and didn't use pthreads, (had some revisions like this:
on pthreads class:

```
class ReadLinks {// extends Thread {
//insert other codes
public function readLinks() {
        $this->logMsg("Links");
        foreach ($this->links as $link) {
            $link = trim(preg_replace('/\s\s+/', ' ', $link));
            $this->logMsg("Link: " . $link);
            $html = html_readLink($link);
            $this->logMsg(getTitle($html));
//           
            break;
        }
    }
```

and change the way this is called like this:

```
try {
        $thread = new ReadLinks($conn, $revLinks, createlog());
        $thread->readLinks();
//        if ($thread->start()) {
//            $thread->join();
//        } else {
//            echo "something i need to research if this happens";
//        }
    } catch (Exception $err) {
        echo $err; //something i need to debug and research if this happens
    }
```

everything works fine, i get the desired results.

pthreads is something i need to use since loading bulk links and reading each of them is quite a time consuming process. and i need it to be on a separate thread. now i dont know whats wrong i have done with implementing pthreads.

is there any other way?

anyone??

**Comment by krakjoe** [comment]
Please provide executable code that exhibits the behaviour you think is a bug.

**Comment by brunoboss** [comment]
1) Put your require in the run function
2) when call start, pass PTHREAD_INHERIT_NONE

this should call a separate and clan context for the thread to work, and by putting requires in run ensure that you have all the needs loaded.

I don't know if it's the right way, but for sure it's a workaround

    `
       class YourJob extends Thread{
                public function run(){
                     //put here your require
                    //for composer
                    require 'vendor/autoload.php'
                }
          }

       $myJob = new MyJob( Here pass your data if you need );
       $myJob->start(PTHREAD_INHERIT_NONE);
       ....
       $myJob->join 


`

**Comment by tpunt** [comment]
Closing due to a lack of feedback.

For what it's worth, I had a quick look through the Simple HTML DOM library. The error occurs when `$this->nodes` is `null`, which can happen randomly, according to the comment in the library:
> // In rare cases, (always node type 1 or HDOM_TYPE_ELEMENT - observed for some span tags, and some p tags) $this->nodes is set to NULL.
// NOTE: This indicates that there is a problem where it's set to NULL without a clear happening.
// WHY is this happening?

So simply guarding the `foreach` against trying to iterate `null` should work.
