### ISSUE TITLE
Nullified local static array caused by the combination of namespace, static and const

### ISSUE THREAD

**Issue by SirSnyder** [krakjoe/pthreads#564]
Hello @krakjoe,

I don't wanna mess up #536. Let's start a fresh issue. After two months, I've tracked down the initial error of #536:

```
<?php

    namespace any\name\space
    {
        class Test extends \Thread
        {
            const KEY = '';

            public function run()
            {
                static $arrConst = [self::KEY => true];

                var_dump($arrConst);
            }
        }
    }

    namespace
    {
        use any\name\space\Test;

        $objTest = new Test();
        $objTest->start();
        $objTest->join();
    }
```

Result
null

Expected
array(1) {
  [""]=>
  bool(true)
}

Windows 7 x64, php 7.0.3, pthreads 3.1.6

Regards

**Comment by krakjoe** [comment]
I am able to reproduce, but only without opcache loaded, can you confirm you have the same symptoms ?

**Comment by SirSnyder** [comment]
Yes, I can confirm that, strange. I'm developing without opcache by default.

**Comment by SirSnyder** [comment]
Without opcache loaded line https://github.com/krakjoe/pthreads/blob/master/src/copy.h#L40 is true and https://github.com/krakjoe/pthreads/blob/master/src/copy.h#L43 is IS_CONSTANT_AST and not IS_ARRAY.

In this sample
```
namespace any\name\space
    {
        class Example extends \Threaded
        {
            const KEY = '';

            public function somecode()
            {
                static $arrConst = [self::KEY => true];

                var_dump($arrConst);
            }
        }

        class Test extends \Thread
        {
            public function run()
            {
                $example = new Example();
                $example->somecode();
            }
        }
    }

    namespace
    {
        use any\name\space\Test;
        use any\name\space\Example;

        $example = new Example();
        $example->somecode();

        $objTest = new Test();
        $objTest->start();
        $objTest->join();
    }
```
https://github.com/krakjoe/pthreads/blob/master/src/copy.h#L43 is always IS_ARRAY.

**Comment by krakjoe** [comment]
Yeah that's probably it, ```IS_CONSTANT_AST``` is missing from the switch ...

I'll have time to debug it before the weekend, I hope ... sorry about the wait, super busy ;)

**Comment by SirSnyder** [comment]
Chasing the Dragon? ;-) No problem, I try to support you wherever possible. Thanks!

**Comment by JesusTheHun** [comment]
Cannot reproduce on Linux, PHP 7.0.2 , ptreads 3.1.6, opcache disabled.
Can you confirm this bug is Windows specific ?

**Comment by SirSnyder** [comment]
I am able to reproduce on Debian, php 7.0.0, pthreads 3.1.6dev, opcache disabled. I had to disable both, opcache.enable and opcache.enable_cli. With disabled opcache.enable_cli only, it looks like the opcache kicked in. Will upgrade to latest php and pthreads version. I'll talk to you later.

**Comment by JesusTheHun** [comment]
I tried with these scenarios :
- Opcache extension not loaded at all (ini .ini file)
- Opcache loaded but not enable in cli
- Opcache loaded but not enable at all ( both value at 0 )

Can't reproduce :/

**Comment by wwachsmann** [comment]
I am able to reproduce it on OSX, latest PHP 7.0.3 and latest pthreads 3.1.6, disabling or enabling opcache will not differ from the result.
