### ISSUE TITLE
problem in installation 'no rule to make target'

### ISSUE THREAD

**Issue by sredXNY** [krakjoe/pthreads#566]
Hi, I'm trying to install pthreads in a Ubuntu 14.04 server, the steps that I followed are the next:

```
1. wget http://www.php.net/distributions/php-5.6.17.tar.gz
2. wget http://pecl.php.net/get/pthreads-2.0.10.tgz
3. tar zxvf pthreads-2.0.10.tgz
4. tar zxv php-5.6.17.tar.gz
5. mv pthreads-2.0.10 php-5.6.17/ext
6. cd php-5.6.17
7. ./buildconf --force
8. ./configure --help | grep pthreads    //to check id --enable-pthread is listed
9. ./configure --enable-debug --enable-maintainer-zts --enable-pthreads=static --prefix=/usr --with-config-file-path=/etc --with-apxs2 //I included --with-apxs2 to load the module in apache
10. make
```

Then, when I ran `make` I get this error:
`make: *** No rule to make target `/usr/local/php-5.6.17/ext/pthreads/php_pthreads.c', needed by `ext/pthreads/php_pthreads.lo'.  Stop.
`

So, what is wrong? what cause this error? I even tried with PHP 5.4.45 and the same error is displayed. Thank you very much

**Comment by krakjoe** [comment]
This is not a bug in pthreads. Sorry, but I don't have time to answer general questions about building PHP here ...
