### ISSUE TITLE
Assertation failed

### ISSUE THREAD

**Issue by Luigigithub** [krakjoe/pthreads#569]
Not enought storage is available to process this command ..\..\...\src\thread.cpp:51 version 2.0.8 and 2.0.9 php 5.6 thread safety.

class StackableArray extends Stackable {
    /*
     * Always think about caching these types of objects, don't waste the run method or your workers
     */

    public function run() {
        
    }

}

/* a thread for editing */

class T extends Thread {

    public function __construct($test, $notificaciones, $thread) {
        $this->test = $test;
        $this->notificaciones = $notificaciones;
        $this->thread = $thread;
        $this->start();
    }

    public function run() {

        $this->synchronized(function($self) {
            printf("%s(%lu) going to wait ...\n", __CLASS__, $self->getThreadId());
            $self->wait();
            foreach ($self->notificaciones as $notificacion) {
                $destinatarios = json_decode($notificacion["Destinatarios"], true);

                $notificacion["idEncriptado"] = fwEncriptar::doEncrypt($notificacion["idEncriptado"]);
                $notificacion["carpetaPadreId"] = fwEncriptar::doEncrypt($notificacion["carpetaPadreId"]);

                if (count($destinatarios["Usuarios"]) == 0) {
                    goto update;
                }

                $entryData = ["function" => "ordenSinc", "destinarios" => $destinatarios["Usuarios"], "datos" => $notificacion];
                EnviarParaCola($entryData);

                update:
                $self->test[] = $notificacion["Id"];
            }
            $self->done = true;
        }, $this);

        /*
         * NOTE
         * 	If your editing of an array is this simple
         * 		then don't protect these instructions
         * 		you will incurr additional unecessary locking
         */
    }

}

include_once("princ/fw.php");

while(true){
    $i=0;
$a=fwEncriptar::doEncrypt("123");
$bd=new SQLServer();

   $sql = "select top 10 na.*,arch.FechaModificacion as FechaModificacionArchivo,arch.Md5File as Md5Archivo, arch.Nombre as NombreArchivo, car.FechaModificacion as FechaModificacionCarpeta, car.Nombre as NombreCarpeta,car2.Nombre as NombreCarpetaPadre "
                . " from NotificacionArchivo na "
                . " left outer join Archivo arch on arch.Id=na.idEncriptado "
                . " left outer join Carpeta car on car.Id=na.idEncriptado "
                . " left outer join Carpeta car2 on car2.Id=na.carpetaPadreId "
                . " where NotificacionTiempoReal=0 order by Id asc";
        $notificaciones = $bd->q2a($sql, null, []);

        
        
        
        $s = new StackableArray();
        $ts = array();
        $divido = array_chunk($notificaciones, 20);
        while (@$i++ < count($divido)) {
            $ts[] = new T($s, $divido[$i - 1], $i);
        }
      
        foreach ($ts as $t) {
            $t->synchronized(function($self) {

                if (!$self->done) {
                    $self->notify();
                } else
                    printf("Process: error\n");
            }, $t);

            $t->join();
        }
        
        unset($ts);
      
       $s=(array)$s;
        if(count($s)>0){
        $sql = "UPDATE NotificacionArchivo set NotificacionTiempoReal=1 where Id in (".implode(",",$s).")";  
        echo $sql."\n";
        $bd->q2e($sql);
        }
 
        usleep(500);
}

**Comment by krakjoe** [comment]
Reduce the problem to it's simplest form.
