### ISSUE TITLE
Segfault on accessing destroyed closure in threaded object

### ISSUE THREAD

**Issue by Xerkus** [krakjoe/pthreads#571]
pthreads version 3.1.6

While poking at pthreads I noticed that closure assigned to threaded object in child thread causes segfault when accessed from parent thread but already destroyed.

If I replace it with threaded object I get nice runtime exception instead. It would be nice if it was the same for closure if at all possible.

**Comment by Xerkus** [comment]
Code sample triggering segfault:

```php
<?php

class Test extends Thread
{
    private $closure;

    public function run()
    {
        $this->closure = function() {
            echo 'closure!';
        };
    }

    public function getClosure()
    {
        return $this->closure;
    }
}

$thread = new Test();
$thread->start();
$thread->join();
$thread->getClosure(); //segfault
```

**Comment by krakjoe** [comment]
As explained, this is expected.
