### ISSUE TITLE
Random Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by mayeco** [krakjoe/pthreads#576]
We have a random segmentation fault using PHP 7.0.4 with pthreads.

We run the app with this:
https://github.com/symfony-chile/symfony-pthreads/blob/master/sf-app/pthreads.php

This is our Worker:
https://github.com/symfony-chile/symfony-pthreads/blob/master/sf-app/src/sfWorker.php

And this is the Job:
https://github.com/symfony-chile/symfony-pthreads/blob/master/sf-app/src/sfJob.php

We random get a Segmentation fault (core dumped).

![coredump](https://raw.githubusercontent.com/symfony-chile/Symfony-pThreads/master/coredump.jpg)

![coredump](https://raw.githubusercontent.com/symfony-chile/Symfony-pThreads/master/coredump2.jpg)

Can you please give me a clue about this @krakjoe

**Comment by krakjoe** [comment]
As far as I can tell, this was fixed when we required 7.2 ... if I'm wrong, please re-open the issue.
