### ISSUE TITLE
Threaded object is destroyed with child thread even if assigned to Threaded from parent thread

### ISSUE THREAD

**Issue by Xerkus** [krakjoe/pthreads#577]
pthreads 3.1.6

If child thread creates `Threaded` object and parent tries to access it after child process was terminated, destroyed object exception will be thrown.
But, if parent accesses said `Threaded` object at least once before child is terminated, it will not be destroyed. 

```php
<?php

class ChildThreaded extends Threaded
{
    public function itsAme()
    {
        echo "Mario!\n";
    }
}

class Test extends Thread
{
    private $threaded;

    public function run()
    {
        $this->threaded = new ChildThreaded;
        sleep(1);
    }

    public function getThreaded()
    {
        return $this->synchronized(function() {
            while (!$this->threaded)
                $this->wait();
            return $this->threaded;
        });
    }
}


echo "Case 1:\n";
$thread = new Test();
$thread->start();

$thread->getThreaded()->itsAme();
$thread->join();
$threaded = $thread->getThreaded();
unset($thread);
$threaded->itsAme();

echo "Case 2:\n";
$thread = new Test();
$thread->start();
$thread->join();
try {
    $thread->getThreaded();
} catch (\RuntimeException $e) {
    echo "Uh oh: " . $e->getMessage() . "\n";
} 
```

> $ zts-php -f issue.php 
> Case 1:
> Mario!
> Mario!
> Case 2:
> Uh oh: pthreads detected an attempt to connect to an object which has already been destroyed

I'm not sure if this can be considered a bug.

But since `Threaded` can survive child termination in case 1, i want to make an improvement request:
If threaded is assigned to another `Threaded` from another thread, do not destroy it.

**Comment by krakjoe** [comment]
This is not possible.

The object created in the thread exists only on the heap of that thread, you manipulate it via a shadow copy in other threads. When the context is destroyed, the object must be destroyed.

**Comment by Xerkus** [comment]
But it is not, as you can see in case 1

**Comment by krakjoe** [comment]
The first call to the method on the threaded object happens to occur while the thread still exists, because you forced it to sleep.

If you try to reference the object after you know it has been destroyed, you will get an exception.

	<?php

	class ChildThreaded extends Threaded
	{
		public $thing = "Mario";

		public function itsAme()
		{
		   	return "{$this->thing}!\n";
		}
	}

	class Test extends Thread
	{
		private $threaded;

		public function run()
		{
		    $this->threaded = new ChildThreaded;
		}

		public function getThreaded()
		{
		    return $this->synchronized(function() {
		        while (!$this->threaded)
		            $this->wait();
		        return $this->threaded;
		    });
		}
	}

	echo "Case 1:\n";

	$thread = new Test();
	$thread->start();
	$thread->join();

	$threaded = $thread->getThreaded();

	echo $threaded->itsAme();

**Comment by Xerkus** [comment]
I understand.

But if i reference it before $thread->join(), i no longer get exception afterwards.That looks like a bug from user viewpoint.

```
<?php

class ChildThreaded extends Threaded
{
    public $thing = "Mario";

    public function itsAme()
    {
        return "{$this->thing}!\n";
    }
}

class Test extends Thread
{
    private $threaded;

    public function run()
    {
        $this->threaded = new ChildThreaded;
        sleep(1);
    }

    public function getThreaded()
    {
        return $this->synchronized(function() {
            while (!$this->threaded)
                $this->wait();
            return $this->threaded;
        });
    }
}

$thread = new Test();
$thread->start();
echo $thread->getThreaded()->itsAme();
$thread->join();
echo $thread->getThreaded()->itsAme();
```

> 
> $ zts-php -f issue.php 
> Mario!
> !

**Comment by Xerkus** [comment]
As an unrelated question: can it be possible to create `Threaded` object in another context? And expose that to us as something like `Threaded::createInContext($otherThreadThreaded, ...);`
Pretty sure answer to that is no, but if there is a possibility to explore,  i can open another issue for that.

**Comment by krakjoe** [comment]
Caching functions is not a feature of pthreads, it's a feature of Zend, that we do not want to disable ... I agree, it's a little surprising ... 

> As an unrelated question: can it be possible to create ...

I'm afraid not ... PHP is shared nothing; no context can manipulate the heap of another context directly, that's why we have to use shadow objects.

**Comment by Xerkus** [comment]
Well, at least i know now that php is indeed thread **safe**. Pun intended.

**Comment by Xerkus** [comment]
This issue actually opens another problem: how do I detect `Threaded` is gone?
It is an object with an empty state that does not cause any kind of errors on setting or getting variables or calling its methods.

**Comment by Xerkus** [comment]
Deleted previous comment.

This issue have another side effect: I can't detect if `Threaded` is gone. Setting or getting variables or calling methods does not produce any kind of errors.  And `Threaded::isTerminated()` does not work and, according to description at php.net, is not meant for this check anyway:

```php
<?php

class ChildThreaded extends Volatile
{
    public $thing = "Mario";

    public function itsAme()
    {
        return "{$this->thing}!\n";
    }
}

class Test extends Thread
{
    private $threaded;

    public function run()
    {
        $this->threaded = new ChildThreaded;
        sleep(1);
    }

    public function getThreaded()
    {
        return $this->synchronized(function() {
            while (!$this->threaded)
                $this->wait();
            return $this->threaded;
        });
    }
}

$thread = new Test();
$thread->start();

$thread->getThreaded()->itsAme();
$thread->join();

var_dump($thread->getThreaded()->isTerminated());
```

> $ zts-php -f issue.php 
> bool(false)
