### ISSUE TITLE
Sockets class site parser based on pthreads?

### ISSUE THREAD

**Issue by Roundik** [krakjoe/pthreads#578]
Hello!

Someone has examples of work with sockets using pthreads?

Thanks!

Best regards,

**Comment by wagnert** [comment]
Have a look at Joe's [examples](https://github.com/krakjoe/pthreads/blob/master/examples/SocketServer.php) or at our webserver [implementation](https://github.com/appserver-io/webserver) :)

**Comment by Roundik** [comment]
Thank you for the answer!
I try to code simple pthreads tcp query function, but main problem is that run function is not run :(
http://pastebin.com/tW2w6VdR 

example from here (in code below pastebin - working) 
http://blog.madewithlove.be/post/thread-carefully/

But i don't know what the problem. Maybe with set variables or what else?
Thanks!
