### ISSUE TITLE
Stream is broken after passing stream in class extending from Thread

### ISSUE THREAD

**Issue by morphesus** [krakjoe/pthreads#579]
Hello there,

I'm trying to build a full featured WebServer for my PHP7 Framework. Everything is working fine, I'm using PHP 7.0.2 with ZTS (of course) and pthreads 3.1.7dev. Previously I used the latest stable version of pthreads - same outcome.

First off, some code:
```php
<?php

namespace NodePHP;

class Client extends \Thread {
    protected $listeners;
    protected $request;
    protected static $response;
    
    public function __construct($listeners, $request, $response /*<- Is a valid stream resource */) {
        $this->listeners = $listeners;
        $this->request   = $request;
        $this->response  = $response; // $this->response will be int(0) instead of stream resource
        
        $this->start();
    }
    
    public function run() {
        foreach ($this->listeners as $listener) {
            // Give work to listeners
            $listener($this->request, $this->response);
            
            // End connection after processing is done
            $this->response->send()->endConnection();
        }
    }
}
```

The stream passed to client object is created by `stream_socket_accept` and embedded as private class field in the class Response (passed to client object as $response).

When I check the content of $reponse in __contruct with var_dump, it's still a valid stream. But when I check $this->response with var_dump AFTER the assignment, the value of the variable is int(0).

Do you know any solution for this? I checked my code multiple times, looked for your examples and searched for maybe already closed issues (there was one, but it doesn't resolved my problem)

Thank you in advance!

Kind regards
Enrico Ludwig

**Comment by krakjoe** [comment]
Your ```$response``` object is not ```Threaded```, so upon setting ```$this->response``` it is serialized and resources do not support serialization.

This isn't a bug, but expected behaviour :)

**Comment by wagnert** [comment]
Hi Enrico, have a look at appserver.io's [webserver](http://www.github.com/appserver-io/webserver) implementation, although it's running on PHP 5.6 yet. We'll update to PHP 7 the next month. I'm sure you'll find a lot useful examples that will help you to build your own webserver :)

**Comment by morphesus** [comment]
Thank you very much for fast response @krakjoe @wagnert ! I'll try and have a look to appserver.io :)

@wagnert Is appserver.io open source? I thought it's a commercial project?

**Comment by wagnert** [comment]
@morphesus appserver.io is an open source project and will ever be :)

**Comment by morphesus** [comment]
@wagnert That's nice! Maybe I'll contribute some code to the project, if desired :)

**Comment by wagnert** [comment]
@morphesus Your contributions will be appreciated, for sure :) We also have the first [apperver.io Hackathon](http://appserver.io/community/1st-hackathon.html) next month, it would be nice to have you with us :)

**Comment by morphesus** [comment]
@wagnert Sounds great, thank you for invite me! I need to check if I have time to join. Maybe we can stay in contact with Skype? I think our conversation is no more related to the topic of the issue :P

**Comment by wagnert** [comment]
It would be really nice if you find the time to join :). We can use Skype or Gitter, as we use Gitter for our support chat. My skype name is wagner83104 if you would prefer that :)

**Comment by morphesus** [comment]
Btw @krakjoe : Extending my HttpResponse class with Threaded solved the issue! Thank you very much :) I now got the error `zend_mm_heap corrupted`, solved this by starting my application like this: `USE_ZEND_ALLOC=0 php index.php` - do you think this is an applicable way?

**Comment by SaitamaSama** [comment]
@morphesus I strongly recommend that you review your code, as, `zend_mm_heap corrupted` is a sign of memory leak. Which SHOULD NOT happen.

**Comment by morphesus** [comment]
@SaitamaSama See https://github.com/krakjoe/pthreads/issues/579#issuecomment-200272959 :)
