### ISSUE TITLE
--enable-pthreads

### ISSUE THREAD

**Issue by ghost** [krakjoe/pthreads#58]
Hello, i downloaded latest version of php but when i use --enable-pthreads option when configuring it , it says configure: WARNING: unrecognized options: --enable-pthreads

i use this code :

 ./configure  --enable-pthreads --enable-maintainer-zts --disable-fileinfo --disable-pdo --enable-bcmath --enable-calendar --enable-exif --enable-ftp --enable-gd-native-ttf --enable-libxml --enable-magic-quotes --enable-mbstring --enable-safe-mode --enable-soap --enable-sockets --enable-zip --prefix=/usr/local --with-apxs2=/usr/local/apache/bin/apxs --with-config-file-path=/usr/local/lib --with-config-file-scan-dir=/usr/local/lib/php.ini.d --with-curl=/opt/curlssl/ --with-curlwrappers --with-freetype-dir=/usr --with-gd --with-gettext --with-imap=/opt/php_with_imap_client/ --with-imap-ssl=/usr --with-jpeg-dir=/usr --with-kerberos --with-libdir=lib64 --with-libexpat-dir=/usr --with-libxml-dir=/opt/xml2 --with-libxml-dir=/opt/xml2/ --with-mcrypt=/opt/libmcrypt/ --with-mysql=/usr --with-mysql-sock=/var/lib/mysql/mysql.sock --with-mysqli=/usr/bin/mysql_config --with-openssl=/usr --with-openssl-dir=/usr --with-pcre-regex=/opt/pcre --with-pic --with-png-dir=/usr --with-xmlrpc --with-xpm-dir=/usr --with-zlib --with-zlib-dir=/usr

Is php manual in php.net not updated or should i download a specific php version?
thanks

**Comment by somenathdey1** [comment]
Hi,
I am configuring php thread on php-5.3.29. However I have stuck with notice during compile,
It said following
```Notice: Following unknown configure options were used:
--enable-pthreads
Check './configure --help' for available options```
Do you have any idea what will be the possible reason for this ?

Steps that I have followed,
cd /usr/local/src
wget http://uk1.php.net/get/php-5.3.29.tar.gz/from/this/mirror -O php-thread-5.3.29.tar.gz
tar xzvf php-thread-5.3.29.tar.gz
cd php-thread-5.3.29/ext
git clone https://github.com/krakjoe/pthreads.git
cd pthreads
git checkout PHP5
cd /usr/local/src/php-thread-5.3.29
./buildconf --force

make clean

./configure \
--prefix=/usr/local/src/php-thread-5.3.29 \
--with-libdir=/lib/x86_64-linux-gnu/ \
--with-openssl=/usr --with-curl=/usr \
--disable-cgi \
--with-config-file-path=:/usr/local/src/php-thread-5.3.29/etc \
--enable-gd-native-ttf --enable-mysqlnd \
--enable-opcache --enable-pcntl \
--enable-debug --enable-maintainer-zts \
--enable-pthreads --enable-mbstring \
--enable-bcmath --enable-exif \
--enable-ftp --enable-shmop \
--enable-soap --enable-sockets \
--enable-sysvmsg --enable-sysvsem \
--enable-sysvshm --enable-wddx \
--enable-opcache --enable-zip --enable-dba

make
make install

It said, 

```Notice: Following unknown configure options were used:
--enable-pthreads
Check './configure --help' for available options```
