### ISSUE TITLE
How to enable pthreads in PHP 5.6 at ubuntu

### ISSUE THREAD

**Issue by guotong1988** [krakjoe/pthreads#584]
I get the point from
https://github.com/krakjoe/pthreads/issues/488
I'm in ubuntu and I run
`apt-cache search pthreads`
and get the result that seems do not have php things
```
libevent-pthreads-2.0-5 - Asynchronous event notification library (pthreads)
libilmbase12 - several utility libraries from ILM used by OpenEXR
libpthread-stubs0-dev - pthread stubs not provided by native libc, development files
blcr-testsuite - Userspace tools to Checkpoint and Restart Linux processes
blcr-util - Userspace tools to Checkpoint and Restart Linux processes
lib32cr0 - (32bit) Libraries to Checkpoint and Restart Linux processes
libcr-dbg - Libraries to Checkpoint and Restart Linux processes
libcr-dev - Development files for BLCR
libcr0 - Libraries to Checkpoint and Restart Linux processes
libzthread-2.3-2 - Object-oriented synchronization library for C++
libzthread-dev - Object-oriented synchronization library for C++
pbzip2 - parallel bzip2 implementation
```

**Comment by morphesus** [comment]
Please see my comment here: https://github.com/krakjoe/pthreads/issues/488#issuecomment-203785192

There is no way to enable pthreads like other modules. You need to compile PHP thread safe. In the comment I linked I explained a bit how you can do this.

Maybe as an alternative: There is a PPA from Ondřej Surý for PHP7 which is already compiled thread safe. (See here: https://launchpad.net/~ondrej/+archive/ubuntu/php-zts)

To make use of this, do the following:

```
sudo apt-get install -y language-pack-en-base
LC_ALL=en_US.UTF-8 sudo add-apt-repository ppa:ondrej/php-zts

sudo apt-get update
sudo apt-get install php7.0-zts php7.0-zts-dev
```

Congratz! PHP7 with thread safety is installed.
Now let's install pthreads:

```
sudo apt-get install git # If not installed

git clone https://github.com/krakjoe/pthreads.git
cd pthreads

phpize # Here we need the php7.0-zts-dev package

make -j8
sudo make install

sudo mkdir -p /etc/php/7.0-zts/conf.d/ # make sure the path is existing

echo "extension=pthreads.so" > /etc/php/7.0-zts/conf.d/pthreads.ini # Enable the extension
```

It should work now. Not tested, just guessed based on the installations I did before this way.

~ Morph

**Comment by sageeki** [comment]
@morphesus did an awesome job with the guide above, but just one small thing:
In order for pthreads to be enabled in the CLI, you have to enter /etc/php/7.0-zts/cli/conf.d/ and make a symbolic link to the pthreads.ini or place the file there.  

cd /etc/php/7.0-zts/cli/conf.d/
ln -s ../../conf.d/pthreads.ini

**Now it works.**

root@box:/etc/php/7.0-zts/cli/conf.d# php -m | grep pthreads
pthreads

**Comment by kalebora** [comment]
Hello
I know you love PHP7  
"PHP7 is MUCH more awesome than PHP5 :D "  [#488 (comment)](https://github.com/krakjoe/pthreads/issues/488#issuecomment-203785192)
"pthreads v3 requires PHP7 or above" [#rquirements (pthreads)](https://github.com/krakjoe/pthreads/#requirements)

I love it too , but unfortunately a lot of PHP  library still using PHP5 and it needs adjustments to be working in 7 

so I'm hanging with 5 for now , I tried to make it work with pthreads but I couldn't and every installation guide is focusing in php7


 "For pthreads 3.x.x you'll need......and you need php7-dev installed - compiled with..." [#488 (comment)](https://github.com/krakjoe/pthreads/issues/488#issuecomment-203785192)

I cannot use PHP7 so I’m really happy with  pthreads v2 (; , how can I make it work with PHP5 ?

Note: I know my problem not an issue and it's not related pthreads 3 ,I'm sorry for that please help.
Note2:  I'm running ubuntu.

**Comment by gloffreda** [comment]
Hi

Trying to follow @morphesus tuto but I'm having this problem:

```
root@vps190138:~/pthreads# make -j8

Build complete.
Don't forget to run 'make test'.
root@vps190138:~/pthreads# sudo make install
make: Nothing to be done for `install'.
```

Any help will be very appreciated.
Thanks

**Comment by Cartman34** [comment]
@morphesus  It seems we need to do "./configure" to build this source.

**Comment by ocheems** [comment]
@morphesus I try to follow the commands, as soon as I reach `sudo apt-get install php7.0-zts php7.0-zts-dev`
I get the following error:
```
robotics@playground:~$ sudo apt-get install php7.0-zts php7.0-zts-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 php7.0-zts : Depends: libapache2-mod-php7.0-zts (>= 7.0.2-1+zts+deb.sury.org~trusty+1~) but it is not going to be installed or
                       php7.0-zts-cgi (>= 7.0.2-1+zts+deb.sury.org~trusty+1~) but it is not going to be installed or
                       php7.0-zts-fpm (>= 7.0.2-1+zts+deb.sury.org~trusty+1~) but it is not going to be installed
              Depends: php7.0-zts-common (>= 7.0.2-1+zts+deb.sury.org~trusty+1~) but it is not going to be installed
 php7.0-zts-dev : Depends: php7.0-zts-cli (>= 7.0.5-4+donate.sury.org~trusty+1) but it is not going to be installed
                  Depends: php7.0-zts-common (= 7.0.5-4+donate.sury.org~trusty+1) but it is not going to be installed
                  Recommends: dh-php but it is not installable
E: Unable to correct problems, you have held broken packages.

```

**Comment by morphesus** [comment]
Hi there @ocheems 

It seems you're using Ubuntu too. Which version do you use?

- Morph

**Comment by Muhammad-Elgendi** [comment]
Hi @morphesus I try to follow the commands, as soon as I reach `make -j8`
I get the following error:
```
Makefile:196: recipe for target 'php_pthreads.lo' failed
make: *** [php_pthreads.lo] Error 1
```
I am using linuxmint Based on: Debian, Ubuntu 16.04 (LTS)

Any help would be appreciated

**Comment by morphesus** [comment]
Hi @Muhammad-Elgendi

First off remove the `-j8` parameter to disable multithreaded compiling. If this doesn't show any effect consider to open a [new ticket](https://github.com/krakjoe/pthreads/issues/new).

Kind regards
