### ISSUE TITLE
set_error_handler() causes Segmentaion Fault when using Lambda function in Worker

### ISSUE THREAD

**Issue by soda0289** [krakjoe/pthreads#587]
Environment
==========

  * PHP: PHP 7.0.5 (cli) (built: Mar 30 2016 10:02:33) ( ZTS )
  * pthreads: Version => 3.1.6
  * OS: Windows/Linux

Summary
======
When using a lambda function as an argument for set_error_handler() php crashes on a failed assertion. When using an actual function callback, as the argument, the segmentation fault goes away. I'm currently trying to write code that reproduces this bug. The set_error_handler function is called in an abstract class that extends Threaded. This abstract class is the parent to several job classes. I use the same code, and abstract job class, with a Pool of Workers and it works fine, so far. I'm using a PDO connection per Worker as well.

I am not using any selective inheritance. Will try and post sample code as soon as I can reproduce the error.

Backtrace
========
zend_hash_find(EG(function_table), Z_STR_P(EX_CONSTANT(opline->op1))) returns NULL

#0  0x00007ffff3d76478 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff3d778fa in __GI_abort () at abort.c:89
#2  0x00007ffff3d6f3a7 in __assert_fail_base (fmt=<optimized out>,
    assertion=assertion@entry=0xf43a68 "zfunc != ((void *)0) && (*(zfunc)).value.func->type == 2",
    file=file@entry=0xf42e20 "/home/admin/Workspace/php-src/Zend/zend_vm_execute.h", line=line@entry=8470,
    function=function@entry=0xf448a0 <__PRETTY_FUNCTION__.14054> "ZEND_DECLARE_LAMBDA_FUNCTION_SPEC_CONST_UNUSED_HANDLER")
    at assert.c:92
#3  0x00007ffff3d6f452 in __GI___assert_fail (
    assertion=0xf43a68 "zfunc != ((void *)0) && (*(zfunc)).value.func->type == 2",
    file=0xf42e20 "/home/admin/Workspace/php-src/Zend/zend_vm_execute.h", line=8470,
    function=0xf448a0 <__PRETTY_FUNCTION__.14054> "ZEND_DECLARE_LAMBDA_FUNCTION_SPEC_CONST_UNUSED_HANDLER") at assert.c:101
#4  0x0000000000a4db6d in ZEND_DECLARE_LAMBDA_FUNCTION_SPEC_CONST_UNUSED_HANDLER ()
    at /home/admin/Workspace/php-src/Zend/zend_vm_execute.h:8470
#5  0x0000000000a3a960 in execute_ex (ex=0x7fffeea14190) at /home/admin/Workspace/php-src/Zend/zend_vm_execute.h:424
#6  0x00007fffefc3a3ad in pthreads_execute_ex (data=0x7fffeea14190) at /home/admin/Workspace/pthreads/php_pthreads.c:143
#7  0x0000000000a3c51f in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER ()
    at /home/admin/Workspace/php-src/Zend/zend_vm_execute.h:985
#8  0x0000000000a3a960 in execute_ex (ex=0x7fffeea14100) at /home/admin/Workspace/php-src/Zend/zend_vm_execute.h:424
#9  0x00007fffefc3a3ad in pthreads_execute_ex (data=0x7fffeea14100) at /home/admin/Workspace/pthreads/php_pthreads.c:143
#10 0x0000000000a3c51f in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER ()
    at /home/admin/Workspace/php-src/Zend/zend_vm_execute.h:985
#11 0x0000000000a3a960 in execute_ex (ex=0x7fffeea14030) at /home/admin/Workspace/php-src/Zend/zend_vm_execute.h:424
#12 0x00007fffefc3a3ad in pthreads_execute_ex (data=0x7fffeea14030) at /home/admin/Workspace/pthreads/php_pthreads.c:143
#13 0x00000000009bc05f in zend_call_function (fci=0x7fffef5fec90, fci_cache=0x7fffef5fecd0)
    at /home/admin/Workspace/php-src/Zend/zend_execute_API.c:859
#14 0x00007fffefc4b305 in pthreads_routine_run_function (object=0x7fffef6287e0, connection=0x7fffec429d20,
    work=0x7fffef5fee00) at /home/admin/Workspace/pthreads/src/object.c:464
#15 0x00007fffefc4b62d in pthreads_routine (routine=0x7fffffffa640) at /home/admin/Workspace/pthreads/src/object.c:500
#16 0x00007ffff40ee454 in start_thread (arg=0x7fffef5ff700) at pthread_create.c:334
#17 0x00007ffff3e2bedd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by krakjoe** [comment]
Please re-open the report when you have a reproducing script.
