### ISSUE TITLE
Which function can replace kill()

### ISSUE THREAD

**Issue by aodzip** [krakjoe/pthreads#588]
pthreads remove kill() in PHP7 , but here will be some trouble when shutdown a class contain "php://stdin" , the thread will continue wait until get an input from keyboard.  The program become wierd -> user will need type another "\n" to continue shutdown procees . 
Is there any solutions?

**Comment by BurakDev** [comment]
Create a boolean on your threaded class, and stop run function when this boolean is false.

And you can create a public method to change this boolean, this like kill.

**Comment by 2072** [comment]
you can also set STDIN to non-blocking using:
```php
 stream_set_blocking(STDIN, false);
```
 and then periodically check in your thread if there is something to read while still being able to react on other events...

**Comment by dktapps** [comment]
stream_set_blocking does not work on Windows. This is why this issue was created. On Windows, any thread reading STDIN will suffer from the issue mentioned, where fgets() will block the thread until another input is received allowing the thread to exit.
