### ISSUE TITLE
pthread not to inherit definer and includes file

### ISSUE THREAD

**Issue by nkumarjain** [krakjoe/pthreads#591]
Environment
==========

  * PHP: 5.6
  * pthreads: 2.0
  * OS: CentOS

Summary
======

Is there any possibilities that could not inherit includes files and definer variable in pthread run method? I have tried with PTHREADS_INHERIT_NONE but it seems not working. We have used below code 

Reproducing Code
==============

```
$domain_root='/home/user/abc';
define('DIR_FS_DOMAIN_ROOT', $domain_root);
class NEWThread extends Thread{
    public function __construct()
    {

   }
    public function run()
    {
         $this->html=DIR_FS_DOMAIN_ROOT;
    }
}
$th=new NEWThread(PTHREADS_INHERIT_NONE);
$th->start();
$th->join();
echo $th->html;


```
Expected Output 

Nothing but its printing  '/home/user/abc'
=============

it should not print anything. But its printing '/home/user/abc'

Actual Output
============

 its printing '/home/user/abc'

**Comment by krakjoe** [comment]
You are supposed to pass options to start, not constructor.
