### ISSUE TITLE
Is built-in CLI webserver supported or not?

### ISSUE THREAD

**Issue by quantuumsnot** [krakjoe/pthreads#592]
[Environment]
* PHP: 7.0.6-VC14-TS-x64
* pthreads: php_pthreads-3.1.6-7.0-ts-vc14-x64
* OS: Windows 7 x64

[Summary]
Trying to run PHP built-in server with pthreads enabled

[Reproducing Code]
php.exe -S 127.0.0.1:9000

[Expected Output]
Well, expecting the built-in webserver to start

[Actual Output]
[Mon May  2 16:07:05 2016] PHP Fatal error:  The cli-server SAPI is not supported by threads in Unknown on line 0
[Mon May  2 16:07:05 2016] PHP Fatal error:  Unable to start pthreads module in Unknown on line 0

**Comment by krakjoe** [comment]
No.

Add extension=pthreads.so to php-cli.ini in the same path as php.ini, then it will only load in CLI.

**Comment by quantuumsnot** [comment]
So, give me an idea how to test with WeigHTTP some code that uses pthreads?

**Comment by krakjoe** [comment]
I don't understand the question.

> weighttp (pronounced weighty) is a lightweight and small benchmarking tool for webservers.

Why would you be testing a CLI application, that cannot be deployed to a webserver, with a webserver benchmarking tool ?

**Comment by quantuumsnot** [comment]
That's the question - how to test rps performance of web-app when pthreads don't work with the built-in CLI-server, only with cli, and at the moment I don't want to use 3rd party web-server

**Comment by krakjoe** [comment]
Your web app doesn't use pthreads, so:

> Add extension=pthreads.so to php-cli.ini in the same path as php.ini, then it will only load in CLI.

In case not clear, remove ```extension=pthreads.so``` from all other ini files.

**Comment by freshguy** [comment]
hi krakjoe，

I use php5.6.22 + pthread2.0.10，for instance as below

`<?php
class demo extends Thread{
    public $num = 0;
    public function __construct($num){
        $this->num = $num+200;
    }

    public function run(){
        //当执行start方法时，run会执行，所以没有直接调用run的方法
        return $this->num;
    }
}

//时间计算开始
$t = microtime(true);
for($i = 0 ;$i < 10 ; $i++){
    //创建线程池
    $pool[] = new demo($i);
}

foreach($pool as $work){
    //在独立线程中执行 run 方法
    $work->start();
}

foreach($pool as $key=>$value){
    //对象是否正在运行
    while($value->isRunning()){
        usleep(10);
    }
    //让当前执行上下文等待被引用线程执行完毕
    if($value->join()){
        $row[$key] = $value->num;
    }
}
//时间计算结束
$e = microtime(true);

var_dump($row);
echo '<br />';
echo ($e-$t);`
