### ISSUE TITLE
PHP7.0.6, Can not make.

### ISSUE THREAD

**Issue by bleakwind** [krakjoe/pthreads#595]
` cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/pub/_bleakwind/php-7.0.6/ext/pthread -DPHP_ATOM_INC -I/pub/_bleakwind/php-7.0.6/ext/pthread/include -I/pub/_bleakwind/php-7.0.6/ext/pthread/main -I/pub/_bleakwind/php-7.0.6/ext/pthread -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/pub/_bleakwind/php-7.0.6/ext/pthread/. -DHAVE_CONFIG_H -g -O2 -c /pub/_bleakwind/php-7.0.6/ext/pthread/php_pthreads.c  -fPIC -DPIC -o .libs/php_pthreads.o
In file included from /pub/_bleakwind/php-7.0.6/ext/pthread/php_pthreads.c:22:
In file included from ./src/pthreads.h:53:
In file included from /usr/local/include/php/ext/spl/spl_iterators.h:27:
/usr/local/include/php/ext/pcre/php_pcre.h:29:10: fatal error: 'pcre.h' file not found
#include "pcre.h"
         ^
1 error generated.
*** Error code 1

Stop.
make: stopped in /pub/_bleakwind/php-7.0.6/ext/pthread`

FreeBSD10.3, PHP7.0.6-ZTS.

**Comment by krakjoe** [comment]
PCRE headers are either provided by php-src, or, your distro if php-src is configured with ```--with-pcre-dir``` or ```--with-pcre-regex```.

It looks like you have chosen to use your distro's PCRE, but the header is missing, maybe try installing ```pcre-devel``` or similar.

This isn't a bug in pthreads.
