### ISSUE TITLE
block occurs when assign a new Thread to var

### ISSUE THREAD

**Issue by woudygao** [krakjoe/pthreads#599]
*If you know how to write phpt tests, please open a PR with environment information, and your test, this will cause CI to test your issue before a human is able to look*

Environment
==========
PHP 7.0.4 (cli) (built: May 24 2016 16:56:50) ( ZTS )
Description:	CentOS release 6.3 (Final)
LSB Version:	:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
  * PHP: *can be obtained with ```php -v```*
  * pthreads: *can be obtained with ```php -dextension=pthreads.so --ri pthreads | grep Version```*
  * OS: *if Windows, include arch*

Summary
======
when I try to new Thread and Start Thread in for loop; The next new operation will deadlock without any massage;
I guess there is a theory that every thread what is not completed should have at least one var point to it; when try to assign a  new value to the var  what will make no var point to a running thread ; It will block until the thread is running over for wild pointer safe or garbage collect safe  or anything else;

If someone have a answer please tell me. on github or send to me: woudygao@gmail.com

A summary isn't always necessary, code > words ... delete this section, as applicable.

Reproducing Code
==============
`<?php

class MyThread extends Thread {
    public function run() {
        sleep(10);
    }
}

function main() {
    for ($i = 0; $i < 10; $i ++) {
        echo "Loop: $i" . PHP_EOL;
        $thread  = new MyThread();
        $thread->start();
    }
}

main();`

Bug reports *must* come with reproducing code, please ensure code is formatted correctly.

If the code cannot be a single script, please link to a gist, or a github repository containing the reproducing code. 

Please, do not link to application repositories.

*Please ensure code is self contained, and executable: if the code cannot be executed, the bug cannot be reproduced.*

Expected Output
=============
muti line from Loop 0 to Loop 9 as soon as possible

Please include the expected output, properly formatted.

Actual Output
============
block for 10 second each;

Please include the actual output, properly formatted.

**Comment by krakjoe** [comment]
You are creating and immeidately destroying (and so implicitly joining) ```$thread```:

    $thread = new MyThread();
    $thread->start();

Try creating an array of threads in ```main()```.

**Comment by woudygao** [comment]
Thx for repling!!!

So is the destroying called by cg??; and cg is synchronized in main thread ; none like in java there is another thread for cg

**Comment by krakjoe** [comment]
It's destroyed because ```$thread``` goes out of scope at the end of the iteration.

**Comment by woudygao** [comment]
Until now ; I having the faith that php var scope is just global or in class or function ; The  iteration is not a  scope;

as
`function loop() {
for ($i = 0; $i < 20; $i ++) {
    $sample = $i;
}

var_dump($sample);
}`

will output 19 ; so the var is not destroyed

**Comment by SirSnyder** [comment]
sleep() let the whole process sleep and not just the thread

**Comment by woudygao** [comment]
This is a sample . The original code is not this. I paste it below here:  A little Long

`<?php

define('SHM_LOG_TAG_KEY', 3);
define('SEM_LOG_TAG_KEY', 4);
//define();

class Log {
    //目标是 对象持有句柄
    public $shmid;
    public $shmkey;
    public $file;

    public function __construct($key, $file) {
        //$this->shmid = shm_attach($key);
        $this->shmkey = $key;
        $this->file = $file;
    }

    public function info($msg) {
        $log = "[%s] [%s] %s" . PHP_EOL;
        $this->shmid = shm_attach($this->shmkey);
        $tagmap = shm_get_var($this->shmid, SHM_LOG_TAG_KEY);
        $cptlog = sprintf($log, date('Y-m-d H:i:s'), $tagmap[Thread::getCurrentThreadId()], $msg);
        error_log($cptlog, 3, $this->file);
    }
}

class LogBuilder {
    const LOGFILE = "/home/work/thorct/prototype/mt/run.log";

    public static function getLogger($key) {
        //echo "LogBuilder : $key" . PHP_EOL;
        $log = new Log($key, self::LOGFILE);
        //var_dump($log);
        return $log;
    }
}


class MyLogThread extends Thread {
    private $tag;
    private $logger;
    private $key;
    private $semkey;
    private $semid;

    public function __construct($tag, $key, $semkey) {
        echo "init t: " . $tag . " " . $key . " " . $semkey .PHP_EOL;
        $this->tag = $tag;
        $this->semkey = $semkey;
        //$this->semid = sem_get($this->semkey);
        //echo "semid[$this->semkey]: " . $this->semid . PHP_EOL;
        echo "finish init t: " . $tag . " " . $key . " " . $semkey .PHP_EOL;
    }

    public function run() {

    $this->synchronized(function ($mythread) {
        echo "t: " . $mythread->tag . " Acquire:" . $mythread->semkey . PHP_EOL;
        $semid = sem_get($mythread->semkey);
        echo "b semid[$this->semkey]: " . $semid . PHP_EOL;
        sem_acquire($semid);
        echo "t: " . $mythread->tag . " Acquired:" . $mythread->semkey . PHP_EOL;

        sleep(mt_rand(0,2));
        sleep(mt_rand(0,2));
    }, $this);
    }
}

function main() {
    $tmp = tempnam(__FILE__, 'PHP');
    $key = ftok($tmp, 'a');
    $shmid = shm_attach($key, 1024);

    $logger = LogBuilder::getLogger($key);
    for ($i = 1; $i <= 5; $i ++) {
        echo "In Loop: " . $i . PHP_EOL;
        $tag = "thread-" . $i;

        echo "Main new Thread $tag" . PHP_EOL;
        $thread = new MyLogThread($tag, $key, $i);
        echo "Main finish new Thread $tag" . PHP_EOL;

        $thread->start();

        $thireadid = $thread->getThreadId();
        $tagmap[$thireadid] = $tag;
        var_dump($tagmap);
    }
    $logger->info("hello all t is run");
    shm_put_var($shmid, SHM_LOG_TAG_KEY, $tagmap);

    foreach ($arrSemid as $i => $semid) {
        echo "Main release $i" . PHP_EOL;
        //sem_release($semid);
        echo "Main released $i" . PHP_EOL;
    }
}

main();`

**Comment by SirSnyder** [comment]
Like Joe said, you have to hold the threads in a array. Otherwise they are cleaned up after creation.

```
$threads = [];
for ($i = 1; $i <= 5; $i ++) {
    echo "In Loop: " . $i . PHP_EOL;
    $tag = "thread-" . $i;

    echo "Main new Thread $tag" . PHP_EOL;
    $thread = new MyLogThread($tag, $key, $i);
    echo "Main finish new Thread $tag" . PHP_EOL;

    $thread->start();

    $thireadid = $thread->getThreadId();
    $tagmap[$thireadid] = $tag;
    var_dump($tagmap);
    $threads[] = $thread;
}
```

**Comment by woudygao** [comment]
So the mechanism of "Otherwise they are cleaned up after creation." is what?? where Can I know something underlying ??

**Comment by woudygao** [comment]
Thx you all !!!
