### ISSUE TITLE
Extension cannot be loaded

### ISSUE THREAD

**Issue by hartois** [krakjoe/pthreads#601]
# Environment
- PHP: 7.0.5
- pthreads: master branch (last commit d814b0cf701a2a5fa93bb69f61d1c29178086e82)
- OS: Fedora 23 x86
# Summary

Compiled extension library cannot be loaded with:
undefined symbol: php_network_gethostbyname

```
git clone https://github.com/krakjoe/pthreads
cd pthreads
zts-phpize
./configure --with-php-config=zts-php-config
make

make test

Build complete.
Don't forget to run 'make test'.

PHP Warning:  PHP Startup: Unable to load dynamic library '/tmp/pthreads/modules/pthreads.so' - /tmp/pthreads/modules/pthreads.so: undefined symbol: php_network_gethostbyname in Unknown on line 0
```

Build log attached.
[build.txt](https://github.com/krakjoe/pthreads/files/288346/build.txt)

**Comment by hartois** [comment]
Hmmm... 
Function php_network_gethostbyname was added to the php since 7.0.6. 
Probably should write about this in Readme.

**Comment by krakjoe** [comment]
Yeah the master branch has ongoing work at the moment on socket stuff, there is no release with this stuff included yet ...

Will finalize requirements when they are known, before a release.

**Comment by tpunt** [comment]
The README file has been updated to specify the new requirements (PHP 7.2+), and issue #709 is tracking the remaining documentation problems, so I'm closing this issue.
