### ISSUE TITLE
Thread in array won't start as expected

### ISSUE THREAD

**Issue by zerustech** [krakjoe/pthreads#602]
*If you know how to write phpt tests, please open a PR with environment information, and your test, this will cause CI to test your issue before a human is able to look*

Environment
==========

  * PHP: 5.6.14
  * pthreads: 2.0.10
  * OS: Mac OS X 10.11.5

Summary
======

Under special circumstance, thread object in an array won't start as expected.

Reproducing Code
==============

```php
<?php

class Producer extends Thread
{
    private $inventory;
    
    public function __construct($inventory)
    {
        $this->inventory = $inventory;
    }

    public function run()
    {
        $this->inventory->add('*');
        $this->inventory->report();
    }
}

class Inventory extends Threaded
{
    private $queue;

    public function __construct(Threaded $queue)
    {
        $this->queue = $queue;
    }

    public function add($product)
    {
        $this->queue[] = $product;
    }

    public function report()
    {
        $msg = '';

        foreach ($this->queue as $product) {
            $msg .= $product;
        }

        echo $msg."\n";
    }
}

// This works as expected
/*
$queue = new Threaded();
$inventory = new Inventory($queue);
$p = new Producer($inventory);
$p->start();
*/

// This does not work
$queue = new Threaded();
$inventory = new Inventory($queue);
$pool = [];
$pool[] = new Producer($inventory);
$pool[0]->start();
// It works, if the following line is uncommented:
// $pool[0]->join();
```

Expected Output
=============

```bash
*
```

Actual Output
============
```bash
```

**Comment by krakjoe** [comment]
That's expected ...

The thread is destroyed implicitly, too early by the destruction of the array ... you should join all threads you create.

**Comment by zerustech** [comment]
@krakjoe Thanks for your quick response. However, could you let me know why it only happens to ``array``? As far as I know, this works perfectly if the thread is assigned to a normal variable.

**Comment by zerustech** [comment]
@krakjoe This issue can't be reproduced in PHP 7.
