### ISSUE TITLE
Unexpected exception: pthreads detected an attempt to connect to an object which has already been destroyed

### ISSUE THREAD

**Issue by mctracker** [krakjoe/pthreads#604]
Environment
==========

   PHP 7.0.5 (cli) (built: Mar 30 2016 10:02:33) ( ZTS )
   pthreads Version => 3.1.6
   Windows 2008/7 x64

Summary
======

When manipulating volatile object as array (inside synchronized block) at some point there is exception:  **pthreads detected an attempt to connect to an object which has already been destroyed**

Reproducing Code
==============

Because there is a few files needed I've added an archive https://www.sendspace.com/file/kejk5v
There are classes file, worker file, 2 text files with domains and socks.
```

 public function run(){


        //echo "list size: ".$this->socks_lister->GetListSize()."\n";
        while($this->socks_lister->GetListSize() > 0){
           
            $this->socks = $this->socks_lister->GetRandomSocksCheck();
            $this->VisitUrl($this->domain_data);
            //"Removing socks!\n";
            $this->socks_lister->RemoveSocks($this->socks);
            $r = rand(0,2);
            if($r == 1){
                echo "breaking!\n";
                break;
            }

             
        }
        
        echo "list size: ".$this->socks_lister->GetListSize()."\n";
        if($this->socks_lister->GetListSize() < 1)
            echo "No SOCKS avaliable, exiting!\n";
        return;
       
    }
```
The proble appears at last condition when list size is calculating.

Expected Output
=============
Checking socks 62.173.145.42:45793
Checking socks 112.78.1.204:30216
Checking socks 162.243.24.59:21871
returning valid socks 148.251.43.183:47743
Using socks 148.251.43.183:47743 for url:1
returning valid socks 62.173.145.42:45793
Using socks 62.173.145.42:45793 for url:facebook.com
returning valid socks 91.222.125.194:35154
Using socks 91.222.125.194:35154 for url:youtube.com
Removing 62.173.145.42:45793 from list as not valid

Actual Output
============

Got socks exception: pthreads detected an attempt to connect to an object which
has already been destroyed
Got socks exception: pthreads detected an attempt to connect to an object which
has already been destroyed
Got socks exception: pthreads detected an attempt to connect to an object which
has already been destroyed
list size:

**Comment by webdes87** [comment]
Can you check your Eventlog in Windows? Maybe your php.exe also crashes and for that reason you get that message. Seems similiar error that I have using windows 10.

**Comment by krakjoe** [comment]
This is not a bug in pthreads, it's expected behaviour: It means you are attempting to access an object which was created (either with ```new```, or by assignment of an array) by a ```Thread``` which was already destroyed.

**Comment by mctracker** [comment]
But this object wasn't destroyed nowhere in the code (at least obviously). I'am using volatile object as array container. And for some reason its been destroyed, despite there is code that actually destroys this object.
