### ISSUE TITLE
PHP Crash on Windows 10 when assigning arrays to \Thread

### ISSUE THREAD

**Issue by webdes87** [krakjoe/pthreads#610]
*If you know how to write phpt tests, please open a PR with environment information, and your test, this will cause CI to test your issue before a human is able to look*

Environment
==========

PHP:
D:\dev\xampp\htdocs\musico>php -v
PHP 7.0.5 (cli) (built: Mar 30 2016 10:15:26) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

 OS: WIndows 10 /  x64
Latest pthread release

Summary
======

When using a Thread (class extends \Thread) and assigning an array (propably any complex datatype) to a member variable, php.exe crashes. 
![crash](https://cloud.githubusercontent.com/assets/20090395/16460590/6694846e-3e28-11e6-9acb-108ca5e9bc49.png)

Reproducing Code
==============
https://gist.github.com/webdes87/c90b535f3aa9e72f0d7fa150f104516e

Code will produce error: 

Expected Output
=============
After 1.s Seconds
10 arrays: ["blahkeks", someThreadId]
+ Some progress infos

Actual Output
============
Fatal error: Uncaught RuntimeException: pthreads detected an attempt to connect to an object which has already been destroyed in {WhereEverYourFileIs.php}

Assumption: Thread dies while running due to assignment of array. This behaviour is wether catched nor documeneted or obvisious. In addition, there is no workaround for this use case given.

**Comment by krakjoe** [comment]
$this->result = ['blahkeks', $this->getThreadId()];

This sets ```$this->result``` to a ```Volatile``` object, the ```Volatile``` object belongs to the ```Thread```. When the ```Thread``` is destroyed, so is the ```Volatile``` object, and when the main context attempts to access it, you will raise an error.

If you really meant to use an array, explicitly cast:

    $this->result = (array) ['blahkeks', $this->getThreadId()];

This is expected behaviour.

**Comment by webdes87** [comment]
Ok, I tried it and when (array)-casting it, the php.exe does not seem to crash. Thanks for that hint :)

But can you please enlighten my eyes, why the cast from [] to (array) [] is neccesary to not crash php.exe? And what this is related to volatile, since to my knowledge (Java) it just prevents some internal caching or other optimizations that might result in no write operation?

Under which circumstances can such crashes also happen?

Would be nice, if such conditions would catched, since, for my eyes this is not very obvisious and Thread-Crash should imo not happen.
