### ISSUE TITLE
How to use multi-threading in web api ?

### ISSUE THREAD

**Issue by freshguy** [krakjoe/pthreads#611]
I use php5.6.22(with ‘enable-maintainer-zts’) + pthread2.0.10，a php script is as follows（test_thread.php）。
One problem which make me confused：
run this script in CLI mode(php test_thread.php), it works fine as expected，but when my php web-api have the same built-in multi-thread call, these threads have been constructed, have been started（$work->start()), but the 'run()' mothod(overwrited in my derived thread class which inherited from 'Thread') does work not at all ???

thank you.

----------------------------------------------------- test_thread.php ------------------------------------------------------
<?php
class demo extends Thread{
    public $num = 0;
    public function __construct($num){
        $this->num = $num+200;
    }

    public function run(){
        return $this->num;
    }
}

$t = microtime(true);
for($i = 0 ;$i < 10 ; $i++){
    $pool[] = new demo($i);
}

foreach($pool as $work){
    $work->start();
}

foreach($pool as $key=>$value){
    while($value->isRunning()){
        usleep(10);
    }
    if($value->join()){
        $row[$key] = $value->num;
    }
}
$e = microtime(true);

var_dump($row);
echo ($e-$t) . "\n";

**Comment by mctracker** [comment]
@freshguy, afiak pthreads now works only in cli sapi.

**Comment by freshguy** [comment]
@mctracker  thank you，i have used non-bloking IO asynchronous call instead of of multi-threading call for our  business logic.

**Comment by BurakDev** [comment]
@freshguy On the old version you are using (php5 + pthreads 2.0.10), you can use it on a webserver

**Comment by krakjoe** [comment]
Returning from ```Thread::run``` doesn't and has never worked.

I think there is some confusion here, and I can see no bug.

Closing the issue, feel free to add more info if I'm wrong ...
