### ISSUE TITLE
Unable to initalize module while pthreads has PHP7 support

### ISSUE THREAD

**Issue by quantuumsnot** [krakjoe/pthreads#613]
Error
===
Warning: PHP Startup: pthreads: Unable to initialize module
Module compiled with module API=20151012
PHP    compiled with module API=20160303
These options need to match
 in Unknown on line 0

Environment
========

  * PHP:  7.1.0-alpha3, x64
  * pthreads: 3.1.6-7.0-ts-vc14-x64
  * OS: Windows 7 x64

**Comment by bwoebi** [comment]
This is PHP 7.1. You'll have to compile it yourself there. There are no Windows releases for pthreads on 7.1.

**Comment by quantuumsnot** [comment]
Ok ... but two things:
1. Same happened from version 7.0.2 to this alpha
2. Any tutorial HOW to build the library when:
`	1	IntelliSense: this declaration has no storage class or type specifier	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	23	1	php_pthreads
	2	IntelliSense: identifier "pthreads" is undefined	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	23	20	php_pthreads
	3	IntelliSense: this declaration has no storage class or type specifier	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	24	1	php_pthreads
	4	IntelliSense: identifier "pthreads" is undefined	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	24	24	php_pthreads
	5	IntelliSense: this declaration has no storage class or type specifier	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	25	1	php_pthreads
	6	IntelliSense: identifier "pthreads" is undefined	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	25	20	php_pthreads
	7	IntelliSense: this declaration has no storage class or type specifier	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	26	1	php_pthreads
	8	IntelliSense: identifier "pthreads" is undefined	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	26	24	php_pthreads
	9	IntelliSense: this declaration has no storage class or type specifier	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	27	1	php_pthreads
	10	IntelliSense: identifier "pthreads" is undefined	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	27	20	php_pthreads
	11	IntelliSense: this declaration has no storage class or type specifier	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	28	1	php_pthreads
	12	IntelliSense: identifier "pthreads" is undefined	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	28	36	php_pthreads
	13	IntelliSense: cannot open source file "classes/threaded.h"	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	31	1	php_pthreads
	14	IntelliSense: cannot open source file "classes/thread.h"	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	35	1	php_pthreads
	15	IntelliSense: cannot open source file "classes/collectable.h"	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	39	1	php_pthreads
	16	IntelliSense: cannot open source file "classes/worker.h"	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	43	1	php_pthreads
	17	IntelliSense: cannot open source file "classes/pool.h"	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	47	1	php_pthreads
	18	IntelliSense: cannot open source file "classes/socket.h"	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	51	1	php_pthreads
	19	IntelliSense: identifier "zend_module_entry" is undefined	h:\programming\softuni\teamwork tasks\php_pthreads\php_pthreads\php_pthreads.h	54	8	php_pthreads
`
This is on VS2013 x64 and yes - it's on "Release" for x64 platform

**Comment by krakjoe** [comment]
This isn't a bug in pthreads :)

**Comment by molchanov1983** [comment]
Hello
Question to quantuumsnot
Have you found php_threads.dll for PHP: 7.1.0-alpha3, x64
I have the same php version and OS version
If you have it could you give me dll file?
Thanks

**Comment by chinmay235** [comment]
Hello @krakjoe 
I have faced same problem. #672  https://github.com/krakjoe/pthreads/issues/672#issuecomment-346809403

Warning: PHP Startup: pthreads: Unable to initialize module
Module compiled with module API=20151012
PHP    compiled with module API=20160303
These options need to match
 in Unknown on line 0

Please help me.
