### ISSUE TITLE
Undefined property P::$work and empty array

### ISSUE THREAD

**Issue by quantuumsnot** [krakjoe/pthreads#615]
Environment
==========

  * PHP:  7.0.9 x64 TS-vc14
  * pthreads: 3.1.6-7.0-ts-vc14-x64
  * OS: Windows 7 x64
---
[Reproducing Code]
---
```
<?php
class T extends Threaded Implements Collectable {
  public function __construct($input) {
    $this->input = $input;
    $this->garbage = false;
  }

  public function run() {
    $this->data = 2*3.141592*($this->input); //2*Pi*r
    $this->garbage = true;
  }
  
  public function isGarbage() : bool { 
    return $this->garbage; 
  }
}

class W extends Worker {
  public function run() {
  }
}

class P extends Pool {
  public $results = [];

  public function process() {
    while (count($this->work)) {
      $this->collect(function (Collectable $job) {
        if ($job->isGarbage()) {
          $this->results[$job->input] = $job->data;
        }
      });
    }

    $this->shutdown();

    return $this->results;
  }
}

$i = 0;
$pool = new P($cpuCores, W::class);
do {
  $pool->submit(new T($i+1));
  $i++;
} while ($i < 8);
$data = $pool->process();
var_dump($data);
?>
```
---
[Expected Output] - a filled array
[Actual Output ]- array(0) {} and "Notice: Undefined property: P::$work in file on line ..."

**Comment by krakjoe** [comment]
A few misunderstandings make the code incorrect:

   - ```Threaded``` implements ```Collectable``` for you.
   - A ```Threaded``` passed to your collector function is by definition garbage
   - The collector function still needs to return true (as the default implementation does)

The code should look more like:

	<?php
	class T extends Threaded {
	  public function __construct($input) {
		$this->input = $input;
	  }

	  public function run() {
		$this->data = 2*3.141592*($this->input); //2*Pi*r
	  }
	}

	class W extends Worker {
	  public function run() {
	  }
	}

	class P extends Pool {
	  public $results = [];

	  public function process() {

		while ($this->collect(function (Collectable $job) {
		    $this->results
				[$job->input] = $job->data;
			return true;
		  }));

		$this->shutdown();

		return $this->results;
	  }
	}

	$i = 0;
	$pool = new P(16, W::class);
	do {
	  $pool->submit(new T($i+1));
	  $i++;
	} while ($i < 16);


	$data = $pool->process();
	var_dump($data);
	?>
