### ISSUE TITLE
Loading in the presence of Apache - can it fail gracefully?

### ISSUE THREAD

**Issue by studio2222** [krakjoe/pthreads#617]
Hi guys!

I need to install and use pthreads for command line jobs that we run nightly on our website, so I added the php_pthreads.dll extension to my php.ini file. I am aware that you cannot use pthreads when php is being loaded via apache -- only cli. That's fine. However, apache will not even start with extension=php_pthreads.dll present in  my php.ini file. 

I want to avoid having to have two php.ini files -- one for cli and one for web (why create havoc for just one line difference : )), and I've been unable to find a way to have the extension=php_pthreads.dll line skipped if php is running in an apache environment.

Is there a trick anyone can think of? Or can php_pthreads.dll be designed to simply not load silently if php is being loaded in an apache environment (instead of causing apache to die immediately, which it does currently)?

**Comment by JesusTheHun** [comment]
You can execute

`php.exe -dextension=php_pthreads.dll myScript.php`

It will load the extension only for this execution. Also, GitHub issue are not a help forum, to find help about php or apache in general, ask on stackoverflow for exemple.

**Comment by studio2222** [comment]
I was being generous, but thanks for the unnecessary rebuke. I was deferentially asking whether pthreads can be designed to work to play nice in a mixed apache/offline use environment by not preventing apache from loading, but rather silently disable itself during startup if apache is detected -- to avoid precisely the workaround you've suggsted. In a multi server environment each additional piece we need to add to the command line script to overcome some deficiency in componentry is one more item that has to be cared for, potentially forgotten, or can malfunction. Simple is better, and the extension should disable itself silently vs crash it's parent. It's that simple.

**Comment by bwoebi** [comment]
I think I agree here; the classes etc. just should not be imported then and it should properly crash because of undefined class in a non-CLI environment.

**Comment by JesusTheHun** [comment]
If I load an extension not design for the environnement, shouldn't it blow up ?
Also it can be confusing when using the polyfill.
