### ISSUE TITLE
Readme does not mention pthreads cannot run on Apache web server

### ISSUE THREAD

**Issue by joshbernfeld** [krakjoe/pthreads#618]
Readme does not mention that v3 does not support running pthreads with Apache but only in CLI

http://stackoverflow.com/questions/32795281/apache2-pthreads-fatal-error-the-apache2handler-sapi-is-not-supported-by-pthre

**Comment by JesusTheHun** [comment]
Yes it does.

See https://github.com/krakjoe/pthreads#sapi-support

**Comment by krakjoe** [comment]
It really does :)
