### ISSUE TITLE
Problem with static variable

### ISSUE THREAD

**Issue by gollariel** [krakjoe/pthreads#619]
Hi! Maybe you help me.

I migrate to pthread v3, and i catch incorrect handling.

If i use static array on different class - static array does not copy. But I thought that only objects, and resources will deleted

My example. But i have correct result if i set static array after start pthread:

```
class TestThread extends Thread
{
	public function __construct()
	{
		$this->start();
	}

	public function run()
	{
		var_dump(Object::valid('test'));
	}
}

class Object
{
	protected static $default = [
		'test' => 1
	];
	protected static $validate = [
		'test' => 'bool'
	];

	public static function thread()
	{
		if (!isset(static::$default)) {
			static::$default = [
				'test' => 1
			];
		}
		if (!isset(static::$validate)) {
			static::$validate = [
				'test' => 'bool'
			];
		}
	}

	public static function valid($field)
	{
//		static::thread();
		var_dump(static::$default);
		var_dump(static::$validate);

		return static::$validate[$field]??null;
	}
}

$test = new TestThread();
```

Is it possible to somehow change behavior without adding method "thread" (in example)?

I am use PHP 7.0.8 and pthread 3.1.6

**Comment by krakjoe** [comment]
This is fixed in latest sources of pthreads (3.1.7dev)
