### ISSUE TITLE
Using Pthreads with Composer v1.1+ on PHP5.6+

### ISSUE THREAD

**Issue by khelle** [krakjoe/pthreads#621]
Composer 1.1 released on 10th May 2016 changed the way of storing dependencies' classmaps from files containing arrays (autload_classmap, autoload_psr4, autoload_namespaces) to static class (autoload_static) for PHP5.6+. Since Pthreads nullifies static variables it automatically drops all this data making Composer unusable in Threads. Is there a workaround for this, or the only option is to overwrite composer getLoader method to imitate pre-v1.1 behaviour?

**Comment by khelle** [comment]
I have found easier solution in Composer issue pages. If anyone will be reading this in future, here it is described: https://github.com/composer/composer/issues/5482.

@krakjoe I belive this repository https://github.com/krakjoe/pthreads-autoloading-composer should be updated to show this workaround.

**Comment by krakjoe** [comment]
I think this is a thing I broke, temporarily with v3.

I just tested (and fixed, a little) the autoloader example ... everything is working normal with 3.1.7dev, can you confirm ?

**Comment by ultralamer** [comment]
It works for me. Thanks!
