### ISSUE TITLE
Thread::globally in PHP7 is missing

### ISSUE THREAD

**Issue by dekker-m** [krakjoe/pthreads#622]
Environment
==========

  * PHP: PHP 7.0.6RC1 (cli) (built: Apr 14 2016 10:54:04) ( ZTS )
  * pthreads: 3.1.6
  * OS: Windows 10 64-bit, Intel(R) Xeon(R) CPU E3-1535M v5

Summary
======

The `Thread::globally()` method does not exist anymore in v3. However, the change is not documented. The [examples/stub.php](blob/v3.1.6/examples/stub.php) file still includes this method (I use the stub.php for autocompletion).

Will the `globally()` method be implemented again or is it permanently removed? If so, is there a work around which achieve the same? I got some trouble with a log class. The log class should be able to log errors/exceptions/shutdown errors from all the different threads. I'm trying to write to an error file and to the console (if a console is detected). Both of the actual writers are implemented using Zend\Log.

**Comment by krakjoe** [comment]
I just updated the stub.

It was removed permanently.

The documentation is out of date a little, it's a thing I plan to fix.

I'm closing the bug, but that doesn't end the conversation; If you want to show me some code (I'm not familiar with Zend\Log or \Zend) I'll be happy to suggest a better way :)
