### ISSUE TITLE
NULL pointer access in zend_API.c due to being passed NULL class_type

### ISSUE THREAD

**Issue by maximalmin** [krakjoe/pthreads#623]
Attached is a backtrace from gdb showing the issue.  The problem occurred when running pocketmine on Ubuntu 16.04 x64.  Also included is the  "make test" result from pthreads extension.

[php_bug.txt](https://github.com/krakjoe/pthreads/files/479555/php_bug.txt)

**Comment by kam187** [comment]
You can use my fork for now.  Tested and working on pocketmine clear sky 

https://github.com/kam187/pthreads

**Comment by krakjoe** [comment]
Required is a simple reproducing test case, as explained by the template :)
