### ISSUE TITLE
Segmentation fault (core dumped) | PHP7 | defining constants as an array in Thread Context

### ISSUE THREAD

**Issue by 7snovic** [krakjoe/pthreads#624]
Environment
==========

  * PHP: *PHP 7.0.8 (cli) (built: Sep 19 2016 01:41:41) ( ZTS )*
  * pthreads: *Version => 3.1.6*
  * OS: *Ubuntu 16.04*

Summary
======

i don't know where is the problem , is there in pthreads it self or what
when i define constants as an array like this: checkout int [php.net](http://php.net/manual/en/language.constants.syntax.php) Example # 2

> // Works as of PHP 5.6.0
> const ANOTHER_CONST = CONSTANT.'; Goodbye World';
> echo ANOTHER_CONST;
> 
> const ANIMALS = array('dog', 'cat', 'bird');
> echo ANIMALS[1]; // outputs "cat"
> 
> // Works as of PHP 7
> define('ANIMALS', array(
>     'dog',
>     'cat',
>     'bird'
> ));
> echo ANIMALS[1]; // outputs "cat"

when i run my code which contains some constants like this
i got that error
`Segmentation fault (core dumped)`

when i turn my constants to the normal way like:

> define("CONSTANT", "Hello world.");

it's works fine

Reproducing Code
==============
from `SelectiveInheritance.php` Example:

```php
<?php
class my_class {}

function my_function(){
    return __FUNCTION__;
}

define ("MYMYMY", [
    'log' => 'test'
]);
var_dump(MYMYMY);
class Selective extends Thread {
    public function run() {
        /* functions exist where PTHREADS_INHERIT_FUNCTIONS is set */
        var_dump(function_exists("my_function"));
        /* classes exist where PTHREADS_INHERIT_CLASSES is set **BE CAREFUL** */
        var_dump(class_exists("my_class"));
        /* constants exist where PTHREADS_INHERIT_CONSTANTS is set */
        var_dump(defined("my_constant"));
        var_dump(MYMYMY);
    }
}
$test = new Selective();
$test->start();
$test->join();
?>
```
Expected Output
=============

when i run this code from CLI

> array(1) {
>   ["log"]=>
>   string(3) "test"
> }
> bool(false)
> bool(false)
> bool(false)
> array(1) {
>   ["log"]=>
>   string(3) "test"
> }

Actual Output
============

> array(1) {
>   ["log"]=>
>   string(3) "test"
> }
> bool(false)
> bool(false)
> bool(false)
> Segmentation fault (core dumped)

**Comment by 7snovic** [comment]
well , after some tries to fix this out
i figured that when i run my code using php in inter active mode `php -a` it works fine

```bash
root@ubuntu:~# phpts -a
Interactive shell

php > define ("MYMYMY", [
php (     'log' => 'test'
php ( ]);
php > var_dump(MYMYMY);
array(1) {
  ["log"]=>
  string(3) "test"
}
php > class Selective extends Thread {
php {     public function run() {
php {         /* functions exist where PTHREADS_INHERIT_FUNCTIONS is set */
php {         var_dump(function_exists("my_function"));
php {         /* classes exist where PTHREADS_INHERIT_CLASSES is set **BE CAREFUL** */
php {         var_dump(class_exists("my_class"));
php {         /* constants exist where PTHREADS_INHERIT_CONSTANTS is set */
php {         var_dump(defined("my_constant"));
php {         var_dump(MYMYMY);
php {     }
php { }
php > $test = new Selective();
php > $test->start();
bool(false)
bool(false)
bool(false)
php > array(1) {
$test->join();  ["log"]=>
  string(3) "test"
}

php > exit
root@ubuntu:~#
```

the problem is that i want to run my code using exec function or any other alternative
and till now i can't find any way to run my php as interactive shell using exec function

**Comment by krakjoe** [comment]
I am not able to reproduce using 7.0 or 7.1 or 7.2 and the latest dev sources of pthreads; can you try using the latest sources and report back ?

**Comment by 7snovic** [comment]
Excuse me , which sources do you mean ?
pthreads ? or php ?
i already use the latest version of pthread from [https://pecl.php.net/package/pthreads](https://pecl.php.net/package/pthreads)
do you mean that use github repo instead of pecl.php.net ?

Regards :)

**Comment by krakjoe** [comment]
I mean use the latest sources from github, because they contain as yet unreleased changes.

**Comment by 7snovic** [comment]
great
it's now works fine with the latest source from github
the problem was with the pecl.php.net source

thank you :+1:
