### ISSUE TITLE
$db and $this->db are different

### ISSUE THREAD

**Issue by arthuragnar** [krakjoe/pthreads#627]
class Test extends thread {
     function __construct(&$db,$userObj) {  
     $this -> userObj = $userObj;
     print "Original:";
     var_dump($db);
     $this->db = $db;
     print "InThread:";
     var_dump($this->db);      
     // as value of $this->db and db(in constructor) is different I am gettting different values. 
  }
 public function run(){
  $userId = $this->userObj->getUserId();
  $data = $this->db->getData();
 // as value of $this->db and db(in constructor) is different I am getting different values. 
  }

 function getData(&$db,$userObj){
  $thread = new Test($db,$userObj);
  $thread->start();
  }

**Comment by krakjoe** [comment]
That is expected behaviour, please see examples, tests and documentation.

**Comment by arthuragnar** [comment]
What if I want to access the values of $db in run() ?

**Comment by krakjoe** [comment]
This is not the place to ask for coding help, sorry.

**Comment by arthuragnar** [comment]
I have already asked this question on stackoverflow 
[http://stackoverflow.com/questions/39658119/how-to-access-variable-of-threads-constructor-in-run-function](url)
