### ISSUE TITLE
pthreads on PHP7 crashes Apache 2.4 on Linux

### ISSUE THREAD

**Issue by capsandiego** [krakjoe/pthreads#630]
I tried many times to install PHP7 with pthreads with Apache 2.4 on Linux. If pthreads is enabled, Apache won't start (procedure and error below). 
What did I do wrong?
MANY THANKS

---------------------
Linux Ubuntu 14.04
PHP 7.0.11 (cli) (built: Oct 11 2016 10:54:56) ( ZTS ) and Apache 2.4.20
--------------

- 1. downloaded Apache 2.4 from http://httpd.apache.org/download.cgi#apache24
- 2. unzip the httpd-2.4.20.tar.gz file
- 3. downloaded both APR and APR-UTIL from http://apr.apache.org/download.cgi
- 4. unzip the apr into httpd-2.4.20/srclib/apr e apr-util into httpd-2.4.20/srclib/apr-util
- 5. Download PCRE 1 (not 2) from PCRE.org. Compile: sudo ./configure --prefix=/usr/local/pcre
- 6. compile Apache: sudo ./configure --enable-so --with-included-apr --with-pcre=/usr/local/pcre
- 7. compile PHP7: sudo ./configure --prefix=/usr/local/php/7.0.11 --enable-libxml --with-apxs2=/usr/local/apache2/bin/apxs --enable-maintainer-zts 
- 8. After php.ini/httpd.conf changes, Apache works with PHP7 (phpinfo() shows up)
- 9. Add pthreads: sudo pecl install pecl.php.net/pthreads-3.1.6
- 10. If I add extension=pthreads.so the php -m shows the pthreads module but **Apache won't restart anymore**

Apache log:
[Tue Oct 11 11:39:46.601858 2016] [mpm_event:notice] [pid 28629:tid 140462263105344] AH00491: caught SIGTERM, shutting down
[Tue Oct 11 11:39:58.132877 2016] [mpm_event:notice] [pid 28869:tid 140157854152512] AH00489: Apache/2.4.20 (Unix) PHP/7.0.11 configured -- resuming normal operations
[Tue Oct 11 11:39:58.132972 2016] [core:notice] [pid 28869:tid 140157854152512] AH00094: Command line: '/usr/local/apache2/bin/httpd'

**Comment by krakjoe** [comment]
You cannot load pthreads inside apache.

**Comment by smolinari** [comment]
Here is Joe's more in-depth explanation for it not working (as it should): 

> I didn't disable pthreads in web server environments to annoy you; I done it to keep you safe, and will not reverse that decision.
> 
> PHP and Apache do not provide the API required to make it properly safe.
> 
> If I patched Apache and PHP tomorrow to include some additional hooks in an effort to make it properly safe, you would never be able to make it scale.
> 
> Threads are not a utility for an Apache worker mpm server, they are part of the architecture of the software; Coming in and starting additional threads inside that architecture is reckless and destroys the ability of that architecture to scale and operate as it was intended.
> 
> It never made sense to use pthreads inside Apache, I left it working in previous versions in an attempt to lower the entry barrier (everyone is comfortable with a web server). That was a mistake, my mistake; Threading is not simple, when you try to make something inherently complicated simple, you just make it stupid.
> 
> Allowing threads to be started inside Apache without the ability to make either PHP or Apache properly aware of the change in architecture was abusive, and extremely stupid.

Found here in a 5 second google search: https://github.com/krakjoe/pthreads/issues/598

Scott

**Comment by capsandiego** [comment]
Thank you for the explanation! Silly question from my side as I plan to use
your (really fantastic!) pthreads only from CLI
Regards
Sergio
