### ISSUE TITLE
Patching of 2.x with __get __set support?

### ISSUE THREAD

**Issue by adam-rocska** [krakjoe/pthreads#631]
# Environment
- PHP 5.6.12 (cli) (built: Oct 11 2016 10:31:10)  
  Copyright (c) 1997-2015 The PHP Group  
  Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies  
  with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
- pthreads: 2.0.10
- OS:  MacOSX El Capitan 10.11.4
# Summary

Just would like to ask for a patch of [this commit of yours](https://github.com/krakjoe/pthreads/commit/1f69d46f170f3f3a79ae304d6241ea3a6af045b4) on major version 2, so that I can have __get & __set support on php 5.6. 

If I would be competent in C, I would love to submit a pull request. But at the moment I don't even know if there are any technical reasons why it wouldn't work.
# Reproducing Code

Just simply trying to use magic __get and magic __set functions provided by PhalconPHP to make my life way easier.

The value to be retreived. For example, in this case : 

```
$this->outputInfo->writeLine("New execution flow from ...");
```

if outputInfo is not yet set, the DI creates a new service instance, assigns the value && returns it via the magic __get.
# Expected Output

In the provided case outputInfo would always be resolved to an OutputInfo instance.
# Actual Output

I get nulls.

**Comment by adam-rocska** [comment]
Just in case there would be any confusion : I did try the PHP5 branch, with 2.0.11 pthreads version, but that one just causes tons of segfaults locally for basically any basic task.

Also, `make test` fails with 2.0.11 locally (the described environment in this issue).

Any help is appreciated.

**Comment by krakjoe** [comment]
Sorry but, I don't have time to work on PHP 5 stuff any more, the PHP 5 branch should be considered unmaintained.

Please upgrade to PHP 7, if you are still experiencing a problem, open a new report.
