### ISSUE TITLE
Thread dosen't executes methods from other objects async

### ISSUE THREAD

**Issue by Ne00n** [krakjoe/pthreads#633]
Environment
==========

  * PHP: PHP 7.0.12 (cli) (built: Oct 26 2016 19:15:51) ( ZTS )
  * pthreads: 3.1.7dev
  * OS: Jessie 64bit

Summary
======

Thread is not executed asynchronously

Reproducing Code
==============

> class test {
> 
>   public function check() {
>     $fp = fsockopen('10.10.5.55','80', $errno, $errstr, 1.5);
>   }
> 
> }
> 
> class Main extends Thread {
> 
>   public function run() {
>     $N = new test();
>     $N->check();
>   }
> 
> }
> 
> $N = new Main();
> $N->start();

=============

Expected: Should be done instant, since its async
Currently: Waits until the fsockopen request is finished.

Any Idea why it does not the expected stuff?

**Comment by Ne00n** [comment]
?

**Comment by krakjoe** [comment]
There is no bug, this is not the place to ask for help with code.

**Comment by Ne00n** [comment]
@krakjoe Well, then please add a Example for that, using other objects in a async Thread.

It seems like people on Stackoverflow got no idea but upvotes:
http://stackoverflow.com/questions/40378525/php-pthreads-thread-dosent-executes-methods-from-other-objects-async

**Comment by xorinzor** [comment]
@krakjoe gonna agree with Ne00n here, if there were other places to look for documentation / examples that'd be fine.

But everything is out-of-date and there's no clear distinction between versions.

**Comment by BurakDev** [comment]
@Ne00n : The process will end only when all threads finish jobs. But you can do other things/threads when your first thread is pending.
