### ISSUE TITLE
getTerminationInfo()?

### ISSUE THREAD

**Issue by schursin** [krakjoe/pthreads#637]
Removed in V3. Any variants?

**Comment by NicklasWallgren** [comment]
How do we get hold on the thread termination information?

**Comment by tpunt** [comment]
I mentioned this in my [Upgrading from Pthreads v2 to v3](https://www.sitepoint.com/upgrading-pthreads-v2-v3-look/) article. To quote the relevant part:

> The `Threaded::getTerminatedInfo` method was removed due to it being unsafe to serialize exceptions. There are no built-in alternatives, but since PHP 7 has converted the vast majority of fatal errors to exceptions, catch-all exceptions handlers can be used instead:
```php
$task = new class extends Thread {
    public function run()
    {
        try {
            $this->task();
        } catch (Throwable $ex) {
            // handle error here
            var_dump($ex->getMessage());
        }
    }
    private function task()
    {
        $this->data = new Threaded();
        $this->data = new StdClass(); // RuntimeException thrown
        var_dump(1); // never reached
    }
};
$task->start() && $task->join();
```
