### ISSUE TITLE
Destructors for Worker and Threaded called twice

### ISSUE THREAD

**Issue by ultralamer** [krakjoe/pthreads#638]
PHP 7.0.13 (cli) (built: Nov 17 2016 01:09:29) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0RC4, Copyright (c) 2002-2016, by Derick Rethans

pthreads => 3.1.7dev
ubuntu 16.10
```
<?php
class WebWorker extends Worker {

    public function __construct() {
        echo "constructing worker\n";
    }

    public function __destruct() {
        echo "destructing worker\n";
    }
}

class WebWork extends \Threaded implements \Collectable {
    public function run() {

    }

    public function isGarbage() :bool {
        return true;
    }

    public function __destruct() {
        echo "destructing\n";
    }
}

echo "Creating pool...\n";
$pool = new Pool(4, 'WebWorker');

echo "Submitting Work...\n";
for ($i=0;$i<10;$i++) {
    $pool->submit(new WebWork());
}

echo "Collecting from Pool...\n";
$pool->collect(function($work){
    echo "collecting\n";
    return $work->isGarbage();
});

echo "Shutting Down Pool...\n";
$pool->shutdown();

var_dump($pool);

unset($pool);

echo "End of Program...\n";
?>
```

Creating pool...
Submitting Work...
constructing worker
destructing
constructing worker
destructing
constructing worker
constructing worker
destructing
destructing
destructing
destructing
Collecting from Pool...
destructing
collecting
destructing
collecting
destructing
collecting
destructing
collecting
destructing
collecting
destructing
collecting
destructing
collecting
destructing
Shutting Down Pool...
destructing worker
destructing
destructing
destructing
destructing worker
destructing worker
destructing worker
destructing
destructing
destructing worker
destructing worker
destructing worker
destructing worker
destructing

**Comment by krakjoe** [comment]
This is expected, the objects must be constructed in every context that references them.

When you access a ```Threaded``` object inside a ```Thread```, it is distinct from the ```Threaded``` you created in the context that created the ```Thread```.
