### ISSUE TITLE
Crash using APC in a thread

### ISSUE THREAD

**Issue by rinu** [krakjoe/pthreads#639]
Environment
==========

  * PHP: 7.0
  * pthreads: 3.1.6
  * APCu: 5.1.6
  * OS: Windows x64

Summary
======

When using APC in a thread, the script will crash or segfault.
I'm actually reposting this here because the PHP Bug is not getting the right kind of attention: https://bugs.php.net/bug.php?id=67196

Reproducing Code
==============

```
<?php
class MyThread extends Thread {
	public function run() {
		apcu_store("key", "value");
	}
}
$thread = new MyThread();
$thread->start();
```

**Comment by krakjoe** [comment]
Set ```apc.enable_cli=1```.

This is a bug in apcu, not pthreads.

**Comment by krakjoe** [comment]
On closer inspection there is something strange going on.
