### ISSUE TITLE
Pthreads performance drop with big dataset

### ISSUE THREAD

**Issue by capsandiego** [krakjoe/pthreads#640]
*If you know how to write phpt tests, please open a PR with environment information, and your test, this will cause CI to test your issue before a human is able to look*

Environment
==========

  * PHP: 7.0.12
  * pthreads: 3.1.6
  * OS: Linux Ubuntu 14.04 (4.4.0-42) 

Summary
======
When a large array is passed to Threads and used into run() the code runs extremely (thousands of times) slower than with no threads.  
I'm sure this is not a bug, I just can't explain it and thought this could be useful to other users as well. 

Reproducing Code
==============
```
<?php
class Job extends Thread {
    protected $lookup_array;
    public function __construct($lookup_array) {
        $this->lookup_array    = $lookup_array;
    }   
    public function run() {
        // use the lookup array
        for($i=0;$i<10000;$i++){
            $myvalue = $this->lookup_array[$i];
            // do something with the values
        }
    }
}

/* 
 * Create a big lookup array (allocates ~2GB of memory) 
 * that will be used by the threads (only one in this example)
 */
$lookup_array = [];
for($i=0;$i<50000000;$i++){
    $lookup_array[] = rand(1,2000);
}

$start = microtime(true);

$thread = new Job($lookup_array);
$pool[] = $thread;
foreach ($pool as $work) $work->start();
foreach ($pool as $work) $work->join();

$stop = microtime(true);
$time1 = $stop - $start;
echo "\nElapsed Time: ".$time1." secs\n\n";
```

Expected Output
=============

Expected ~0.0002 secs while I get 3,3 secs
Repeating the experiment with no Threads the script is obviously very fast.

**Comment by krakjoe** [comment]
```Threaded``` objects provide safety automatically, and this is not free. When you read a member property a lock must be acquired while it is copied and then released.

**Comment by capsandiego** [comment]
Thanks for the answer, Joe. So, if I well understand, the solution to my
problem (an app that uses lots of lookup tables to operate) would be to
create the big lookup arrays directly in each thread?
Regards, Sergio
