### ISSUE TITLE
PHP is crashing with CakePHP

### ISSUE THREAD

**Issue by fdalex** [krakjoe/pthreads#642]
Environment
==========
Windows Server 2012R2 Standard
apache2.4.18-win64
php7.0.2-win64
php_pthreads-3.1.6-7.0-ts-vc14-x64

Summary
======

Hi !
I'm running a web server and I need to use a command with pthread to speedup a process (ping several machines on a local network). Pthread is working great with cmd, but I'm having issues to add this in my proejct with the framework CakePHP 2.8.0, php is crashing when I call ..\Console\cake.bat with pthread loaded.

Reproducing Code
==============

Very simple test, I'm using the code of Benchmark.php for testing, in the CakePHP project it goes in ..\app\Console\Command\PthreadCakeShell.php (class name is random)

code 

```
<?php
class PthreadCakeShell extends Shell {

    //put your code here

    public function main() {
        $max = @$argv[1] ? $argv[1] : 100;
        $sample = @$argv[2] ? $argv[2] : 5;

        CakeLog::write('collect', "Start($max) ...");
//        printf("Start(%d) ...", $max);
        $it = 0;
        do {
            $s = microtime(true);
            /* begin test */
            $ts = [];
            while (count($ts) < $max) {
                $t = new Thread();
                $t->start();
                $ts[] = $t;
            }
            $ts = [];
            /* end test */

            $ti [] = $max / (microtime(true) - $s);
//            printf(".");
            CakeLog::write('collect', ".");
            
        } while ($it++ < $sample);

        CakeLog::write('collect', " %.3f tps\n", array_sum($ti) / count($ti));
//        printf(" %.3f tps\n", array_sum($ti) / count($ti));
    }
}
```
Expected Output
=============
Result from cmd when using command line, everything is OK
C:\myproject\webroot\app>C:\myproject\bin\php\php7.0.2-win64\php-win.exe -c C:\myproject\bin\
php\php7.0.2-win64\php-cli.ini C:\myproject\thread\pthreads-master\examples\Benchma
rk.php

Start(100) ......... 852.724 tps

Actual Output
============
(note : instead of Console\cake I'm using a custom version to point on php-cli.ini which include pthread)
When using the cakephp command line C:\myproject\webroot\app>Console\cake-thread.bat PthreadCake

Result inside my log file : 
Start(100) ...

CLI POPUP with the following error : 

```
Signature du problème :
  Nom d’événement de problème:	APPCRASH
  Nom de l’application:	php-win.exe
  Version de l’application:	7.0.2.0
  Horodatage de l’application:	568d81a9
  Nom du module par défaut:	php7ts.dll
  Version du module par défaut:	7.0.2.0
  Horodateur du module par défaut:	568d8ca4
  Code de l’exception:	c0000005
  Décalage de l’exception:	000000000003e484
  Version du système:	6.3.9600.2.0.0.272.7
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	c983
  Information supplémentaire n° 2:	c983596f52229134b72a0535057cc900
  Information supplémentaire n° 3:	80e0
  Information supplémentaire n° 4:	80e07e54188b3c913ecbd7e501874a3b

Lire notre déclaration de confidentialité en ligne :
  http://go.microsoft.com/fwlink/?linkid=280262

Si la déclaration de confidentialité en ligne n’est pas disponible, lisez la version hors connexion :
  C:\Windows\system32\fr-FR\erofflps.txt

```

Crash happens on the line $t->start(); If I remove this line the command is not crashing.

**Comment by jippi** [comment]
quote from the readme 

```
pthreads v3 is restricted to operating in CLI only: I have spent many years trying to explain that threads in a web server just don't make sense, after 1,111 commits to pthreads I have realised that, my advice is going unheeded.
```

**Comment by fdalex** [comment]
Sorry for the bad explain, I am using pthread with CLI (php-win.exe). In the framework we can use classes that are used in command line, like batch, it is just to have access to the framework core classes.
The command line used is : C:\myapp\bin\php\php7.0.2-win64\php-win.exe -c C:\myapp\bin\php\php7.0.2-win64\php-cli.ini -q "%lib%cake.php" -working "%CD% " %*

**Comment by krakjoe** [comment]
I need reproducing code, please decouple the problem from cake - with which I am totally unfamiliar, and refuse to become familiar.

**Comment by fdalex** [comment]
Hi, I will do it an other way without the need of the framework. You can close this.
