### ISSUE TITLE
PHP Pthread start() method not working with Slim framework

### ISSUE THREAD

**Issue by somenathdey1** [krakjoe/pthreads#643]
Here is my extended class
```
namespace Service\Component\ThreadWebRequest;
use Thread;
class ThreadWebRequest extends Thread {

    public $url;
    public $headers;
    public $data;

    function __construct($url, $headers) {
      $this->url  = $url;
      $this->headers = $headers;
      //$this->start();
    }

    public function run() {
      $timeout = 0; // set to zero for no timeout
      $ch = curl_init();

      curl_setopt ($ch, CURLOPT_URL, $this->url);
      curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/4.0"); //Optional
      curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE); // Avoid SSL certificate issue
      curl_setopt ($ch, CURLOPT_RETURNTRANSFER, 1);
      curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
      curl_setopt($ch, CURLOPT_HTTPHEADER, $this->headers);
      $file_contents = curl_exec($ch);

      if(curl_errno($ch))
      {
          return 'Curl error: ' . curl_error($ch);
      }
      curl_close($ch);

      $this->data = $file_contents;
    }

}
```
In my controller I have this,
```
$threadRequest = new ThreadWebRequest($value['uri'], $headers);
 $threadRequest->start() && $threadRequest->join();
 $batchResponse = $threadRequest->data;
```
Fatal error : 
I am getting this error. PHP Fatal error: Call to a member function findFile() on a non-object in /opt/services-api/v2/vendor/composer/ClassLoader.php on line 300

If I access thread outside slim it's working fine. Not sure what needs be done to start a thread within slim framework router.

**Comment by DomHudson** [comment]
I'm not a pthreads dev nor do I have experience of Slim, but my guess is that line 300 of ClassLoader.php is a reference to the instance of the framework? If so you will get issues. You need to treat your threaded application like a package that can run outside of the context of your framework.

**Comment by somenathdey1** [comment]
I am closing this issue as it's not relevant to Pthread. I am posting this issue to Slim team.
