### ISSUE TITLE
Pool->submit stuck / hanging

### ISSUE THREAD

**Issue by xorinzor** [krakjoe/pthreads#647]
Pool->submit stuck / hanging on PHP7.2.0-dev with pthreads

Please see the question over at stackoverflow: https://stackoverflow.com/questions/41188606/pthreads-hangs-stuck-on-pool-submit

I can't find any up-to-date documentation or examples.

**Comment by NicklasWallgren** [comment]
@xorinzor Still an issue or did you solve the problem?

**Comment by xorinzor** [comment]
@NicklasWallgren the original "hanging" issue got solved on stackoverflow.

Still running into the problem that PHP doesn't seem to log or show errors that are happening within the started threads though :/ not sure if other people have the same issue.

Basically, whether I'm creating a new instance of a class, or calling a static function of a class (either within the new thread); Both will prevent the thread from working but I don't see any errors in the console.
