### ISSUE TITLE
Where is Worker::isWorking()

### ISSUE THREAD

**Issue by aodzip** [krakjoe/pthreads#648]
Environment
==========

PHP 7.0.13 (cli) (built: Nov 19 2016 20:24:00) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13, Copyright (c) 1999-2016, by Zend Technologies

pthreads 3.1.6

Ubuntu 16.04 x64

Summary
======

\Worker lost isWorking() method

Reproducing Code
==============

http://php.net/manual/zh/worker.isworking.php
`<?php
$my = new Worker();
$my->start();
/* ... */
if ($my->isWorking()) {
    /* ... the Worker is busy executing another object */
}
`

Expected Output
=============

exit as 0

Actual Output
============

Fatal error: Uncaught Error: Call to undefined method Worker::isWorking() in /home/aodzip/test.php:5

**Comment by tpunt** [comment]
The `Worker::isWorking()` method has been removed in pthreads v3. I've made a note of this on its docs page. Much of pthreads' documentation still targets v2, so if an example doesn't work, just assume that the docs are at fault (i.e. outdated), than the extension itself.

**Comment by aodzip** [comment]
Okay, I know.
Then how to judge if a worker is doing some work when I use Pool and submit some work?
I need a way to judge if the pool is full or emoty and I can resize it.

**Comment by viviengaetan** [comment]
@aodzip According to php.net english documentation ([link](http://php.net/manual/en/worker.isworking.php)) you should use [`Worker::getStacked`](http://php.net/manual/zh/worker.getstacked.php) to "see if the worker still has tasks to execute"

**Comment by tpunt** [comment]
This has been documented. See #709 for more docs-related problems.

**Comment by ekr3peeK** [comment]
The two function are not interchangeable. `Worker::getStacked` is not a viable alternative to `Worker::isWorking`, as according to my tests, as soon as a worker starts working on a job, it removes it from it's stack. Thus, by using `Worker::getStacked` we must assign at least 2 jobs for each worker to execute in a cycle, and if those 2 jobs are the most timeconsuming ones in the bunch, the time it would require to finish all the jobs would be higher.

Is there any possibility that you will reintroduce `Worker::isWorking` in the future?
