### ISSUE TITLE
issues with Symfony debug

### ISSUE THREAD

**Issue by xorinzor** [krakjoe/pthreads#649]
Environment
==========

  * PHP: 7.2-dev
  * pthreads: 3.1.7dev
  * OS: Debian 8
  * Symfony: 3.0.0

Summary
======

This is the full stacktrace that's returned, [reported it at symfony](https://github.com/symfony/symfony/issues/21048) first but they couldn't seem to find an issue in their code.

```
Fatal error: Uncaught Error: Cannot access private property Symfony\Component\Debug\ErrorHandler::$reservedMemory in <snip>/public/app/vendor/symfony/debug/ErrorHandler.php on line 559

Error: Cannot access private property Symfony\Component\Debug\ErrorHandler::$reservedMemory in <snip>/public/app/vendor/symfony/debug/ErrorHandler.php on line 559

Call Stack:
    0.2689    7668344   1. Symfony\Component\Debug\ErrorHandler::handleFatalError() <snip>/public/app/vendor/symfony/debug/ErrorHandler.php:0

Segmentation fault
```

Reproducing Code
==============

I'm afraid I cannot include code for this as this is not a public project, it is a extension however for Pagekit, ran via CLI. I'm guessing any code using the Symfony Debug component would run into the same issue as it's using the same error handler that's registered.

I do have xdebug installed, if I can do anything else to help debug this that's not a problem.

Expected Output
=============

Either an actual error or nothing at all, since without using the thread wrappers etc, the code runs fine.

Actual Output
============

See above.

**Comment by theofidry** [comment]
@xorinzor maybe you could try on a fresh Symfony SE install?
