### ISSUE TITLE
Global variables not accessible within classes extending Thread

### ISSUE THREAD

**Issue by beetree** [krakjoe/pthreads#651]
Environment
==========

See: https://github.com/krakjoe/pthreads/issues/650

Summary
======

If you try to access a global variable using `global $variable;` the value doesn't come through within a class extending `Thread`.

Reproducing Code
==============

I can provide this if necessary, but I'm assuming this is a known limitation. I just want to reconfirm this.

**Comment by krakjoe** [comment]
Expected behaviour.

**Comment by alencarandre** [comment]
Ok, but, how I souve that, its possible? I'm using legacy system and I need to use global variables inside threads. Please, help
