### ISSUE TITLE
Snmp requests with pthread won't end if thread > 1

### ISSUE THREAD

**Issue by fdalex** [krakjoe/pthreads#652]
Environment
==========
Windows Server 2012R2 Standard
apache2.4.18-win64
php7.0.2-win64
php_pthreads-3.1.6-7.0-ts-vc14-x64

Summary
======

Hi !
I'm having issues with pthread and Snmp requests (requests to collect data on our network printers), I'm not sure if the problem is in pthread or if i'm doing something wrong but the code won't shutdown if i set more than 1 thread (but sometimes it works, like 10% of the time ... could it be because of the snmp session not closing ?). I used a simple usage of Pool to do this. I also used others methods (pool with a $pool->collect(...), or from stackable examples, it always get stucked).

Reproducing Code
==============

```
<?php

class SnmpWork extends Threaded {

    public $ip;
    public $oids;

    public function __construct($ip, $oids) {
        $this->ip = $ip;
        $this->oids = $oids;
    }

    public function snmpRequest() {
        $community = 'public';
        $timeout = 300000; // microsecondes
        $retry = 3;
        $snmpSession = new SNMP(SNMP::VERSION_1, $this->ip, $community, $timeout, $retry);

        foreach ($this->oids as $oid) {
            $snmpGetResult['oids'][$oid] = @$snmpSession->get($oid, true);
            $snmpGetResult['errno'] = $snmpSession->getErrno();
            $snmpGetResult['error'] = $snmpSession->getError();
        }
        
        $snmpSession->close();

        return $snmpGetResult;
    }

    public function run() {
        $taskStart = microtime(true);

        $snmpGetResult = $this->snmpRequest();

        $taskEnd = microtime(true);
        $snmpGetResult['latency'] = $taskEnd - $taskStart;
        echo json_encode($snmpGetResult) . "\n";
    }

}

class SnmpWorker extends Worker {

    public function run() {
        
    }

}

// start
$machines = [
    [
        'ip' => '192.168.0.2',
        'oids' => ['.1.3.6.1.4.1.253.8.53.3.2.1.3.1', '.1.3.6.1.2.1.2.2.1.6.1', '.1.3.6.1.2.1.1.6.0']
    ],
    [
        'ip' => '192.168.0.3',
        'oids' => ['.1.3.6.1.2.1.43.5.1.1.17.1', '.1.3.6.1.2.1.2.2.1.6.2', '.1.3.6.1.2.1.1.6.0']
    ],
    [
        'ip' => '192.168.0.4',
        'oids' => ['.1.3.6.1.4.1.253.8.53.3.2.1.3.1', '.1.3.6.1.2.1.2.2.1.6.1', '.1.3.6.1.2.1.1.6.0']
    ],
    [
        'ip' => '192.168.0.5',
        'oids' => ['.1.3.6.1.4.1.253.8.53.3.2.1.3.1', '.1.3.6.1.2.1.2.2.1.6.1', '.1.3.6.1.2.1.1.6.0']
    ],
    [
        'ip' => '192.168.0.6',
        'oids' => ['.1.3.6.1.4.1.253.8.53.3.2.1.3.1', '.1.3.6.1.2.1.2.2.1.6.1', '.1.3.6.1.2.1.1.6.0']
    ]
];

$nbThread = 1; // **if nbThread = 1 everything is ok, if > 1 then the code won't stop**

$pool = new Pool($nbThread, SnmpWorker::class);
$i = 0;
$nbMachine = count($machines);
while ($i < $nbMachine) {
    $pool->submit(new SnmpWork($machines[$i]['ip'], $machines[$i]['oids']));
    $i++;
}
$pool->shutdown();
```

Expected Output
=============

Using this code : 
```
$command = $phpPath . DS . 'php-win.exe' .
                    ' -c ' . $phpPath . DS . 'php-cli.ini' . ' ' .
                    VENDORS . 'pthread' . DS . 'ThreadTest.php';

exec($command, $output, $returnVar);

echo json_encode($output);
```

Correct result if 1 thread : 5 json lines
```
{"oids":{".1.3.6.1.4.1.253.8.53.3.2.1.3.1":false,".1.3.6.1.2.1.2.2.1.6.1":false,".1.3.6.1.2.1.1.6.0":false},"errno":4,"error":"No response from 192.168.0.2","latency":3.7524521350861}
{"oids":{".1.3.6.1.2.1.43.5.1.1.17.1":"STRING: \"xxx\"",".1.3.6.1.2.1.2.2.1.6.2":"STRING: 00:11:22:33:44:55",".1.3.6.1.2.1.1.6.0":"STRING: "},"errno":0,"error":"","latency":0.31486392021179}
{"oids":{".1.3.6.1.4.1.253.8.53.3.2.1.3.1":"STRING: \"yyy\"",".1.3.6.1.2.1.2.2.1.6.1":"STRING: 01:02:03:04:05:06",".1.3.6.1.2.1.1.6.0":"STRING: There"},"errno":0,"error":"","latency":0.23863887786865}
{"oids":{".1.3.6.1.4.1.253.8.53.3.2.1.3.1":"STRING: \"zzz\"",".1.3.6.1.2.1.2.2.1.6.1":"STRING: aa:bb:cc:dd:ee:ff",".1.3.6.1.2.1.1.6.0":"STRING: Here"},"errno":0,"error":"","latency":0.25181007385254}
{"oids":".1.3.6.1.4.1.253.8.53.3.2.1.3.1":false,".1.3.6.1.2.1.2.2.1.6.1":false,".1.3.6.1.2.1.1.6.0":false},"errno":4,"error":"No response from 192.168.0.6","latency":3.7536361217499}
```

Please include the expected output, properly formatted.

Actual Output
============

If i set more than 1 thread ($nbThread = 2 or more) :

```
{"oids":{".1.3.6.1.4.1.253.8.53.3.2.1.3.1":false,".1.3.6.1.2.1.2.2.1.6.1":false,".1.3.6.1.2.1.1.6.0":false},"errno":4,"error":"No response from 192.168.0.2","latency":3.7514688968658}
{"oids":{".1.3.6.1.4.1.253.8.53.3.2.1.3.1":"STRING: \"zzz\"",".1.3.6.1.2.1.2.2.1.6.1":"STRING: aa:bb:cc:dd:ee:ff",".1.3.6.1.2.1.1.6.0":"Here"},"errno":0,"error":"","latency":0.21297001838684}
{"oids":{".1.3.6.1.4.1.253.8.53.3.2.1.3.1":false,".1.3.6.1.2.1.2.2.1.6.1":false,".1.3.6.1.2.1.1.6.0":false},"errno":4,"error":"No response from 192.168.0.6","latency":3.7585380077362}
```

Result is a little random, sometimes i get more or less lines but the script won't end, I have to ctrl+C or kill php CLI.

Thanks for the help

Edit : 

If I set only IPs that are not responding, I get the following error (php crashes)

Signature du problème :
  Nom d’événement de problème:	APPCRASH
  Nom de l’application:	php-win.exe
  Version de l’application:	7.0.2.0
  Horodatage de l’application:	568d81a9
  Nom du module par défaut:	php_snmp.dll
  Version du module par défaut:	7.0.2.0
  Horodateur du module par défaut:	568d87da
  Code de l’exception:	c0000005
  Décalage de l’exception:	000000000001b252
  Version du système:	6.3.9600.2.0.0.272.7
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	28c9
  Information supplémentaire n° 2:	28c9a026d0f40e7983a53e8c666a2246
  Information supplémentaire n° 3:	472e
  Information supplémentaire n° 4:	472eef5c4fa75a9a0376ffb990896aa4

Lire notre déclaration de confidentialité en ligne :
  http://go.microsoft.com/fwlink/?linkid=280262

Si la déclaration de confidentialité en ligne n’est pas disponible, lisez la version hors connexion :
  C:\Windows\system32\fr-FR\erofflps.txt

**Comment by paulobezerr** [comment]
I have problem like yours with some little differences:
- I am creating thread SOAP requests
- The instance is shared by the worker
- The main process terminates.

But the results does not come with a random behavior.

Probably the requests are done successfully as happen to me.
I turn on wireshark in my machine, the packets are transmitted and received with success, but no result to collector.

I think there could be a problem with collector.

**Comment by krakjoe** [comment]
@paulobezerr please open new issues, do not post on the end of another persons thread.

@fdalex you need to reduce this to simplest possible test case, I don't have a network of printers or any such hardware to test with.

**Comment by fdalex** [comment]
Hi and thanks for your reply. I think i can make a simplier code if i request only 1 oid on the same machine but several times, it will probably be blocked too. I'll do that tomorrow when at work ;)
About the crash case I'll try to make something similar too.

**Comment by fdalex** [comment]
HI again, I tried to simply as much as I could the code, only one machine with one oid but called 7 times :
```
<?php

class TSimpleSnmp extends Thread {

    private $machine;

    public function __construct($machine) {
        $this->machine = $machine;
        $this->start();
    }

    public function __destruct() {
        echo "destructed ...\n";
    }

    public function snmpRequest() {
        $community = 'public';
        $timeout = 300000; // microsecondes
        $retry = 3;
        $snmpSession = new SNMP(SNMP::VERSION_1, $this->machine['ip'], $community, $timeout, $retry);

        foreach ($this->machine['oids'] as $oid) {
            $snmpGetResult['oids'][$oid] = @$snmpSession->get($oid, true);
            $snmpGetResult['errno'] = $snmpSession->getErrno();
            $snmpGetResult['error'] = $snmpSession->getError();
        }

        $snmpSession->close();

        return $snmpGetResult;
    }

    public function run() {
        echo json_encode($this->snmpRequest()) . "\n";
    }

}

$machines = [
    [
        'ip' => '10.1.3.3',
        'oids' => ['.1.3.6.1.2.1.2.2.1.6.1']
    ],
    [
        'ip' => '10.1.3.3',
        'oids' => ['.1.3.6.1.2.1.2.2.1.6.1']
    ],
    [
        'ip' => '10.1.3.3',
        'oids' => ['.1.3.6.1.2.1.2.2.1.6.1']
    ],
    [
        'ip' => '10.1.3.3',
        'oids' => ['.1.3.6.1.2.1.2.2.1.6.1']
    ],
    [
        'ip' => '10.1.3.3',
        'oids' => ['.1.3.6.1.2.1.2.2.1.6.1']
    ],
    [
        'ip' => '10.1.3.3',
        'oids' => ['.1.3.6.1.2.1.2.2.1.6.1']
    ],
    [
        'ip' => '10.1.3.3',
        'oids' => ['.1.3.6.1.2.1.2.2.1.6.1']
    ]
];

$ts = array();
$i = 0;
while ($i < count($machines)) {
    $ts[] = new TSimpleSnmp($machines[$i]);
    $i++;
    echo "thread $i\n";
}
/* we want all threads to complete */
foreach ($ts as $t) {
    echo "foreach ts\n";
    $t->join();
}
echo "end ...";
?>
```

The result from exec() in my php script : (need to kill CLI to get the result on the web page or it never stop charging)

array(
	(int) 0 => 'thread 1',
	(int) 1 => 'thread 2',
	(int) 2 => 'thread 3',
	(int) 3 => 'thread 4',
	(int) 4 => 'thread 5',
	(int) 5 => 'thread 6',
	(int) 6 => 'thread 7',
	(int) 7 => 'foreach ts',
	(int) 8 => '{"oids":{".1.3.6.1.2.1.2.2.1.6.1":"STRING: 0:0:aa:63:1b:bb"},"errno":0,"error":""}',
	(int) 9 => 'destructed ...'
)

Looks like it get stucked on $t->join(); ...

**Comment by krakjoe** [comment]
I never got the reproducing code I asked for ... if this is still a problem, please provide code that doesn't require specific hardware, reduce to simplest possible form.
