### ISSUE TITLE
The apache2handler SAPI is not supported by pthreads in Unknown on line 0

### ISSUE THREAD

**Issue by ismail0234** [krakjoe/pthreads#655]
hi php 7.0 And wampserver using.

Thread Safety	: enabled
Php.ini : extension=php_pthreads.dll
Ext folder : php_pthreads-3.1.6-7.0-ts-vc14-x64.zip

Pthreads error : 

The apache2handler SAPI is not supported by pthreads in Unknown on line 0

Can you help me ?

**Comment by krakjoe** [comment]
No, that's expected, see readme.

**Comment by My1** [comment]
@krakjoe 
but why is it not safe to use on webservers and the like?
I mean if you make sure that the threads end themselves before doing out of thread stuff, I dont see that problem.

for example when the server should do some fairly large calculations for some reason or another I could load a half-finished loading page which kicks open the threads and as soon as all of the threads close I could continue by displaying the result and ending the page properly.
