### ISSUE TITLE
Memory Leak Socket with pThread

### ISSUE THREAD

**Issue by guillaume-lecoz** [krakjoe/pthreads#656]
Hi,

I'm currently working on a push server implementation in PHP to manage millions of client socket, it's working well and I have good performance but I have a memory leak.

I simplified my code step by step to isolate the memory leak and I have the memory leak when a socket is created from a thread and sent to another Thread. To reproduce not even need to start the thread, The simple fact of putting a socket resource into a member variable of thread class create a memory leak.

Environment
==========

  * PHP: 7.0.14
  * pthreads: 3.1.6

Reproducing Code
==============

	class TestThread extends Thread //If I remove extends Threads, I don't have leak
	{
		private $mSocket = null;

		public function __construct($socket)
		{
			$this->mSocket = $socket;
		}
	}

	$loop = 0;
	while (true)
	{
		$socket = @socket_create(AF_INET, SOCK_STREAM, SOL_TCP); //We can reproduce same leak with an accepted socket 
		$test = new TestThread($socket); //REPRODUCE Leak with and without start thread
		
		socket_close($socket);
				
		if ($loop % 10000 == 0)
			echo "Memory Usage: 	".memory_get_usage()."\n";

		$loop++;
	}

Expected Output
=============
Memory Usage:   365.93 KB
Memory Usage:   365.96 KB
Memory Usage:   365.96 KB
Memory Usage:   365.96 KB
Memory Usage:   365.96 KB
Memory Usage:   365.96 KB
.....

Actual Output
============

Memory Usage:   367.07 KB
Memory Usage:   1.69 MB
Memory Usage:   3.25 MB
Memory Usage:   6.19 MB
Memory Usage:   6.88 MB
Memory Usage:   11.56 MB
....

**Comment by krakjoe** [comment]
Sorry, resources are officially unsupported ...

However, pthreads has an unreleased `Socket` class of it's own now, use sources from git ;)

**Comment by guillaume-lecoz** [comment]
Thanks for your quick response, 
I had seen this class on git source but it was not accessible. I had downloaded pthreads on the site pecl, I will try with a custum pthreads build.
Is there a reason why this class is not released and Do you think this Socket class can solve my problem?

**Comment by krakjoe** [comment]
I'm just stretched very thin ... and suspicious that no bugs have been reported with it yet ...

It should solve the problem, yes.

**Comment by guillaume-lecoz** [comment]
Thanks, I will try with this class, do you have a sample code for this class?
