### ISSUE TITLE
Windows dlls are outdated [module API doesn't match]

### ISSUE THREAD

**Issue by wapmorgan** [krakjoe/pthreads#660]
Environment
==========

  * PHP: 7.1.0 (cli) (built: Dec  2 2016 05:24:57) ( ZTS MSVC14 (Visual C++ 2015) x64 )
  * pthreads: 3.1.6
  * OS: Windows 10 x64

Summary
======

Last built dlls dont work. I downloaded 3.1.6, unpacked, changed php.ini and run `php -m`.

Expected Output
=============

`php -m` should print all modules including `pthreads`.

Actual Output
============

```
PHP Warning:  PHP Startup: pthreads: Unable to initialize module
Module compiled with module API=20151012
PHP    compiled with module API=20160303
These options need to match
 in Unknown on line 0
```

**Comment by quantuumsnot** [comment]
Same here, reverting to 7.0.x

**Comment by SirSnyder** [comment]
This topic has already been mentioned in #646

**Comment by krakjoe** [comment]
There are no dlls for 7.1 yet: you should not expect 7.0 dlls to work with 7.1.

**Comment by My1** [comment]
well then it MAYBE should be stated somewhere that it's only for 7.0 because the requirements say "PHP7+" which obviously means 7 or higher.
and if that only affects windows then write it somewhere in there. in the readme from the windows ZIP I got from windows.php.net it states "pthreads v3 requires PHP7 or above" so well...

**Comment by SirSnyder** [comment]
Try https://github.com/SirSnyder/pthreads/releases/tag/v3.1.7-beta.1

**Comment by PSF1** [comment]
With the suggestion of SirSnyder it's working, thanks ...

PHP 7.1.4 (cli) (built: Apr 11 2017 19:54:37) ( ZTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
