### ISSUE TITLE
Zend_mm_heap corrupted

### ISSUE THREAD

**Issue by quantuumsnot** [krakjoe/pthreads#664]
Environment
==========
  * PHP 7.0.9-TS-VC14-x64 (cli) (built: Jul 20 2016 10:47:51) ( ZTS )
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
  * pthreads: php_pthreads-3.1.6-7.0-ts-vc14-x64
  * OS:  Windows 7 x64

Summary
======
Testing weighttp.exe against \examples\SocketServer.php
Only changed listening port from 13000 to 80
opcache IS disabled

Reproducing Code
==============
1. Started with "php SocketServer.php"
2. Started testing with weighttp.exe -n 100 -t 1 -c 1 http://127.0.0.1:80/

Expected Output
=============
For example:
Finished in 0 sec, 221 millisec and 0 microsec, 452 req/s, 387 kbyte/s.
Requests: 100 total, 100 started, 100 done, 100 succeeded, 0 failed, 0 errored.

Actual Output
============
zend_mm_heap corrupted

Tried to change socket_read to be ($client, 4096, PHP_BINARY_READ) but got the same message
Same happens and when tried to open 127.0.0.1 in the browser - socket server stops and drops this message

**Comment by krakjoe** [comment]
Sorry, resources are unsupported.

Perhaps checkout `Socket` which is available in repo, as yet unreleased ...

**Comment by quantuumsnot** [comment]
Could you explain what means 'resources are unsupported'? Thanks in advance

**Comment by krakjoe** [comment]
All resources are written to be used in a non-threaded environment, and unlike objects that have an internal API that allows pthreads to make them (`Threaded` objects) safe, resources cannot be made safe.

It "works" because earlier versions of pthreads forced it to work, and I haven't removed that functionality, for the case where someone writes an extension that does (somehow) allow their particular resource type to be used in multiple threads, or for the case where a particular resource type may be made safe in userland using synchronization built into pthreads (I don't know of any such resource type today).

The built-in resource types, like streams, will never be safe, and so I've started to work on `Socket` and plan others (`File` and such) also.

**Comment by quantuumsnot** [comment]
So, the example from pthreads repo works only on paper, and we cannot do anything to rly work?
Can you at least add some code to 'SocketServer.php' to see how is the proper way of destroying each 'Client' object which is not running?

**Comment by krakjoe** [comment]
`
/*
* @NOTE
*	RESOURCES ARE BEING TRIED OUT, THIS MAY CRASH OR KILL THE EXECUTOR OF THE SCRIPT: NOT MY FAULT
*
*	It's pretty clear that people want resources to work, and I cannot deny it would be useful.
*	Officially, resources are unsupported, if it doesn't work there is NOTHING I can do about it.
*	I do NOT have the time to make every kind of resource safe, or ensure compatibility.
*	I can apply some cleverness to make sure resources are destroyed by whoever creates them, that is ALL.
*	In the case of sockets, this appears to work, the code below ran all day on pthreads.org without interruption.
*	AGAIN: 	If this does not work, there is NOTHING more I can do. 
			If a particular type of resource wigs out, there is NOTHING I can do.
			If this kills you, horribly, there is NOTHING I can do.
*/
`

Perhaps read the examples before you execute them ;)

**Comment by quantuumsnot** [comment]
imho I think the problem is that pthreads relies on zend_mm. Looking in pthreads.h you are using Zend memory manager which has a good history of trying to free something in memory that is already freed. Do you think if there is a workaround?

**Comment by krakjoe** [comment]
> imho I think the problem is that pthreads relies on zend_mm. Looking in pthreads.h you are using Zend memory manager which has a good history of trying to free something in memory that is already freed

I don't know what you are talking about.

Disabling zend mm will not help, at all. It's nothing whatever to do with the allocator being used.

The reasons have already been explained.
