### ISSUE TITLE
Maybe a memory is not freed?

### ISSUE THREAD

**Issue by quantuumsnot** [krakjoe/pthreads#667]
Environment
==========
  * PHP 7.0.9-TS-VC14-x64 (cli) (built: Jul 20 2016 10:47:51) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
  * php_pthreads-3.1.6-7.0-ts-vc14-x64
  * OS: Windows 7 x64

Summary
======
I don't know

Reproducing Code
==============
somescript.php
`<?php

set_time_limit(0);

class Test extends Thread {
	public function __construct($socket){
		$this->socket = $socket;
    $this->start(PTHREADS_INHERIT_FUNCTIONS);
	}
	
	public function run(){
    $client = socket_accept($this->socket);
    if ($client !== false) { 
      $input = socket_recv($client, $buff, 4096, 0);
      if ($input !== false && socket_last_error($client) != 104) { 
        $incoming = array();
         $incoming = explode("\r\n", $buff);

        $fetchArray = array();
        $fetchArray = explode(" ", $incoming[0]);

        $file = $fetchArray[1];
        if($file == "/") { 
          $file = "index.html";
        } else {
          $filearray = array();
          $filearray = explode("/", $file);
          $file = $filearray[1];
        }

        $output = "";
        $header = "HTTP/1.1 200 OK \r\n" . gmdate("D, d M Y H:i:s T") . "\r\n" . "Content-Type: text/html; charset=utf-8 \r\n\r\n";
        $content = file_get_contents($file);
        $output = $header . $content;

        socket_write($client, $output, strlen($output));
        socket_shutdown($client, 2);
        socket_close($client);
      } else $this->join();
    } else $this->join();
	}
}

$ipaddress = "127.0.0.1";
$port = 80;
$sock = socket_create(AF_INET, SOCK_STREAM, 0);
socket_set_option($sock, SOL_SOCKET, SO_REUSEADDR, 1);
socket_bind($sock, $ipaddress, $port);
socket_listen($sock, 0);
$workers = array();
while (true) {
  $clientPool = array($sock);
  $connections = socket_select($clientPool, $write, $except, 0, 16000);
  if ($connections !== false && $connections > 0) {
    $workers[] = new Test($clientPool[0]);
    array_pop($workers); //no more handles leak (we'll speak for that later), only memory is not freed
  }
}

socket_shutdown($sock, 2);
socket_close($sock);
exit();

?>`

1. Started with "php somescript.php"
2. Started testing with weighttp.exe -n 100 -t 1 -c 1 http://127.0.0.1:80/

Expected Output
=============
Same code but without using pthreads in task Manager Memory (Private Working Set) shows ~7MB used while with pthreads after each test the usage grows

Actual Output
============
I don't know

**Comment by krakjoe** [comment]
Sorry, resources are unsupported.
