### ISSUE TITLE
make dll file for php 7.1

### ISSUE THREAD

**Issue by molchanov1983** [krakjoe/pthreads#672]
Hello everybody
I donot know how to make dll (windows 7) file for php 7.1
Or maybe anybody knows where i could download it

Thanks

**Comment by Jerry-Shaw** [comment]
Is there binaries for windows on PECL? I could try to compile it after I get back home days later.

**Comment by molchanov1983** [comment]
https://github.com/krakjoe/pthreads/issues/646 (php 7.1 support issue) Please look at this issue.

**Comment by molchanov1983** [comment]
Maybe anybody could say me what application i should use for making dll?

**Comment by jens1o** [comment]
I would like to have it too. How can I build it myself?

**Comment by Jerry-Shaw** [comment]
I tried, but without luck on PHP 7.1.1. Lots of files are missing somehow. But it could be compiled successfully under PHP 7.0.

**Comment by molchanov1983** [comment]
Thanks Jerry-Shaw for your help

**Comment by Jerry-Shaw** [comment]
I'll try it again when I have time. The deps of php7.1 changed a little maybe.

**Comment by SirSnyder** [comment]
You could try the experimental sdk https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2. Maybe that works.

**Comment by SirSnyder** [comment]
Please try https://github.com/SirSnyder/pthreads/releases/tag/v3.1.7-beta.1

**Comment by Jerry-Shaw** [comment]
Thanks, I'll try it when I have time, too busy those days.

**Comment by molchanov1983** [comment]
http://prntscr.com/ejw8ei
It does not work for windows 7 for php 7.1.2 VC14 x64 Thread Safe (2017-Feb-14 23:28:27)

PHP Warning: PHP Startup: Unable to load dynamic library 'C:\Program Files\Nectus\Web\php-7.1.2\ext\php_pthreads.dll' - The specified module could not be found.

**Comment by molchanov1983** [comment]
Also i tried PHP Version 7.1.0alpha3 and the same result 
php[22972]
PHP Warning: PHP Startup: Unable to load dynamic library 'C:\Program Files\Nectus\Web\php-7.1.0\ext\php_pthreads.dll' - The specified procedure could not be found.

**Comment by Gemorroj** [comment]
@molchanov1983, denver? lol =)

**Comment by SirSnyder** [comment]
@molchanov1983 the path to the dll must be wrong or the dll is missing. I've just tested PHP 7.1.2 (cli) (built: Feb 14 2017 21:24:49) ( ZTS MSVC14 (Visual C++ 2015) x64 ) on win 7 and 10, no problems.

**Comment by molchanov1983** [comment]
Thanks 
Everything works using 
php.exe - f file through console
Is it possible to use php_threads as apache mode. I put pthreadVC2.dll to apache/bin and got this error message
php[24728]
PHP Fatal error: Unable to start pthreads module ("...\Apache24\bin\httpd.exe" -k runservice)

Thanks again

**Comment by cmyker** [comment]
From README.md

> SAPI Support

pthreads v3 is restricted to operating in CLI only: I have spent many years trying to explain that threads in a web server just don't make sense, after 1,111 commits to pthreads I have realised that, my advice is going unheeded.

So I'm promoting the advice to hard and fast fact: you can't use pthreads safely and sensibly anywhere but CLI.

**Comment by matt-o-matic** [comment]
Is there a link to a pre-compiled pthreads module for windows and PHP 7.1.x?  Preferably 64bit and using VC14?

**Comment by SirSnyder** [comment]
@matt-o-matic https://github.com/SirSnyder/pthreads/releases/tag/v3.1.7-beta.1

**Comment by Jan-E** [comment]
@SirSnyder Is there any update on https://github.com/SirSnyder/pthreads/issues/1 ?

**Comment by matt-o-matic** [comment]
@SirSnyder - that is awesome, thank you so much... not to be too picky... but is there a production-ready version of this out there? (ie, not beta?)  I've been reading around and it looks like 3.1.6 isn't even compatible with PHP 7.1 on any platform??

**Comment by tpunt** [comment]
@matt-o-matic The master branch of pthreads is the only compatible branch with PHP 7.1 and 7.2 so far. There are no official releases yet that support these versions of PHP due to ongoing work on socket handling in the master branch. Until that is completed (or separated out to another branch), stable releases will not be made.

**Comment by matt-o-matic** [comment]
Totally understand... is there someplace that I can give some money to maybe speed up the development and release of 3.1.7?

**Comment by Hanmac** [comment]
need a build for 7.1.2 on 32bit for windows

**Comment by krakjoe** [comment]
The next release of pthreads will not support 7.0 or 7.1, sorry about that ...

**Comment by jens1o** [comment]
@krakjoe Are there any reasons not to provide that support?

**Comment by krakjoe** [comment]
Yes, ZTS in 7.0 and 7.1 is broken.

**Comment by Jan-E** [comment]
I asked a question about this on internals. Is it a painful subject because nobody responds?

**Comment by krakjoe** [comment]
The problem is the fix - which is a considerable patch to strings and TSRM - contains ABI breaks that would effect NTS builds; Since the vast majority use NTS we cannot justify breaking their ABI for the sake of the tiny minority that use ZTS.

**Comment by Jan-E** [comment]
I saw the huge commit that fixed it fot PHP7.2, so I can imagine you do not wanna backport it. But if ZTS is really broken, it should be actively discouraged. With every PHP 7.1 release new ZTS binaries are put online at https://windows.php.net ....

**Comment by chinmay235** [comment]
My PHP version 7.1.11
I have used 3.1.6. x86 dll files. After restarting my xampp I got this error message:

Warning: PHP Startup: pthreads: Unable to initialize module
Module compiled with module API=20151012
PHP    compiled with module API=20160303
These options need to match
 in Unknown on line 0

Please suggest me.
