### ISSUE TITLE
memory_limit applies per thread and not to the whole php process

### ISSUE THREAD

**Issue by dktapps** [krakjoe/pthreads#678]
*If you know how to write phpt tests, please open a PR with environment information, and your test, this will cause CI to test your issue before a human is able to look*

Environment
==========

  * PHP 7.0.15 (cli) (built: Jan 17 2017 13:46:07) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
  * pthreads: 3.1.6
  * OS: Windows 10 x64 (Intel)

Summary
======
`memory_limit` set in php.ini or by `ini_set()` appears to apply per _thread_ instead of to the whole php process. This behaviour is unexpected to me. Is this intended behaviour? I couldn't find documentation on this anywhere.

This behaviour is a little bit undesirable, since I don't expect each thread to be allowed 512M, but the whole _process_ to be allowed 512M.

Reproducing Code
==============
```
<?php

ini_set("memory_limit", "512M");

class spam extends Thread{
	public function run(){
		$array = [];
		while(true){
			$array[] = str_repeat("\x00", 1024);
		}
	}
};

$thread1 = new spam();
$thread2 = new spam();

$thread1->start();
$thread2->start();

$thread1->join();
$thread2->join();

echo "done\n";
```

Expected Output
=============
```
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in C:\Users\User\Desktop\test.php on line 10
```

Actual Output
============
```
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in C:\Users\User\Desktop\test.php on line 10
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in C:\Users\User\Desktop\test.php on line 10
done
```

**Comment by tpunt** [comment]
This is by design. pthreads employs a shared-nothing architecture, which means that for each thread you create, a new instance of the PHP interpreter is created (effectively a copy from the main interpreter instance). The Zend Memory Manager is tied to each interpreter instance, and that's what tracks and manages memory usage. Thus, the limit you set is applied *per thread*, rather than to the PHP process as a whole.

**Comment by dktapps** [comment]
Alright thanks. I'll need to find an alternative way to keep things under control. Thank you.
