### ISSUE TITLE
Autoloading classes

### ISSUE THREAD

**Issue by janwalther** [krakjoe/pthreads#68]
This extension really looks great but I have the following problem:
In the run() method of a thread I want to use classes which should be loaded by autoloading (spl_register_autoload). I used var_dump() to check if the script actually uses the autoload function but it does not.

Here is my code which should print "string 'Foo' (length=3)" and an error message for not finding the class after that. But it does not go into the autoload method and only says "Class foo not found".
```php
function autoload($classname)
{
  var_dump($classname);
}
spl_autoload_register('autoload');

class ThreadClass extends Thread {
    public function run(){
    new Foo();
  }
}

$g = new ThreadClass();
$g->start();
```

I hope you can show me a solution to this problem?

**Comment by kwhat** [comment]
I am having the same issue and this is not an effective solution.  No only do the autoloaders have issues, there are issues with objects that are set on the thread that are not copied...  basically if you implement LoggerAwareInterface, and you set a logger to your thread, and then you start the thread it shits its pants.  Honestly, after spending the better part of a month fighting though this, I am going back to forking.  This extension is just too unstable.
