### ISSUE TITLE
WHY can't you use pthreads safely and sensibly anywhere but CLI?

### ISSUE THREAD

**Issue by My1** [krakjoe/pthreads#692]
it was written often enough that pthreads cant be safely and sensibly be used outside of CLI, but may I ask WHY that is the case? does it really matter that much on where you use it? I mean this restriction can be easily bypassed by using an exec or shell_exec and kickstarting pthreads that way.

I mean I would love to for example but some super complciated calculations in some threads, and let the main thread wait, while the others do their thing and continue the output afterwards, while doing so single threaded takes quite a bit more time, just as an example.

having it directly on a website also makes it easy for people who are plainly too dumb to use CLI (the user isnt always a developer) and makes it very convenient, since you don't need more than a browser to do it, making it available literally everywhere.

**Comment by DaveRandom** [comment]
> the user isnt always a developer

...then why the hell are they messing with threads???

**Comment by My1** [comment]
kind of a weird argument. in that case multi-threaded applications wouldnt even exist except for a few ones that only devs could use like Visual Studio and whatnot.

**Comment by DaveRandom** [comment]
Threading is really, really, *really* hard. It is not a thing that non-programmers should be messing with (in 99.999% of cases it's not even a thing that experience programmers should be messing with).

Regardless, the reasons for not allowing threading in a web server environment are more practical than anything else. A lot of web servers are already invoking PHP in an extremely complex managed threaded environment already, finely tuned to maximise performance in that scenario without overloading the system. If you start arbitrarily creating new worker threads in that environment, you are going to have a bad time.

[Here](https://web.stanford.edu/~ouster/cgi-bin/papers/threads.pdf) are some slides from a talk - more than *2 decades* old and just as valid today - on why threads are almost always a bad idea.

**Comment by DaveRandom** [comment]
See also http://stackoverflow.com/a/1398603/889949

**Comment by My1** [comment]
@DaveRandom thanks for the information.

well non programmers arent the people directly messing with the threads anyway, as said before the dev is doing the threading, if using that logic neither chrome nor opera nor any kind of user-targeted software should run.

it's true that threading might be complex, but there are things where threads are relatively simple for example for throwing a ton of the same calculations that dont have to directly share anything directly with each other.

I actually ran into a few problems myself with the includes not working from the main thread into the subthreads but that wasnt that much of a problem to care about, just relocated them into the starting of the thread and was sorted out quickly, and at least imo not enough to completely kill it for anything but CLI.

I for example do some heavy calculations with data obtained from a database and to make the process faster and smoother every thread gathers what it needs into some variables, and does the calculations, and puts the results back into the database concurrent access by multiple threads into the database isnt a problem anyway since they are made to handle stuff like that and they are just adding new stuff meaning the case is one which technically could even run seperately on multiple computers, assuming the have the same input data before (database clone for example) and the output dbs could be merged afterwards)

also the performance increased drastically by using threads, I dont have numbers but long story short, PHP just used 1 thread in both CLI and FCGI interfaces without doing the threading, essentially just using a fourth of the available power, pthreads increased the amount tremendously.

meaning the part about whether threading is hard or not hard is heavily dependent on what you are doing, with mutually dependent data it isnt going to be easy, true but with completely independent calculations it should be a lot easier. I think the key in making threads as good as possible is to try to make them mutually independent, so they dont even need to lock anything up, of course that isnt always possible.

essentially I am just splitting the for loop into x parts by making the first start with zero, the second with 1 and so on, and they all have an increment by x (the number of threads), and by not being mutually independent, it doesnt matter who finishes what first.

and in my case honestly system load isnt much of a concern since the whole thing isnt publica facing anyway and doing these calculations is the main task of the server with a nice, secure administration website as the "GUI", so my boss can input the base data and start the number crunching.

as an analogy one could say that it could be similar to making a rainbow table, without threading it would take eternities but by splitting the search space it becomes a lot faster.
do be more exact, it's about calculating certain properties of pairs of dates, and with about 1,2 billion date combinations in the unix timespace (a little bit more than 1902-2037 is what you can do with unix timestamps on 32 bit PHP) threads become a very helpful tool.

and while these shades are really intresting most of the stuff doesnt apply at the very least in my case, especially with them talking about real-time GUIs (like PC programs) and stuff. from what I see, technically a website is also essentially just a remote triggered commandline application and the browser just parses the output of that.

well at the end a few more questions:
so why is it a problem to force CLI to pthreads? is the dev getting the fault for any problems with bad thread coding?
is CLI helping in resolving the thread issues?
wouldnt it just be possible to circumvent the whole thing by just using exec anyway?
