### ISSUE TITLE
windows 7 php 7.1.2  zend_mm_heap corrupted issue

### ISSUE THREAD

**Issue by molchanov1983** [krakjoe/pthreads#694]
Hello 
i stuck one issue using windows 7 yii 1 and threads
 "C:\Program Files\Nectus\Web\php-7.1.2\php.exe" "C:/Program Files/Nectus/Web/Apache24/htdocs/sshcmd.php"

OUTPUT : zend_mm_heap corrupted
Firstly everything worked well  but after some time  (about 4 hours testing) it stopped working and i got this error message
https://github.com/molchanov1983/yii_thread
This is repository where i put files
Thanks

**Comment by krakjoe** [comment]
Can a windows fan have a look at this with 7.2 and latest sources and tell me if it reproduces ?

/cc @Jan-E maybe

**Comment by lchb369** [comment]
ubuntu 16.04  php7.2.3   pthread 3.1.7dev  has same error

**Comment by SirSnyder** [comment]
If the issue still exists, please reopen!
