### ISSUE TITLE
Directly accessing an attribute of a shared object that contains $this inside of an array throws a segfault (php-src/Zend/zend_gc.c:269: gc_possible_root: Assertion `(ref)->gc.u.v.type == 7 || (ref)->gc.u.v.type == 8' failed.).

### ISSUE THREAD

**Issue by danog** [krakjoe/pthreads#695]
Environment
==========

  * PHP: 7.1.4RC1 ( ZTS DEBUG )
  * pthreads:  3.1.7dev
  * OS: Debian Jessie 8.7, Linux 4.10.0-xanmod1

Summary
======

Directly accessing (without var_dumping the whole object) an attribute of a shared object that contains $this inside of an array throws a segfault (php-src/Zend/zend_gc.c:269: gc_possible_root: Assertion `(ref)->gc.u.v.type == 7 || (ref)->gc.u.v.type == 8' failed.).
Also, I noticed that assignment of a reference of an object to an attribute of the same object from the run method of a threaded does not work (null is assigned instead).
And one last weird bug, assigning $this to an attribute of a shared object inside the run method of a threaded does not assign anything.
A fix would be really nice (especially for the first bug, since it breaks some callables).

Reproducing Code
==============

```
<?php
$pool = new \Pool(1);

class thr extends \Threaded
{
    public $test;
    public function __construct($test) {
        $this->test = $test;
    }
    public function run() {
        $this->test->him = $this->test;
        $this->test->thread = $this;
        var_dump($this->test); // test->me is readable, but test->him is null, and test->thread is not set
        var_dump($this->test->me); // Correctly prints a representation of test->me and then throws a segfault (php: /home/pwrtelegram/repos/php-src/Zend/zend_gc.c:269: gc_possible_root: Assertion `(ref)->gc.u.v.type == 7 || (ref)->gc.u.v.type == 8' failed.)
    }
}

class test {
    public $him;
    public function __construct() {
        $this->me = [$this];
    }
}

$API = new test;
$pool->submit(new thr($API));
```

Expected Output
=============

```
object(test)#4 (2) {
  ["him"]=>
  *RECURSION*
  ["me"]=>
  array(1) {
    [0]=>
    *RECURSION*
  }
  ["thread"]=>
    HUUUUUUUUGE RECURSION
  }
}
array(1) {
  [0]=>
  *RECURSION*
}

```

Actual Output
============

```
object(test)#4 (2) {
  ["him"]=>
  NULL
  ["me"]=>
  array(1) {
    [0]=>
    *RECURSION*
  }
}
array(1) {
  [0]=>
  *RECURSION*
}
php: /home/pwrtelegram/repos/php-src/Zend/zend_gc.c:269: gc_possible_root: Assertion `(ref)->gc.u.v.type == 7 || (ref)->gc.u.v.type == 8' failed.
Aborted
```

**Comment by SirSnyder** [comment]
Class test is not Threaded which leads to such issues. Not-threaded objects must be marshalled between threads. Extend the class, that could solve the issue.

**Comment by danog** [comment]
That does fix this bug, but also has some consequences: I cannot redefine an array stored in an attribute of Threaded, since it is a Volatile object that extends Threaded, and Threaded members previously set to Threaded objects are immutable.
Any solution (apart from storing everything into objects instead of arrays?)

**Comment by SirSnyder** [comment]
Hm, quick thought. Use Volatile instead of Threaded to extend the class. Otherwise, if you wanna stuck with Threaded, you could reuse the already set Volatile object

**Comment by danog** [comment]
That works, thanks. Another issue: volatile members cannot be fetched as references D:

**Comment by danog** [comment]
Lesson learned: no references pls.
To fix the serialization of Volatile objects I created https://Github.com/danog/MagicalSerializer
