### ISSUE TITLE
In pthreads 3+ not working PTHREADS_ALLOW_GLOBALS functionality

### ISSUE THREAD

**Issue by nike80** [krakjoe/pthreads#698]
Hi krakjoe!

Pthreads is great, thanks for your job!

But in pthreads 3+ not working PTHREADS_ALLOW_GLOBALS functionality (Allow global inheritance for new threads).

This is very important functionality. It used in hi-powered engines (CDNs, games engines, ect.): in first stage the engine allocate resources and queues, calculate tables and slots which will be **(by many reasons) global variables**, and will be used all branches of code and threads together.

More about this technique you may find f.e. in books of André LaMothe ( https://en.wikipedia.org/wiki/André_LaMothe )
at http://www.amazon.com/s/ref=nb_sb_noss_1?url=search-alias%3Daps&field-keywords=andre+lamothe

Without this technique no way creating hi-powered systems and deploy the power of PHP engine.

So, krakjoe, please, restore PTHREADS_ALLOW_GLOBALS functionality in pthreads.
Thanks!

**Comment by danog** [comment]
Imo you really should never use global variables: OOP attributes are the best way to share content between threads.

**Comment by nike80** [comment]
danog, thanks’ for your opinion.
Hi-speed engine like DB engines, 3D engines, math-engines always use globals for allocate pre-calculated tables and common memory slots as I described before.

**This is fastest and besets way for sharing big quantity of memory with complex structures between workers. There is no any alternative for this.**

Please read books by link which I gave, and see the code of PostgreSQL or Quake engines for example.

PS Also if you open krakjoe's code of pthreads extension, you can found globals there. Don’t fear globals. :)

**Comment by krakjoe** [comment]
Sorry, but globals don't fit in a multi-threaded environment.
