### ISSUE TITLE
A pool not assigned to any variable blocks during the submission of a job

### ISSUE THREAD

**Issue by danog** [krakjoe/pthreads#700]
Environment
==========

  * PHP: 7.1.4RC1 ( ZTS DEBUG )
  * pthreads:  3.1.7dev
  * OS: Debian Jessie 8.7, Linux 4.10.0-xanmod1

Summary
======

A pool not assigned to any variable blocks during submission of a job, and while it is running.

Reproducing Code
==============

```
<?php

class a extends Threaded {
    public function run() {
        while (true);
    }
}
$a = new a;
(new Pool(1))->submit($a);
echo "YAY";
```

Expected Output
=============

`YAY`

Actual Output
============

Nothing

**Comment by krakjoe** [comment]
Expected behaviour: the pool cannot shutdown (and it's implicitly shutdown when the un-named variable is destroyed) because you are blocking it while(true).
