### ISSUE TITLE
Socket::read() normal read

### ISSUE THREAD

**Issue by userqq** [krakjoe/pthreads#706]
Hi. 
unlike to <a href="http://php.net/manual/en/function.socket-read.php">socket_read</a>, Socket::read() requires flags from <a href="http://php.net/manual/en/function.socket-recv.php">socket_recv</a> function (MSG_OOB, MSG_PEEK, MSG_WAITALL, MSG_DONTWAIT) and only default read mode (PHP_BINARY_READ) is possible.

any plans to add PHP_NORMAL_READ?

**Comment by krakjoe** [comment]
There are plans to enhance Socket, but I don't have the time right now ...

**Comment by SirSnyder** [comment]
Merged #828
