### ISSUE TITLE
Type hinting sometime causes segfault

### ISSUE THREAD

**Issue by userqq** [krakjoe/pthreads#707]
Sometimes type hinting in methods, which are was called inside thread causes error "Segmentation fault. Core dumped".
When I remove type hinting from these methods everything is ok.
So currently some methods in theads works with typehinthing and some not.

I'm using ubuntu 17.04 x64, PHP 7.2.0-dev with pThreads from master branch.

Please see the <a href="https://github.com/userqq/pthreads-type-hinting-segfault ">repo</a>.
"?string" in <a href="https://github.com/userqq/pthreads-type-hinting-segfault/blob/master/application/http/HeadersCollection.php#L32">HeadersCollection.php#L32</a> provokes error, when i removing it everything is ok and I can see correct response in browser.

P.S.: Sorry for my terrible English :)

**Comment by SirSnyder** [comment]
This issue got fixed in https://github.com/SirSnyder/pthreads/tree/php/71

**Comment by krakjoe** [comment]
Any reason your changes are not in a pull request?

**Comment by krakjoe** [comment]
I just realised they are waiting ... I will review them as soon as I am
able. (Recovering from surgery)

**Comment by SirSnyder** [comment]
Nice to read you @krakjoe. Feared we've lost you to another project and pthreads is orphaned. Therefore, I've referred to my fork. Yes, there are some pending pull requests and some more to come. I could need your experience in #696, maybe you have an idea or possible solution.

Get well soon!

**Comment by krakjoe** [comment]
This was fixed when we prepared for 7.2, anything after 5bb20583ac8cbdcdc830134e8cf6b2fdbc6a918c should be fine ... (use latest).
