### ISSUE TITLE
Worker segfault when stacking a task defined after thread start

### ISSUE THREAD

**Issue by dktapps** [krakjoe/pthreads#711]
Environment
==========

  * PHP: 7.0.19 ZTS
  * pthreads: 3.1.6
  * OS: Windows 10 x64

Summary
======
Defining the class for a Worker job causes a segfault when stacked if the class was defined after the worker was started.

Also observed similar behaviour on PHP 7.1 with the latest master on Linux.

Starting the Worker thread with PTHREADS_INHERIT_ALL also resolves the issue, however I find a segmentation fault unexpected.

Reproducing Code
==============
Working:
```
<?php

$worker = new \Worker();
$worker->start();

class task extends \Threaded implements \Collectable{
    
    public function __construct(){
        var_dump("constructor");
    }
    
    public function run(){

    }
}

var_dump("stacking");
$worker->stack(new task());
var_dump("stacked");
while($worker->collect());
$worker->shutdown();
var_dump("ok");
```

Broken:
```
<?php

class task extends \Threaded implements \Collectable{
    
    public function __construct(){
        var_dump("constructor");
    }
    
    public function run(){

    }
}

$worker = new \Worker();
$worker->start();

var_dump("stacking");
$worker->stack(new task());
var_dump("stacked");
while($worker->collect());
$worker->shutdown();
var_dump("ok");
```

Expected Output
=============
```
string(8) "stacking"
string(11) "constructor"
string(7) "stacked"
string(2) "ok"
```

Actual Output
============
```
string(8) "stacking"
string(11) "constructor"
string(7) "stacked"
```
followed by a segmentation fault.

**Comment by krakjoe** [comment]
Fixed by 082f2eff01ddfbbbda3d5223a331d58c40ec6489

Thanks.
