### ISSUE TITLE
Can't overload Threaded::run from internal class

### ISSUE THREAD

**Issue by ClosetMonkey** [krakjoe/pthreads#716]
[Here's an gist of what I'm attempting](https://gist.github.com/ClosetMonkey/55d179e1205942c1d7b8b4617985e973)

As you can see, it should overload run within pthreads_thread_entry parent, but it doesn't.

```
<?php
$test = new Test();
$test->start();
$test->join();
?>
```

Should print a thread id and sleep 10 seconds, but it doesn't print anything (but `var_dump($test->start())` returns bool true) and it does't sleep. However, directly calling `$test->run();` will work (however likely not within it's own thread - haven't tested)

What gives? How do you overload Threaded::run inside of a custom internal class within pthread ext?

**Comment by tpunt** [comment]
It's not enough to simply fill in the `run` method of `Threaded`. Pthreads internally does not actually invoke its builtin (empty) `run` method - it only invokes `run` if it is defined in PHP. To bypass this behaviour, simply comment out [this check](https://github.com/krakjoe/pthreads/blob/2645c78154c87b390908a8e8e1f59b99c8dfb30a/src/object.c#L468) (and its corresponding closing curly brace).

Also, please post any future questions you have on StackOverflow. The issue tracker on here is only bugs.

**Comment by ClosetMonkey** [comment]
Technically I'm extending Threaded internally, but I see that the core of the issue is that it is expected to be done in PHP user space. Thanks! Might I suggest changing the if() to check class name if the point is just to verify that it's not trying to invoke Threaded's empty run() method?
