### ISSUE TITLE
PHP 7.2 Dll File needed

### ISSUE THREAD

**Issue by ghost** [krakjoe/pthreads#721]
Just need a DLL file for 7.2
PHP-7.2.0beta1-Win32-VC15-x64 - thread safe.

You can download it through php.net now, 
I Need there new crypto library and bug fixes thanks!

**Comment by krakjoe** [comment]
I'm looking into what we can do here ... the windows dlls are created by the windows.php.net build system when PECL releases are created ...

You could download artifacts from appveyor to test with, but these are not production builds ...

It may be possible to get the windows build system to build a tag/commit automatically, or we may be able to get a trigger to create on-demand builds ...

/cc @weltling

**Comment by weltling** [comment]
It is planned to start snapshot PECL builds with 7.2 in a near future. At the early stage it makes less sense, because ABI breaches would render the PECL builds unusable, thus making it a wasted effort. I guess with beta2 or 3 there will be a parallel run with 7.2 pre. 

@Punxor which exact DLLs are you talking about?

Thanks.

**Comment by Punxor** [comment]
@weltling Hey I basically need (php_pthreads.dll, pthreadVC2.dll) compiled that works with 7.2 but as you said it wouldn't make sense to have an early build for 7.2 I'll stick with 7.1 for now, Also suggestion if you guy's can add a Timer "Loop a function every x second / min/hour".

It makes sense since to do that you would need a thread I made a class in PHP but it would be nice to have it in PThreads to just extends Timer.

Sorry for the late response.

**Comment by My1** [comment]
@Punxor was there even a 7.1 dll file? iirc the last has been for 7.0.

but a test version to see how well it works (or doesnt work) for 7.2 would be awesome, especially since it's out of beta and now in RC stage.

also the readme states that 7.0 and 7.1 aint supported because they are broken, so trying out the 7.2 RC would be the

**Comment by weltling** [comment]
Thanks for the ping. This ticket went from my radar. Please fetch the current master snapshots against 7.2 here http://windows.php.net/downloads/pecl/snaps/pthreads/3.1.6/

Thanks.

**Comment by My1** [comment]
thanks, looks nice on 7.2 although I found a difference in behavior, in php 7.0 you can throw open the threads and not care about the rest and the threads continue working (at least until the execution  time has been hit or they finish, obviously).

in 7.2 apparently if you dont explicitly start waiting for the threads nothing is going to happen.

not a problem and probably my thing has been technically wrong but I just needed some threads to do stuff on their own without needing anything on the main part.

**Comment by snowleopard24** [comment]
@weltling Any idea when we can see pthreads for PHP7.2?

**Comment by My1** [comment]
the link above is for the rc of php 7.2

**Comment by My1** [comment]
@weltling 
PHP 7.2.0 released thursday. any chance of a full release against 7.2?

dont want to hurry, just curious.

**Comment by ivanjaros** [comment]
So yeah, win dlls seem quite outdated(last build 2/13/2016)

> Warning: PHP Startup: pthreads: Unable to initialize module
> Module compiled with module API=20151012
> PHP    compiled with module API=20160303

**Comment by biopowder** [comment]
Downloaded dlls from http://windows.php.net/downloads/pecl/snaps/pthreads/3.1.6/
When starting apache receiving:
`PHP Fatal error:  The apache2handler SAPI is not supported by pthreads in Unknown on line 0
PHP Fatal error:  Unable to start pthreads module in Unknown on line 0`

**Comment by My1** [comment]
well as seen in the readme file this thing is (sadly) not supposed to be ran with apache or anything, just for the CMD.

also while it's probably easy to do it wrong I believe that proper multithreaded works can be done even on non-cli content, also for example argon2 also runs multiple threads, iirc even as default.

also if your threaded thing is very simple (for example with them just crunching some numbers and not being dependent to each other) it's probably a lot easier to do so, as you open the threads, let them run, and the main thread gets into the waiting state, for example.

of course it would be a lot more difficult for highly complex threaded stuffs.

**Comment by Teneobelgium** [comment]
Nu full Windows package yet ? :(

**Comment by snowleopard24** [comment]
Who creates a snapshot PECL build of pthreads for windows? Is this a totally different group than the one working on pthreads?

**Comment by weltling** [comment]
Snapshots for the latest master have been uploaded, please fetch from the same URL.

Thanks.

**Comment by snowleopard24** [comment]
Thanks to all of you who have been giving your precious time for so long to get pthreads out. It's been really helpful to have something like pthreads.
For those following this thread use this link for the snapshot build (this is not a release build) and pthreads is still under development so use it with caution- http://windows.php.net/downloads/pecl/snaps/pthreads/3.1.6/

**Comment by SirSnyder** [comment]
@welting, I've just released pthreads 3.2.0. I'm unfamiliar with the pecl stuff. Are pecl dll's deployed automatically with each fresh release or do I've to trigger something?

**Comment by weltling** [comment]
@SirSnyder as soon as you upload that releas to PECL, the build bot will build them and make available to the website.

Thanks.

**Comment by SirSnyder** [comment]
Thanks for the info @weltling. Can you add me as maintainer to the pecl package or is that a task for @krakjoe as lead? Do I have to apply for a php.net account?

**Comment by weltling** [comment]
@SirSnyder, @krakjoe can do that as lead or any PECL admin (which i'm not one of). Once that happened, you'll need to add yourself also into the package.xml.

I've triggered a snapshot build from 3.2.0 tag for now https://windows.php.net/downloads/pecl/snaps/pthreads/3.2.0/, so it's useful for you also to check logs and for anyone to test.

Thanks.

**Comment by SirSnyder** [comment]
Release [v3.2.0](https://github.com/krakjoe/pthreads/releases/tag/v3.2.0) is live. You will find *.dlls in the release. Alternatively is an official pecl [snapshot](https://windows.php.net/downloads/pecl/snaps/pthreads/3.2.0/) available.

@weltling, I will write to the pecl developers mailing list in the next few days, thx for the snapshot.
