### ISSUE TITLE
Fatal error: Class 'Worker' not found in C:\wamp64\www\pthreads-master\examples\Pooling.php on line 2

### ISSUE THREAD

**Issue by hnk15** [krakjoe/pthreads#726]
Fatal error: Class 'Worker' not found in C:\wamp64\www\pthreads-master\examples\Pooling.php on line 2

We want to ask a query that is it usefull in our case?

Actually we have an application in which users can upload a file (it may be doc, docx, pdf etc), after that our application start processing of that file. 

In between a new user upload a file, although the previous file is still processing, now the new file will have to wait till the previous file complete process.

Actually we want to start process of the second file on the same time when previous is still processing.

how we can do this? any suggestion please!

**Comment by tpunt** [comment]
Your error suggests that you do not have the pthreads extension loaded.

Please keep generic questions (such as this) to StackOverflow. Closing for this reason.
