### ISSUE TITLE
Getting Worker data from Jobs with Pthread/PHP

### ISSUE THREAD

**Issue by JeroenSteen** [krakjoe/pthreads#727]
I construct a Pool with a TermWorker class with Pthread and PHP 7. I select several terms from a Database source, and I want to process it with specific Jobs. This is my code, for doing this:

    $termpool = new Pool(1, TermWorker::class);
    foreach($terms as $term) {
    $termpool->submit(new PostagJob(["termArray" => $termArray, "lamachinePath" => $lamachine_path]));
    $termpool->submit(new ClassifyJob($termArray));
    }

In the PostagJob I want to save data to the worker,
I use a array merge for this, and I'm setting a status, see:

    $this->worker->postag_labels = array_merge(
    $this->worker->postag_labels,
    //Prevent Volatile object, cast to array
    (array)[
    "word" => $word_key,
    "label" => $word["pos"]["@attributes"]["head"],
    "lemma" => $word["pos"]["@attributes"]["class"]
    ]);
    $this->worker->postag_status = "Tagged";

In another Job named ClassifyJob, I do several classifications,
but I also want to use the saved postag_labels (from the worker).
Currently I'm using a while loop for checking the data:

    while(true) {
    //Postag labels are available
    if($this->worker->postag_status === "Tagged") {
    print_r($this->worker->postag_labels); 
    break;
    } else if($this->worker->postag_status === "Untaggable") {
    //Not possible, to classify this way
    break;
    }
    }

I notice that the data is not being printed, and that it keeps waiting/looping.
How can I retreive the data from the worker in the ClassifyJob?
I saw `synchronized()`, `wait()` and `join()`, is that what I need?
How can I implement this, or what else do I need to do?

**Comment by tpunt** [comment]
I saw your question on StackOverflow, but I couldn't answer it because you didn't provide a complete code listing. Can you update your question on there with your full code instead?
