### ISSUE TITLE
"zend_mm_heap corrupted" on SocketServer example

### ISSUE THREAD

**Issue by prolic** [krakjoe/pthreads#728]
Environment
==========

  * PHP 7.2.0beta1
  * pthreads 3.1.7dev (current master)
  * Ubuntu 16.04.2 LTS (`Linux sasa-X1 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`)

Summary
======

- `php examples/SocketServer.php`
- Go to browser at `localhost:13000`
- Website is shown
- Refresh website
- Socket Server dies with "zend_mm_heap corrupted"

**Comment by krakjoe** [comment]
That is an old example that uses resources, and comes with the following warning:

>  RESOURCES ARE BEING TRIED OUT, THIS MAY CRASH OR KILL THE EXECUTOR OF THE SCRIPT: NOT MY FAULT

and

>  AGAIN: 	If this does not work, there is NOTHING more I can do. 
			If a particular type of resource wigs out, there is NOTHING I can do.
			If this kills you, horribly, there is NOTHING I can do.

We should include an example using the new `Socket` class ... but want to keep that original example, even though it's prone to faulting.

**Comment by prolic** [comment]
An example using the `Socket` class would be really helpful.
