### ISSUE TITLE
centos can not compile  pthread successfully

### ISSUE THREAD

**Issue by tgl123** [krakjoe/pthreads#731]
centos7
php version is  php 7.1.
the  errors information is below:

/opt/php71/include/php/Zend/../TSRM/TSRM.h:171:69: 错误：‘zend_executor_globals’没有名为‘scope’的成员
 #define TSRMG_STATIC(id, type, element) (TSRMG_BULK_STATIC(id, type)->element)
                                                                     ^
/opt/php71/include/php/Zend/zend.h:57:20: 附注：in expansion of macro ‘TSRMG_STATIC’
 #define ZEND_TSRMG TSRMG_STATIC
                    ^
/opt/php71/include/php/Zend/zend_globals_macros.h:44:16: 附注：in expansion of macro ‘ZEND_TSRMG’
 # define EG(v) ZEND_TSRMG(executor_globals_id, zend_executor_globals *, v)
                ^
/tmp/pear/temp/pthreads/classes/pool.h:189:30: 附注：in expansion of macro ‘EG’
    zend_class_entry *scope = EG(scope);
                              ^
/opt/php71/include/php/Zend/../TSRM/TSRM.h:171:69: 错误：‘zend_executor_globals’没有名为‘scope’的成员
 #define TSRMG_STATIC(id, type, element) (TSRMG_BULK_STATIC(id, type)->element)
                                                                     ^
/opt/php71/include/php/Zend/zend.h:57:20: 附注：in expansion of macro ‘TSRMG_STATIC’
 #define ZEND_TSRMG TSRMG_STATIC
                    ^
/opt/php71/include/php/Zend/zend_globals_macros.h:44:16: 附注：in expansion of macro ‘ZEND_TSRMG’
 # define EG(v) ZEND_TSRMG(executor_globals_id, zend_executor_globals *, v)
                ^
/tmp/pear/temp/pthreads/classes/pool.h:195:4: 附注：in expansion of macro ‘EG’
    EG(scope) = ce;
    ^
/opt/php71/include/php/Zend/../TSRM/TSRM.h:171:69: 错误：‘zend_executor_globals’没有名为‘scope’的成员
 #define TSRMG_STATIC(id, type, element) (TSRMG_BULK_STATIC(id, type)->element)
                                                                     ^
/opt/php71/include/php/Zend/zend.h:57:20: 附注：in expansion of macro ‘TSRMG_STATIC’
 #define ZEND_TSRMG TSRMG_STATIC
                    ^
/opt/php71/include/php/Zend/zend_globals_macros.h:44:16: 附注：in expansion of macro ‘ZEND_TSRMG’
 # define EG(v) ZEND_TSRMG(executor_globals_id, zend_executor_globals *, v)
                ^
/tmp/pear/temp/pthreads/classes/pool.h:197:4: 附注：in expansion of macro ‘EG’
    EG(scope) = scope;
    ^
In file included from /tmp/pear/temp/pthreads/php_pthreads.c:442:0:
/tmp/pear/temp/pthreads/classes/pool.h:204:8: 错误：‘zend_fcall_info’没有名为‘function_table’的成员
     fci.function_table = EG(function_table);
        ^
In file included from /opt/php71/include/php/Zend/zend_portability.h:52:0,

please,help me,what should i do.

**Comment by krakjoe** [comment]
PHP 7.1 is not supported, sorry.
