### ISSUE TITLE
support only for php 7.2+

### ISSUE THREAD

**Issue by ms502040** [krakjoe/pthreads#732]
with this commit:
[Remove superfluous version checks](https://github.com/krakjoe/pthreads/commit/c28075ba3869a5e32e3dfe6ce23b10f1dbae58cf)
you support php 7.2+ change doc plz.

**Comment by tpunt** [comment]
Support for 7.2+ only was first enforced in 5bb20583ac8cbdcdc830134e8cf6b2fdbc6a918c.

Since this issue is already being tracked in #709, I'm closing this issue.
