### ISSUE TITLE
recipe for target 'php_pthreads.lo' failed

### ISSUE THREAD

**Issue by bamboohome** [krakjoe/pthreads#735]
Environment
==========

Apache:
Server version: Apache/2.4.27 (Unix)
Server built:   Aug 15 2017 09:20:51
Server's Module Magic Number: 20120211:68
Server loaded:  APR 1.6.2, APR-UTIL 1.6.0
Compiled using: APR 1.6.2, APR-UTIL 1.6.0
Architecture:   64-bit
Server MPM:     worker
  threaded:     yes (fixed thread count)
    forked:     yes (variable process count)

PHP:
PHP 7.1.8 (cli) (built: Aug 15 2017 09:42:56) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

OS:
Debian GNU/Linux 9

Summary
======

I did the following to install pthreads:

git clone https://github.com/krakjoe/pthreads.git
cd pthreads
phpize
./configure
make

the last outputs are:
[...] (if you need this, i will post it, it is very much)
./classes/socket.h:129:2: note: in expansion of macro ‘PHP_ME’
  PHP_ME(Socket, getSockName, Socket_getHost, ZEND_ACC_PUBLIC)
  ^~~~~~
./classes/socket.h:129:30: note: (near initialization for ‘pthreads_socket_methods[13].arg_info’)
  PHP_ME(Socket, getSockName, Socket_getHost, ZEND_ACC_PUBLIC)
                              ^
/usr/local/include/php/Zend/zend_API.h:70:75: note: in definition of macro ‘ZEND_FENTRY’
 #define ZEND_FENTRY(zend_name, name, arg_info, flags) { #zend_name, name, arg_info, (uint32_t) (sizeof(arg_info)/sizeof(struct _zend_internal_arg_info)-1), flags },
                                                                           ^~~~~~~~
/usr/local/include/php/main/php.h:363:25: note: in expansion of macro ‘ZEND_ME’
 #define PHP_ME          ZEND_ME
                         ^~~~~~~
./classes/socket.h:129:2: note: in expansion of macro ‘PHP_ME’
  PHP_ME(Socket, getSockName, Socket_getHost, ZEND_ACC_PUBLIC)
  ^~~~~~
/usr/local/include/php/Zend/zend_API.h:70:113: error: invalid operands to binary / (have ‘zend_function_entry * {aka struct _zend_function_entry *}’ and ‘long unsigned int’)
 Y(zend_name, name, arg_info, flags) { #zend_name, name, arg_info, (uint32_t) (sizeof(arg_info)/sizeof(struct _zend_internal_arg_info)-1), flags },
                                                                               ~               ^
/usr/local/include/php/Zend/zend_API.h:81:51: note: in expansion of macro ‘ZEND_FENTRY’
 #define ZEND_ME(classname, name, arg_info, flags) ZEND_FENTRY(name, ZEND_MN(classname##_##name), arg_info, flags)
                                                   ^~~~~~~~~~~
/usr/local/include/php/main/php.h:363:25: note: in expansion of macro ‘ZEND_ME’
 #define PHP_ME          ZEND_ME
                         ^~~~~~~
./classes/socket.h:129:2: note: in expansion of macro ‘PHP_ME’
  PHP_ME(Socket, getSockName, Socket_getHost, ZEND_ACC_PUBLIC)
  ^~~~~~
/usr/local/include/php/Zend/zend_API.h:70:85: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 #define ZEND_FENTRY(zend_name, name, arg_info, flags) { #zend_name, name, arg_info, (uint32_t) (sizeof(arg_info)/sizeof(struct _zend_internal_arg_info)-1), flags },
                                                                                     ^
/usr/local/include/php/Zend/zend_API.h:81:51: note: in expansion of macro ‘ZEND_FENTRY’
 #define ZEND_ME(classname, name, arg_info, flags) ZEND_FENTRY(name, ZEND_MN(classname##_##name), arg_info, flags)
                                                   ^~~~~~~~~~~
/usr/local/include/php/main/php.h:363:25: note: in expansion of macro ‘ZEND_ME’
 #define PHP_ME          ZEND_ME
                         ^~~~~~~
./classes/socket.h:129:2: note: in expansion of macro ‘PHP_ME’
  PHP_ME(Socket, getSockName, Socket_getHost, ZEND_ACC_PUBLIC)
  ^~~~~~
/usr/local/include/php/Zend/zend_API.h:70:85: error: initializer element is not constant
 #define ZEND_FENTRY(zend_name, name, arg_info, flags) { #zend_name, name, arg_info, (uint32_t) (sizeof(arg_info)/sizeof(struct _zend_internal_arg_info)-1), flags },
                                                                                     ^
/usr/local/include/php/Zend/zend_API.h:81:51: note: in expansion of macro ‘ZEND_FENTRY’
 #define ZEND_ME(classname, name, arg_info, flags) ZEND_FENTRY(name, ZEND_MN(classname##_##name), arg_info, flags)
                                                   ^~~~~~~~~~~
/usr/local/include/php/main/php.h:363:25: note: in expansion of macro ‘ZEND_ME’
 #define PHP_ME          ZEND_ME
                         ^~~~~~~
./classes/socket.h:129:2: note: in expansion of macro ‘PHP_ME’
  PHP_ME(Socket, getSockName, Socket_getHost, ZEND_ACC_PUBLIC)
  ^~~~~~
/usr/local/include/php/Zend/zend_API.h:70:85: note: (near initialization for ‘pthreads_socket_methods[13].num_args’)
 #define ZEND_FENTRY(zend_name, name, arg_info, flags) { #zend_name, name, arg_info, (uint32_t) (sizeof(arg_info)/sizeof(struct _zend_internal_arg_info)-1), flags },
                                                                                     ^
/usr/local/include/php/Zend/zend_API.h:81:51: note: in expansion of macro ‘ZEND_FENTRY’
 #define ZEND_ME(classname, name, arg_info, flags) ZEND_FENTRY(name, ZEND_MN(classname##_##name), arg_info, flags)
                                                   ^~~~~~~~~~~
/usr/local/include/php/main/php.h:363:25: note: in expansion of macro ‘ZEND_ME’
 #define PHP_ME          ZEND_ME
                         ^~~~~~~
./classes/socket.h:129:2: note: in expansion of macro ‘PHP_ME’
  PHP_ME(Socket, getSockName, Socket_getHost, ZEND_ACC_PUBLIC)
  ^~~~~~
Makefile:196: recipe for target 'php_pthreads.lo' failed
make: *** [php_pthreads.lo] Error 1

Is this a problem of PHP 7.1.8? I installed pthreads often but i have never had this type of error message. I don't know how to fix it.

**Comment by tpunt** [comment]
> Is this a problem of PHP 7.1.8?

Yes. Pthreads no longer supports PHP 7.0 or PHP 7.1 due to safety issues with ZTS mode. You will need to use PHP 7.2 now, along with the master branch of pthreads.
