### ISSUE TITLE
Php 7  Class 'Thread' not found in pthreads in Mac with Ampps

### ISSUE THREAD

**Issue by ananddayalan** [krakjoe/pthreads#736]
Environment
==========

  PHP 7.1.2 (cli) (built: Apr 19 2017 19:17:16) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.6.0-dev, Copyright (c) 2002-2017, by Derick Rethans

php -dextension=pthreads.so --ri pthreads | grep Version
PHP Warning:  PHP Startup: Unable to load dynamic library '/Applications/AMPPS/php-7.1/lib/extensions/ext/pthreads.so' - dlopen(/Applications/AMPPS/php-7.1/lib/extensions/ext/pthreads.so, 9): image not found in Unknown on line 0

Summary
======

Getting Error Class 'Thread' not found in pthreads in Mac with Ampps. The documentation says pthreads works in Mac and doesn't specify any installation steps. Is there an installation step that I need to follow? pthreads.so doesn't present on my machine and I'm not sure how to install this.

I tried the following as well, but no luck

brew install php71 --with-thread-safety

when I tried building pthreads src, i got the following error 
checking for ZTS... configure: error: pthreads requires ZTS, please re-compile PHP with ZTS enabled

So tried building php source from github getting following error

php-src ananddayalan$ sudo ./configure --enable-pthreads --enable-maintainer-zts  --with-iconv=$(brew --prefix libiconv)

configure: WARNING: unrecognized options: --enable-pthreads

make

clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      _zif_iconv_substr in iconv.o
      _zif_iconv_mime_encode in iconv.o
      _php_iconv_string in iconv.o
      __php_iconv_strlen in iconv.o
      __php_iconv_strpos in iconv.o
      __php_iconv_appendl in iconv.o
      _php_iconv_stream_filter_append_bucket in iconv.o
      ...
  "_libiconv_close", referenced from:
      _zif_iconv_substr in iconv.o
      _zif_iconv_mime_encode in iconv.o
      _php_iconv_string in iconv.o
      __php_iconv_strlen in iconv.o
      __php_iconv_strpos in iconv.o
      __php_iconv_mime_decode in iconv.o
      _php_iconv_stream_filter_factory_create in iconv.o
      ...
  "_libiconv_open", referenced from:
      _zif_iconv_substr in iconv.o
      _zif_iconv_mime_encode in iconv.o
      _php_iconv_string in iconv.o
      __php_iconv_strlen in iconv.o
      __php_iconv_strpos in iconv.o
      __php_iconv_mime_decode in iconv.o
      _php_iconv_stream_filter_factory_create in iconv.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cli/php] Error 1

Reproducing Code
==============
```

<?php

class AsyncOperation extends Thread
{
    public function __construct($threadId)
    {
        $this->threadId = $threadId;
    }

    public function run()
    {
        printf("T %s: Sleeping 3sec\n", $this->threadId);
        sleep(3);
        printf("T %s: Hello World\n", $this->threadId);
    }
}

$start = microtime(true);
for ($i = 1; $i <= 5; $i++) {
    $t[$i] = new AsyncOperation($i);
    $t[$i]->start();
}
echo microtime(true) - $start . "\n";
echo "end\n";

?>
```

Expected Output
=============

Execute threads

Actual Output
============
Class 'Thread' not found

**Comment by tpunt** [comment]
Whilst pthreads is compatible with OS X, it is not compatible with PHP 7.1 (or PHP 7.0). The ZTS mode of these two versions is not safe, and so support for them was dropped. You will need to use either the PHP 7.2 or master branches of PHP in order to use pthreads now.

With respect to your configure command:
> sudo ./configure --enable-pthreads --enable-maintainer-zts --with-iconv=$(brew --prefix libiconv)

Pthreads is not a bundled core extension, and so it cannot be built statically like this. To build it as a shared extension, simply clone this repo, run `phpize && ./configure && make && make install`, and link to the resulting `pthreads.so` file in your php.ini file. To build pthreads statically, clone this repo into php-src/ext, and then run `./buildconf --force` in php-src to rebuild the config files.

Regarding your compilation errors, ensure that libiconv is actually installed and up-to-date.

**Comment by ananddayalan** [comment]
@tpunt Okay, after I installed libiconv, I'm getting the following error while installing 7.2 with

`brew install php72 --with-thread-safety --with-freetype-dir=/usr/local`

 or 

`brew install php72 --with-thread-safety `


```
Last 15 lines from /Users/ananddayalan/Library/Logs/Homebrew/php72/02.make:
make: *** Waiting for unfinished jobs....
  "_libiconv_open", referenced from:
      _do_convert in gdkanji.o
      _zif_iconv_substr in iconv.o
      _zif_iconv_mime_encode in iconv.o
      _php_iconv_string in iconv.o
      __php_iconv_strlen in iconv.o
      __php_iconv_strpos in iconv.o
      __php_iconv_mime_decode in iconv.o
      ...
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cgi/php-cgi] Error 1
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [sapi/cli/php] Error 1
```

**Comment by tpunt** [comment]
I'm not familiar with installing PHP via Homebrew, so I cannot really provide much help here. A quick Google search leads me to [this trouble shooting page](https://github.com/phpbrew/phpbrew/wiki/Trouble-Shooting:-Can%27t-build-PHP-on-OS-X-El-Capitan). Perhaps that will solve your issue.

In any case, this question does not belong on pthread's issue tracker, so I'm closing this now. Feel free to reply back if you're still having issues, but I can only really provide support with building PHP from source.
