### ISSUE TITLE
Segfault in threads created by threads

### ISSUE THREAD

**Issue by angstymeat** [krakjoe/pthreads#738]
Environment
==========
PHP
```
PHP 7.2.0beta2 (cli) (built: Aug  9 2017 20:35:16) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
```
pthreads
```
Version => 3.1.7dev
```
OS
```
CentOS 7
3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Summary
======
I have an application that spawns several threads that are each responsible for different functions (receiving emails, parsing those email and inserting the results into a database, scheduled maintenance, etc). Some of these threads spawn and manage their own threads (for example, the parsing thread runs every 5 minutes and will then divide up the emails a thousand at a time and pass them off to threads it spawns for parsing in parallel).

The parent & child threads are all based on the same base class that extends the Thread class.

I'm using Composer to include some other projects like Monolog & Propel. All threads are started with PTHREADS_INHERIT_NONE, and I include the vendor/autoload.php in the run() method of each thread.

I've noticed a problem in the child threads. If they try to call a function in their base class that uses synchronized(), they will segfault.

If I start the child threads with PTHREADS_INHERIT_ALL they do not segfault, but I then have autoload-related issues (the documented issues where classes not included in the parent thread are inaccessible in the child). I tried a number of combinations, and the actual flags that cause this issue involve PTHREADS_INHERIT_FUNCTIONS and PTHREADS_INHERIT_CLASSES, but I think that's where you expect the problem to be.

I don't know if threads aren't supposed to spawn threads, or if I'm doing something incorrectly here. I would expect to just be able to use PTHREADS_INHERIT_NONE, and every thread would start up the same way instead of the children faulting or failing to use the autoloader.

Reproducing Code
==============
I tried breaking the example code into a single file, but I couldn't get it to work out. Here's a link the github repo: https://github.com/angstymeat/pthreads-segfault-example

You should be able to execute it with "`zts-php threadTest.php`".

Expected Output
=============
```
Main Thread Start
Main: Sync
SubThread Start
SubThread: Sync
SubThread End
SubThread waiting to join
SubThread joined
Main Thread End
```

Actual Output
============
```
Main Thread Start
Main: Sync
SubThread Start
Segmentation fault
```

**Comment by tpunt** [comment]
Fixed, thanks!

**Comment by angstymeat** [comment]
Awesome, thank you! Looks like it is working fine, now.
