### ISSUE TITLE
pthread make error in mac php7.1.8

### ISSUE THREAD

**Issue by Kingtree2009** [krakjoe/pthreads#748]
➜  
my env: mac php7.1.8 pthread 3.1.6

I phpize and ./configure --with-php-config=
and make
so following errors:
how can i fix the errors or bug

pthreads git:(master) ✗ make
/bin/sh /Users/kt/source/pthreads/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/Users/kt/source/pthreads -DPHP_ATOM_INC -I/Users/kt/source/pthreads/include -I/Users/kt/source/pthreads/main -I/Users/kt/source/pthreads -I/usr/local/Cellar/php71/7.1.8_20/include/php -I/usr/local/Cellar/php71/7.1.8_20/include/php/main -I/usr/local/Cellar/php71/7.1.8_20/include/php/TSRM -I/usr/local/Cellar/php71/7.1.8_20/include/php/Zend -I/usr/local/Cellar/php71/7.1.8_20/include/php/ext -I/usr/local/Cellar/php71/7.1.8_20/include/php/ext/date/lib -I/Users/kt/source/pthreads/.  -DHAVE_CONFIG_H  -g -O2   -c /Users/kt/source/pthreads/php_pthreads.c -o php_pthreads.lo 
mkdir .libs
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/Users/kt/source/pthreads -DPHP_ATOM_INC -I/Users/kt/source/pthreads/include -I/Users/kt/source/pthreads/main -I/Users/kt/source/pthreads -I/usr/local/Cellar/php71/7.1.8_20/include/php -I/usr/local/Cellar/php71/7.1.8_20/include/php/main -I/usr/local/Cellar/php71/7.1.8_20/include/php/TSRM -I/usr/local/Cellar/php71/7.1.8_20/include/php/Zend -I/usr/local/Cellar/php71/7.1.8_20/include/php/ext -I/usr/local/Cellar/php71/7.1.8_20/include/php/ext/date/lib -I/Users/kt/source/pthreads/. -DHAVE_CONFIG_H -g -O2 -c /Users/kt/source/pthreads/php_pthreads.c  -fno-common -DPIC -o .libs/php_pthreads.o
In file included from /Users/kt/source/pthreads/php_pthreads.c:26:
In file included from ./php_pthreads.h:31:
./classes/threaded.h:89:78: error: too few arguments provided to
      function-like macro invocation
  ...0, 0, _IS_BOOL, 0)
                      ^
/usr/local/Cellar/php71/7.1.8_20/include/php/Zend/zend_API.h:109:9: note: 
      macro 'ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX' defined here
#define ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(name, return_refere...
        ^
In file included from /Users/kt/source/pthreads/php_pthreads.c:26:
In file included from ./php_pthreads.h:31:
./classes/threaded.h:89:1: error: unknown type name
      'ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX'
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(Threaded_isGarbage, 0, 0, _...
^
./classes/threaded.h:90:1: error: expected identifier or '('
ZEND_END_ARG_INFO()
^
/usr/local/Cellar/php71/7.1.8_20/include/php/Zend/zend_API.h:120:30: note: 
      expanded from macro 'ZEND_END_ARG_INFO'
#define ZEND_END_ARG_INFO()             };
                                        ^
In file included from /Users/kt/source/pthreads/php_pthreads.c:26:
In file included from ./php_pthreads.h:31:
./classes/threaded.h:90:1: error: extraneous closing brace ('}')
/usr/local/Cellar/php71/7.1.8_20/include/php/Zend/zend_API.h:120:30: note: 
      expanded from macro 'ZEND_END_ARG_INFO'
#define ZEND_END_ARG_INFO()             };
                                        ^
In file included from /Users/kt/source/pthreads/php_pthreads.c:26:
In file included from ./php_pthreads.h:39:
./classes/collectable.h:20:81: error: too few arguments provided to
      function-like macro invocation
  ...0, 0, _IS_BOOL, 0)
                      ^
/usr/local/Cellar/php71/7.1.8_20/include/php/Zend/zend_API.h:109:9: note: 
      macro 'ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX' defined here
#define ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(name, return_refere...
        ^
In file included from /Users/kt/source/pthreads/php_pthreads.c:26:
In file included from ./php_pthreads.h:39:
./classes/collectable.h:20:1: error: unknown type name
      'ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX'
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(Collectable_isGarbage, 0, 0...
^
./classes/collectable.h:21:1: error: expected identifier or '('
ZEND_END_ARG_INFO()
^
/usr/local/Cellar/php71/7.1.8_20/include/php/Zend/zend_API.h:120:30: note: 
      expanded from macro 'ZEND_END_ARG_INFO'
#define ZEND_END_ARG_INFO()             };
                                        ^
In file included from /Users/kt/source/pthreads/php_pthreads.c:26:
In file included from ./php_pthreads.h:39:
./classes/collectable.h:21:1: error: extraneous closing brace ('}')
/usr/local/Cellar/php71/7.1.8_20/include/php/Zend/zend_API.h:120:30: note: 
      expanded from macro 'ZEND_END_ARG_INFO'
#define ZEND_END_ARG_INFO()             };
                                        ^
In file included from /Users/kt/source/pthreads/php_pthreads.c:26:
In file included from ./php_pthreads.h:51:
./classes/socket.h:47:76: error: too few arguments provided to
      function-like macro invocation
  ...0, 2, _IS_BOOL, 0)
                      ^
/usr/local/Cellar/php71/7.1.8_20/include/php/Zend/zend_API.h:109:9: note: 
      macro 'ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX' defined here
#define ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(name, return_refere...
        ^
In file included from /Users/kt/source/pthreads/php_pthreads.c:26:
In file included from ./php_pthreads.h:51:
./classes/socket.h:47:1: warning: type specifier missing, defaults to 'int'
      [-Wimplicit-int]
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(Socket_setOption, 0, 2, _IS...
^
./classes/socket.h:47:40: error: expected ';' after top level declarator
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(Socket_setOption, 0, 2, _IS...
                                       ^
                                       ;
./classes/socket.h:51:1: error: extraneous closing brace ('}')
ZEND_END_ARG_INFO()
^
/usr/local/Cellar/php71/7.1.8_20/include/php/Zend/zend_API.h:120:30: note: 
      expanded from macro 'ZEND_END_ARG_INFO'
#define ZEND_END_ARG_INFO()             };
                                        ^
In file included from /Users/kt/source/pthreads/php_pthreads.c:26:
In file included from ./php_pthreads.h:51:
./classes/socket.h:53:75: error: too few arguments provided to
      function-like macro invocation
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(Socket_getOption, 0, 2, IS_LONG, 0)
                                                                          ^
/usr/local/Cellar/php71/7.1.8_20/include/php/Zend/zend_API.h:109:9: note: 
      macro 'ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX' defined here
#define ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(name, return_refere...
        ^
In file included from /Users/kt/source/pthreads/php_pthreads.c:26:
In file included from ./php_pthreads.h:51:
./classes/socket.h:53:1: warning: type specifier missing, defaults to 'int'
      [-Wimplicit-int]
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(Socket_getOption, 0, 2, IS_LONG, 0)
^
./classes/socket.h:53:40: error: expected ';' after top level declarator
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(Socket_getOption, 0, 2, IS_LONG, 0)
                                       ^
                                       ;
./classes/socket.h:56:1: error: extraneous closing brace ('}')
ZEND_END_ARG_INFO()
^
/usr/local/Cellar/php71/7.1.8_20/include/php/Zend/zend_API.h:120:30: note: 
      expanded from macro 'ZEND_END_ARG_INFO'
#define ZEND_END_ARG_INFO()             };
                                        ^
In file included from /Users/kt/source/pthreads/php_pthreads.c:26:
In file included from ./php_pthreads.h:51:
./classes/socket.h:58:71: error: too few arguments provided to
      function-like macro invocation
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(Socket_bind, 0, 2, _IS_BOOL, 0)
                                                                      ^
/usr/local/Cellar/php71/7.1.8_20/include/php/Zend/zend_API.h:109:9: note: 
      macro 'ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX' defined here
#define ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(name, return_refere...
        ^
In file included from /Users/kt/source/pthreads/php_pthreads.c:26:
In file included from ./php_pthreads.h:51:
./classes/socket.h:58:1: warning: type specifier missing, defaults to 'int'
      [-Wimplicit-int]
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(Socket_bind, 0, 2, _IS_BOOL, 0)
^
./classes/socket.h:58:40: error: expected ';' after top level declarator
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(Socket_bind, 0, 2, _IS_BOOL, 0)
                                       ^
                                       ;
./classes/socket.h:61:1: error: extraneous closing brace ('}')
ZEND_END_ARG_INFO()
^
/usr/local/Cellar/php71/7.1.8_20/include/php/Zend/zend_API.h:120:30: note: 
      expanded from macro 'ZEND_END_ARG_INFO'
#define ZEND_END_ARG_INFO()             };
                                        ^
In file included from /Users/kt/source/pthreads/php_pthreads.c:26:
In file included from ./php_pthreads.h:51:
./classes/socket.h:63:73: error: too few arguments provided to
      function-like macro invocation
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(Socket_listen, 0, 2, _IS_BOOL, 0)
                                                                        ^
/usr/local/Cellar/php71/7.1.8_20/include/php/Zend/zend_API.h:109:9: note: 
      macro 'ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX' defined here
#define ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(name, return_refere...
        ^
In file included from /Users/kt/source/pthreads/php_pthreads.c:26:
In file included from ./php_pthreads.h:51:
./classes/socket.h:63:1: warning: type specifier missing, defaults to 'int'
      [-Wimplicit-int]
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(Socket_listen, 0, 2, _IS_BOOL, 0)
^
./classes/socket.h:63:40: error: expected ';' after top level declarator
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(Socket_listen, 0, 2, _IS_BOOL, 0)
                                       ^
                                       ;
fatal error: too many errors emitted, stopping now [-ferror-limit=]
4 warnings and 20 errors generated.
make: *** [php_pthreads.lo] Error 1
➜  pthreads git:(master) ✗

**Comment by tpunt** [comment]
Please see the README:
> Note that only PHP 7.2+ is now supported (requiring the current master branch of pthreads). This is due to safety issues with ZTS mode on PHP 7.0 and 7.1.

The last release (v3.1.6) could be used (unsafely) with PHP 7.0, but no release was made for PHP 7.1.
