### ISSUE TITLE
please help me setup pthread on linux

### ISSUE THREAD

**Issue by sallce** [krakjoe/pthreads#756]
*I hope someone can help me to install pthread on llinux system by using the master branch.*

Environment
==========

  * PHP:7
  * pthreads: master branch
  * OS: centos or ubuntu

**Comment by tpunt** [comment]
There are *so many* resources online showing how to build PHP extensions from source on Unix platforms - have you looked at any of these yet? The details on pthreads' version compatibility with PHP can also be found in the README of this repository.

In any case, the issue tracker is not the place to ask these questions. If you are still unable to build the correct environment to run pthreads, then ask for support on StackOverflow (perhaps give it a search first, too).
