### ISSUE TITLE
Static property access issues since ~1day

### ISSUE THREAD

**Issue by dktapps** [krakjoe/pthreads#757]
*If you know how to write phpt tests, please open a PR with environment information, and your test, this will cause CI to test your issue before a human is able to look*

Environment
==========

  * PHP: 7.2.0RC1
  * pthreads: https://github.com/krakjoe/pthreads/commit/b764eef259bfc5d9a39b42a668928dc6ff13a6aa
  * OS: Ubuntu Trusty (Travis CI worker image)

Summary
======
Since #755 was merged, our project's CI builds have been consistently failing. Build logs can be seen in https://travis-ci.org/pmmp/PocketMine-MP/builds/276584898 and any build since that commit was merged. (Our CI currently clones and builds pthreads' master branch.)

TL:DR
```
PHP Fatal error:  Uncaught Error: Access to undeclared static property: pmmp\TesterPlugin\tests\TestAsyncTask::$destroyed in /home/travis/build/pmmp/PocketMine-MP/plugins/PocketMine-TesterPlugin/src/pmmp/TesterPlugin/tests/AsyncTaskMemoryLeakTest.php:58
Stack trace:
#0 [internal function]: pmmp\TesterPlugin\tests\TestAsyncTask->__destruct()
#1 {main}
  thrown in /home/travis/build/pmmp/PocketMine-MP/plugins/PocketMine-TesterPlugin/src/pmmp/TesterPlugin/tests/AsyncTaskMemoryLeakTest.php on line 58
[19:03:12] [Server thread/CRITICAL]: RuntimeException: "pthreads detected an attempt to connect to an object which has already been destroyed" (EXCEPTION) in "src/pocketmine/scheduler/AsyncTask" at line 296
```

I don't know the exact cause of this issue yet, but the worker task responsible for this error can be seen here: https://github.com/pmmp/PocketMine-TesterPlugin/blob/master/src/pmmp/TesterPlugin/tests/AsyncTaskMemoryLeakTest.php#L50

Reproducing Code
==============
currently recompiling PHP so I can create a reproducing test case... TBD

**Comment by tpunt** [comment]
Thanks for the report. I've reverted the commit that I believe was the cause of this issue (95df2759388043dac1db60ab9ca8e70e8505eb6f), and I'll have a deeper look into this tomorrow. If this still hasn't fixed your problem, or if you do manage to find a short reproducing script, then please let me know!

**Comment by dktapps** [comment]
@tpunt Reverting that commit didn't solve the issue, however it works correctly after additionally reverting 277fd279e4f2149d505df17441f21243fc17d6a6 . I'll try and debug this further tomorrow.

Thanks.

**Comment by tpunt** [comment]
@dktapps Right, I've found one bug regarding statics:
```php
<?php

class C extends Threaded
{
    static $c = 1;
    public function run()
    {
        var_dump(static::$c);
    }
}

$w = new Worker();
$w->start();
$w->stack(new class extends C {});
$w->shutdown();
```

It requires an anonymous class that is unbounded and does not directly extend `Threaded`. Does this look like it could be the issue? I'll try to provide a fix for it later today.

**Comment by dktapps** [comment]
I'm not using anonymous classes anywhere, but I tested that snippet with and without https://github.com/krakjoe/pthreads/commit/277fd279e4f2149d505df17441f21243fc17d6a6 and they are behaving differently (no output with the statics commit). Something is definitely broken there.

I'm still trying to find out how to reproduce this outside of the project, but no success so far.

**Comment by dktapps** [comment]
@tpunt several headaches later, I came up with this test case (the symptoms aren't quite the same, no fatal error output, but the behaviour is similarly odd):

```php
<?php

declare(strict_types=1);

$worker = new \Worker();
$worker->start();

class TestAsyncTask extends ManInTheMiddle{
        public static $destroyed = false;

        public function run(){
                usleep(50 * 1000); //1 server tick
        }

        public function __destruct(){
                var_dump("hi");
                self::$destroyed = true;
                var_dump("bye");
        }
}

abstract class ManInTheMiddle extends \Threaded{}

error_reporting(-1);

$worker->stack($t = new TestAsyncTask());
while($worker->collect());
$worker->shutdown();
```

Expected output:
```
string(2) "hi"
string(3) "bye"
string(2) "hi"
string(3) "bye"
```

Actual output:
```
string(2) "hi"
string(2) "hi"
string(3) "bye"
```

It would appear that the same fatal error is occurring, but without any output, since the other `bye` is not output.

The bug does not occur if:
  - `TestAsyncTask` directly extends `Threaded`
  - `ManInTheMiddle` is declared _before_ `TestAsyncTask`
  - the `Worker` is created after the classes are declared.

**Comment by tpunt** [comment]
@dktapps Thanks for taking the time to create a reproducing script. I've decided to revert the specified commit, reapply my previous commit (with a few changes), and add a few more tests (including your snippet above) to ensure that we don't see this regression again in the future when refactoring the codebase.

If things still do not work, then please let me know.

**Comment by dktapps** [comment]
Looks like it's working now, thanks!
