### ISSUE TITLE
Is there any way to ensure thread safety used resource ?

### ISSUE THREAD

**Issue by superbogy** [krakjoe/pthreads#759]
I try to write a http server use php, when I close the
 socket, make `zend_mm_heap corrupted` error~! I had read history issue, it is sorry to hear that resource is not support.so, Is there any way to solution？

**Comment by wagnert** [comment]
Have a look at the [appserver-io/webserver](https://github.com/appserver-io/webserver) and the socket implementation used there. This also works with PHP 7.x

**Comment by userqq** [comment]
you can try pThreads' Socket class to build your own TCP listener.

```php
class Task extends Thread{
	protected $socket; 
	public function __construct($socket) {
		$this->socket = $socket;
	}
	public function run() {        
        $buffer = '';        
        if (!strpos($buffer, "\r\n\r\n")) {
            $buffer .= $this->socket->read(2048);
        }
        
        echo explode("\r\n\r\n", $buffer)[0] . PHP_EOL;
        
        $this->socket->write("HTTP 1.0 OK\r\n\r\nHelloWorld\r\n");
        $this->socket->close();
    }
}

$s = new Socket(AF_INET, SOCK_STREAM, SOL_TCP);
$s->bind('127.0.0.1', 1234);
$s->listen(0);
$s->setBlocking(false);

$pool = new Pool(8);

while (true) {
    try {
        $client = $s->accept();
        
        $pool->submit(new Task($client));
    } catch (\Exception $e) {
        // Uncaught RuntimeException: socket found in invalid state in ...
        // Nevermind
    }
}
```
and then you can start server by command
```bash
php -dextension=pthreads.so http.php
```

and test it with curl
```bash
curl -D - http://127.0.0.1:1234
```

**Comment by tpunt** [comment]
As mentioned above, pthreads has a new `Socket` class in the master branch that can do this. Current resources in PHP will likely never be thread safe.
