### ISSUE TITLE
Cannot access private const

### ISSUE THREAD

**Issue by prolic** [krakjoe/pthreads#760]
In a thread I am using a PHP 7.1 library which uses private consts. This leads to `Cannot access private const` fatal error.

Environment
==========

  * PHP: 7.2.0beta3*
  * pthreads: from master branch (3.1.7dev)*
  * OS: Ubuntu 16.04, amd64*

**Comment by SirSnyder** [comment]
Fixed with #746

**Comment by prolic** [comment]
nice, thanks! :)

**Comment by tpunt** [comment]
@prolic Can you please confirm that your issue has been fixed with the current master?

**Comment by prolic** [comment]
@tpunt Sorry for late reply. I can confirm that ... now nothing works anymore and I get segfaults.

Tested using PHP 7.2.0 (self compiled with zts) and pthreads (self-compiled from master) on Ubuntu 16.04.

My gdb backtrace is pretty useless:
```
(gdb) bt
#0  0x00007f04259a3bbc in ?? ()
#1  0x0000000000000000 in ?? ()
```

Steps to reproduce:
```
git clone https://github.com/prooph/event-store-benchmarks
cd event-store-benchmarks
vi .env
// make some adjustments
vi src/functions.php
// uncomment any db vendor you don't have installed (f.e. arangodb and mariadb if you only have mysql and postgres on your local)
php src/benchmark.php
```

**Comment by dktapps** [comment]
Is this bug still in effect with latest master changes?

**Comment by SirSnyder** [comment]
If the issue still exists, please reopen!
