### ISSUE TITLE
Pthreads in a web server with Nginx

### ISSUE THREAD

**Issue by luanorlandi** [krakjoe/pthreads#763]
Hi,

I successfully added pthreads and can run a script with thread in PHP CLI, but in a web server is still not being recognized:

`PHP Fatal error:  Class 'Thread' not found in path/to/file.php on line 25`

I restarted php, php-fpm and nginx services, but no changes were applied.

Does it require any other configuration? Maybe in Nginx config?

I know that pthreads is not available in Apache web server, but what about Nginx? From what I searched in discussions here, it looks like it's possible, could anyone please confirm that?

Environment
==========

  * PHP CLI and FPM: 7.1.2
  * pthreads: 3.1.7dev
  * OS: CentOS Linux release 7.2.1511 (Core)

**Comment by kilgor** [comment]
Maybe you use namespaces?
Try \Thread

From cli start php7-zts -m and give output
Show source of path/to/file.php on line 25

**Comment by pawaclawczyk** [comment]
Regarding the PHP version, 7.1 is not supported - https://github.com/krakjoe/pthreads#supported-php-versions
Regarding running as FPM, SAPI other than CLI is not supported -  https://github.com/krakjoe/pthreads#sapi-support

**Comment by luanorlandi** [comment]
Thanks @kilgor and @pawaclawczyk, I will reply to your comments in order:

I checked the directory path with `pwd`, no spaces found.

The command `php7-zts` is not recognized. I executed `php -v` and `php -m`, here is the full output:

```bash
$ php -v
Failed loading /usr/lib64/php/modules/opcache.so:  /usr/lib64/php/modules/opcache.so: undefined symbol: compiler_globals
PHP 7.1.2 (cli) (built: Sep 26 2017 13:58:02) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

$ php -m | grep pthreads
Failed loading /usr/lib64/php/modules/opcache.so:  /usr/lib64/php/modules/opcache.so: undefined symbol: compiler_globals
pthreads
```

I also tried `php-fpm -v` and `php-fpm -m` and it looks like php-fpm can't load pthreads extension, I'm going to look further on this today:

```bash
$ php-fpm -v
Cannot load Zend OPcache - it was already loaded
[03-Oct-2017 13:14:41] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/pthreads.so' - /usr/lib64/php/modules/pthreads.so: undefined symbol: sapi_globals_id in Unknown on line 0
PHP 7.1.2 (fpm-fcgi) (built: Feb 18 2017 11:24:49)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.2, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

$ php-fpm -m | grep pthreads
Cannot load Zend OPcache - it was already loaded
[03-Oct-2017 13:15:51] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/pthreads.so' - /usr/lib64/php/modules/pthreads.so: undefined symbol: sapi_globals_id in Unknown on line 0
```

The source file tested is this example of use with thread in PHP:
http://php.net/manual/en/thread.start.php

In CLI the result is the output expected, but in the web server the result is the `Class 'Thread' not found...`

I agree that it does not support PHP 7.1 (https://github.com/krakjoe/pthreads#supported-php-versions). But I'm using this release https://github.com/SirSnyder/pthreads/releases/tag/v3.1.7-beta.1, which is forked from this repository and works with PHP 7.1.2 (at least in CLI)

I found other issues in the past using PHP FPM with pthread (https://github.com/krakjoe/pthreads/issues/293 and https://github.com/krakjoe/pthreads/issues/339), but in previous versions of PHP.

I'm assuming that PHP 5 supported pthread in PHP-FPM with Nginx (or else those issues were invalid).
@pawaclawczyk, PHP 7 doesn't support pthread in any version for web server then? @krakjoe, can you please help confirm this?

**Comment by tpunt** [comment]
> I agree that it does not support PHP 7.1 (https://github.com/krakjoe/pthreads#supported-php-versions). But I'm using this release https://github.com/SirSnyder/pthreads/releases/tag/v3.1.7-beta.1, which is forked from this repository and works with PHP 7.1.2 (at least in CLI)

There's a good reason why we dropped support for PHP 7.0 and PHP 7.1. ZTS mode on these versions is not safe, where race conditions will likely cause your PHP applications to segfault. If you would like to continue using pthreads, then you should upgrade your PHP version. The only reason why that tagged release from the forked repo works is because it doesn't contain the latest commits from this repo's master branch (which removed support for PHP 7.1 and below for the aforementioned reason).

> I'm assuming that PHP 5 supported pthread in PHP-FPM with Nginx (or else those issues were invalid).

Pthreads didn't prevent you from loading the extension in a web server environment on PHP 5.x - instead, it just *strongly* recommended you *don't* do this. Pthreads on PHP 7.x now prevents you from loading it in a web server environment because it simply is not safe to do so and does not scale well (e.g. creating one or more threads per PHP request will quickly inundate your web server).

> PHP 7 doesn't support pthread in any version for web server then? @krakjoe, can you please help confirm this?

Can confirm. Please keep usage of pthreads to CLI-based applications only.

**Comment by Valehero** [comment]
If you REALLY want to run pthreads from WEB Server use:

```
<?php
	echo shell_exec('php my-pthreads.php');
?>

```
