### ISSUE TITLE
Pthreads detected an attempt to connect to an object which has already been destroyed

### ISSUE THREAD

**Issue by sdjnsfijsdoiukjl** [krakjoe/pthreads#765]
<?php
    $v = new Volatile;
    
    $t = new class($v) extends Thread
    {
       function __construct(Volatile $v)
       {
          $this->v = $v;
       }
    
       function run()
       {
         $this->v[] = "str";
       }
    };
    
    $t->start(); $t->join();
    
    var_dump($v);

Dump:

    object(Volatile)#1 (1) {
      [0]=>
      string(3) "str"
    }

If I do this:
    
    <?php
    $v = new Volatile;
    
    $t = new class($v) extends Thread
    {
       function __construct(Volatile $v)
       {
          $this->v = $v;
       }
       
       function run()
       {
          $this->v[] = ["array" => ["test"]];
       }
    };
    
    $t->start(); $t->join();
    
    var_dump($v);

Error:

> Fatal error: Uncaught RuntimeException: pthreads detected an attempt
> to connect to an object which has already been destroyed

How to fix this code?

It is also not working:
```php
$this->v[] = (array) ["array" => ["test"]];
```

**Comment by tpunt** [comment]
> It is also not working:
> ```php
> $this->v[] = (array) ["array" => ["test"]];
> ```

Your code works fine for me when using the explicit `(array)` cast. What version of pthreads and PHP are you using?

**Comment by sdjnsfijsdoiukjl** [comment]
@tpunt PHP 7.2.0RC1 (cli) (built: Sep  2 2017 18:01:34) ( ZTS )

the latest version of pthreads from github

**Comment by sdjnsfijsdoiukjl** [comment]
And how to fix this code? The same error (`pthreads detected an attempt
to connect to an object which has already been destroyed`)

`test` class must inherit from Volatile

```php
class test extends Volatile
{
	public $value;
	function __construct()
	{
		$this->value = rand();
	}
}

$th = new class extends Thread
{
	public $s;
	function run()
	{
		$this->s = new test;
	}
};
$th->start();
$th->join();

var_dump($th->s);
```

**Comment by tpunt** [comment]
> And how to fix this code?

`Threaded` objects are tied to the context in which they are created. This means that the Volatile object contained in `$this->s` is tied to the context of the spawned thread (the context being the scope of the `Thread::run` method). Upon joining this thread, `$this->s` becomes invalid. If you would like to use it in the outer context, then the `test` class needs to be instantiated in the outer thread (e.g. in the constructor).

Regarding your original problem, I'm still pessimistic that the following code throws an error:
```php
<?php
$v = new Volatile;

$t = new class($v) extends Thread
{
   function __construct(Volatile $v)
   {
      $this->v = $v;
   }

   function run()
   {
      $this->v[] = (array)["array" => ["test"]];
   }
};

$t->start(); $t->join();

var_dump($v);
```

Can you run the above again please?

**Comment by sdjnsfijsdoiukjl** [comment]
@tpunt Error:

```
Fatal error: Uncaught RuntimeException: pthreads detected an attempt to connect to an object which has already been destroyed in /home/e.php:19
Stack trace:
#0 /home/e.php(19): var_dump(Object(Volatile))
#1 {main}
  thrown in /home/e.php on line 19
```

**Comment by sdjnsfijsdoiukjl** [comment]
This only works with (object)

```php
<?php
$v = new Volatile;

$t = new class($v) extends Thread
{
   function __construct(Volatile $v)
   {
      $this->v = $v;
   }

   function run()
   {
      $this->v[] = (object)["array" => ["test"]];
   }
};

$t->start(); $t->join();

var_dump($v);
```

```
object(Volatile)#1 (1) {
  [0]=>
  object(stdClass)#3 (1) {
    ["array"]=>
    array(1) {
      [0]=>
      string(4) "test"
    }
  }
}
```

**Comment by tpunt** [comment]
@sdjnsfijsdoiukjl Are you still having these same problems with the current master branch? If so, could you show me what the following outputs for you:
```php
<?php
$v = new Volatile;

$t = new class($v) extends Thread
{
    function __construct(Volatile $v)
    {
        $this->v = $v;
    }

    function run()
    {
        $this->v[] = (array)["array" => ["test"]];
    }
};

$t->start();
while (!isset($v[0]));
var_dump($v);
$t->join();
```

**Comment by SirSnyder** [comment]
If the issue still exists, please reopen!
