### ISSUE TITLE
Change the properties of the class not working

### ISSUE THREAD

**Issue by sdjnsfijsdoiukjl** [krakjoe/pthreads#767]
Pthreads: 3.1.7dev

PHP 7.2.0RC1 (cli) (built: Sep  2 2017 18:01:34) ( ZTS )
Zend Engine v3.2.0-dev, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.2.0RC1, Copyright (c) 1999-2017, by Zend Technologies

```php
$storage = new Volatile;

class Test
{
   public $property =
   [
      0 => [],
   ];
}

$storage["test"] = new Test;
$storage["test"]->property[0][] = "123";

var_dump($storage["test"]);
```

Dump:
```php
object(Test)#10 (1) {
  ["property"]=>
  array(1) {
    [0]=>
    array(0) {
    }
  }
}
```

Expected dump:
```php
object(Test)#11 (1) {
  ["property"]=>
  array(1) {
    [0]=>
    array(1) {
      [0]=>
      string(3) "123"
    }
  }
}
```

**Comment by SirSnyder** [comment]
Class `Test` is not threadable and therefore gets serialized. Extend `Test` by `Threaded` or `Volatile` to get rid of this issue. If the issue still exists, please reopen!
