### ISSUE TITLE
PHP 7.1 x64 on Windows Server 2016  Unable to load dynamic library

### ISSUE THREAD

**Issue by denniskrol** [krakjoe/pthreads#775]
Environment
==========

  * PHP:  PHP 7.1.9 (cli) (built: Aug 30 2017 18:34:46) ( ZTS MSVC14 (Visual C++ 2015) x64 )
  * pthreads: php_pthreads-3.1.7-beta.1-7.1-ts-vc14-x64
  * OS: Windows Server 2016 x64

Summary
======

I downloaded this build: https://github.com/SirSnyder/pthreads/releases/tag/v3.1.7-beta.1 which works on my Windows 10 desktop with the same PHP version.
On Server 2016 I get:

PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\Program Files\PHP\ext\php_pthreads.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\Program Files\PHP\ext\php_pthreads.dll' - The specified module could not be found.
 in Unknown on line 0

The extension is in C:\Program Files\PHP\ext\. I put pthreadVC2.dll in the PHP directory ('C:\Program Files\PHP), which is in my path, because php -v works in the commandline.

This used to work, I reinstalled the server, copied everything back, and now it doesn't. I am probably doing something stupid, but I can't figure it out. 
PHP is 7.1, thread safe, VC14, x64, so that should work.

**Comment by dktapps** [comment]
> Note that only PHP 7.2+ is now supported (requiring the current master branch of pthreads). This is due to safety issues with ZTS mode on PHP 7.0 and 7.1.

**Comment by tpunt** [comment]
As mentioned above (as well as in the readme, php docs, etc), we do not support PHP 7.1. If you are using someone else's fork of this repo, then you should open the issue on their fork.
