### ISSUE TITLE
socket_recvfrom()/socket_sendto() equivalents?

### ISSUE THREAD

**Issue by dktapps** [krakjoe/pthreads#776]
Environment
==========
  * PHP: 7.2.0RC5
  * pthreads: 3.1.7dev (https://github.com/krakjoe/pthreads/commit/1c9787e5d918a3602661290ff5efe32ba3df74c8)
  * OS: Windows 10 (x64)

Summary
======
There don't appear to be any equivalents for the `socket_recvfrom()` and `socket_sendto()` functions in PHP sockets. This presents a problem when wanting to work with connectionless protocols (like UDP).

**Comment by SirSnyder** [comment]
@dktapps could you test the PR, please?
