### ISSUE TITLE
Segfault when using a class with a constant and PTHREADS_INHERIT_NONE

### ISSUE THREAD

**Issue by angstymeat** [krakjoe/pthreads#782]
Environment
==========

  * PHP:
```
PHP 7.2.0 (cli) (built: Nov 28 2017 20:29:04) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.2.0, Copyright (c) 1999-2017, by Zend Technologies
```

  * pthreads:
```
Version => 3.1.7dev
```

  * OS:
```
Linux 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Summary
======

When using a class that contains a constant, starting a thread with PTHREADS_INHERIT_NONE causes a segfault.

This worked correctly with a09f289da09aa587a8baa251b7dd7d71852977a1, but appears to have broken with 4c978ec98ff2c0406d61d905000dbd9ee08b860c.

Reproducing Code
==============

```
<?php

class testClass extends \Thread {

  const TEST_CONSTANT=0x00;

  public function run() {
    echo "Hey!\n";
  }

}

$x = new testClass();
$x->start(PTHREADS_INHERIT_NONE);
$x->join();
```

Expected Output
=============

```
Hey!
```

Actual Output
============
```
Segmentation fault
```

**Comment by SirSnyder** [comment]
Will push a fix later today

**Comment by angstymeat** [comment]
Thanks!

For right now, I'm just running with 4c978ec98ff2c0406d61d905000dbd9ee08b860c patched-out.

**Comment by krakjoe** [comment]
@SirSnyder you have been given write access to this repo, your point of contact for queries is Thomas ...

Thank you guys for putting in the effort, it's appreciated ...

**Comment by SirSnyder** [comment]
@krakjoe thanks for the invite. I'am happy to support this great project!

@angstymeat could you test PR #783, please?

**Comment by angstymeat** [comment]
It fixes the example code I posted, but not it fails if I try to access the constant inside of synchronized() like:
```
class baseTest extends \Thread {

  const TEST_CONSTANT = 0x00;

  public function test() {
    $this->synchronized(function () {
      echo "Test Constant: " . self::TEST_CONSTANT . "\n";
    });
  }

}

class testClass extends baseTest {

  protected $testVal;

  public function __construct() {
    $this->testVal = self::TEST_CONSTANT;
  }

  public function run() {
    echo "Hey!\n";
    echo "Constant: " . self::TEST_CONSTANT . "\n";
    $this->test();
  }

}

$x = new testClass();
$x->start(PTHREADS_INHERIT_NONE);
$x->join();
```

With the above, it fails with ``` Uncaught Error: Undefined class constant 'TEST_CONSTANT'```.

It works if I specify ```$this::TEST_CONSTANT```.

**Comment by SirSnyder** [comment]
@angstymeat should be fixed now, can you confirm it?

**Comment by angstymeat** [comment]
Trying it now, I'll post an update in a few minutes.

**Comment by angstymeat** [comment]
That appears to be working for my test code and my project!

**Comment by SirSnyder** [comment]
Great! Thx for reporting this issue.
