### ISSUE TITLE
need explaination: contradiction between readme and pthreads.org

### ISSUE THREAD

**Issue by OussamaElgoumri** [krakjoe/pthreads#789]
this is not a technical issue, but a request for clarification.. so please read on:

on the readme pthreads said:

> 
pthreads v3 is restricted to operating in CLI only: I have spent many years trying to explain that threads in a web server just don't make sense, after 1,111 commits to pthreads I have realised that, my advice is going unheeded.

but on pthreads.org 

> Being able to thread in PHP makes it a real candidate for enterprising applications, and it'll make your personal home page be able to do things it simply didn't have the time to do before.

also

> when developing enterprising web applications we often find ourselves looking to other fully fledged languages and frameworks to write backend, or data-centric web applications because PHP isn't able to take advantage of the hardware we have at our disposal

if i understand correctly, the website present pthreads as a solution to threading web applications, but in the readme and every article i find it said that it should only be used in the CLI!

please explain once and for all the technical difference, and where and where not pthread should be used, and what kind of application should be used with, for example when used on the CLI with GuzzleHttp it throws the CORE and segmentation falt, with no errors.

Thank you

**Comment by robske110** [comment]
The website is mostly referring to BACKEND php applications, which run in the CLI. You should not use pthreads inside a web server (e.g. Apache).

**Comment by tpunt** [comment]
Threading is not a suitable tool to be used in *any* environment where you do not have *direct* control over the concurrency of such an environment. Traditional web servers are just one of these environments, where they will use their own heuristics to determine how many process or threads should be used to handle web requests concurrently.

For example, if you have a PHP script that spawns 4 threads, and you do not have control over how that script is executed (with respect to concurrency), then the web server could be executing that script 25 times *at the same time*, causing 100 threads to be spawned on your machine. This is not desirable, nor suitable regarding scalability.

With respect to the following quotes:
> Being able to thread in PHP makes it a real candidate for enterprising applications, and it'll make your personal home page be able to do things it simply didn't have the time to do before.

That could be referring to multithreaded job/message queues written in PHP. If it's not being executed by the web server, then it's perfectly fine to augment your web application with multithreaded tools and libraries.

> when developing enterprising web applications we often find ourselves looking to other fully fledged languages and frameworks to write backend, or data-centric web applications because PHP isn't able to take advantage of the hardware we have at our disposal

If you control the concurrency (i.e. having the entire web stack written in PHP), then there's nothing wrong with this.

Anyway, the information on pthreads.org is currently in need of updating, which is being tracked in issue #709. So maybe it will be rephrased then.

> for example when used on the CLI with GuzzleHttp it throws the CORE and segmentation falt, with no errors

That sounds like either a misuse of pthreads (such as trying to pass around resources between threads), or a bug in pthreads itself. It's difficult to say without any reproducing code (please do feel free to submit it as another bug report if you can provide a small reproducing script).

Finally, please keep such questions to StackOverflow. The pthreads issue tracker is only for the development of pthreads itself.
