### ISSUE TITLE
Segmentation fault with call GuzzleHttp\Client

### ISSUE THREAD

**Issue by designh2o** [krakjoe/pthreads#790]
Hi. A segmentation fault error occurs if you call the creation of an object of class GuzzleHttp \ Client (http://guzzlephp.org/) in the code. The error occurs in any example from the /examples/ folder, if at the beginning (or in the Threaded thread itself) call $guzzleClient = new GuzzleHttp\Client([]); 
How can I solve the problem?

Environment
==========

  * PHP: PHP 7.3.0-dev (cli) (built: Dec 20 2017 10:00:34) ( ZTS DEBUG )
  * pthreads: Version => 3.1.7dev
  * OS: Ubuntu 16.04.1 LTS , x86_64

Reproducing Code
==============
//example Synchronization.php
require __DIR__.'/../vendor/autoload.php';
$guzzleClient = new GuzzleHttp\Client([]);
$thread = new class extends Thread {
	public function run() {
		
		$this->synchronized(function(){
			$this->awake = true;
			$this->notify();
		});
	}
};

$thread->start();
$thread->synchronized(function() use($thread) {
	while (!$thread->awake) {
		$thread->wait();
	}
});
$thread->join();

Expected Output
=============

Actual Output
============

Segmentation fault

**Comment by tpunt** [comment]
This was caused due to the infinite recursion problem in the thread preparation logic. This has now been fixed, so I am closing this. Thanks for the report.
