### ISSUE TITLE
Can anyone help me understanding of Pool::collect?

### ISSUE THREAD

**Issue by liesauer** [krakjoe/pthreads#791]
```php
<?php

ini_set("memory_limit", -1);

$pool = new Pool(50);

for ($i = 0; $i < 100000; $i++) {
    $pool->submit(new Threaded());
    // while ($pool->collect()); // 12M
}

// while ($pool->collect()); // 46M
$pool->shutdown();

echo 'done';
sleep(600);

```

i can't understand why take me more mem after submitting all works, and how can i free them.
(i get mem usage from task manager)

**Comment by tpunt** [comment]
The `::collect()` method garbage collects items that have finished executing in the pool (or by the worker). It should be run after the pool has finished executing to cleanup all used resources, though ideally it would be run periodically to prevent memory usage from getting too high. I wrote some more about this in my [Parallel Programming with Pthreads in PHP – the Fundamentals](https://www.sitepoint.com/parallel-programming-pthreads-php-fundamentals/) article.

Also, please keep such questions to StackOverflow (where you should also receive quicker replies).
