### ISSUE TITLE
PTHREADS on Window 10 on PHP 7.2

### ISSUE THREAD

**Issue by juliocoliveira** [krakjoe/pthreads#792]
I installed this extension and now I'm getting this error:
![capture](https://user-images.githubusercontent.com/6606725/34358834-289eb2fa-ea3a-11e7-9a6c-1122e3b9d91d.PNG)

Environment
==========

  * PHP: 
```
PHP 7.2.0 (cli) (built: Nov 28 2017 23:48:49) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
```
  * pthreads: http://windows.php.net/downloads/pecl/releases/pthreads/3.1.6/php_pthreads-3.1.6-7.0-ts-vc14-x64.zip
  * OS:  Windows 10 (v 1709) 16229.125

**Comment by damaainan** [comment]
php_pthreads no support php7.1 and php7.2 , php_pthreads.dll no one todo .

**Comment by nmapx** [comment]
3.1.6 won't work with 7.2

**Comment by tpunt** [comment]
As mentioned, the version you attempted to use was not compatible with PHP 7.2. The latest snapshot linked above (which was from the master branch a little while ago, despite being tagged as version 3.1.6) may work for you if you are not able to build from source.

The release of a new version of pthreads is currently being tracked in another issue, so I'm going to close this one.
