### ISSUE TITLE
cannot install pthread extension

### ISSUE THREAD

**Issue by harrisdt15f** [krakjoe/pthreads#793]
Environment
==========
PHP 7.2.1 (cli) (built: Jan  6 2018 14:46:18) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2017 Zend Technologies
 
pthread  version is 3.1.6 and I downloaded it from https://pecl.php.net/get/pthreads-3.1.6.tgz

OS 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

Summary
======
Because of the requirement, I re-installed upgrade to version 7.2.1
I don't know how to install it in php7.2.1.  Please help me or guide me. Thanks a lots.

Reproducing Code
==============

Expected Output
=============

Actual Output
============

sudo make install
/bin/bash /home/harris/php-7.2.1/libtool --silent --preserve-dup-deps --mode=compile /home/harris/php-7.2.1/meta_ccld -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Iext/pthreads-3.1.6/ -I/home/harris/php-7.2.1/ext/pthreads-3.1.6/ -DPHP_ATOM_INC -I/home/harris/php-7.2.1/include -I/home/harris/php-7.2.1/main -I/home/harris/php-7.2.1 -I/home/harris/php-7.2.1/ext/date/lib -I/usr/include/libxml2 -I/home/harris/php-7.2.1/ext/sqlite3/libsqlite -I/home/harris/php-7.2.1/ext/pthreads-3.1.6 -I/home/harris/php-7.2.1/TSRM -I/home/harris/php-7.2.1/Zend  -D_REENTRANT  -I/usr/include -g -fvisibility=hidden -pthread -O0 -Wall -DZTS -DZEND_SIGNALS   -c /home/harris/php-7.2.1/ext/pthreads-3.1.6/php_pthreads.c -o ext/pthreads-3.1.6/php_pthreads.lo 
libtool: Version mismatch error.  This is libtool 2.4.6 Debian-2.4.6-0.1, but the
libtool: definition of this LT_INIT comes from an older release.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6 Debian-2.4.6-0.1
libtool: and run autoconf again.
Makefile:929: recipe for target 'ext/pthreads-3.1.6/php_pthreads.lo' failed
make: *** [ext/pthreads-3.1.6/php_pthreads.lo] Error 63

**Comment by dktapps** [comment]
3.1.6 isn't compatible with PHP > 7.0, you need to use the master branch for 7.2.

**Comment by nmapx** [comment]
@dktapps is it hard to release 3.1.7 with 7.2 fix?

**Comment by harrisdt15f** [comment]
Is this branch is master branch? I tried with the below link also not working, please guide me. Thanks.
https://github.com/krakjoe/pthreads.git

**Comment by nmapx** [comment]
@harrisdt15f 
```bash
# clone the repository (master branch only)
git clone -b master --single-branch git@github.com:krakjoe/pthreads.git
# then compile the extension
```

**Comment by harrisdt15f** [comment]
I will try it , thanks

**Comment by tpunt** [comment]
It looks like you've gotten your answer, so I'm closing this. I've also added build instructions to the project README for Unix-based OSs.

**Comment by gldneagl** [comment]
@nmapx 

Your solution from Jan. 6 no longer works due an authentication issue.

"Cloning into 'pthreads'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access right
and the repository exists."

This is the third time I have found this suggested solution using Google and still it does not work.

**Comment by nmapx** [comment]
@gldneagl 
Have you tried pulling the repository using `https` protocol? It seems you have an authentication issue.
