### ISSUE TITLE
`new Socket(...)` fails on Windows with `Error (0): unknown`

### ISSUE THREAD

**Issue by dktapps** [krakjoe/pthreads#798]
Environment
==========

  * PHP: 7.2.1
  * pthreads: https://github.com/krakjoe/pthreads/commit/43ffd00a70dd6c737af8b3a1e827f20ca5e033b9
  * OS: Windows 10 x64

Reproducing Code
==============
```php
$socket = new \Socket(AF_INET, SOCK_DGRAM, SOL_UDP);
```

Expected Output
=============
This bug only appears to occur on Windows (the Ubuntu machine I tested worked fine).
```
Fatal error: Uncaught RuntimeException: Error (0): unknown in [script]
```

Actual Output
============
nothing

**Comment by SirSnyder** [comment]
Do you know the last working commit?

**Comment by dktapps** [comment]
@SirSnyder I don't, but last time I tested this (a couple of months ago, when I opened #776 ) it wasn't working either. I didn't have chance to test further or report at the time. I guess tests for Socket would be good.

**Comment by dktapps** [comment]
This appears to be because of the definition of `php_socket_t`. On Windows, it's ultimately defined as an unsigned int32/64, whereas on unix it is signed. Result is that [this check](https://github.com/krakjoe/pthreads/blob/master/src/socket.c#L71) always fails on Windows, even when a valid socket descriptor is returned.

When it fails, Windows returns always returns `INVALID_SOCKET`, which is defined as `(~0)`. php-src checks for this using the `IS_INVALID_SOCKET` macro, but pthreads does not.

![image](https://user-images.githubusercontent.com/14214667/34905209-fae927e4-f84b-11e7-9f5a-a62a6ace2001.png)
