### ISSUE TITLE
Windows memory issues

### ISSUE THREAD

**Issue by dktapps** [krakjoe/pthreads#822]
Environment
==========

  * PHP: 7.2.2
  * pthreads: https://github.com/krakjoe/pthreads/commit/866ed9b671bbae9acd9207e6d9d0a1fee890addf
  * OS: windows 10 x64

Summary
======
Run the below code for a while on Windows. Watch the memory usage in TaskManager.

This issue does not occur when I tested the same code on Ubuntu 17.10; it appears to be Windows-specific.

Given 10 minutes or so the memory usage reaches ~1GB on my machine.

`memory_get_usage()` on both threads does not give any indication that there is a problem (both report roughly static memory usages).

Reproducing Code
==============
```php
<?php

ini_set('memory_limit', '256M');
gc_enable();

class Test extends Threaded{}

$worker = new class extends Worker{
	public function run(){
		ini_set('memory_limit', '256M');
		gc_enable();
	}
};
$worker->start();

while(true){
    $function = new Test();

    $worker->stack($function);
    while($worker->collect());
}
```

Expected Output
=============
Memory usage should remain stable, as it does on Ubuntu.

Actual Output
============
Memory usage steadily grows the longer the script is running.

**Comment by snowleopard24** [comment]
@dktapps , @tpunt When do you think we could be ready with a snapshot PECL build of pthread with php 7.2 for windows?

**Comment by dktapps** [comment]
see #814

**Comment by CXW0504** [comment]
Environment
php :  
PHP 7.2.8 (cli) (built: Jul 18 2018 10:03:03) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
pthreads: php_pthreads-3.1.6-7.2-ts-vc15-x64.zip
OS: win7 企业版   service pack 1
-----------------------------------------------------------------------------------------
Run the same code for a while on Windows.found the same bug.

**Comment by CXW0504** [comment]
Environment
php :
PHP 7.2.8 (cli) (built: Jul 18 2018 10:03:03) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
pthreads: php_pthreads-3.1.6-7.2-ts-vc15-x64.zip
OS: win7 企业版 service pack 1

Run the same code for a while on Windows.found the same bug.

**Comment by CXW0504** [comment]
Environment
php :
PHP 7.2.8 (cli) (built: Jul 18 2018 10:03:03) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
pthreads: php_pthreads-3.1.6-7.2-ts-vc15-x64.zip
OS: win7 企业版 service pack 1

Run the same code for a while on Windows.found the same bug
@dktapps , @tpunt

**Comment by dktapps** [comment]
#846 fixes this bug, but the project maintainers are unfortunately inactive.

**Comment by SirSnyder** [comment]
I will be back in the project in a few weeks
