### ISSUE TITLE
Problem to install pthreads on windows 10

### ISSUE THREAD

**Issue by darvin123** [krakjoe/pthreads#849]
I'm trying install the pthreads without success.

My version of PHP is: PHP 7.2.3 (cli)
My Windows is: Windows 10 Pro 64 bits

What I've made is:

1 - Download the lib from here: https://windows.php.net/downloads/pecl/releases/pthreads/3.1.6/
2 - I've added the file pthreadVC2.dll in my "C:\php" folder
3 - I've added the file php_pthreads.dll in my "C:\php\ext"folder
4 - I've modified the file php.ini, enabling the extension:

```
extension=php_pthreads.dll
```

After this, I've created a folder in my desktop with a PHP file containing this code:

```
<?php
$thread = new class extends Thread {
	public function run() {
		echo "Hello World\n";
	}
};

$thread->start() && $thread->join();
?>

```

I've went in the CMD and made:

```
php teste.php
```

But I get the following error: 

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_pthreads.dll' (tried: C:\php\ext\php_pthreads.dll (NÒo foi possÝvel encontrar o m¾dulo especificado.), C:\php\ext\php_php_pthreads.dll.dll (NÒo foi possÝvel encontrar o m¾dulo especificado.)) in Unknown on line 0
PHP Fatal error:  Class 'Thread' not found in C:\Users\Darvin\Desktop\Teste\teste.php on line 2

```

Someone can help me please?

**Comment by robske110** [comment]
pthreads 3.1.6 is not compatible with php 7. Use master.

**Comment by darvin123** [comment]
i didn't understand, I've used the branch master that is the default branch in this repository.
![master](https://user-images.githubusercontent.com/37346873/37566698-9a40c050-2a9b-11e8-86c3-b32c74b05b58.png)

**Comment by robske110** [comment]
well, you have to rebuild pthreads from the master branch.
The 3.1.6 version does not support php 7.2

**Comment by elcantador** [comment]
hi what do you mean by rebuild pthreads from the master branch ? (there's no pthreadVC2.dll and no php_pthreads.dll ?)

**Comment by dana321** [comment]
Ok, i have to explain this - the snaps folder contains 3.1.6 which supports pthreads 7.2, the other 3.1.6 version in the releases folder only supports 7.0 ( check the filename and you will see what i mean)

https://windows.php.net/downloads/pecl/snaps/pthreads/3.1.6/

**Comment by onlynoiseonwires** [comment]
Could you please build some binaries with VC15? Cuz it's said pthreads isn't supported by PHP 7.0 and 7.1 due ZTS mode issues, and PHP 7.2+ builds are by default VC15.

**Comment by dana321** [comment]
> 
> 
> Could you please build some binaries with VC15? Cuz it's said pthreads isn't supported by PHP 7.0 and 7.1 due ZTS mode issues, and PHP 7.2+ builds are by default VC15.

Build them yourself, its not rocket science!

**Comment by dktapps** [comment]
You can download prebuilts for the master branch from the AppVeyor build job [here](https://ci.appveyor.com/project/krakjoe/pthreads/branch/master) (click on the job, go to Artifacts, download the zip), but note that the AppVeyor builds require both vc++redist 2010 AND 2017 (due to outdated pthreadvc2 dll).

**Comment by SirSnyder** [comment]
Release [v3.2.0](https://github.com/krakjoe/pthreads/releases/tag/v3.2.0) is live. You will find *.dlls in the release. Alternatively is an official pecl [snapshot](https://windows.php.net/downloads/pecl/snaps/pthreads/3.2.0/) available.

**Comment by Shubham7020** [comment]
> Ok, i have to explain this - the snaps folder contains 3.1.6 which supports pthreads 7.2, the other 3.1.6 version in the releases folder only supports 7.0 ( check the filename and you will see what i mean)
> 
> https://windows.php.net/downloads/pecl/snaps/pthreads/3.1.6/

i try what you said that but it still show class not found error (my vc is 15 and system is x64)

**Comment by Pax125** [comment]
I am using XAMPP v3.2.2. How can I know which pthreads version is compatible with XAMPP v3.2.2
https://windows.php.net/downloads/pecl/releases/pthreads/

Already tried php_pthreads-3.0.7-7.0-ts-vc14-x64 and php_pthreads-3.1.6-7.0-ts-vc14-x64 which does not work.
