### ISSUE TITLE
Getting Error when using pthread for php5.3.5

### ISSUE THREAD

**Issue by boyapatimoni** [krakjoe/pthreads#85]
I have downloaded the dll file from http://windows.php.net/downloads/pecl/releases/pthreads/ and enabled it in php.ini as below:
extension=pthreadVC2.dll
extension=php_pthreads.dll

I have thread safety enabled in phpinfo().

I have used the sample code given in the link: https://github.com/krakjoe/pthreads.When I execute the php file got error:

   Fatal error: Class 'Thread' not found in C:\htdocs\threads\AsyncOperation.php 
    on line 2 Call Stack: 0.0008 333464 1. {main}() 
    C:\htdocs\threads\AsyncOperation.php:0

should i configure anything else? Please help me

**Comment by pthreadVC2** [comment]
I'm using apach2.2.21 and php5.3.8 VC9, (x32).
everything is ok, exept when i use this line : extension=pthreadVC2.dll
i try to restart my server, but it's broken it won't start.
and when i take it off, my php.ini be like :
;extension=pthreadVC2.dll
extension=php_pthreads.dll
, it works fine.

if i use php -m, it gives me pthreads as loaded module.

please any suggestions.
