### ISSUE TITLE
pthreads installation get error 

### ISSUE THREAD

**Issue by sondangpangrib** [krakjoe/pthreads#856]
Hi.. all 
i using windows 64bit with php 7.1.9 instal pthread with no luck and i get this error..
Module compiled with module API=20151012
PHP    compiled with module API=20160303
php info: https://prnt.sc/j13ceu
and install this : https://windows.php.net/downloads/pecl/releases/pthreads/3.1.6/php_pthreads-3.1.6-7.0-ts-vc14-x64.zip

whats wrong ??

Thanks and regard
sondang

**Comment by tpunt** [comment]
When installing an extension, you must make sure that the extension is built for the correct minor version of PHP. In this case, you're trying to load a module compiled against PHP 7.0 for your PHP installation (PHP 7.1), hence the mismatch in API version numbers.

And as specified in the README, PHP 7.1 is not supported. You will need to use PHP 7.2 and above.
