### ISSUE TITLE
New thread doesn't start if the same variable is used

### ISSUE THREAD

**Issue by vchik** [krakjoe/pthreads#862]
Compare two pieces of code.

The first one is using the same variable named `$thread`. In this case threads start one-by-one.

The second one is using different variable named `$thread2`. In this case threads start simultaneously. 

How can it be explained? 

```
<?php

class T extends \Thread
{
    public function run()
    {
        echo 'in ';
        sleep(3);
        echo 'out ';
    }
}

$thread = new T();
$thread->start();

$thread = new T();
$thread->start();

echo 'main ';
```

Output: in out in main out 

```
<?php

class T extends \Thread
{
    public function run()
    {
        echo 'in ';
        sleep(3);
        echo 'out ';
    }
}

$thread = new T();
$thread->start();

$thread2 = new T();
$thread2->start();

echo 'main ';
```

Output: in main in out out

**Comment by dktapps** [comment]
If I remember correctly, pthreads tries to join threads when they go out of scope, which will block the main thread until the thread stops. In the top example you destroy all refs to the first thread when you overwrite the `$thread` variable with a new object.

**Comment by SirSnyder** [comment]
If the issue still exists, please reopen!
