### ISSUE TITLE
malloc_consolidate(): invalid chunk size 

### ISSUE THREAD

**Issue by 1722393429** [krakjoe/pthreads#868]
*If you know how to write phpt tests, please open a PR with environment information, and your test, this will cause CI to test your issue before a human is able to look*

Environment
==========

  * PHP: *can be obtained with ```php -v```*
  * pthreads: *can be obtained with ```php -dextension=pthreads.so --ri pthreads | grep Version```*
  * OS: *if Windows, include arch*

Summary
======

A summary isn't always necessary, code > words ... delete this section, as applicable.

Reproducing Code

May  7 14:27:55 cjj kernel: [18057.756830] traps: php[27613] general protection ip:7fc592877782 sp:7fc4e5ffe430 error:0 in libc-2.27.so[7fc5927f7000+1b1000]
==============

Bug reports *must* come with reproducing code, please ensure code is formatted correctly.

If the code cannot be a single script, please link to a gist, or a github repository containing the reproducing code. 

Please, do not link to application repositories.

*Please ensure code is self contained, and executable: if the code cannot be executed, the bug cannot be reproduced.*

Expected Output
=============

Please include the expected output, properly formatted.

Actual Output
============

Please include the actual output, properly formatted.

**Comment by SirSnyder** [comment]
If you have a running example or code to reproduce, please reopen
