### ISSUE TITLE
The threads do not complement

### ISSUE THREAD

**Issue by anajo333** [krakjoe/pthreads#871]
Hello
I have a problem using pthreads
I making web requests with curl
When I'm out for 500 threads
This error appears to me
The CLI depends
Is it a way to skip
Most threads are successfully completed
I think the thread
It still has a presence in the class
Is there a solution please
The project must be delivered within a week
I hope the help of the honorable

ERROR : 

> Fatal error: Uncaught exception 'RuntimeException' with message 'pthreads has detected that the could not be started, the system lacks the necessary resources or the system-imposed limit would be exceeded'

Thread Start Code :

`foreach ($f2 as $key => $value) {
	for ($i=0; $i < count($f1); $i++) {
		$stack[] = new AsyncOperation(trim($f1[$i]),trim($value));
	}
}
foreach ( $stack as $t ) {
	$t->start();
}`

**Comment by robske110** [comment]
Your system doesn‘t allow any more threads to be started for the php process.

**Comment by tpunt** [comment]
This issue tracker is specifically for the development of pthreads - please use StackOverflow for generic help instead.

Also, a thread pool here would be more suitable than spawning a separate thread for every task. Or better yet, look into async I/O (perhaps [`curl_multi_init`](http://php.net/manual/en/function.curl-multi-init.php) will be suitable for your use-case).
