### ISSUE TITLE
Das angegebene Modul wurde nicht gefunden.

### ISSUE THREAD

**Issue by Jonbeckas** [krakjoe/pthreads#885]
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_pthreads.php' (tried: ext\php_pthreads.php (Das angegebene Modul wurde nicht gefunden.), ext\php_php_pthreads.php.dll (Das angegebene Modul wurde nicht gefunden.)) in Unknown on line 0
Start(100) ...PHP Fatal error:  Uncaught Error: Class 'Thread' not found in H:\Jonas\Desktop\PHP TCP\Benchmark.php:23
Stack trace:
#0 {main}
  thrown in H:\Jonas\Desktop\PHP TCP\Benchmark.php on line 2

i become this issue but why?

**Comment by SirSnyder** [comment]
@Jonbeckas does the problem still exist?

**Comment by Jonbeckas** [comment]
yes

**Comment by SirSnyder** [comment]
Drop me an email. You will find my email address in my profile.
