### ISSUE TITLE
PHP Fatal error: Class 'Stackable' not found

### ISSUE THREAD

**Issue by CLNoob** [krakjoe/pthreads#892]
I am trying to get PHP workers getting to work in Ubuntu 18.04 (https://gist.github.com/krakjoe/9384409)

I rebuilt PHP using this guide: https://blog.programster.org/ubuntu16-04-compile-php-7-2-with-pthreads

Except, I used PHP version 7.2.8 instead of 7.2.2, cloned the pthreads git repository inside the `ext` folder (tried adding pthreads separately as shown in the guide as well, same outcome), and changed the configure options to this:

```
CONFIGURE_STRING="--prefix=/etc/php7 --with-bz2 --with-zlib --enable-zip --disable-cgi \
   --enable-soap --enable-intl --with-openssl --with-readline --with-curl \
   --enable-ftp --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd \
   --enable-sockets --enable-pcntl --with-pspell --with-enchant --with-gettext \
   --with-gd --enable-exif --with-jpeg-dir --with-png-dir --with-freetype-dir --with-xsl \
   --enable-bcmath --enable-mbstring --enable-calendar --enable-simplexml --enable-json \
   --enable-hash --enable-session --enable-xml --enable-wddx --enable-opcache \
   --with-pcre-regex --with-config-file-path=/etc/php7/cli \
   --with-config-file-scan-dir=/etc/php7/etc --enable-cli --enable-maintainer-zts --enable-pthreads \
   --with-tsrm-pthreads --enable-debug --enable-fpm \
   --with-fpm-user=www-data --with-fpm-group=www-data \
   --with-apxs2"
```
   
The given test script runs okay.

And then when I try to run the sample PHP script from https://gist.github.com/krakjoe/9384409 (using CLI), it shows the dreaded error:

`PHP Fatal error:  Class 'Stackable' not found in /home/<blablabla...>/worker.php on line 2`

I tried these (although I'm not sure if these are necessary while using PHP from CLI):

```
sudo a2dismod php7.2
sudo a2dismod mpm_prefork
sudo a2enmod mpm_worker
sudo a2enmod php7.2
```

But then I get this:

```
Considering dependency mpm_prefork for php7.2:
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
ERROR: Module mpm_worker is enabled - cannot proceed due to conflicts. It needs to be disabled first!
ERROR: Could not enable dependency mpm_prefork for php7.2, aborting
```

Hours of Googling, and found nothing that works. Can anyone help?

**Comment by dktapps** [comment]
That gist is many years out of date. See the [README](https://github.com/krakjoe/pthreads#php7) - it documents changes that were done to the API for pthreads v3. The stackable class no longer exists.

**Comment by CLNoob** [comment]
Oh! I see. Okay, I am taking a look at the new stuff then. Thanks!
