### ISSUE TITLE
How to install on ubuntu 18.04?

### ISSUE THREAD

**Issue by alibaraneser** [krakjoe/pthreads#896]
Hi, I want to use pthreads, but I can't see anything to install ?

**Comment by Redominus** [comment]
Try this script of [mine](https://github.com/Redominus/useful-scripts/blob/master/php/ubuntu-php7.2.8.sh). Chagin the version at the end changes the php version target.

**Comment by SirSnyder** [comment]
You will find instructions to build pthreads from source in the [README.md](https://github.com/krakjoe/pthreads/blob/master/README.md) under `Unix-based Building from Source`. If your issue still exists, please reopen.
