### ISSUE TITLE
extension directive

### ISSUE THREAD

**Issue by AlBundyLoves69** [krakjoe/pthreads#898]
Environment
==========

  * PHP: *can be obtained with ```php -v```*
7.2.9
  * pthreads: *can be obtained with ```php -dextension=pthreads.so --ri pthreads | grep Version```*
3.1.7dev
  * OS: *if Windows, include arch*
SLES 12.3

Summary
======
How to set ```extension=pthreads``` permanently in the ```php.ini``` so Apache 2.4 restart doesn't fail with the error message ```PHP Fatal error:  The apache2handler SAPI is not supported by pthreads in Unknown on line 0```?

In other words, is there a way that the Apache and CLI settings can be distinguished in **one** ```php.ini``` file?

For the moment the only work-around is putting the ```extension``` directive into a separate file ```/etc/php7/cli/php.ini``` and passing the ```-c``` switch with the path when running the php CLI version.

You write 

> Update your php.ini file to load the pthreads.so file using the extension directive

but this only works as I described above.

**Comment by SirSnyder** [comment]
No. Pthreads v3 is restricted to operating in CLI only. So one single ``*.ini`` for apache and cli sapi is not possible.
