### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by xyrintech** [krakjoe/pthreads#899]
configure: error: pthreads requires ZTS, please re-compile PHP with ZTS enabled

PHP 7.2.9-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: Aug 19 2018 07:44:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.9-1+ubuntu14.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by dktapps** [comment]
https://github.com/krakjoe/pthreads#requirements

**Comment by xyrintech** [comment]
https://stackoverflow.com/questions/52317129/pthread-setup-for-apache2/52317365#52317365

**Comment by tpunt** [comment]
NTS = Not Thread Safe. A ZTS (Zend Thread Safe) version of PHP is required.
