### ISSUE TITLE
pthreads will not build in php:7.3.0-zts Docker image

### ISSUE THREAD

**Issue by jerrac** [krakjoe/pthreads#910]
What the issue title says.

See: https://gist.github.com/jerrac/cc260053fc411003160e6b89532e1cff for an example Dockerfile and what the output is.

I can paste that into this issue if you'd prefer.

Hopefully this is enough info, I'm not sure how to fit this into the issue template. Sorry about that. :\

**Comment by CharlotteDunois** [comment]
PHP 7.3 is not supported yet. See PR #882.

**Comment by jerrac** [comment]
Really? Huh. The readme says 7.2+, and I didn't see anything saying 7.3 wasn't supported. That's why I tried 7.3. 

Thanks for the info. I'll stick with 7.2 from now on.
