### ISSUE TITLE
PHP 7.1.23 compile failed 

### ISSUE THREAD

**Issue by fengruichao** [krakjoe/pthreads#937]
*If you know how to write phpt tests, please open a PR with environment information, and your test, this will cause CI to test your issue before a human is able to look*

Environment
==========

  * PHP: *7.1.23
  * pthreads: *3.1.6
  * OS: macOS Mojave 10.12.4

Summary
======

A summary isn't always necessary, code > words ... delete this section, as applicable.

Reproducing Code
==============

Bug reports *must* come with reproducing code, please ensure code is formatted correctly.

If the code cannot be a single script, please link to a gist, or a github repository containing the reproducing code. 

Please, do not link to application repositories.

*Please ensure code is self contained, and executable: if the code cannot be executed, the bug cannot be reproduced.*

Expected Output
=============

Please include the expected output, properly formatted.

Actual Output
============
downloading pthreads-3.1.6.tgz ...
Starting to download pthreads-3.1.6.tgz (80,932 bytes)
...................done: 80,932 bytes
28 source files, building
running: phpize
Configuring for:
PHP Api Version:         20160303
Zend Module Api No:      20160303
Zend Extension Api No:   320160303
building in /private/tmp/pear/install/pear-build-rootKXTSt4/pthreads-3.1.6
running: /private/tmp/pear/install/pthreads/configure --with-php-config=/usr/bin/php-config
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin18.5.0
checking host system type... x86_64-apple-darwin18.5.0
checking target system type... x86_64-apple-darwin18.5.0
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib/php/extensions/no-debug-zts-20160303
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... yes
checking for re2c... re2c
checking for re2c version... 1.0.3 (ok)
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable pthreads... yes, shared
checking whether to enable AddressSanitizer for pthreads... no
checking whether to enable dmalloc for pthreads... no
checking for ZTS... ok
checking for ld used by cc... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 196608
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking if cc supports -fno-rtti -fno-exceptions... yes
checking for cc option to produce PIC... -fno-common
checking if cc PIC flag -fno-common works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin18.5.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/sh /private/tmp/pear/install/pear-build-rootKXTSt4/pthreads-3.1.6/libtool --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/private/tmp/pear/install/pthreads -DPHP_ATOM_INC -I/private/tmp/pear/install/pear-build-rootKXTSt4/pthreads-3.1.6/include -I/private/tmp/pear/install/pear-build-rootKXTSt4/pthreads-3.1.6/main -I/private/tmp/pear/install/pthreads -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/private/tmp/pear/install/pear-build-rootKXTSt4/pthreads-3.1.6/.  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/pear/install/pthreads/php_pthreads.c -o php_pthreads.lo
mkdir .libs
 cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/private/tmp/pear/install/pthreads -DPHP_ATOM_INC -I/private/tmp/pear/install/pear-build-rootKXTSt4/pthreads-3.1.6/include -I/private/tmp/pear/install/pear-build-rootKXTSt4/pthreads-3.1.6/main -I/private/tmp/pear/install/pthreads -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib -I/private/tmp/pear/install/pear-build-rootKXTSt4/pthreads-3.1.6/. -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/install/pthreads/php_pthreads.c  -fno-common -DPIC -o .libs/php_pthreads.o
In file included from /private/tmp/pear/install/pthreads/php_pthreads.c:30:
/private/tmp/pear/install/pthreads/src/object.h:41:1: warning: '/*' within block comment [-Wcomment]
/* {{{ */
^
In file included from /private/tmp/pear/install/pthreads/php_pthreads.c:426:
/private/tmp/pear/install/pthreads/classes/threaded.h:322:32: error: no member named 'called_scope' in 'struct _zend_execute_data'
    zend_do_inheritance(ce, EX(called_scope));
                            ~~~^~~~~~~~~~~~~
/usr/include/php/Zend/zend_compile.h:516:41: note: expanded from macro 'EX'
#define EX(element)                     ((execute_data)->element)
                                         ~~~~~~~~~~~~~~  ^
In file included from /private/tmp/pear/install/pthreads/php_pthreads.c:426:
/private/tmp/pear/install/pthreads/classes/threaded.h:327:44: error: no member named 'called_scope' in 'struct _zend_execute_data'
    RETURN_BOOL(instanceof_function(ce, EX(called_scope)));
                                        ~~~^~~~~~~~~~~~~
/usr/include/php/Zend/zend_compile.h:516:41: note: expanded from macro 'EX'
#define EX(element)                     ((execute_data)->element)
                                         ~~~~~~~~~~~~~~  ^
/usr/include/php/Zend/zend_API.h:640:43: note: expanded from macro 'RETURN_BOOL'
#define RETURN_BOOL(b)                                  { RETVAL_BOOL(b); return; }
                                                                      ^
/usr/include/php/Zend/zend_API.h:622:52: note: expanded from macro 'RETVAL_BOOL'
#define RETVAL_BOOL(b)                                  ZVAL_BOOL(return_value, b)
                                                                                ^
/usr/include/php/Zend/zend_types.h:612:5: note: expanded from macro 'ZVAL_BOOL'
                        (b) ? IS_TRUE : IS_FALSE;       \
                         ^
In file included from /private/tmp/pear/install/pthreads/php_pthreads.c:438:
/private/tmp/pear/install/pthreads/classes/worker.h:227:3: error: no member named 'function_table' in 'struct _zend_fcall_info'; did you mean 'function_name'?
                PTHREADS_WORKER_COLLECTOR_INIT(call, Z_OBJ_P(getThis()));
                ^
/private/tmp/pear/install/pthreads/classes/worker.h:53:11: note: expanded from macro 'PTHREADS_WORKER_COLLECTOR_INIT'
        call.fci.function_table = &(w)->ce->function_table; \
                 ^
/usr/include/php/Zend/zend_API.h:46:7: note: 'function_name' declared here
        zval function_name;
             ^
In file included from /private/tmp/pear/install/pthreads/php_pthreads.c:438:
/private/tmp/pear/install/pthreads/classes/worker.h:227:3: error: assigning to 'zval' (aka 'struct _zval_struct') from incompatible type 'HashTable *' (aka 'struct _zend_array *')
                PTHREADS_WORKER_COLLECTOR_INIT(call, Z_OBJ_P(getThis()));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/pear/install/pthreads/classes/worker.h:53:26: note: expanded from macro 'PTHREADS_WORKER_COLLECTOR_INIT'
        call.fci.function_table = &(w)->ce->function_table; \
                                ^ ~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /private/tmp/pear/install/pthreads/php_pthreads.c:438:
/private/tmp/pear/install/pthreads/classes/worker.h:227:3: error: no member named 'function_table' in 'struct _zend_fcall_info'
                PTHREADS_WORKER_COLLECTOR_INIT(call, Z_OBJ_P(getThis()));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/pear/install/pthreads/classes/worker.h:55:58: note: expanded from macro 'PTHREADS_WORKER_COLLECTOR_INIT'
        call.fcc.function_handler = zend_hash_find_ptr(call.fci.function_table, Z_STR(call.fci.function_name)); \
                                                       ~~~~~~~~ ^
In file included from /private/tmp/pear/install/pthreads/php_pthreads.c:442:
/private/tmp/pear/install/pthreads/classes/pool.h:189:33: error: no member named 'scope' in 'struct _zend_executor_globals'
                        zend_class_entry *scope = EG(scope);
                                                  ~~~^~~~~~
/usr/include/php/Zend/zend_globals_macros.h:44:73: note: expanded from macro 'EG'
# define EG(v) ZEND_TSRMG(executor_globals_id, zend_executor_globals *, v)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/include/php/TSRM/TSRM.h:171:71: note: expanded from macro 'TSRMG_STATIC'
#define TSRMG_STATIC(id, type, element) (TSRMG_BULK_STATIC(id, type)->element)
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
In file included from /private/tmp/pear/install/pthreads/php_pthreads.c:442:
/private/tmp/pear/install/pthreads/classes/pool.h:195:7: error: no member named 'scope' in 'struct _zend_executor_globals'
                        EG(scope) = ce;
                        ~~~^~~~~~
/usr/include/php/Zend/zend_globals_macros.h:44:73: note: expanded from macro 'EG'
# define EG(v) ZEND_TSRMG(executor_globals_id, zend_executor_globals *, v)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/include/php/TSRM/TSRM.h:171:71: note: expanded from macro 'TSRMG_STATIC'
#define TSRMG_STATIC(id, type, element) (TSRMG_BULK_STATIC(id, type)->element)
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
In file included from /private/tmp/pear/install/pthreads/php_pthreads.c:442:
/private/tmp/pear/install/pthreads/classes/pool.h:197:7: error: no member named 'scope' in 'struct _zend_executor_globals'
                        EG(scope) = scope;
                        ~~~^~~~~~
/usr/include/php/Zend/zend_globals_macros.h:44:73: note: expanded from macro 'EG'
# define EG(v) ZEND_TSRMG(executor_globals_id, zend_executor_globals *, v)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/include/php/TSRM/TSRM.h:171:71: note: expanded from macro 'TSRMG_STATIC'
#define TSRMG_STATIC(id, type, element) (TSRMG_BULK_STATIC(id, type)->element)
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
In file included from /private/tmp/pear/install/pthreads/php_pthreads.c:442:
/private/tmp/pear/install/pthreads/classes/pool.h:204:9: error: no member named 'function_table' in 'struct _zend_fcall_info'; did you mean 'function_name'?
                                fci.function_table = EG(function_table);
                                    ^~~~~~~~~~~~~~
                                    function_name
/usr/include/php/Zend/zend_API.h:46:7: note: 'function_name' declared here
        zval function_name;
             ^
In file included from /private/tmp/pear/install/pthreads/php_pthreads.c:442:
/private/tmp/pear/install/pthreads/classes/pool.h:204:24: error: assigning to 'zval' (aka 'struct _zval_struct') from incompatible type 'HashTable *' (aka 'struct _zend_array *')
                                fci.function_table = EG(function_table);
                                                   ^ ~~~~~~~~~~~~~~~~~~
/private/tmp/pear/install/pthreads/classes/pool.h:211:28: error: no member named 'scope' in 'struct _zend_executor_globals'
                                fcc.calling_scope = EG(scope);
                                                    ~~~^~~~~~
/usr/include/php/Zend/zend_globals_macros.h:44:73: note: expanded from macro 'EG'
# define EG(v) ZEND_TSRMG(executor_globals_id, zend_executor_globals *, v)
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/include/php/TSRM/TSRM.h:171:71: note: expanded from macro 'TSRMG_STATIC'
#define TSRMG_STATIC(id, type, element) (TSRMG_BULK_STATIC(id, type)->element)
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
In file included from /private/tmp/pear/install/pthreads/php_pthreads.c:442:
/private/tmp/pear/install/pthreads/classes/pool.h:293:4: error: no member named 'function_table' in 'struct _zend_fcall_info'; did you mean 'function_name'?
                        PTHREADS_WORKER_COLLECTOR_INIT(call, Z_OBJ_P(worker));
                        ^
/private/tmp/pear/install/pthreads/classes/worker.h:53:11: note: expanded from macro 'PTHREADS_WORKER_COLLECTOR_INIT'
        call.fci.function_table = &(w)->ce->function_table; \
                 ^
/usr/include/php/Zend/zend_API.h:46:7: note: 'function_name' declared here
        zval function_name;
             ^
In file included from /private/tmp/pear/install/pthreads/php_pthreads.c:442:
/private/tmp/pear/install/pthreads/classes/pool.h:293:4: error: assigning to 'zval' (aka 'struct _zval_struct') from incompatible type 'HashTable *' (aka 'struct _zend_array *')
                        PTHREADS_WORKER_COLLECTOR_INIT(call, Z_OBJ_P(worker));
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/pear/install/pthreads/classes/worker.h:53:26: note: expanded from macro 'PTHREADS_WORKER_COLLECTOR_INIT'
        call.fci.function_table = &(w)->ce->function_table; \
                                ^ ~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /private/tmp/pear/install/pthreads/php_pthreads.c:442:
/private/tmp/pear/install/pthreads/classes/pool.h:293:4: error: no member named 'function_table' in 'struct _zend_fcall_info'
                        PTHREADS_WORKER_COLLECTOR_INIT(call, Z_OBJ_P(worker));
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/pear/install/pthreads/classes/worker.h:55:58: note: expanded from macro 'PTHREADS_WORKER_COLLECTOR_INIT'
        call.fcc.function_handler = zend_hash_find_ptr(call.fci.function_table, Z_STR(call.fci.function_name)); \
                                                       ~~~~~~~~ ^
1 warning and 14 errors generated.
make: *** [php_pthreads.lo] Error 1
ERROR: `make' failed
Please include the actual output, properly formatted.

**Comment by fengruichao** [comment]
PHP 7.1.23 (cli) (built: May  8 2019 16:44:49) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

**Comment by CharlotteDunois** [comment]
Use 3.2.0 (available with github releases or git tag).

**Comment by fengruichao** [comment]
Ok, got it. Thank you
