### ISSUE TITLE
Memory "leak" when passing large payload tasks to pool

### ISSUE THREAD

**Issue by BasBuur** [krakjoe/pthreads#948]
I'm in a position where I need to pass tasks with a large payload to a pool every 10 seconds or so for about 30 minutes. We're talking about payloads anywhere from 50mb to 200mb in size. However, instead of the memory being released when the task is done, the memory stays occupied and my memory sticks fill up fast. Am I missing something in the documentation, is this a bug or is there no way around this?

Example script:
```php
<?php

class TestTask extends \Thread {

    private $testData;

    public function __construct($testData) {
        $this->testData = $testData;
    }

    public function run() {
        // Do nothing
    }

}

$pool = new Pool(4);

$payload = openssl_random_pseudo_bytes(100 * 1000000);

for($i=0; $i<1000; $i++) {
    $pool->submit(new TestTask($payload));
    sleep(1);
}

while($pool->collect());
```

**Comment by BasBuur** [comment]
Calling `collect` on the pool every time I submit a new task seems to solve the issue. Is this a correct way to handle this?

```php
for($i=0; $i<1000; $i++) {
    $pool->submit(new TestTask($payload));
    $pool->collect();
    sleep(1);
}
```

**Comment by dktapps** [comment]
You're supposed to collect to fetch the results of finished tasks. Tasks won't be freed until you do.
